import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, ArrowRight, Eye, Upload } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { Textarea } from "@/components/ui/Textarea";
import { SchemaFieldBuilder } from "../components/SchemaFieldBuilder";
import { NamingStrategyEditor } from "../components/NamingStrategyEditor";
import { SchemaImpactPanel } from "../components/SchemaImpactPanel";
import { ImportSchemaDialog } from "../components/ImportSchemaDialog";
import { ROUTES, type EntityDefinitionCreate, type FieldDefinitionInput, type NamingConfiguration, type NamingStrategy, type PreviewResult } from "../contracts";
import { metadataModelingService } from "../services/metadata-modeling-service";
import { PageHeader, idempotencyKey } from "./page-utils";

const STEPS = ["Identity", "Behavior", "Fields", "Naming", "Review"] as const;
// The wizard's branch count mirrors its five explicit, independently validated steps.
// eslint-disable-next-line complexity
export function CreateMetadataSchemaPage() {
  const navigate = useNavigate(); const [step, setStep] = useState(0); const [dirty, setDirty] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [importOpen, setImportOpen] = useState(false); const [preview, setPreview] = useState<PreviewResult | null>(null);
  const [identity, setIdentity] = useState({ name: "", plural_name: "", code: "", description: "", icon: "" }); const [behavior, setBehavior] = useState({ is_submittable: false, track_changes: true }); const [fields, setFields] = useState<readonly FieldDefinitionInput[]>([]); const [namingStrategy, setNamingStrategy] = useState<NamingStrategy>("uuid"); const [namingConfig, setNamingConfig] = useState<NamingConfiguration>({});
  useEffect(() => { const protect = (event: BeforeUnloadEvent) => { if (dirty) { event.preventDefault(); event.returnValue = ""; } }; window.addEventListener("beforeunload", protect); return () => window.removeEventListener("beforeunload", protect); }, [dirty]);
  const payload: EntityDefinitionCreate = useMemo(() => ({ ...identity, is_submittable: behavior.is_submittable, track_changes: behavior.track_changes, naming_strategy: namingStrategy, naming_config: namingConfig }), [identity, behavior, namingStrategy, namingConfig]);
  const mutate = (operation: () => void) => { operation(); setDirty(true); setPreview(null); };
  const fieldErrors = fields.flatMap((field, index) => { const errors: string[] = []; if (!field.name.trim()) errors.push(`Field ${index + 1} needs a label.`); if (!/^[a-z][a-z0-9_]*$/u.test(field.key)) errors.push(`Field ${index + 1} needs a valid API key.`); if (field.field_type === "select" && field.options.length === 0) errors.push(`${field.name || `Field ${index + 1}`} needs options.`); if (field.field_type === "reference" && !field.reference_entity_code) errors.push(`${field.name || `Field ${index + 1}`} needs a reference target.`); return errors; });
  const canAdvance = step === 0 ? Boolean(identity.name && identity.plural_name && /^[a-z][a-z0-9-]*$/u.test(identity.code)) : step === 2 ? fields.length > 0 && fieldErrors.length === 0 : step === 3 ? namingStrategy !== "field" || Boolean(namingConfig.field_key) : true;
  const runPreview = async () => { setBusy(true); setError(""); try { setPreview(await metadataModelingService.previewNewDefinition(payload, fields)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Preview failed."); } finally { setBusy(false); } };
  const create = async () => { if (!preview) { setError("Run the server preview before creating the model."); return; } setBusy(true); setError(""); try { const definition = await metadataModelingService.createDefinition(payload, idempotencyKey()); await metadataModelingService.createCandidate(definition.id, { fields, based_on_version_id: null, change_summary: "Initial schema" }); setDirty(false); navigate(ROUTES.schemaEdit(definition.id), { replace: true }); } catch (reason) { setError(reason instanceof Error ? reason.message : "Creation failed."); } finally { setBusy(false); } };
  return <main id="main-content" className="space-y-6 p-4 md:p-8"><PageHeader title="Create Metadata Model" description="Build a validated, versioned schema in five focused steps." actions={<Button variant="outline" onClick={() => setImportOpen(true)}><Upload className="mr-2 h-4 w-4" />Import</Button>} />
    <ol aria-label="Creation progress" className="grid grid-cols-5 gap-1">{STEPS.map((label, index) => <li key={label} className={`rounded px-2 py-2 text-center text-xs md:text-sm ${index === step ? "bg-primary text-primary-foreground" : index < step ? "bg-muted font-medium" : "border border-border text-muted-foreground"}`}>{index + 1}. {label}</li>)}</ol>
    <section className="min-h-[360px] rounded-lg border border-border bg-card p-5 md:p-7">
      {step === 0 && <div className="grid max-w-3xl gap-5 md:grid-cols-2"><Input id="schema-name" label="Singular name" value={identity.name} required autoFocus onChange={(event) => mutate(() => setIdentity({ ...identity, name: event.target.value }))} /><Input id="schema-plural" label="Plural name" value={identity.plural_name} required onChange={(event) => mutate(() => setIdentity({ ...identity, plural_name: event.target.value }))} /><Input id="schema-code" label="Stable code" value={identity.code} required pattern="[a-z][a-z0-9-]*" onChange={(event) => mutate(() => setIdentity({ ...identity, code: event.target.value.toLowerCase().replace(/[^a-z0-9-]/gu, "-") }))} /><Input id="schema-icon" label="Icon registry key" value={identity.icon} onChange={(event) => mutate(() => setIdentity({ ...identity, icon: event.target.value }))} /><div className="md:col-span-2"><label htmlFor="schema-description" className="text-sm font-medium">Description</label><Textarea id="schema-description" value={identity.description} onChange={(event) => mutate(() => setIdentity({ ...identity, description: event.target.value }))} /></div></div>}
      {step === 1 && <fieldset className="space-y-5"><legend className="text-lg font-semibold">Behavior</legend><label className="flex items-start gap-3 rounded border border-border p-4"><input type="checkbox" checked={behavior.is_submittable} onChange={(event) => mutate(() => setBehavior({ ...behavior, is_submittable: event.target.checked }))} /><span><strong className="block">Submittable records</strong><span className="text-sm text-muted-foreground">Adds draft, submitted, and cancelled lifecycle controls.</span></span></label><label className="flex items-start gap-3 rounded border border-border p-4"><input type="checkbox" checked={behavior.track_changes} onChange={(event) => mutate(() => setBehavior({ ...behavior, track_changes: event.target.checked }))} /><span><strong className="block">Track changes</strong><span className="text-sm text-muted-foreground">Keep immutable evidence for each successful record mutation.</span></span></label></fieldset>}
      {step === 2 && <><SchemaFieldBuilder fields={fields} onChange={(next) => mutate(() => setFields(next))} />{fieldErrors.length > 0 && <ul role="alert" className="mt-4 list-disc pl-5 text-sm text-destructive">{fieldErrors.map((message) => <li key={message}>{message}</li>)}</ul>}</>}
      {step === 3 && <NamingStrategyEditor strategy={namingStrategy} config={namingConfig} fields={fields} onChange={(strategy, config) => mutate(() => { setNamingStrategy(strategy); setNamingConfig(config); })} />}
      {step === 4 && <div className="space-y-5"><dl className="grid gap-4 md:grid-cols-3"><div><dt className="text-xs uppercase text-muted-foreground">Identity</dt><dd className="font-medium">{identity.name} · {identity.code}</dd></div><div><dt className="text-xs uppercase text-muted-foreground">Fields</dt><dd className="font-medium">{fields.length}</dd></div><div><dt className="text-xs uppercase text-muted-foreground">Naming</dt><dd className="font-medium capitalize">{namingStrategy}</dd></div></dl><Button type="button" variant="outline" disabled={busy} onClick={() => void runPreview()}><Eye className="mr-2 h-4 w-4" />{busy ? "Validating…" : "Run server preview"}</Button>{preview && <><SchemaImpactPanel report={preview.impact} /><div className="rounded-lg border border-border p-4"><h2 className="font-semibold">Generated form preview</h2><p className="text-sm text-muted-foreground">{preview.form_descriptor.length} controls generated from the normalized contract.</p></div></>}</div>}
      {error && <p role="alert" className="mt-5 rounded border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}
    </section>
    <div className="flex justify-between"><Button variant="outline" disabled={step === 0 || busy} onClick={() => setStep((value) => value - 1)}><ArrowLeft className="mr-2 h-4 w-4" />Back</Button>{step < STEPS.length - 1 ? <Button disabled={!canAdvance} onClick={() => setStep((value) => value + 1)}>Continue<ArrowRight className="ml-2 h-4 w-4" /></Button> : <Button disabled={!preview || busy} onClick={() => void create()}>{busy ? "Creating…" : "Create draft"}</Button>}</div>
    <ImportSchemaDialog open={importOpen} onOpenChange={setImportOpen} onImport={async (request) => { await metadataModelingService.importDefinition(request, idempotencyKey()); }} />
  </main>;
}
