import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { FilePlus2, Rows3, Search } from "lucide-react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { EmptyState } from "@/components/ui/EmptyState";
import { ROUTES, type DynamicResourceState, type JSONValue } from "../contracts";
import { metadataModelingService } from "../services/metadata-modeling-service";
import { GovernedErrorState, PageHeader, PageSkeleton, formatDate } from "./page-utils";

function displayValue(value: JSONValue | undefined): string { if (value === null || value === undefined) return "—"; if (typeof value === "object") return JSON.stringify(value); return String(value); }
// List branches deliberately keep no-schema, loading, governed-error, and empty states distinct.
// eslint-disable-next-line complexity
export function DynamicResourceListPage() {
  const navigate = useNavigate(); const [params, setParams] = useSearchParams(); const [search, setSearch] = useState(params.get("search") ?? ""); const [state, setState] = useState<DynamicResourceState | "">(""); const [after, setAfter] = useState(""); const [before, setBefore] = useState(""); const [ordering, setOrdering] = useState<"-created_at" | "display_name" | "record_key">("-created_at"); const [page, setPage] = useState(1); const entityId = params.get("entity_id") ?? params.get("entity") ?? "";
  const definitions = useQuery({ queryKey: ["metadata-definitions", "published"], queryFn: () => metadataModelingService.listDefinitions({ status: "published", page_size: 100, ordering: "name" }) });
  const selected = useQuery({ queryKey: ["metadata-definition", entityId], queryFn: () => metadataModelingService.getDefinition(entityId), enabled: Boolean(entityId) });
  const resources = useQuery({ queryKey: ["metadata-resources", { entityId, search, state, after, before, ordering, page }], queryFn: () => metadataModelingService.listResources({ entity_id: entityId, search: search || undefined, state: state || undefined, created_after: after || undefined, created_before: before || undefined, ordering, page, page_size: 25 }), enabled: Boolean(entityId) });
  const columns = useMemo(() => selected.data?.active_fields.filter((field) => field.is_searchable).slice(0, 4) ?? [], [selected.data]);
  if (definitions.isLoading) return <PageSkeleton />; if (definitions.error) return <GovernedErrorState error={definitions.error} onRetry={() => void definitions.refetch()} />; const models = definitions.data?.items ?? [];
  return <main id="main-content" className="space-y-6 p-4 md:p-8"><PageHeader title="Dynamic Records" description="Work with tenant records through their published, version-pinned metadata contracts." actions={entityId ? <Button onClick={() => navigate(ROUTES.recordCreateFor(entityId))}><FilePlus2 className="mr-2 h-4 w-4" />Create record</Button> : undefined} />
    {models.length === 0 ? <EmptyState icon={Rows3} title="Publish a metadata model first" description="Records require a published schema. Create, preview, and publish a model to unlock this workspace." action={{ label: "Create schema", onClick: () => navigate(ROUTES.schemaCreate) }} /> : <><section aria-label="Record filters" className="grid gap-3 rounded-lg border border-border bg-card p-4 md:grid-cols-6"><select aria-label="Metadata model" className="rounded-md border border-input bg-background px-3 md:col-span-2" value={entityId} onChange={(event) => { const next = new URLSearchParams(params); if (event.target.value) next.set("entity_id", event.target.value); else next.delete("entity_id"); next.delete("entity"); setParams(next); setPage(1); }}><option value="">Select a metadata model</option>{models.map((model) => <option key={model.id} value={model.id}>{model.plural_name}</option>)}</select><div className="relative md:col-span-2"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input aria-label="Search records" className="pl-9" value={search} disabled={!entityId} placeholder="Server-side search" onChange={(event) => { setSearch(event.target.value); setPage(1); }} /></div><select aria-label="Record state" disabled={!entityId} className="rounded-md border border-input bg-background px-3" value={state} onChange={(event) => { setState(event.target.value as DynamicResourceState | ""); setPage(1); }}><option value="">All states</option><option value="draft">Draft</option><option value="submitted">Submitted</option><option value="cancelled">Cancelled</option></select><select aria-label="Order records" disabled={!entityId} className="rounded-md border border-input bg-background px-3" value={ordering} onChange={(event) => setOrdering(event.target.value as "-created_at" | "display_name" | "record_key")}><option value="-created_at">Newest</option><option value="display_name">Display name</option><option value="record_key">Record key</option></select><Input aria-label="Created after" type="date" value={after} disabled={!entityId} onChange={(event) => setAfter(event.target.value)} /><Input aria-label="Created before" type="date" value={before} disabled={!entityId} onChange={(event) => setBefore(event.target.value)} /></section>
      {!entityId ? <EmptyState icon={Rows3} title="Choose a metadata model" description="Select a published model to load its server-filtered records and dynamic columns." /> : selected.isLoading || resources.isLoading ? <PageSkeleton /> : selected.error ? <GovernedErrorState error={selected.error} onRetry={() => void selected.refetch()} /> : resources.error ? <GovernedErrorState error={resources.error} onRetry={() => void resources.refetch()} /> : resources.data?.items.length === 0 ? <EmptyState icon={Rows3} title={search || state || after || before ? "No matching records" : `No ${selected.data?.plural_name ?? "records"} yet`} description={search || state || after || before ? "Change the server-side filters to broaden the result." : "Create the first record against this published schema."} action={search || state || after || before ? undefined : { label: "Create record", onClick: () => navigate(ROUTES.recordCreateFor(entityId)) }} /> : resources.data && <><div className="overflow-x-auto rounded-lg border border-border"><table className="w-full text-left text-sm"><thead className="bg-muted"><tr><th className="px-4 py-3">Record</th><th className="px-4 py-3">State</th>{columns.map((field) => <th key={field.key} className="px-4 py-3">{field.name}</th>)}<th className="px-4 py-3">Updated</th></tr></thead><tbody>{resources.data.items.map((record) => <tr key={record.id} className="border-t border-border"><td className="px-4 py-3"><Link to={ROUTES.recordDetail(record.id)} className="font-medium text-primary hover:underline">{record.display_name}</Link><p className="text-xs text-muted-foreground">{record.record_key}</p></td><td className="px-4 py-3 capitalize">{record.state}</td>{columns.map((field) => <td key={field.key} className="max-w-48 truncate px-4 py-3">{displayValue(record.searchable_data[field.key])}</td>)}<td className="px-4 py-3 whitespace-nowrap">{formatDate(record.updated_at)}</td></tr>)}</tbody></table></div><div className="flex justify-between"><p className="text-sm text-muted-foreground">{resources.data.pagination.count} records</p><div className="flex gap-2"><Button variant="outline" disabled={!resources.data.pagination.has_previous} onClick={() => setPage((value) => Math.max(1, value - 1))}>Previous</Button><Button variant="outline" disabled={!resources.data.pagination.has_next} onClick={() => setPage((value) => value + 1)}>Next</Button></div></div></>}</>}
  </main>;
}
