import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Copy, Edit3, Send, Trash2, XCircle } from "lucide-react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { Button } from "@/components/ui/Button";
import { ConfirmDialog, Dialog } from "@/components/ui/Dialog";
import { Input } from "@/components/ui/Input";
import { ROUTES, type JSONValue } from "../contracts";
import { ResourceVersionTimeline } from "../components/ResourceVersionTimeline";
import { metadataModelingService } from "../services/metadata-modeling-service";
import { GovernedErrorState, PageHeader, PageSkeleton, formatDate, idempotencyKey } from "./page-utils";

function rendered(value: JSONValue | undefined): string { if (value === undefined || value === null) return "—"; if (typeof value === "boolean") return value ? "Yes" : "No"; if (typeof value === "object") return JSON.stringify(value, null, 2); return String(value); }
// Lifecycle branches are intentionally visible so illegal actions are unreachable.
// eslint-disable-next-line complexity
export function DynamicResourceDetailPage() {
  const { id = "" } = useParams(); const navigate = useNavigate(); const cache = useQueryClient(); const [confirm, setConfirm] = useState<"submit" | "delete" | null>(null); const [cancelOpen, setCancelOpen] = useState(false); const [reason, setReason] = useState("");
  const detail = useQuery({ queryKey: ["metadata-resource", id], queryFn: () => metadataModelingService.getResource(id), enabled: Boolean(id) }); const history = useQuery({ queryKey: ["metadata-resource-versions", id], queryFn: () => metadataModelingService.listResourceVersions(id), enabled: Boolean(id) });
  const transition = useMutation({ mutationFn: async (action: "submit" | "delete" | "cancel" | "duplicate") => { const record = detail.data; if (!record) return null; if (action === "submit") return metadataModelingService.submitResource(id, record.lock_version, idempotencyKey()); if (action === "cancel") return metadataModelingService.cancelResource(id, reason, record.lock_version, idempotencyKey()); if (action === "duplicate") return metadataModelingService.duplicateResource(id); await metadataModelingService.deleteResource(id, record.lock_version); return null; }, onSuccess: async (record, action) => { setConfirm(null); setCancelOpen(false); if (action === "delete") navigate(`${ROUTES.records}?entity_id=${encodeURIComponent(detail.data?.entity_definition ?? "")}`, { replace: true }); else if (action === "duplicate" && record) navigate(ROUTES.recordDetail(record.id)); else await Promise.all([cache.invalidateQueries({ queryKey: ["metadata-resource", id] }), cache.invalidateQueries({ queryKey: ["metadata-resource-versions", id] })]); } });
  if (detail.isLoading) return <PageSkeleton rows={7} />; if (detail.error) return <GovernedErrorState error={detail.error} onRetry={() => void detail.refetch()} />; const record = detail.data; if (!record) return null; const allowed = (name: string) => record.allowed_actions?.includes(name) ?? true; const mutable = record.state === "draft";
  return <main id="main-content" className="space-y-6 p-4 md:p-8"><PageHeader eyebrow={`${record.entity_name} · schema v${record.schema_version_number}`} title={record.display_name} description={`Record key ${record.record_key}`} actions={<>{mutable && allowed("update") && <Button onClick={() => navigate(ROUTES.recordEdit(id))}><Edit3 className="mr-2 h-4 w-4" />Edit</Button>}{allowed("duplicate") && <Button variant="outline" onClick={() => transition.mutate("duplicate")}><Copy className="mr-2 h-4 w-4" />Duplicate</Button>}{mutable && allowed("submit") && <Button onClick={() => setConfirm("submit")}><Send className="mr-2 h-4 w-4" />Submit</Button>}{record.state === "submitted" && allowed("cancel") && <Button variant="outline" onClick={() => setCancelOpen(true)}><XCircle className="mr-2 h-4 w-4" />Cancel</Button>}{mutable && allowed("delete") && <Button variant="danger" onClick={() => setConfirm("delete")}><Trash2 className="mr-2 h-4 w-4" />Delete</Button>}</>} />
    <section className="grid gap-4 md:grid-cols-4">{[["State", record.state], ["Schema version", record.schema_version_number], ["Created", formatDate(record.created_at)], ["Updated", formatDate(record.updated_at)]].map(([label, value]) => <div key={label} className="rounded-lg border border-border bg-card p-4"><p className="text-xs uppercase text-muted-foreground">{label}</p><p className="mt-1 font-medium capitalize">{value}</p></div>)}</section>
    {record.state !== "draft" && <div className="rounded-lg border border-border bg-muted p-4 text-sm"><strong>Read-only lifecycle state.</strong> Submitted and cancelled record data is immutable. Duplicate it to make a new draft.</div>}
    <section className="rounded-lg border border-border bg-card"><div className="border-b border-border p-4"><h2 className="text-lg font-semibold">Record values</h2></div><dl className="grid gap-px bg-border md:grid-cols-2">{record.fields.map((field) => <div key={field.id} className="bg-card p-4"><dt className="text-xs uppercase tracking-wide text-muted-foreground">{field.name}</dt><dd className="mt-1 whitespace-pre-wrap break-words">{field.field_type === "reference" && typeof record.data[field.key] === "string" && allowed("read_references") ? <Link className="text-primary hover:underline" to={ROUTES.recordDetail(rendered(record.data[field.key]))}>{rendered(record.data[field.key])}</Link> : rendered(record.data[field.key])}</dd></div>)}</dl></section>
    <section className="rounded-lg border border-border bg-card p-5"><h2 className="mb-5 text-lg font-semibold">Immutable version history</h2>{history.isLoading ? <PageSkeleton rows={3} /> : history.error ? <GovernedErrorState error={history.error} onRetry={() => void history.refetch()} /> : <ResourceVersionTimeline versions={history.data?.items ?? []} />}</section>
    <ConfirmDialog open={confirm !== null} onOpenChange={(open) => { if (!open) setConfirm(null); }} title={confirm === "submit" ? "Submit this record?" : "Delete this draft?"} description={confirm === "submit" ? "Submission makes record data immutable." : "The record is soft-deleted and retained in immutable history."} confirmLabel={confirm === "submit" ? "Submit" : "Delete"} variant={confirm === "delete" ? "danger" : "default"} onConfirm={() => { if (confirm) transition.mutate(confirm); }} />
    <Dialog open={cancelOpen} onOpenChange={setCancelOpen} title="Cancel submitted record" description="Give an auditable reason for this terminal transition."><div className="space-y-4"><Input id="cancel-reason" label="Reason" required value={reason} onChange={(event) => setReason(event.target.value)} /><div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setCancelOpen(false)}>Keep record</Button><Button variant="danger" disabled={!reason.trim()} onClick={() => transition.mutate("cancel")}>Cancel record</Button></div></div></Dialog>
  </main>;
}
