import { useEffect, useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, Save } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { ApiError } from "@/services/api-client";
import { Button } from "@/components/ui/Button";
import { DynamicResourceForm } from "../components/DynamicResourceForm";
import { validateDynamicValues } from "../components/dynamic-validation";
import { ROUTES, type JSONObject } from "../contracts";
import { metadataModelingService } from "../services/metadata-modeling-service";
import { GovernedErrorState, PageHeader, PageSkeleton, fieldErrorsFrom } from "./page-utils";

export function EditDynamicResourcePage() {
  const { id = "" } = useParams(); const navigate = useNavigate(); const cache = useQueryClient(); const query = useQuery({ queryKey: ["metadata-resource", id], queryFn: () => metadataModelingService.getResource(id), enabled: Boolean(id) }); const [values, setValues] = useState<JSONObject>({}); const [displayName, setDisplayName] = useState(""); const [busy, setBusy] = useState(false); const [serverError, setServerError] = useState<Error | null>(null); const [conflict, setConflict] = useState(false);
  useEffect(() => { if (query.data) { setValues(query.data.data); setDisplayName(query.data.display_name); } }, [query.data]);
  const changed = useMemo(() => query.data ? query.data.fields.filter((field) => JSON.stringify(query.data?.data[field.key]) !== JSON.stringify(values[field.key])).map((field) => field.key) : [], [query.data, values]); const clientErrors = query.data ? validateDynamicValues(query.data.fields, values) : {};
  useEffect(() => { const protect = (event: BeforeUnloadEvent) => { if (changed.length > 0) { event.preventDefault(); event.returnValue = ""; } }; window.addEventListener("beforeunload", protect); return () => window.removeEventListener("beforeunload", protect); }, [changed.length]);
  if (query.isLoading) return <PageSkeleton />; if (query.error) return <GovernedErrorState error={query.error} onRetry={() => void query.refetch()} />; const record = query.data; if (!record) return null;
  if (record.state !== "draft") return <main id="main-content" className="p-4 md:p-8"><div className="rounded-lg border border-border bg-card p-8 text-center"><h1 className="text-2xl font-bold">This record is read-only</h1><p className="mt-2 text-muted-foreground">Submitted and cancelled records cannot be edited. Duplicate it to create a new draft.</p><Button className="mt-5" onClick={() => navigate(ROUTES.recordDetail(id))}>Return to record</Button></div></main>;
  const save = async () => { if (Object.keys(clientErrors).length > 0 || changed.length === 0) return; setBusy(true); setServerError(null); try { const changes: JSONObject = {}; for (const key of changed) { const value = values[key]; if (value !== undefined) changes[key] = value; } const updated = await metadataModelingService.patchResource(id, { changes, display_name: displayName }, record.lock_version); await cache.setQueryData(["metadata-resource", id], updated); navigate(ROUTES.recordDetail(id)); } catch (reason) { if (reason instanceof ApiError && reason.status === 409) setConflict(true); else setServerError(reason instanceof Error ? reason : new Error("Update failed.")); } finally { setBusy(false); } };
  if (conflict) return <main id="main-content" className="p-4 md:p-8"><div className="mx-auto max-w-2xl rounded-lg border border-destructive/40 bg-card p-8 text-center"><AlertTriangle className="mx-auto h-10 w-10 text-destructive" /><h1 className="mt-4 text-2xl font-bold">This record changed elsewhere</h1><p className="mt-2 text-muted-foreground">Nothing was overwritten. Keep this draft open to compare, or reload the latest server version.</p><div className="mt-5 flex justify-center gap-2"><Button variant="outline" onClick={() => setConflict(false)}>Keep my changes</Button><Button onClick={() => { setConflict(false); void query.refetch().then((result) => { if (result.data) { setValues(result.data.data); setDisplayName(result.data.display_name); } }); }}>Reload latest</Button></div></div></main>;
  const errors = { ...clientErrors, ...(serverError ? fieldErrorsFrom(serverError) : {}) };
  return <main id="main-content" className="space-y-6 p-4 md:p-8"><PageHeader eyebrow={`${record.entity_name} · ${record.record_key}`} title="Edit Dynamic Record" description={`Pinned to schema version ${record.schema_version_number}. PATCH sends only the top-level fields shown in the review.`} /><section className="space-y-6 rounded-lg border border-border bg-card p-5"><label className="block"><span className="text-sm font-medium">Display name</span><input className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3" value={displayName} onChange={(event) => setDisplayName(event.target.value)} /></label><DynamicResourceForm fields={record.fields} values={values} errors={errors} disabled={busy} onChange={(next) => { setValues(next); setServerError(null); }} /><section className="rounded-lg border border-border bg-muted p-4"><h2 className="font-semibold">Changed-field review</h2>{changed.length === 0 ? <p className="mt-1 text-sm text-muted-foreground">No data fields changed.</p> : <ul className="mt-2 flex flex-wrap gap-2">{changed.map((key) => <li key={key} className="rounded bg-background px-2 py-1 text-sm"><code>{key}</code></li>)}</ul>}</section>{serverError && <p role="alert" className="text-sm text-destructive">{serverError.message}</p>}<div className="flex justify-end gap-2"><Button variant="outline" onClick={() => navigate(ROUTES.recordDetail(id))}>Cancel</Button><Button disabled={busy || changed.length === 0 || Object.keys(clientErrors).length > 0} onClick={() => void save()}><Save className="mr-2 h-4 w-4" />{busy ? "Saving…" : "Save changes"}</Button></div></section></main>;
}
