import { useEffect, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { RefreshCw, Send, XCircle } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { ApiError } from "@/services/api-client";
import { Button } from "@/components/ui/Button";
import { ConfirmDialog } from "@/components/ui/Dialog";
import { SchemaFieldBuilder } from "../components/SchemaFieldBuilder";
import { SchemaDiffViewer } from "../components/SchemaDiffViewer";
import { SchemaImpactPanel } from "../components/SchemaImpactPanel";
import type { EntitySchemaVersionDetail, FieldDefinition, FieldDefinitionInput, SchemaDiff, SchemaValidationReport } from "../contracts";
import { ROUTES } from "../contracts";
import { metadataModelingService } from "../services/metadata-modeling-service";
import { GovernedErrorState, PageHeader, PageSkeleton, idempotencyKey } from "./page-utils";

function writable(field: FieldDefinition): FieldDefinitionInput { return { name: field.name, key: field.key, field_type: field.field_type, is_required: field.is_required, is_read_only: field.is_read_only, is_searchable: field.is_searchable, default_value: field.default_value, validation_rules: field.validation_rules, options: field.options, reference_entity_code: field.reference_entity_code, help_text: field.help_text, placeholder: field.placeholder, order: field.order }; }
// Candidate, validation, publication, rejection, and conflict states are explicit branches.
// eslint-disable-next-line complexity
export function EditMetadataSchemaPage() {
  const { id = "" } = useParams(); const navigate = useNavigate(); const cache = useQueryClient(); const definition = useQuery({ queryKey: ["metadata-definition", id], queryFn: () => metadataModelingService.getDefinition(id), enabled: Boolean(id) });
  const [fields, setFields] = useState<readonly FieldDefinitionInput[]>([]); const [summary, setSummary] = useState(""); const [candidate, setCandidate] = useState<EntitySchemaVersionDetail | null>(null); const [report, setReport] = useState<SchemaValidationReport | null>(null); const [diff, setDiff] = useState<SchemaDiff | null>(null); const [confirm, setConfirm] = useState<"publish" | "reject" | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [conflict, setConflict] = useState(false);
  useEffect(() => { if (definition.data && fields.length === 0) setFields(definition.data.active_fields.map(writable)); }, [definition.data, fields.length]);
  if (definition.isLoading) return <PageSkeleton rows={8} />; if (definition.error) return <GovernedErrorState error={definition.error} onRetry={() => void definition.refetch()} />; const model = definition.data; if (!model) return null;
  if (conflict) return <main id="main-content" className="p-4 md:p-8"><div className="mx-auto max-w-2xl rounded-lg border border-destructive/40 bg-card p-8 text-center"><RefreshCw className="mx-auto h-10 w-10 text-destructive" /><h1 className="mt-4 text-2xl font-bold">A newer edit exists</h1><p className="mt-2 text-muted-foreground">Your changes are preserved on this screen. Reload the server version to compare before deciding what to reapply.</p><div className="mt-6 flex justify-center gap-2"><Button variant="outline" onClick={() => setConflict(false)}>Keep my draft</Button><Button onClick={() => { setFields(model.active_fields.map(writable)); setCandidate(null); setDiff(null); setConflict(false); void definition.refetch(); }}>Reload latest</Button></div></div></main>;
  const save = async () => { setBusy(true); setError(""); try { await metadataModelingService.updateDefinition(id, { name: model.name, plural_name: model.plural_name, description: model.description, icon: model.icon, is_submittable: model.is_submittable, track_changes: model.track_changes, naming_strategy: model.naming_strategy, naming_config: model.naming_config }, model.lock_version); const created = await metadataModelingService.createCandidate(id, { fields, based_on_version_id: model.active_version, change_summary: summary }); setCandidate(created); const validation = await metadataModelingService.validateCandidate(id, created.id); setReport(validation); if (model.active_version) setDiff(await metadataModelingService.diffVersions(id, model.active_version, created.id)); await cache.invalidateQueries({ queryKey: ["metadata-versions", id] }); } catch (reason) { if (reason instanceof ApiError && reason.status === 409) setConflict(true); else setError(reason instanceof Error ? reason.message : "Could not save candidate."); } finally { setBusy(false); } };
  const transition = async () => { if (!candidate || !confirm) return; setBusy(true); try { if (confirm === "publish") await metadataModelingService.publishCandidate(id, candidate.id, idempotencyKey()); else await metadataModelingService.rejectCandidate(id, candidate.id, "Rejected by editor"); await cache.invalidateQueries({ queryKey: ["metadata-definition", id] }); navigate(ROUTES.schemaDetail(id)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Transition failed."); } finally { setBusy(false); setConfirm(null); } };
  return <main id="main-content" className="space-y-6 p-4 md:p-8"><PageHeader title="Edit Metadata Model" description={model.status === "published" ? "Changes create an immutable candidate. Validate its impact before publication." : "Build and validate the first candidate version."} actions={<Button variant="outline" onClick={() => navigate(ROUTES.schemaDetail(id))}>Cancel</Button>} />
    <SchemaFieldBuilder fields={fields} disabled={busy || candidate !== null} onChange={(next) => { setFields(next); setCandidate(null); setReport(null); setDiff(null); }} /><label className="block"><span className="text-sm font-medium">Change summary</span><textarea className="mt-1 min-h-24 w-full rounded-md border border-input bg-background p-3" value={summary} disabled={busy || candidate !== null} onChange={(event) => setSummary(event.target.value)} /></label>
    <div className="flex flex-wrap gap-2"><Button disabled={busy || candidate !== null || fields.length === 0} onClick={() => void save()}>{busy ? "Validating…" : "Save and validate candidate"}</Button>{candidate && report?.valid && <Button onClick={() => setConfirm("publish")}><Send className="mr-2 h-4 w-4" />Publish version {candidate.version}</Button>}{candidate && <Button variant="outline" onClick={() => setConfirm("reject")}><XCircle className="mr-2 h-4 w-4" />Reject candidate</Button>}</div>
    {error && <p role="alert" className="rounded border border-destructive/40 bg-destructive/10 p-3 text-destructive">{error}</p>}<div className="grid gap-5 lg:grid-cols-2"><SchemaDiffViewer diff={diff} /><SchemaImpactPanel report={report} /></div>
    <ConfirmDialog open={confirm !== null} onOpenChange={(open) => { if (!open) setConfirm(null); }} title={confirm === "publish" ? "Publish this schema version?" : "Reject this candidate?"} description={confirm === "publish" ? "Existing records were validated against this exact immutable candidate." : "The candidate remains in history as rejected and cannot be edited."} confirmLabel={confirm === "publish" ? "Publish" : "Reject"} variant={confirm === "reject" ? "danger" : "default"} onConfirm={() => void transition()} />
  </main>;
}
