import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, Edit3, RotateCcw, TableProperties } from "lucide-react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { Button } from "@/components/ui/Button";
import { ConfirmDialog } from "@/components/ui/Dialog";
import { ROUTES } from "../contracts";
import { metadataModelingService } from "../services/metadata-modeling-service";
import { ExportSchemaButton } from "../components/ExportSchemaButton";
import { GovernedErrorState, PageHeader, PageSkeleton, formatDate, idempotencyKey } from "./page-utils";

// Lifecycle and governed-error branches intentionally render distinct operator states.
// eslint-disable-next-line complexity
export function MetadataSchemaDetailPage() {
  const { id = "" } = useParams(); const navigate = useNavigate(); const cache = useQueryClient(); const [confirm, setConfirm] = useState<{ action: "archive" | "restore" | "rollback"; versionId?: string } | null>(null);
  const detail = useQuery({ queryKey: ["metadata-definition", id], queryFn: () => metadataModelingService.getDefinition(id), enabled: Boolean(id) });
  const versions = useQuery({ queryKey: ["metadata-versions", id], queryFn: () => metadataModelingService.listVersions(id), enabled: Boolean(id) });
  const action = useMutation({ mutationFn: async () => { if (!confirm) return; if (confirm.action === "archive") await metadataModelingService.archiveDefinition(id, idempotencyKey()); if (confirm.action === "restore") await metadataModelingService.restoreDefinition(id, idempotencyKey()); if (confirm.action === "rollback" && confirm.versionId) await metadataModelingService.rollbackVersion(id, confirm.versionId, idempotencyKey()); }, onSuccess: async () => { setConfirm(null); await Promise.all([cache.invalidateQueries({ queryKey: ["metadata-definition", id] }), cache.invalidateQueries({ queryKey: ["metadata-versions", id] })]); } });
  if (detail.isLoading) return <PageSkeleton rows={7} />;
  if (detail.error) return <GovernedErrorState error={detail.error} onRetry={() => void detail.refetch()} />;
  const definition = detail.data; if (!definition) return null;
  const allowed = (name: string) => definition.allowed_actions?.includes(name) ?? true;
  return <main id="main-content" className="space-y-6 p-4 md:p-8"><PageHeader eyebrow={`${definition.origin} · ${definition.owner_module}`} title={definition.name} description={definition.description || `Metadata contract ${definition.code}`} actions={<><Button variant="outline" onClick={() => navigate(`${ROUTES.records}?entity_id=${encodeURIComponent(id)}`)}><TableProperties className="mr-2 h-4 w-4" />{definition.record_count} records</Button><ExportSchemaButton definitionId={id} code={definition.code} />{definition.status !== "archived" && allowed("update") && <Button onClick={() => navigate(ROUTES.schemaEdit(id))}><Edit3 className="mr-2 h-4 w-4" />Edit schema</Button>}{definition.status !== "archived" && allowed("archive") && <Button variant="danger" onClick={() => setConfirm({ action: "archive" })}><Archive className="mr-2 h-4 w-4" />Archive</Button>}{definition.status === "archived" && allowed("restore") && <Button onClick={() => setConfirm({ action: "restore" })}><RotateCcw className="mr-2 h-4 w-4" />Restore</Button>}</>} />
    {definition.status === "archived" && <div role="status" className="rounded-lg border border-border bg-muted p-4"><strong>Archived model.</strong> Records remain readable, but creation and schema publication are unavailable until restoration.</div>}
    <section className="grid gap-4 md:grid-cols-4">{[["Status", definition.status], ["Active version", definition.active_version_number ?? "—"], ["Naming", definition.naming_strategy], ["Updated", formatDate(definition.updated_at)]].map(([label, value]) => <div key={label} className="rounded-lg border border-border bg-card p-4"><p className="text-xs uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 font-semibold capitalize">{value}</p></div>)}</section>
    <div className="grid gap-6 lg:grid-cols-[2fr,1fr]"><section className="rounded-lg border border-border bg-card"><div className="border-b border-border p-4"><h2 className="font-semibold">Active fields</h2><p className="text-sm text-muted-foreground">Ordered descriptors pinned to version {definition.active_version_number ?? "draft"}.</p></div>{definition.active_fields.length === 0 ? <p className="p-6 text-muted-foreground">No fields have been defined.</p> : <div className="divide-y divide-border">{definition.active_fields.map((field) => <div key={field.id} className="grid gap-2 p-4 md:grid-cols-[1fr,1fr,2fr]"><div><p className="font-medium">{field.name}</p><code className="text-xs">{field.key}</code></div><p className="capitalize">{field.field_type}{field.is_required ? " · required" : ""}</p><p className="text-sm text-muted-foreground">{Object.keys(field.validation_rules).length ? JSON.stringify(field.validation_rules) : "No additional validation"}</p></div>)}</div>}</section><aside className="space-y-4"><section className="rounded-lg border border-border bg-card p-4"><h2 className="font-semibold">Behavior</h2><dl className="mt-3 space-y-2 text-sm"><div className="flex justify-between"><dt>Submittable</dt><dd>{definition.is_submittable ? "Yes" : "No"}</dd></div><div className="flex justify-between"><dt>Track changes</dt><dd>{definition.track_changes ? "Yes" : "No"}</dd></div><div className="flex justify-between"><dt>Lock version</dt><dd>{definition.lock_version}</dd></div></dl></section><section className="rounded-lg border border-border bg-card p-4"><h2 className="font-semibold">Naming configuration</h2><pre className="mt-3 overflow-auto rounded bg-muted p-3 text-xs">{JSON.stringify(definition.naming_config, null, 2)}</pre></section></aside></div>
    <section className="rounded-lg border border-border bg-card p-4"><h2 className="text-lg font-semibold">Version timeline</h2>{versions.isLoading && <PageSkeleton rows={3} />}{versions.error && <GovernedErrorState error={versions.error} onRetry={() => void versions.refetch()} />}{versions.data && <ol className="mt-4 space-y-3">{versions.data.items.map((version) => <li key={version.id} className="flex flex-col justify-between gap-3 rounded border border-border p-3 md:flex-row md:items-center"><div><p className="font-medium">Version {version.version} · <span className="capitalize">{version.status}</span></p><p className="text-sm text-muted-foreground">{version.change_summary || "No change summary"} · {formatDate(version.created_at)}</p></div><div className="flex gap-2">{definition.active_version && version.id !== definition.active_version && allowed("rollback") && <Button size="sm" variant="outline" onClick={() => setConfirm({ action: "rollback", versionId: version.id })}>Rollback</Button>}<Link className="self-center text-sm text-primary hover:underline" to={`${ROUTES.schemaEdit(id)}?version=${encodeURIComponent(version.id)}`}>Compare</Link></div></li>)}</ol>}</section>
    <ConfirmDialog open={confirm !== null} onOpenChange={(open) => { if (!open) setConfirm(null); }} title={confirm?.action === "rollback" ? "Publish rollback as a new version?" : confirm?.action === "restore" ? "Restore metadata model?" : "Archive metadata model?"} description="This governed action is immutable in the audit history and can be reversed through an explicit lifecycle command." confirmLabel={confirm?.action === "rollback" ? "Rollback" : confirm?.action === "restore" ? "Restore" : "Archive"} variant={confirm?.action === "archive" ? "danger" : "default"} onConfirm={() => action.mutate()} />
  </main>;
}
