import { useEffect, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Download, Eye, History, RotateCcw, Save, Upload } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { ConfirmDialog } from "@/components/ui/Dialog";
import { Input } from "@/components/ui/Input";
import type { ConfigurationExportDocument, ConfigurationPreview, FieldType, MetadataEnvironment, MetadataModelingConfiguration, MetadataModelingConfigurationValues } from "../contracts";
import { metadataModelingService } from "../services/metadata-modeling-service";
import { GovernedErrorState, PageHeader, PageSkeleton, formatDate } from "./page-utils";

const FIELD_TYPES: readonly FieldType[] = ["text", "number", "date", "boolean", "select", "reference", "json"];
function editable(config: MetadataModelingConfiguration): MetadataModelingConfigurationValues { return { synchronous_validation_limit: config.synchronous_validation_limit, max_fields_per_schema: config.max_fields_per_schema, max_schema_bytes: config.max_schema_bytes, max_record_data_bytes: config.max_record_data_bytes, max_regex_length: config.max_regex_length, default_page_size: config.default_page_size, max_page_size: config.max_page_size, allowed_field_types: config.allowed_field_types, feature_flags: config.feature_flags, rollout: config.rollout }; }
function isObject(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
function isConfigurationExport(value: unknown): value is ConfigurationExportDocument { return isObject(value) && typeof value.format_version === "string" && typeof value.environment === "string" && typeof value.checksum === "string" && isObject(value.values); }

// Configuration states remain explicit to prevent preview/apply/rollback ambiguity.
// eslint-disable-next-line complexity
export function MetadataModelingSettingsPage() {
  const cache = useQueryClient(); const [environment, setEnvironment] = useState<MetadataEnvironment>("development"); const [values, setValues] = useState<MetadataModelingConfigurationValues | null>(null); const [preview, setPreview] = useState<ConfigurationPreview | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [rollbackVersion, setRollbackVersion] = useState<number | null>(null);
  const configuration = useQuery({ queryKey: ["metadata-configuration", environment], queryFn: () => metadataModelingService.getConfiguration(environment) }); const history = useQuery({ queryKey: ["metadata-configuration-versions", environment], queryFn: () => metadataModelingService.listConfigurationVersions(environment) });
  useEffect(() => { if (configuration.data) { setValues(editable(configuration.data)); setPreview(null); setError(""); } }, [configuration.data]);
  if (configuration.isLoading) return <PageSkeleton rows={8} />; if (configuration.error) return <GovernedErrorState error={configuration.error} onRetry={() => void configuration.refetch()} />; const config = configuration.data; if (!config || !values) return null;
  const change = (next: MetadataModelingConfigurationValues) => { setValues(next); setPreview(null); setError(""); };
  const numeric = (key: "synchronous_validation_limit" | "max_fields_per_schema" | "max_schema_bytes" | "max_record_data_bytes" | "max_regex_length" | "default_page_size" | "max_page_size", value: number) => change({ ...values, [key]: value });
  const clientError = Object.values({ synchronous_validation_limit: values.synchronous_validation_limit, max_fields_per_schema: values.max_fields_per_schema, max_schema_bytes: values.max_schema_bytes, max_record_data_bytes: values.max_record_data_bytes, max_regex_length: values.max_regex_length, default_page_size: values.default_page_size, max_page_size: values.max_page_size }).some((value) => !Number.isInteger(value) || value < 1) ? "Limits must be positive whole numbers." : values.default_page_size > values.max_page_size ? "Default page size cannot exceed maximum page size." : values.allowed_field_types.length === 0 ? "At least one field type must remain available." : "";
  const previewChanges = async () => { if (clientError) return; setBusy(true); try { setPreview(await metadataModelingService.previewConfiguration(environment, values)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Preview failed."); } finally { setBusy(false); } };
  const apply = async () => { if (!preview?.valid) return; setBusy(true); try { await metadataModelingService.updateConfiguration(environment, values, config.version); setPreview(null); await Promise.all([cache.invalidateQueries({ queryKey: ["metadata-configuration", environment] }), cache.invalidateQueries({ queryKey: ["metadata-configuration-versions", environment] })]); } catch (reason) { setError(reason instanceof Error ? reason.message : "Update failed."); } finally { setBusy(false); } };
  const exportDocument = async () => { const document = await metadataModelingService.exportConfiguration(environment); const url = URL.createObjectURL(new Blob([JSON.stringify(document, null, 2)], { type: "application/json" })); const link = window.document.createElement("a"); link.href = url; link.download = `metadata-modeling-${environment}-configuration.json`; link.click(); URL.revokeObjectURL(url); };
  const importDocument = async (file: File) => { setBusy(true); setError(""); try { const parsed: unknown = JSON.parse(await file.text()); if (!isConfigurationExport(parsed)) throw new Error("The configuration document is malformed."); const validation = await metadataModelingService.importConfiguration({ environment, document: parsed, validate_only: true }); if ("effective_values" in validation) { setValues(validation.effective_values); setPreview(validation); } else throw new Error("Validate-only import returned an applied configuration."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Import failed."); } finally { setBusy(false); } };
  return <main id="main-content" className="space-y-6 p-4 md:p-8"><PageHeader title="Metadata Modeling Settings" description="Versioned, tenant-scoped operational policy. Preview every change, then apply it through the same governed API used by automation." actions={<><label className="inline-flex cursor-pointer items-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium hover:bg-accent"><Upload className="mr-2 h-4 w-4" />Import<input className="sr-only" type="file" accept="application/json,.json" onChange={(event) => { const file = event.target.files?.[0]; if (file) void importDocument(file); }} /></label><Button variant="outline" onClick={() => void exportDocument()}><Download className="mr-2 h-4 w-4" />Export</Button></>} />
    <section className="rounded-lg border border-border bg-card p-5"><label className="block max-w-sm"><span className="text-sm font-medium">Environment</span><select className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3" value={environment} onChange={(event) => setEnvironment(event.target.value as MetadataEnvironment)}><option value="development">Development</option><option value="staging">Staging</option><option value="production">Production</option></select></label><p className="mt-2 text-xs text-muted-foreground">Configuration version {config.version} · updated {formatDate(config.updated_at)} by {config.updated_by}</p></section>
    <section className="grid gap-5 rounded-lg border border-border bg-card p-5 md:grid-cols-2 lg:grid-cols-3"><h2 className="col-span-full text-lg font-semibold">Safe operating limits</h2><Input type="number" min={1} label="Synchronous validation records" value={values.synchronous_validation_limit} onChange={(event) => numeric("synchronous_validation_limit", Number(event.target.value))} /><Input type="number" min={1} label="Fields per schema" value={values.max_fields_per_schema} onChange={(event) => numeric("max_fields_per_schema", Number(event.target.value))} /><Input type="number" min={1} label="Schema bytes" value={values.max_schema_bytes} onChange={(event) => numeric("max_schema_bytes", Number(event.target.value))} /><Input type="number" min={1} label="Record data bytes" value={values.max_record_data_bytes} onChange={(event) => numeric("max_record_data_bytes", Number(event.target.value))} /><Input type="number" min={1} label="Regex length" value={values.max_regex_length} onChange={(event) => numeric("max_regex_length", Number(event.target.value))} /><Input type="number" min={1} label="Default page size" value={values.default_page_size} onChange={(event) => numeric("default_page_size", Number(event.target.value))} /><Input type="number" min={1} label="Maximum page size" value={values.max_page_size} onChange={(event) => numeric("max_page_size", Number(event.target.value))} />{clientError && <p role="alert" className="col-span-full text-sm text-destructive">{clientError}</p>}</section>
    <section className="rounded-lg border border-border bg-card p-5"><h2 className="text-lg font-semibold">Allowed field types</h2><p className="text-sm text-muted-foreground">Disable a type for new candidates without invalidating historical schemas.</p><div className="mt-4 flex flex-wrap gap-4">{FIELD_TYPES.map((type) => <label key={type} className="flex items-center gap-2"><input type="checkbox" checked={values.allowed_field_types.includes(type)} onChange={(event) => change({ ...values, allowed_field_types: event.target.checked ? [...values.allowed_field_types, type] : values.allowed_field_types.filter((item) => item !== type) })} />{type}</label>)}</div></section>
    <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-lg border border-border bg-card p-5"><h2 className="text-lg font-semibold">Feature flags</h2><div className="mt-4 space-y-3">{Object.entries(values.feature_flags).map(([flag, enabled]) => <label key={flag} className="flex items-center justify-between rounded border border-border p-3"><code>{flag}</code><input type="checkbox" checked={enabled} onChange={(event) => change({ ...values, feature_flags: { ...values.feature_flags, [flag]: event.target.checked } })} /></label>)}</div></div><div className="rounded-lg border border-border bg-card p-5"><h2 className="text-lg font-semibold">Phased rollout</h2><div className="mt-4 space-y-4">{Object.entries(values.rollout).map(([capability, rollout]) => <fieldset key={capability} className="rounded border border-border p-3"><legend className="px-1 font-mono text-sm">{capability}</legend><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={rollout.enabled} onChange={(event) => change({ ...values, rollout: { ...values.rollout, [capability]: { ...rollout, enabled: event.target.checked } } })} />Enabled</label><Input className="mt-2" type="number" min={0} max={100} label="Tenant percentage" value={rollout.tenant_percentage} onChange={(event) => change({ ...values, rollout: { ...values.rollout, [capability]: { ...rollout, tenant_percentage: Math.min(100, Math.max(0, Number(event.target.value))) } } })} /><p className="mt-2 text-xs text-muted-foreground">Roles: {rollout.roles.join(", ") || "all"} · Cohorts: {rollout.cohorts.join(", ") || "all"}</p></fieldset>)}</div></div></section>
    <section className="rounded-lg border border-border bg-card p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-lg font-semibold">Preview and apply</h2><p className="text-sm text-muted-foreground">Server validation and an exact diff are required before apply.</p></div><div className="flex gap-2"><Button variant="outline" disabled={busy || Boolean(clientError)} onClick={() => void previewChanges()}><Eye className="mr-2 h-4 w-4" />Preview diff</Button><Button disabled={busy || !preview?.valid} onClick={() => void apply()}><Save className="mr-2 h-4 w-4" />Apply version</Button></div></div>{preview && <div className="mt-4 space-y-2">{preview.diff.length === 0 ? <p className="text-sm text-muted-foreground">No effective changes.</p> : preview.diff.map((entry) => <div key={entry.path} className="grid gap-2 rounded border border-border p-3 text-sm md:grid-cols-[1fr,2fr,2fr]"><code>{entry.path}</code><span className="break-all text-muted-foreground">{JSON.stringify(entry.before)}</span><span className="break-all">{JSON.stringify(entry.after)}</span></div>)}{preview.errors.map((item, index) => <p key={`${item.code}:${index}`} className="text-sm text-destructive">{item.message}</p>)}</div>}{error && <p role="alert" className="mt-4 text-sm text-destructive">{error}</p>}</section>
    <section className="rounded-lg border border-border bg-card p-5"><h2 className="flex items-center gap-2 text-lg font-semibold"><History className="h-5 w-5" />Immutable audit history</h2>{history.isLoading ? <PageSkeleton rows={3} /> : history.error ? <GovernedErrorState error={history.error} onRetry={() => void history.refetch()} /> : <ol className="mt-4 space-y-3">{history.data?.items.map((version) => <li key={version.id} className="flex flex-col justify-between gap-3 rounded border border-border p-3 md:flex-row md:items-center"><div><p className="font-medium">Version {version.version} · {version.operation}</p><p className="text-xs text-muted-foreground">{formatDate(version.changed_at)} · {version.changed_by} · Correlation {version.correlation_id}</p><p className="mt-1 text-sm text-muted-foreground">{version.changes.length} changed values</p></div><Button variant="outline" size="sm" disabled={version.version === config.version} onClick={() => setRollbackVersion(version.version)}><RotateCcw className="mr-2 h-4 w-4" />Rollback</Button></li>)}</ol>}</section>
    <ConfirmDialog open={rollbackVersion !== null} onOpenChange={(open) => { if (!open) setRollbackVersion(null); }} title={`Rollback to version ${rollbackVersion ?? ""}?`} description="Rollback creates a new immutable configuration version; it never rewrites audit history." confirmLabel="Create rollback version" onConfirm={() => { if (rollbackVersion === null) return; setBusy(true); void metadataModelingService.rollbackConfiguration(environment, rollbackVersion).then(async () => { setRollbackVersion(null); await Promise.all([cache.invalidateQueries({ queryKey: ["metadata-configuration", environment] }), cache.invalidateQueries({ queryKey: ["metadata-configuration-versions", environment] })]); }).catch((reason: Error) => setError(reason.message)).finally(() => setBusy(false)); }} />
  </main>;
}
