import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, Copy, Database, Plus, Search } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { EmptyState } from "@/components/ui/EmptyState";
import { ConfirmDialog } from "@/components/ui/Dialog";
import { ROUTES, type EntityOrigin, type EntityStatus } from "../contracts";
import { metadataModelingService } from "../services/metadata-modeling-service";
import { ExportSchemaButton } from "../components/ExportSchemaButton";
import { GovernedErrorState, PageHeader, PageSkeleton, formatDate, idempotencyKey } from "./page-utils";

export function MetadataSchemaListPage() {
  const navigate = useNavigate(); const client = useQueryClient();
  const [search, setSearch] = useState(""); const [status, setStatus] = useState<EntityStatus | "">(""); const [origin, setOrigin] = useState<EntityOrigin | "">(""); const [owner, setOwner] = useState(""); const [ordering, setOrdering] = useState<"name" | "-name" | "-updated_at">("name"); const [page, setPage] = useState(1); const [archiveId, setArchiveId] = useState<string | null>(null);
  const query = useQuery({ queryKey: ["metadata-definitions", { search, status, origin, owner, ordering, page }], queryFn: () => metadataModelingService.listDefinitions({ search: search || undefined, status: status || undefined, origin: origin || undefined, owner_module: owner || undefined, ordering, page, page_size: 25 }) });
  if (query.isLoading) return <PageSkeleton />;
  if (query.error) return <GovernedErrorState error={query.error} onRetry={() => void query.refetch()} />;
  const result = query.data; if (!result) return null; const filtered = Boolean(search || status || origin || owner);
  const clone = async (definitionId: string, code: string, name: string) => { await metadataModelingService.cloneDefinition(definitionId, `${code}-copy`, `${name} copy`); await client.invalidateQueries({ queryKey: ["metadata-definitions"] }); };
  return <main id="main-content" className="space-y-6 p-4 md:p-8"><PageHeader title="Metadata Models" description="Design, validate, publish, and roll back tenant-owned data models without database changes." actions={<Button onClick={() => navigate(ROUTES.schemaCreate)}><Plus className="mr-2 h-4 w-4" />Create schema</Button>} />
    <section aria-label="Schema filters" className="grid gap-3 rounded-lg border border-border bg-card p-4 md:grid-cols-5"><div className="relative md:col-span-2"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input aria-label="Search schemas" className="pl-9" value={search} placeholder="Search name or code" onChange={(event) => { setSearch(event.target.value); setPage(1); }} /></div><select aria-label="Status" className="rounded-md border border-input bg-background px-3" value={status} onChange={(event) => { setStatus(event.target.value as EntityStatus | ""); setPage(1); }}><option value="">All statuses</option><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select><select aria-label="Origin" className="rounded-md border border-input bg-background px-3" value={origin} onChange={(event) => { setOrigin(event.target.value as EntityOrigin | ""); setPage(1); }}><option value="">All origins</option><option value="custom">Custom</option><option value="system">System</option><option value="extension">Extension</option></select><Input aria-label="Owner module" value={owner} placeholder="Owner module" onChange={(event) => { setOwner(event.target.value); setPage(1); }} /></section>
    {result.items.length === 0 ? <EmptyState icon={Database} title={filtered ? "No matching metadata models" : "Create your first metadata model"} description={filtered ? "Change or clear the server-side filters." : "Define fields, preview the generated form, then publish safely."} action={filtered ? undefined : { label: "Create schema", onClick: () => navigate(ROUTES.schemaCreate) }} /> : <div className="overflow-x-auto rounded-lg border border-border"><table className="w-full text-left text-sm"><thead className="bg-muted"><tr>{[["name", "Name"], ["code", "Code"], ["owner", "Owner"], ["origin", "Origin"], ["status", "Status"], ["version", "Version"], ["count", "Records"]].map((column) => <th key={column[0]} className="px-4 py-3 font-medium">{column[1]}</th>)}<th className="px-4 py-3"><button onClick={() => setOrdering(ordering === "-updated_at" ? "name" : "-updated_at")}>Updated ↕</button></th><th className="px-4 py-3">Actions</th></tr></thead><tbody>{result.items.map((definition) => <tr key={definition.id} className="border-t border-border"><td className="px-4 py-3 font-medium"><Link className="text-primary hover:underline" to={ROUTES.schemaDetail(definition.id)}>{definition.name}</Link></td><td className="px-4 py-3"><code>{definition.code}</code></td><td className="px-4 py-3">{definition.owner_module}</td><td className="px-4 py-3 capitalize">{definition.origin}</td><td className="px-4 py-3 capitalize">{definition.status}</td><td className="px-4 py-3">{definition.active_version_number ?? "—"}</td><td className="px-4 py-3">{definition.record_count}</td><td className="px-4 py-3 whitespace-nowrap">{formatDate(definition.updated_at)}</td><td className="px-4 py-3"><div className="flex gap-1"><Button size="sm" variant="ghost" onClick={() => navigate(ROUTES.schemaDetail(definition.id))}>View</Button>{definition.status === "draft" && <Button size="sm" variant="ghost" onClick={() => navigate(ROUTES.schemaEdit(definition.id))}>Edit</Button>}<Button size="icon" variant="ghost" aria-label={`Clone ${definition.name}`} onClick={() => void clone(definition.id, definition.code, definition.name)}><Copy className="h-4 w-4" /></Button><ExportSchemaButton size="icon" aria-label={`Export ${definition.name}`} definitionId={definition.id} code={definition.code} /><Button size="icon" variant="ghost" aria-label={`Archive ${definition.name}`} disabled={definition.status === "archived"} onClick={() => setArchiveId(definition.id)}><Archive className="h-4 w-4" /></Button></div></td></tr>)}</tbody></table></div>}
    <div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">Page {result.pagination.page} of {result.pagination.total_pages || 1} · {result.pagination.count} models</p><div className="flex gap-2"><Button variant="outline" disabled={!result.pagination.has_previous} onClick={() => setPage((value) => Math.max(1, value - 1))}>Previous</Button><Button variant="outline" disabled={!result.pagination.has_next} onClick={() => setPage((value) => value + 1)}>Next</Button></div></div>
    <ConfirmDialog open={archiveId !== null} onOpenChange={(open) => { if (!open) setArchiveId(null); }} title="Archive metadata model?" description="New records cannot be created until the model is restored." confirmLabel="Archive" variant="danger" onConfirm={() => { if (!archiveId) return; void metadataModelingService.archiveDefinition(archiveId, idempotencyKey()).then(() => client.invalidateQueries({ queryKey: ["metadata-definitions"] })); }} />
  </main>;
}
