import { useMutation } from '@tanstack/react-query';
import { useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Button } from '@/components/ui/Button'; import { Card } from '@/components/ui/Card'; import { Input } from '@/components/ui/Input'; import { Textarea } from '@/components/ui/Textarea';
import { PROCESS_MINING_ROUTES, type ProcessGraph } from '../contracts';
import { ApiProblem, PageHeader } from '../components/ModuleShell';
import { processMiningService } from '../services/process_mining-service';

export function CreateProcessModelPage() {
  const navigate = useNavigate(); const [params] = useSearchParams(); const [name, setName] = useState(''); const [processName, setProcessName] = useState(params.get('process_name') ?? ''); const [description, setDescription] = useState(''); const [graph, setGraph] = useState('{\n  "schema_version": "1.0",\n  "nodes": [],\n  "edges": []\n}'); const [validation, setValidation] = useState('');
  const mutation = useMutation({ mutationFn: async () => { let model: ProcessGraph; try { model = JSON.parse(graph) as ProcessGraph; } catch { throw new Error('Model graph must be valid JSON.'); } if (model.schema_version !== '1.0' || !Array.isArray(model.nodes) || model.nodes.length === 0 || !Array.isArray(model.edges)) throw new Error('Use graph schema 1.0 with at least one node and an edge array.'); return processMiningService.createModel({ name: name.trim(), process_name: processName.trim(), description: description.trim(), model_data: model }); }, onSuccess: (model) => navigate(PROCESS_MINING_ROUTES.MODEL_MAP(model.id)) });
  return <main className="space-y-6 p-4 sm:p-8"><PageHeader title="Create process model" description="Import a validated canonical graph, or start a discovery from an existing event log." actions={<Button variant="outline" onClick={() => navigate(PROCESS_MINING_ROUTES.DISCOVERY_CREATE_FOR_PROCESS(processName))}>Discover instead</Button>}/>{mutation.error && <ApiProblem error={mutation.error} onRetry={() => mutation.reset()}/>}<Card className="mx-auto max-w-4xl p-6"><form className="space-y-5" onSubmit={(event) => { event.preventDefault(); setValidation(''); if (!name.trim() || !processName.trim()) { setValidation('Name and process name are required.'); return; } mutation.mutate(); }}><div className="grid gap-4 sm:grid-cols-2"><Input id="model-name" label="Model name" value={name} onChange={(event) => setName(event.target.value)} required/><Input id="process-name" label="Process name" value={processName} onChange={(event) => setProcessName(event.target.value)} required/></div><Textarea id="description" label="Description" value={description} onChange={(event) => setDescription(event.target.value)} rows={3}/><Textarea id="graph" label="Canonical graph JSON" value={graph} onChange={(event) => setGraph(event.target.value)} rows={15} className="font-mono text-xs" aria-describedby="graph-help"/><p id="graph-help" className="text-xs text-muted-foreground">Schema 1.0 uses deterministic node ids, node types start/activity/end/gateway, and edges whose endpoints exist.</p>{validation && <p role="alert" className="text-sm text-destructive">{validation}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => navigate(PROCESS_MINING_ROUTES.PROCESSES)}>Cancel</Button><Button type="submit" disabled={mutation.isPending}>{mutation.isPending ? 'Validating and publishing…' : 'Publish immutable version'}</Button></div></form></Card></main>;
}
