import { useState } from 'react'; import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate, useSearchParams } from 'react-router-dom'; import { Clock, Plus } from 'lucide-react'; import { toast } from 'sonner';
import { Button } from '@/components/ui/Button'; import { ROUTES, hrKeys } from '../contracts'; import type { AttendanceFilters, AttendanceStatus } from '../contracts';
import { hrService, newIntentKey } from '../services/hr-service'; import { can, EmptyPanel, GovernedError, PageShell, PageSkeleton, Pagination, StatusChip, formatInstant } from '../components/hr-ui';
import { useHumanResourcesConfiguration } from '../hooks/use-hr-configuration';
// eslint-disable-next-line complexity -- filtering, governed clocking, and evidence rendering are one page flow.
export function AttendanceListPage() {
  const navigate = useNavigate(); const client = useQueryClient(); const [params, setParams] = useSearchParams(); const [clockEmployee, setClockEmployee] = useState('');
  const configuration = useHumanResourcesConfiguration(); const document = configuration.data?.data.document;
  const filters: AttendanceFilters = { page: Number(params.get('page') ?? 1), page_size: document?.limits.list_page_size, search: params.get('search') ?? undefined, status: (params.get('status') ?? undefined) as AttendanceStatus | undefined, ordering: '-attendance_date' };
  const query = useQuery({ queryKey: hrKeys.attendances(filters), queryFn: () => hrService.listAttendances(filters), enabled: Boolean(document) });
  const employeeFilters = { page: 1, page_size: document?.limits.lookup_page_size };
  const employees = useQuery({ queryKey: hrKeys.employees(employeeFilters), queryFn: () => hrService.listEmployees(employeeFilters), enabled: Boolean(document) });
  const clockIn = useMutation({ mutationFn: (employeeId: string) => hrService.clockIn({ employee_id: employeeId, idempotency_key: newIntentKey() }), onSuccess: () => { void client.invalidateQueries({ queryKey: hrKeys.all }); toast.success('Clock-in recorded'); } });
  const update = (key: string, value: string) => { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); if (key !== 'page') next.set('page', '1'); setParams(next); };
  if (configuration.isLoading || query.isLoading || employees.isLoading) return <PageSkeleton />; if (configuration.error || query.error || employees.error) return <PageShell title="Attendance" description="Daily attendance evidence."><GovernedError error={configuration.error ?? query.error ?? employees.error} retry={() => { void configuration.refetch(); void query.refetch(); void employees.refetch(); }} resource="Attendance" /></PageShell>;
  const result = query.data; return <PageShell title="Attendance" description="Capture daily status, clock evidence, and auditable corrections." actions={<>{result && can(result.capabilities, 'hr.attendance:create') ? <Button variant="outline" className="min-h-11" onClick={() => navigate(ROUTES.ATTENDANCE_CREATE)}><Plus className="mr-2 h-4 w-4" />Manual record</Button> : null}</>}>
    <section aria-label="Attendance filters" className="grid gap-3 rounded-xl border bg-card p-4 sm:grid-cols-2 lg:grid-cols-4"><input aria-label="Search attendance" className="min-h-11 rounded-md border bg-background px-3" placeholder="Employee name or number" value={filters.search ?? ''} onChange={(event) => update('search', event.target.value)} /><select aria-label="Attendance status" className="min-h-11 rounded-md border bg-background px-3" value={filters.status ?? ''} onChange={(event) => update('status', event.target.value)}><option value="">All statuses</option>{document!.allowed_values.attendance_statuses.map((item) => <option key={item}>{item}</option>)}</select>{result && can(result.capabilities, 'hr.attendance:clock') ? employees.data?.items.length ? <><select aria-label="Employee to clock in" className="min-h-11 rounded-md border bg-background px-3" value={clockEmployee} onChange={(event) => setClockEmployee(event.target.value)}><option value="">Select employee to clock in</option>{employees.data.items.map((employee) => <option key={employee.id} value={employee.id}>{employee.full_name} · {employee.employee_number}</option>)}</select><Button variant="outline" disabled={clockIn.isPending || !clockEmployee} onClick={() => clockIn.mutate(clockEmployee)}><Clock className="mr-2 h-4 w-4" />{clockIn.isPending ? 'Clocking in…' : 'Clock in'}</Button></> : <p className="self-center text-sm text-muted-foreground lg:col-span-2">No configured clock-eligible employees are available.</p> : <p className="self-center text-sm text-muted-foreground lg:col-span-2">Clock actions are unavailable until access policy returns an explicit decision.</p>}</section>
    {clockIn.error ? <GovernedError error={clockIn.error} resource="Clock-in" /> : null}
    {!result?.items.length ? <EmptyPanel title="No attendance records" description="No records match the current filters. Create a manual record when authorized." action={result && can(result.capabilities, 'hr.attendance:create') ? { label: 'Record attendance', onClick: () => navigate(ROUTES.ATTENDANCE_CREATE) } : undefined} /> : <section className="overflow-hidden rounded-xl border bg-card"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="bg-muted/50 text-left text-xs uppercase text-muted-foreground"><tr><th className="px-4 py-3">Employee</th><th className="px-4 py-3">Date</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Check in</th><th className="px-4 py-3">Check out</th><th className="px-4 py-3">Hours</th></tr></thead><tbody className="divide-y">{result.items.map((item) => <tr key={item.id}><td className="px-4 py-4"><Link className="font-semibold text-primary hover:underline" to={ROUTES.ATTENDANCE_DETAIL(item.id)}>{item.employee_name}</Link><span className="block text-xs text-muted-foreground">{item.employee_number}</span></td><td className="px-4 py-4">{item.attendance_date}</td><td className="px-4 py-4"><StatusChip status={item.status} /></td><td className="px-4 py-4">{formatInstant(item.check_in_time)}</td><td className="px-4 py-4">{formatInstant(item.check_out_time)}</td><td className="px-4 py-4">{item.hours_worked}</td></tr>)}</tbody></table></div><Pagination page={result.pagination.page} totalPages={result.pagination.total_pages} onPage={(page) => update('page', String(page))} /></section>}
  </PageShell>;
}
