import { useQuery } from '@tanstack/react-query';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { Plus, Search } from 'lucide-react';
import { Button } from '@/components/ui/Button'; import { Input } from '@/components/ui/Input';
import { ROUTES, hrKeys } from '../contracts'; import type { DepartmentFilters } from '../contracts'; import { hrService } from '../services/hr-service';
import { can, EmptyPanel, GovernedError, PageShell, PageSkeleton, Pagination, StatusChip } from '../components/hr-ui';
export function DepartmentListPage() {
  const navigate = useNavigate(); const [params, setParams] = useSearchParams();
  const filters: DepartmentFilters = { page: Number(params.get('page') ?? 1), page_size: 25, search: params.get('search') ?? undefined, is_active: params.get('active') ? params.get('active') === 'true' : undefined, ordering: 'department_code' };
  const query = useQuery({ queryKey: hrKeys.departments(filters), queryFn: () => hrService.listDepartments(filters) });
  const update = (key: string, value: string) => { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); if (key !== 'page') next.set('page', '1'); setParams(next); };
  if (query.isLoading) return <PageSkeleton />; if (query.error) return <PageShell title="Departments" description="Organizational hierarchy."><GovernedError error={query.error} retry={() => void query.refetch()} resource="Departments" /></PageShell>;
  const result = query.data; return <PageShell title="Departments" description="Navigate the organization through named, manager-owned departments." actions={result && can(result.capabilities, 'hr.department:create') ? <Button className="min-h-11" onClick={() => navigate(ROUTES.DEPARTMENT_CREATE)}><Plus className="mr-2 h-4 w-4" />New department</Button> : null}>
    <section className="grid gap-3 rounded-xl border bg-card p-4 sm:grid-cols-2" aria-label="Department filters"><div className="relative"><Search className="absolute left-3 top-3.5 h-4 w-4 text-muted-foreground" /><Input aria-label="Search departments" className="pl-9" value={filters.search ?? ''} onChange={(event) => update('search', event.target.value)} placeholder="Code or name" /></div><select aria-label="Department state" className="min-h-11 rounded-md border bg-background px-3" value={params.get('active') ?? ''} onChange={(event) => update('active', event.target.value)}><option value="">All departments</option><option value="true">Active</option><option value="false">Inactive</option></select></section>
    {!result?.items.length ? <EmptyPanel title="No departments found" description="Create a top-level department or change the current filters." action={result && can(result.capabilities, 'hr.department:create') ? { label: 'Create department', onClick: () => navigate(ROUTES.DEPARTMENT_CREATE) } : undefined} /> : <section className="overflow-hidden rounded-xl border bg-card"><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead className="bg-muted/50 text-left text-xs uppercase text-muted-foreground"><tr><th className="px-4 py-3">Department</th><th className="px-4 py-3">Parent</th><th className="px-4 py-3">Manager</th><th className="px-4 py-3">State</th></tr></thead><tbody className="divide-y">{result.items.map((item) => <tr key={item.id}><td className="px-4 py-4"><Link className="font-semibold text-primary hover:underline" to={ROUTES.DEPARTMENT_DETAIL(item.id)}>{item.department_name}</Link><span className="block text-xs text-muted-foreground">{item.department_code}</span></td><td className="px-4 py-4">{item.parent_department_name ?? 'Top level'}</td><td className="px-4 py-4">{item.manager_name ?? 'Unassigned'}</td><td className="px-4 py-4"><StatusChip status={item.is_active ? 'active' : 'inactive'} /></td></tr>)}</tbody></table></div><Pagination page={result.pagination.page} totalPages={result.pagination.total_pages} onPage={(page) => update('page', String(page))} /></section>}
  </PageShell>;
}
