import { useQuery } from '@tanstack/react-query'; import { Link, useNavigate, useSearchParams } from 'react-router-dom'; import { CalendarDays, Plus } from 'lucide-react'; import { Button } from '@/components/ui/Button';
import { ROUTES, hrKeys } from '../contracts'; import type { LeaveRequestStatus, LeaveWorkspaceScope } from '../contracts'; import { hrService } from '../services/hr-service';
import { can, EmptyPanel, GovernedError, PageShell, PageSkeleton, Pagination, StatusChip } from '../components/hr-ui';
// eslint-disable-next-line complexity -- balances, scoped requests, and calendar context are one workspace.
export function LeaveWorkspacePage() {
  const navigate = useNavigate(); const [params, setParams] = useSearchParams();
  const scope = (params.get('scope') ?? 'all') as LeaveWorkspaceScope; const status = (params.get('status') ?? undefined) as LeaveRequestStatus | undefined; const page = Number(params.get('page') ?? 1);
  const requests = useQuery({ queryKey: hrKeys.leaveRequests({ page, page_size: 25, scope, status, ordering: '-start_date' }), queryFn: () => hrService.listLeaveRequests({ page, page_size: 25, scope, status, ordering: '-start_date' }) });
  const balances = useQuery({ queryKey: hrKeys.leaveBalances({ page: 1, page_size: 100, active_period: true }), queryFn: () => hrService.listLeaveBalances({ page: 1, page_size: 100, active_period: true }) });
  const set = (key: string, value: string) => { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); if (key !== 'page') next.set('page', '1'); setParams(next); };
  if (requests.isLoading || balances.isLoading) return <PageSkeleton cards={4} />;
  const result = requests.data; return <PageShell title="Leave" description="Balances, requests, approval queue, and calendar context in one governed workspace." actions={<>{result && can(result.capabilities, 'hr.leave_balance:create') ? <Button variant="outline" onClick={() => navigate(ROUTES.LEAVE_BALANCE_CREATE)} className="min-h-11">Allocate leave</Button> : null}{result && can(result.capabilities, 'hr.leave_request:create') ? <Button onClick={() => navigate(ROUTES.LEAVE_REQUEST_CREATE)} className="min-h-11"><Plus className="mr-2 h-4 w-4" />Request leave</Button> : null}</>}>
    <section aria-label="Leave view" className="grid gap-3 rounded-xl border bg-card p-4 sm:grid-cols-2"><select aria-label="Leave scope" className="min-h-11 rounded-md border bg-background px-3" value={scope} onChange={(event) => set('scope', event.target.value)}><option value="all">All allowed requests</option><option value="self">My requests</option><option value="team">My team</option><option value="approval_queue">Approval queue</option></select><select aria-label="Leave status" className="min-h-11 rounded-md border bg-background px-3" value={status ?? ''} onChange={(event) => set('status', event.target.value)}><option value="">All states</option>{['pending', 'approved', 'rejected', 'cancelled'].map((item) => <option key={item}>{item}</option>)}</select></section>
    {balances.error ? <GovernedError error={balances.error} retry={() => void balances.refetch()} resource="Leave balances" /> : <section aria-label="Current balances"><h2 className="mb-3 text-lg font-semibold">Current balances</h2>{!balances.data?.items.length ? <p className="rounded-xl border bg-card p-5 text-sm text-muted-foreground">No current allocations are available. An authorized HR user can create one; requests never invent entitlement.</p> : <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{balances.data.items.map((balance) => <Link key={balance.id} to={ROUTES.LEAVE_BALANCE_DETAIL(balance.id)} className="rounded-xl border bg-card p-4 hover:border-primary/50 focus-visible:ring-2"><span className="text-sm capitalize">{balance.leave_type}</span><strong className="mt-1 block text-2xl">{balance.remaining_days} days</strong><span className="text-xs text-muted-foreground">{balance.employee_name} · {balance.period_end}</span></Link>)}</div>}</section>}
    <section aria-label="Leave requests"><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-semibold">Requests</h2><span className="flex items-center text-xs text-muted-foreground"><CalendarDays className="mr-1 h-4 w-4" />Calendar-day calculation</span></div>{requests.error ? <GovernedError error={requests.error} retry={() => void requests.refetch()} resource={scope === 'self' || scope === 'team' ? 'This leave view' : 'Leave requests'} /> : !result?.items.length ? <EmptyPanel title="No leave requests" description={scope === 'self' || scope === 'team' ? 'This secure view requires an actor-to-employee resolver. If unavailable, use an explicitly policy-scoped view.' : 'No requests match this scope and state.'} action={result && can(result.capabilities, 'hr.leave_request:create') ? { label: 'Request leave', onClick: () => navigate(ROUTES.LEAVE_REQUEST_CREATE) } : undefined} /> : <div className="overflow-hidden rounded-xl border bg-card"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="bg-muted/50 text-left text-xs uppercase text-muted-foreground"><tr><th className="px-4 py-3">Employee</th><th className="px-4 py-3">Leave</th><th className="px-4 py-3">Dates</th><th className="px-4 py-3">Days</th><th className="px-4 py-3">State</th></tr></thead><tbody className="divide-y">{result.items.map((item) => <tr key={item.id}><td className="px-4 py-4"><Link className="font-semibold text-primary hover:underline" to={ROUTES.LEAVE_REQUEST_DETAIL(item.id)}>{item.employee_name}</Link><span className="block text-xs text-muted-foreground">{item.employee_number}</span></td><td className="px-4 py-4 capitalize">{item.leave_type}</td><td className="px-4 py-4">{item.start_date} – {item.end_date}</td><td className="px-4 py-4">{item.days_requested}</td><td className="px-4 py-4"><StatusChip status={item.status} /></td></tr>)}</tbody></table></div><Pagination page={result.pagination.page} totalPages={result.pagination.total_pages} onPage={(next) => set('page', String(next))} /></div>}</section>
  </PageShell>;
}
