import { lazy } from 'react';
import { Building2, ClipboardList, FileCheck2, PackageCheck, ReceiptText, Settings2, Scale } from 'lucide-react';
import type { TenantRoute, TenantRouteIcon } from '@/navigation/tenant-route-types';
import { ROUTES } from './contracts';

const modes = ['development', 'self-hosted', 'saas'] as const;
const pages = {
  SupplierListPage: lazy(() => import('./pages/SupplierListPage').then(value => ({ default: value.SupplierListPage }))), SupplierDetailPage: lazy(() => import('./pages/SupplierDetailPage').then(value => ({ default: value.SupplierDetailPage }))), CreateSupplierPage: lazy(() => import('./pages/CreateSupplierPage').then(value => ({ default: value.CreateSupplierPage }))), EditSupplierPage: lazy(() => import('./pages/EditSupplierPage').then(value => ({ default: value.EditSupplierPage }))),
  RequisitionListPage: lazy(() => import('./pages/RequisitionListPage').then(value => ({ default: value.RequisitionListPage }))), RequisitionDetailPage: lazy(() => import('./pages/RequisitionDetailPage').then(value => ({ default: value.RequisitionDetailPage }))), CreateRequisitionPage: lazy(() => import('./pages/CreateRequisitionPage').then(value => ({ default: value.CreateRequisitionPage }))), EditRequisitionPage: lazy(() => import('./pages/EditRequisitionPage').then(value => ({ default: value.EditRequisitionPage }))),
  RFQListPage: lazy(() => import('./pages/RFQListPage').then(value => ({ default: value.RFQListPage }))), RFQDetailPage: lazy(() => import('./pages/RFQDetailPage').then(value => ({ default: value.RFQDetailPage }))), CreateRFQPage: lazy(() => import('./pages/CreateRFQPage').then(value => ({ default: value.CreateRFQPage }))), EditRFQPage: lazy(() => import('./pages/EditRFQPage').then(value => ({ default: value.EditRFQPage }))),
  QuoteListPage: lazy(() => import('./pages/QuoteListPage').then(value => ({ default: value.QuoteListPage }))), QuoteDetailPage: lazy(() => import('./pages/QuoteDetailPage').then(value => ({ default: value.QuoteDetailPage }))), CreateQuotePage: lazy(() => import('./pages/CreateQuotePage').then(value => ({ default: value.CreateQuotePage }))), EditQuotePage: lazy(() => import('./pages/EditQuotePage').then(value => ({ default: value.EditQuotePage }))),
  PurchaseOrderListPage: lazy(() => import('./pages/PurchaseOrderListPage').then(value => ({ default: value.PurchaseOrderListPage }))), PurchaseOrderDetailPage: lazy(() => import('./pages/PurchaseOrderDetailPage').then(value => ({ default: value.PurchaseOrderDetailPage }))), CreatePurchaseOrderPage: lazy(() => import('./pages/CreatePurchaseOrderPage').then(value => ({ default: value.CreatePurchaseOrderPage }))), EditPurchaseOrderPage: lazy(() => import('./pages/EditPurchaseOrderPage').then(value => ({ default: value.EditPurchaseOrderPage }))),
  ReceiptListPage: lazy(() => import('./pages/ReceiptListPage').then(value => ({ default: value.ReceiptListPage }))), ReceiptDetailPage: lazy(() => import('./pages/ReceiptDetailPage').then(value => ({ default: value.ReceiptDetailPage }))), CreateReceiptPage: lazy(() => import('./pages/CreateReceiptPage').then(value => ({ default: value.CreateReceiptPage }))), EditReceiptPage: lazy(() => import('./pages/EditReceiptPage').then(value => ({ default: value.EditReceiptPage }))),
  ProcurementSettingsPage: lazy(() => import('./pages/ProcurementSettingsPage').then(value => ({ default: value.ProcurementSettingsPage }))), ConfigurationVersionDetailPage: lazy(() => import('./pages/ConfigurationVersionDetailPage').then(value => ({ default: value.ConfigurationVersionDetailPage }))), ConfigurationImportPage: lazy(() => import('./pages/ConfigurationImportPage').then(value => ({ default: value.ConfigurationImportPage }))),
} as const;
type PageName = keyof typeof pages;
const sidebar = (id: string, path: string, title: string, name: PageName, label: string, icon: TenantRouteIcon, order: number): TenantRoute => ({ id, module: 'purchase_management', path, title, sourceFile: `modules/purchase_management/pages/${name}.tsx`, Page: pages[name], modes, navigation: { type: 'sidebar', label, icon, order } });
const contextual = (id: string, path: string, title: string, name: PageName, parentRouteId: string): TenantRoute => ({ id, module: 'purchase_management', path, title, sourceFile: `modules/purchase_management/pages/${name}.tsx`, Page: pages[name], modes, navigation: { type: 'contextual', parentRouteId } });

export const tenantRoutes = [
  sidebar('purchase-management.suppliers.list', ROUTES.SUPPLIERS.LIST, 'Suppliers', 'SupplierListPage', 'Suppliers', Building2, 300),
  contextual('purchase-management.suppliers.create', ROUTES.SUPPLIERS.CREATE, 'Create supplier', 'CreateSupplierPage', 'purchase-management.suppliers.list'), contextual('purchase-management.suppliers.detail', ROUTES.SUPPLIERS.DETAIL(), 'Supplier detail', 'SupplierDetailPage', 'purchase-management.suppliers.list'), contextual('purchase-management.suppliers.edit', ROUTES.SUPPLIERS.EDIT(), 'Edit supplier', 'EditSupplierPage', 'purchase-management.suppliers.list'),
  sidebar('purchase-management.requisitions.list', ROUTES.REQUISITIONS.LIST, 'Purchase requisitions', 'RequisitionListPage', 'Requisitions', ClipboardList, 310),
  contextual('purchase-management.requisitions.create', ROUTES.REQUISITIONS.CREATE, 'Create requisition', 'CreateRequisitionPage', 'purchase-management.requisitions.list'), contextual('purchase-management.requisitions.detail', ROUTES.REQUISITIONS.DETAIL(), 'Requisition detail', 'RequisitionDetailPage', 'purchase-management.requisitions.list'), contextual('purchase-management.requisitions.edit', ROUTES.REQUISITIONS.EDIT(), 'Edit requisition', 'EditRequisitionPage', 'purchase-management.requisitions.list'),
  sidebar('purchase-management.rfqs.list', ROUTES.RFQS.LIST, 'Requests for quotation', 'RFQListPage', 'RFQs', Scale, 320),
  contextual('purchase-management.rfqs.create', ROUTES.RFQS.CREATE, 'Create RFQ', 'CreateRFQPage', 'purchase-management.rfqs.list'), contextual('purchase-management.rfqs.detail', ROUTES.RFQS.DETAIL(), 'RFQ detail and comparison', 'RFQDetailPage', 'purchase-management.rfqs.list'), contextual('purchase-management.rfqs.edit', ROUTES.RFQS.EDIT(), 'Edit RFQ', 'EditRFQPage', 'purchase-management.rfqs.list'),
  sidebar('purchase-management.quotes.list', ROUTES.QUOTES.LIST, 'Supplier quotes', 'QuoteListPage', 'Quotes', ReceiptText, 321),
  contextual('purchase-management.quotes.create', ROUTES.QUOTES.CREATE, 'Create supplier quote', 'CreateQuotePage', 'purchase-management.quotes.list'), contextual('purchase-management.quotes.detail', ROUTES.QUOTES.DETAIL(), 'Supplier quote detail', 'QuoteDetailPage', 'purchase-management.quotes.list'), contextual('purchase-management.quotes.edit', ROUTES.QUOTES.EDIT(), 'Edit supplier quote', 'EditQuotePage', 'purchase-management.quotes.list'),
  sidebar('purchase-management.orders.list', ROUTES.ORDERS.LIST, 'Purchase orders', 'PurchaseOrderListPage', 'Purchase Orders', FileCheck2, 330),
  contextual('purchase-management.orders.create', ROUTES.ORDERS.CREATE, 'Create purchase order', 'CreatePurchaseOrderPage', 'purchase-management.orders.list'), contextual('purchase-management.orders.detail', ROUTES.ORDERS.DETAIL(), 'Purchase order detail', 'PurchaseOrderDetailPage', 'purchase-management.orders.list'), contextual('purchase-management.orders.edit', ROUTES.ORDERS.EDIT(), 'Edit purchase order', 'EditPurchaseOrderPage', 'purchase-management.orders.list'),
  sidebar('purchase-management.receipts.list', ROUTES.RECEIPTS.LIST, 'Goods receipts', 'ReceiptListPage', 'Receipts', PackageCheck, 340),
  contextual('purchase-management.receipts.create', ROUTES.RECEIPTS.CREATE, 'Create goods receipt', 'CreateReceiptPage', 'purchase-management.receipts.list'), contextual('purchase-management.receipts.detail', ROUTES.RECEIPTS.DETAIL(), 'Goods receipt detail', 'ReceiptDetailPage', 'purchase-management.receipts.list'), contextual('purchase-management.receipts.edit', ROUTES.RECEIPTS.EDIT(), 'Edit goods receipt', 'EditReceiptPage', 'purchase-management.receipts.list'),
  sidebar('purchase-management.settings', ROUTES.SETTINGS, 'Procurement settings', 'ProcurementSettingsPage', 'Procurement Settings', Settings2, 350),
  contextual('purchase-management.settings.version', ROUTES.CONFIGURATION_VERSION(), 'Configuration version detail', 'ConfigurationVersionDetailPage', 'purchase-management.settings'), contextual('purchase-management.settings.import', ROUTES.CONFIGURATION_IMPORT, 'Import procurement configuration', 'ConfigurationImportPage', 'purchase-management.settings'),
] satisfies readonly TenantRoute[];
export default tenantRoutes;
