import { useDeferredValue, useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { Plus, Search } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { CrmPage, EmptyPanel, GovernedError, PageSkeleton, Pagination, fieldClass } from './CrmPage';
import type { PageResult } from '../services/crm-service';

export interface ListColumn<T> { key: string; label: string; sortable?: boolean; render: (item:T)=>React.ReactNode; }
export interface FilterChoice { value:string; label:string; }
export interface ListFilter { key:string; label:string; choices?:readonly FilterChoice[]; placeholder?:string; }
export function EntityList<T extends { readonly id:string }>({ title,description,createPath,emptyTitle,emptyDescription,columns,filters=[],query,isLoading,error,refetch,selectable=false,total }:{ title:string;description:string;createPath:string;emptyTitle:string;emptyDescription:string;columns:readonly ListColumn<T>[];filters?:readonly ListFilter[];query?:PageResult<T>;isLoading:boolean;error:unknown;refetch:()=>void;selectable?:boolean;total?:React.ReactNode }) {
  const [params,setParams]=useSearchParams(); const [search,setSearch]=useState(params.get('search')??''); const deferred=useDeferredValue(search); const [selected,setSelected]=useState<Set<string>>(new Set());
  const preferenceKey=`crm.view.${title.toLowerCase()}`;
  useEffect(()=>{if(params.has('ordering')||params.has('page_size'))return;try{const saved=JSON.parse(localStorage.getItem(preferenceKey)??'{}') as {ordering?:string;page_size?:string};if(saved.ordering||saved.page_size){const next=new URLSearchParams(params);if(saved.ordering)next.set('ordering',saved.ordering);if(saved.page_size)next.set('page_size',saved.page_size);setParams(next,{replace:true})}}catch{/* Invalid local preference is ignored; server state remains authoritative. */}},[]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{try{localStorage.setItem(preferenceKey,JSON.stringify({ordering:params.get('ordering')??'',page_size:params.get('page_size')??'25'}))}catch{/* Private browsing can disable storage without disabling CRM. */}},[params,preferenceKey]);
  useEffect(()=>{ const next=new URLSearchParams(params); if(deferred)next.set('search',deferred);else next.delete('search'); next.set('page','1'); if(next.toString()!==params.toString())setParams(next,{replace:true}); },[deferred]); // eslint-disable-line react-hooks/exhaustive-deps
  const activeFilters=[...params.entries()].some(([key,value])=>key!=='page'&&key!=='ordering'&&value);
  const clear=()=>{setSearch('');setParams({page:'1'});};
  const update=(key:string,value:string)=>{const next=new URLSearchParams(params);if(value)next.set(key,value);else next.delete(key);next.set('page','1');setParams(next);};
  const order=(key:string)=>{const current=params.get('ordering');update('ordering',current===key?`-${key}`:key);};
  const allSelected=!!query?.items.length&&query.items.every(item=>selected.has(item.id));
  const actions=<Link to={createPath}><Button><Plus className="mr-2 h-4 w-4"/>Create {title.replace(/s$/u,'')}</Button></Link>;
  return <CrmPage title={title} description={description} actions={actions}>
    <section aria-label={`${title} filters`} className="grid gap-3 rounded-lg border bg-card p-4 sm:grid-cols-2 lg:grid-cols-4"><label className="relative sm:col-span-2"><span className="sr-only">Search {title}</span><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${title.toLowerCase()}…`} className={`${fieldClass} pl-9`}/></label>{filters.map(filter=><label key={filter.key} className="text-sm"><span className="sr-only">{filter.label}</span>{filter.choices?<select aria-label={filter.label} value={params.get(filter.key)??''} onChange={e=>update(filter.key,e.target.value)} className={fieldClass}><option value="">All {filter.label.toLowerCase()}</option>{filter.choices.map(choice=><option key={choice.value} value={choice.value}>{choice.label}</option>)}</select>:<input aria-label={filter.label} value={params.get(filter.key)??''} onChange={e=>update(filter.key,e.target.value)} placeholder={filter.placeholder??filter.label} className={fieldClass}/>}</label>)}</section>
    {total?<div aria-live="polite">{total}</div>:null}
    {isLoading?<PageSkeleton label={`Loading ${title}`}/>:error?<GovernedError error={error} onRetry={refetch} subject={title}/>:!query?.items.length?<EmptyPanel title={activeFilters?`No ${title.toLowerCase()} match this view`:emptyTitle} description={activeFilters?'Clear or change the current filters to recover results.':emptyDescription} action={activeFilters?<Button variant="outline" onClick={clear}>Reset filters</Button>:actions}/>:<Card className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="border-b bg-muted/50"><tr>{selectable?<th className="p-3"><input aria-label="Select all on this page" type="checkbox" checked={allSelected} onChange={e=>setSelected(e.target.checked?new Set(query.items.map(i=>i.id)):new Set())}/></th>:null}{columns.map(column=><th key={column.key} scope="col" className="p-3 text-left font-medium">{column.sortable?<button className="hover:underline" onClick={()=>order(column.key)}>{column.label}</button>:column.label}</th>)}</tr></thead><tbody>{query.items.map(item=><tr key={item.id} className="border-b hover:bg-muted/30">{selectable?<td className="p-3"><input aria-label={`Select ${item.id}`} type="checkbox" checked={selected.has(item.id)} onChange={e=>setSelected(current=>{const next=new Set(current);if(e.target.checked)next.add(item.id);else next.delete(item.id);return next;})}/></td>:null}{columns.map(column=><td key={column.key} className="p-3">{column.render(item)}</td>)}</tr>)}</tbody></table><Pagination meta={query.pagination} onPage={page=>update('page',String(page))}/></Card>}
    {selected.size?<p aria-live="polite" className="rounded bg-muted p-3 text-sm">{selected.size} selected. Selection is limited to this page; no destructive bulk action is performed automatically.</p>:null}
  </CrmPage>;
}
