import { useMemo } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useNavigate, useParams } from 'react-router-dom';
import { toast } from 'sonner';
import { Card } from '@/components/ui/Card';
import { Input } from '@/components/ui/Input';
import { Button } from '@/components/ui/Button';
import { AccountForm, InvoiceForm, JournalEntryForm, PaymentForm, PostingPeriodForm } from '../components/AggregateForms';
import { AccountingFailure, AccountingPageSkeleton, PageHeader } from '../components/AccountingUI';
import { accountingQueryKeys, type APInvoiceCreateRequest, type ARInvoiceCreateRequest, type AccountCreateRequest, type InvoiceLineWriteRequest, type JournalEntryCreateRequest, type PaymentCreateRequest, type PostingPeriodCreateRequest, type PaymentUpdateRequest } from '../contracts';
import { AccountingApiError, accountingService, createIdempotencyKey } from '../services/accounting-service';

const fields = (error: unknown) => error instanceof AccountingApiError ? Object.fromEntries(error.fieldErrors.map((item) => [item.field, item.message])) : {};

export function AccountFormPage({ edit = false }: { edit?: boolean }) {
  const { id = '' } = useParams(); const navigate = useNavigate(); const queryClient = useQueryClient(); const detail = useQuery({ queryKey: accountingQueryKeys.account(id), queryFn: () => accountingService.getAccount(id), enabled: edit && Boolean(id) });
  const mutation = useMutation({ mutationFn: (value: AccountCreateRequest) => edit && detail.data ? accountingService.updateAccount(id, { ...value, version: detail.data.version }) : accountingService.createAccount(value, createIdempotencyKey('account.create')), onSuccess: (account) => { toast.success(edit ? 'Account updated' : 'Account created'); void queryClient.invalidateQueries({ queryKey: accountingQueryKeys.root }); navigate(`/accounting-finance/accounts/${account.id}`, { replace: true }); } });
  if (edit && detail.isLoading) return <AccountingPageSkeleton />; if (detail.error) return <div className="p-8"><AccountingFailure error={detail.error} onRetry={() => void detail.refetch()} /></div>;
  return <main className="space-y-6 p-4 sm:p-8"><PageHeader title={edit ? 'Edit account' : 'Create account'} description="Account type, normal balance, and currency become immutable once posting history exists." /><AccountForm initial={detail.data} pending={mutation.isPending} serverErrors={fields(mutation.error)} onSubmit={(value) => mutation.mutate(value)} onCancel={() => navigate(edit ? `/accounting-finance/accounts/${id}` : '/accounting-finance/accounts')} />{mutation.error && !(mutation.error instanceof AccountingApiError && mutation.error.kind === 'validation') ? <AccountingFailure error={mutation.error} /> : null}</main>;
}

export function PostingPeriodFormPage({ edit = false }: { edit?: boolean }) {
  const { id = '' } = useParams(); const navigate = useNavigate(); const queryClient = useQueryClient(); const detail = useQuery({ queryKey: accountingQueryKeys.period(id), queryFn: () => accountingService.getPostingPeriod(id), enabled: edit && Boolean(id) });
  const initial = detail.data ? { period_name: detail.data.period_name, start_date: detail.data.start_date, end_date: detail.data.end_date, fiscal_year: detail.data.fiscal_year } : undefined;
  const mutation = useMutation({ mutationFn: (value: PostingPeriodCreateRequest) => edit && detail.data ? accountingService.updatePostingPeriod(id, { ...value, version: detail.data.version }) : accountingService.createPostingPeriod(value, createIdempotencyKey('period.create')), onSuccess: (period) => { toast.success(edit ? 'Period updated' : 'Period created'); void queryClient.invalidateQueries({ queryKey: accountingQueryKeys.root }); navigate(`/accounting-finance/periods/${period.id}`, { replace: true }); } });
  if (edit && detail.isLoading) return <AccountingPageSkeleton />; if (detail.error) return <div className="p-8"><AccountingFailure error={detail.error} onRetry={() => void detail.refetch()} /></div>;
  return <main className="space-y-6 p-4 sm:p-8"><PageHeader title={edit ? 'Edit posting period' : 'Create posting period'} description="Overlapping periods are rejected under a database transaction." /><PostingPeriodForm initial={initial} pending={mutation.isPending} serverErrors={fields(mutation.error)} onSubmit={(value) => mutation.mutate(value)} onCancel={() => navigate(edit ? `/accounting-finance/periods/${id}` : '/accounting-finance/periods')} />{mutation.error && !(mutation.error instanceof AccountingApiError && mutation.error.kind === 'validation') ? <AccountingFailure error={mutation.error} /> : null}</main>;
}

export function JournalEntryFormPage({ edit = false }: { edit?: boolean }) {
  const { id = '' } = useParams(); const navigate = useNavigate(); const queryClient = useQueryClient(); const detail = useQuery({ queryKey: accountingQueryKeys.journal(id), queryFn: () => accountingService.getJournalEntry(id), enabled: edit && Boolean(id) });
  const initial: JournalEntryCreateRequest | undefined = detail.data ? { entry_number: detail.data.entry_number, posting_date: detail.data.posting_date, posting_period: detail.data.posting_period, reference: detail.data.reference, description: detail.data.description, currency: detail.data.currency, lines: detail.data.lines.map(({ line_number, account, debit_amount, credit_amount, currency, exchange_rate, description, cost_center, dimension_values }) => ({ line_number, account, debit_amount, credit_amount, currency, exchange_rate, description, cost_center, dimension_values })) } : undefined;
  const mutation = useMutation({ mutationFn: (value: JournalEntryCreateRequest) => edit && detail.data ? accountingService.updateJournalEntry(id, { ...value, version: detail.data.version }) : accountingService.createJournalEntry(value, createIdempotencyKey('journal.create')), onSuccess: (journal) => { toast.success(edit ? 'Journal draft updated' : 'Journal draft created'); void queryClient.invalidateQueries({ queryKey: accountingQueryKeys.root }); navigate(`/accounting-finance/journal-entries/${journal.id}`, { replace: true }); } });
  if (edit && detail.isLoading) return <AccountingPageSkeleton />; if (detail.error) return <div className="p-8"><AccountingFailure error={detail.error} onRetry={() => void detail.refetch()} /></div>;
  return <main className="space-y-6 p-4 sm:p-8"><PageHeader title={edit ? 'Edit journal draft' : 'Create journal draft'} description="Enter lines with the keyboard and confirm exact base-currency balance before posting." /><JournalEntryForm initial={initial} pending={mutation.isPending} serverErrors={fields(mutation.error)} onSubmit={(value) => mutation.mutate(value)} onCancel={() => navigate(edit ? `/accounting-finance/journal-entries/${id}` : '/accounting-finance/journal-entries')} />{mutation.error && !(mutation.error instanceof AccountingApiError && mutation.error.kind === 'validation') ? <AccountingFailure error={mutation.error} /> : null}</main>;
}

export function InvoiceFormPage({ kind, edit = false }: { kind: 'ap' | 'ar'; edit?: boolean }) {
  const { id = '' } = useParams(); const navigate = useNavigate(); const queryClient = useQueryClient(); const listPath = `/accounting-finance/${kind}-invoices`; const key = kind === 'ap' ? accountingQueryKeys.apInvoice(id) : accountingQueryKeys.arInvoice(id);
  const detail = useQuery({ queryKey: key, queryFn: () => kind === 'ap' ? accountingService.getAPInvoice(id) : accountingService.getARInvoice(id), enabled: edit && Boolean(id) });
  const initial = useMemo<APInvoiceCreateRequest | ARInvoiceCreateRequest | undefined>(() => { const invoice = detail.data; if (!invoice) return undefined; const common = { invoice_number: invoice.invoice_number, invoice_date: invoice.invoice_date, due_date: invoice.due_date, currency: invoice.currency, exchange_rate: invoice.exchange_rate, description: invoice.description, lines: invoice.lines.map(({ line_number, description, account, quantity, unit_price, tax_amount, cost_center, dimension_values }): InvoiceLineWriteRequest => ({ line_number, description, account, quantity, unit_price, tax_amount, cost_center, dimension_values })) }; return kind === 'ap' && 'supplier_id' in invoice ? { ...common, supplier_id: invoice.supplier_id } : kind === 'ar' && 'customer_id' in invoice ? { ...common, customer_id: invoice.customer_id } : undefined; }, [detail.data, kind]);
  const mutation = useMutation({ mutationFn: (value: APInvoiceCreateRequest | ARInvoiceCreateRequest) => { if (kind === 'ap' && 'supplier_id' in value) return edit && detail.data ? accountingService.updateAPInvoice(id, { ...value, version: detail.data.version }) : accountingService.createAPInvoice(value, createIdempotencyKey('ap-invoice.create')); if (kind === 'ar' && 'customer_id' in value) return edit && detail.data ? accountingService.updateARInvoice(id, { ...value, version: detail.data.version }) : accountingService.createARInvoice(value, createIdempotencyKey('ar-invoice.create')); throw new AccountingApiError('Invoice party type does not match this workflow.', 400, 'VALIDATION_ERROR', null, null); }, onSuccess: (invoice) => { toast.success(edit ? 'Invoice updated' : 'Invoice created'); void queryClient.invalidateQueries({ queryKey: accountingQueryKeys.root }); navigate(`${listPath}/${invoice.id}`, { replace: true }); } });
  if (edit && detail.isLoading) return <AccountingPageSkeleton />; if (detail.error) return <div className="p-8"><AccountingFailure error={detail.error} onRetry={() => void detail.refetch()} /></div>;
  return <main className="space-y-6 p-4 sm:p-8"><PageHeader title={`${edit ? 'Edit' : 'Create'} ${kind.toUpperCase()} invoice`} description={kind === 'ap' ? 'Supplier identity is validated through tenant-scoped master data before persistence.' : 'Customer identity and credit availability are validated through tenant-scoped master data.'} /><InvoiceForm kind={kind} initial={initial} pending={mutation.isPending} serverErrors={fields(mutation.error)} onSubmit={(value) => mutation.mutate(value)} onCancel={() => navigate(edit ? `${listPath}/${id}` : listPath)} />{mutation.error && !(mutation.error instanceof AccountingApiError && mutation.error.kind === 'validation') ? <AccountingFailure error={mutation.error} /> : null}</main>;
}

export function PaymentFormPage({ edit = false }: { edit?: boolean }) {
  const { id = '' } = useParams(); const navigate = useNavigate(); const queryClient = useQueryClient(); const detail = useQuery({ queryKey: accountingQueryKeys.payment(id), queryFn: () => accountingService.getPayment(id), enabled: edit && Boolean(id) });
  const [reference, description] = [detail.data?.reference_number ?? '', detail.data?.description ?? ''];
  const update = useMutation({ mutationFn: (value: PaymentUpdateRequest) => accountingService.updatePayment(id, value), onSuccess: (payment) => { toast.success('Payment reference updated'); void queryClient.invalidateQueries({ queryKey: accountingQueryKeys.root }); navigate(`/accounting-finance/payments/${payment.id}`, { replace: true }); } });
  const create = useMutation({ mutationFn: (value: PaymentCreateRequest) => accountingService.createPayment(value, createIdempotencyKey('payment.record')), onSuccess: (payment) => { toast.success('Payment recorded'); void queryClient.invalidateQueries({ queryKey: accountingQueryKeys.root }); navigate(`/accounting-finance/payments/${payment.id}`, { replace: true }); } });
  if (edit && detail.isLoading) return <AccountingPageSkeleton />; if (detail.error) return <div className="p-8"><AccountingFailure error={detail.error} onRetry={() => void detail.refetch()} /></div>;
  if (edit) return <main className="space-y-6 p-4 sm:p-8"><PageHeader title="Correct payment reference" description="Financial fields are immutable. Void and recreate a payment to correct date, amount, currency, method, or invoice." /><Card className="max-w-2xl p-5"><form className="space-y-5" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); update.mutate({ reference_number: String(data.get('reference_number') ?? ''), description: String(data.get('description') ?? '') }); }}><Input id="payment-edit-reference" name="reference_number" label="Reference number" defaultValue={reference} /><div><label htmlFor="payment-edit-description" className="mb-1 block text-sm font-medium">Description</label><textarea id="payment-edit-description" name="description" defaultValue={description} className="min-h-24 w-full rounded-md border bg-background p-3" /></div><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => navigate(`/accounting-finance/payments/${id}`)}>Cancel</Button><Button type="submit" disabled={update.isPending}>{update.isPending ? 'Saving…' : 'Save reference'}</Button></div></form></Card>{update.error ? <AccountingFailure error={update.error} /> : null}</main>;
  return <main className="space-y-6 p-4 sm:p-8"><PageHeader title="Record payment" description="The invoice is locked and its outstanding balance recomputed before the payment and GL entry commit atomically." /><PaymentForm pending={create.isPending} serverErrors={fields(create.error)} onSubmit={(value) => create.mutate(value)} onCancel={() => navigate('/accounting-finance/payments')} />{create.error && !(create.error instanceof AccountingApiError && create.error.kind === 'validation') ? <AccountingFailure error={create.error} /> : null}</main>;
}
