import { useState, type ReactNode } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link, useNavigate } from 'react-router-dom';
import { ListTree, Plus, Search, Table2 } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { Input } from '@/components/ui/Input';
import { accountingQueryKeys, type Account, type APInvoice, type ARInvoice, type JournalEntry, type Payment, type PostingPeriod } from '../contracts';
import { accountingService } from '../services/accounting-service';
import { AccountingFailure, AccountingPageSkeleton, EmptyPanel, PageHeader, Pagination, StatusPill, formatMoney, useAccountingAccess } from '../components/AccountingUI';

interface ListPageProps<T> {
  title: string; description: string; newPath: string; newLabel: string; detailPath: (id: string) => string;
  queryKey: readonly unknown[]; query: (page: number, search: string) => Promise<{ items: readonly T[]; pagination: { page: number; page_size: number; total_pages: number; count: number; has_next: boolean; has_previous: boolean } }>;
  columns: readonly string[]; cells: (item: T) => readonly ReactNode[]; rowId: (item: T) => string;
}

function ListPage<T>({ title, description, newPath, newLabel, detailPath, queryKey, query, columns, cells, rowId }: ListPageProps<T>) {
  const navigate = useNavigate(); const access = useAccountingAccess(); const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [committedSearch, setCommittedSearch] = useState('');
  const result = useQuery({ queryKey: [...queryKey, page, committedSearch], queryFn: () => query(page, committedSearch) });
  if (result.isLoading) return <AccountingPageSkeleton />;
  if (result.error) return <div className="p-4 sm:p-8"><AccountingFailure error={result.error} onRetry={() => void result.refetch()} /></div>;
  const data = result.data;
  return <main className="space-y-6 p-4 sm:p-8"><PageHeader title={title} description={description} actions={access.canDraft ? <Button onClick={() => navigate(newPath)}><Plus className="mr-2 h-4 w-4" />{newLabel}</Button> : undefined} /><form className="flex max-w-xl gap-2" role="search" onSubmit={(event) => { event.preventDefault(); setPage(1); setCommittedSearch(search); }}><Input id={`${title.toLowerCase().replaceAll(' ', '-')}-search`} aria-label={`Search ${title}`} value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by number, code, name, or description" /><Button type="submit" variant="outline"><Search className="mr-2 h-4 w-4" />Search</Button></form>{!data || data.items.length === 0 ? <EmptyPanel title={`No ${title.toLowerCase()} found`} description={committedSearch ? 'Try a different search or clear the filter.' : `Create the first ${newLabel.toLowerCase()} when you have permission.`} action={access.canDraft ? <Button onClick={() => navigate(newPath)}>{newLabel}</Button> : undefined} /> : <Card className="overflow-x-auto"><table className="min-w-[760px] w-full text-sm"><thead className="bg-muted/50"><tr>{columns.map((column) => <th scope="col" key={column} className="p-3 text-left font-medium">{column}</th>)}</tr></thead><tbody>{data.items.map((item) => <tr key={rowId(item)} className="border-t hover:bg-muted/30" tabIndex={0} onKeyDown={(event) => { if (event.key === 'Enter') navigate(detailPath(rowId(item))); }}>{cells(item).map((cell, index) => <td className="p-3" key={columns[index]}>{index === 0 ? <Link className="font-medium text-primary hover:underline" to={detailPath(rowId(item))}>{cell}</Link> : cell}</td>)}</tr>)}</tbody></table><Pagination page={page} pagination={data.pagination} onPage={setPage} /></Card>}</main>;
}

export function AccountListView() {
  const [tree, setTree] = useState(false); const access = useAccountingAccess();
  const hierarchy = useQuery({ queryKey: accountingQueryKeys.hierarchy(), queryFn: () => accountingService.accountHierarchy(true), enabled: tree });
  if (tree) return <main className="space-y-6 p-4 sm:p-8"><PageHeader title="Chart of accounts" description="Keyboard-navigable hierarchy of active posting and group accounts." actions={<><Button variant="outline" onClick={() => setTree(false)}><Table2 className="mr-2 h-4 w-4" />Table view</Button>{access.canAdminister ? <Button as-child={undefined} onClick={() => { window.location.assign('/accounting-finance/accounts/new'); }}><Plus className="mr-2 h-4 w-4" />New account</Button> : null}</>} />{hierarchy.isLoading ? <AccountingPageSkeleton rows={4} /> : hierarchy.error ? <AccountingFailure error={hierarchy.error} onRetry={() => void hierarchy.refetch()} /> : hierarchy.data?.length ? <Card className="p-4"><AccountTree nodes={hierarchy.data} /></Card> : <EmptyPanel title="No active accounts" description="Create an account to start the hierarchy." />}</main>;
  return <div><div className="px-4 pt-4 sm:px-8 sm:pt-8"><Button variant="outline" onClick={() => setTree(true)}><ListTree className="mr-2 h-4 w-4" />Tree view</Button></div><ListPage<Account> title="Chart of accounts" description="Search, navigate, and drill from account balances into posted ledger evidence." newPath="/accounting-finance/accounts/new" newLabel="New account" detailPath={(id) => `/accounting-finance/accounts/${id}`} queryKey={accountingQueryKeys.accounts()} query={(page, search) => accountingService.listAccounts({ page, search, ordering: 'code' })} columns={['Code', 'Name', 'Type', 'Balance', 'Status']} rowId={(item) => item.id} cells={(item) => [item.code, item.name, item.account_type, item.balance ? formatMoney(item.balance, item.currency) : 'View ledger', item.is_active ? <StatusPill status="active" /> : <StatusPill status="inactive" />]} /></div>;
}

function AccountTree({ nodes, level = 1 }: { nodes: readonly Account[] & readonly { children?: readonly Account[] }[]; level?: number }) { return <ul role={level === 1 ? 'tree' : 'group'} aria-label={level === 1 ? 'Account hierarchy' : undefined} className={level > 1 ? 'ml-6 border-l pl-3' : ''}>{nodes.map((node) => <li role="treeitem" aria-level={level} key={node.id} className="py-2"><Link className="rounded p-1 font-medium focus-visible:ring-2" to={`/accounting-finance/accounts/${node.id}`}>{node.code} · {node.name}</Link>{node.children?.length ? <AccountTree nodes={node.children} level={level + 1} /> : null}</li>)}</ul>; }

export function PostingPeriodListView() { return <ListPage<PostingPeriod> title="Posting periods" description="Govern open, closed, and locked fiscal periods with an auditable close process." newPath="/accounting-finance/periods/new" newLabel="New period" detailPath={(id) => `/accounting-finance/periods/${id}`} queryKey={accountingQueryKeys.periods()} query={(page, search) => accountingService.listPostingPeriods({ page, search, ordering: '-start_date' })} columns={['Period', 'Dates', 'Fiscal year', 'Status']} rowId={(item) => item.id} cells={(item) => [item.period_name, `${item.start_date} — ${item.end_date}`, item.fiscal_year, <StatusPill status={item.status} />]} />; }
export function JournalEntryListView() { return <ListPage<JournalEntry> title="Journal entries" description="Draft, balance, post, and reverse journal entries without losing their audit trail." newPath="/accounting-finance/journal-entries/new" newLabel="New journal" detailPath={(id) => `/accounting-finance/journal-entries/${id}`} queryKey={accountingQueryKeys.journals()} query={(page, search) => accountingService.listJournalEntries({ page, search, ordering: '-posting_date' })} columns={['Entry', 'Posting date', 'Description', 'Debits', 'Credits', 'Status']} rowId={(item) => item.id} cells={(item) => [item.entry_number, item.posting_date, item.description || '—', formatMoney(item.debit_total, item.currency), formatMoney(item.credit_total, item.currency), <StatusPill status={item.status} />]} />; }
export function APInvoiceListView() { return <ListPage<APInvoice> title="Accounts payable" description="Track supplier invoices from draft through approval, GL posting, and settlement." newPath="/accounting-finance/ap-invoices/new" newLabel="New AP invoice" detailPath={(id) => `/accounting-finance/ap-invoices/${id}`} queryKey={accountingQueryKeys.apInvoices()} query={(page, search) => accountingService.listAPInvoices({ page, search, ordering: 'due_date' })} columns={['Invoice', 'Due', 'Supplier', 'Total', 'Outstanding', 'Status']} rowId={(item) => item.id} cells={(item) => [item.invoice_number, item.due_date, item.supplier_id, formatMoney(item.total_amount, item.currency), `${item.currency} ${item.total_amount} − ${item.paid_amount}`, <StatusPill status={item.status} />]} />; }
export function ARInvoiceListView() { return <ListPage<ARInvoice> title="Accounts receivable" description="Follow customer invoices, credit decisions, due dates, posting, and collections." newPath="/accounting-finance/ar-invoices/new" newLabel="New AR invoice" detailPath={(id) => `/accounting-finance/ar-invoices/${id}`} queryKey={accountingQueryKeys.arInvoices()} query={(page, search) => accountingService.listARInvoices({ page, search, ordering: 'due_date' })} columns={['Invoice', 'Due', 'Customer', 'Total', 'Outstanding', 'Status']} rowId={(item) => item.id} cells={(item) => [item.invoice_number, item.due_date, item.customer_id, formatMoney(item.total_amount, item.currency), `${item.currency} ${item.total_amount} − ${item.paid_amount}`, <StatusPill status={item.status} />]} />; }
export function PaymentListView() { return <ListPage<Payment> title="Payments" description="Recorded settlement evidence. Financial corrections use the explicit void-and-recreate workflow." newPath="/accounting-finance/payments/new" newLabel="Record payment" detailPath={(id) => `/accounting-finance/payments/${id}`} queryKey={accountingQueryKeys.payments()} query={(page, search) => accountingService.listPayments({ page, search, ordering: '-payment_date' })} columns={['Reference', 'Date', 'Method', 'Invoice', 'Amount', 'Status']} rowId={(item) => item.id} cells={(item) => [item.reference_number || item.id.slice(0, 8), item.payment_date, item.payment_method.replaceAll('_', ' '), item.ap_invoice ?? item.ar_invoice ?? '—', formatMoney(item.amount, item.currency), <StatusPill status={item.status} />]} />; }
