import { useState, type ReactNode } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { FileClock, Pencil, ReceiptText, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { accountingQueryKeys, type APInvoice, type ARInvoice, type InvoiceBase, type JournalEntry, type Payment, type PostingPeriod } from '../contracts';
import { accountingService, createIdempotencyKey } from '../services/accounting-service';
import { AccountingFailure, AccountingPageSkeleton, ActionDialog, PageHeader, StatusPill, formatMoney, useAccountingAccess } from '../components/AccountingUI';

function FactGrid({ facts }: { facts: readonly { label: string; value: ReactNode }[] }) { return <dl className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-3">{facts.map((fact) => <div key={fact.label}><dt className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{fact.label}</dt><dd className="mt-1 break-words text-sm font-medium">{fact.value}</dd></div>)}</dl>; }
function History({ items }: { items: readonly { command: string; from_status: string; to_status: string; actor_id: string; occurred_at: string; reason?: string }[] }) { return <Card><h2 className="border-b p-4 font-semibold">Audit timeline</h2>{items.length ? <ol className="space-y-4 p-5">{items.map((item, index) => <li className="border-l-2 pl-4" key={`${item.occurred_at}-${index}`}><p className="font-medium">{item.command}: {item.from_status} → {item.to_status}</p><p className="text-xs text-muted-foreground">{item.occurred_at} · actor {item.actor_id}</p>{item.reason ? <p className="mt-1 text-sm">{item.reason}</p> : null}</li>)}</ol> : <p className="p-5 text-sm text-muted-foreground">No lifecycle transitions recorded yet.</p>}</Card>; }

export function AccountDetailView() {
  const { id = '' } = useParams(); const navigate = useNavigate(); const access = useAccountingAccess(); const queryClient = useQueryClient(); const [confirmDelete, setConfirmDelete] = useState(false);
  const detail = useQuery({ queryKey: accountingQueryKeys.account(id), queryFn: () => accountingService.getAccount(id) }); const remove = useMutation({ mutationFn: () => accountingService.deleteAccount(id), onSuccess: () => { toast.success('Draft account removed'); void queryClient.invalidateQueries({ queryKey: accountingQueryKeys.root }); navigate('/accounting-finance/accounts', { replace: true }); } });
  if (detail.isLoading) return <AccountingPageSkeleton />; if (detail.error || !detail.data) return <div className="p-8"><AccountingFailure error={detail.error} onRetry={() => void detail.refetch()} /></div>; const account = detail.data;
  return <main className="space-y-6 p-4 sm:p-8"><PageHeader title={`${account.code} · ${account.name}`} description="Account definition, balance visibility, and evidence drill-down." actions={<><Button variant="outline" onClick={() => navigate(`/accounting-finance/reports/general-ledger?account_id=${account.id}`)}><ReceiptText className="mr-2 h-4 w-4" />View ledger</Button>{access.canAdminister ? <Button variant="outline" onClick={() => navigate(`/accounting-finance/accounts/${id}/edit`)}><Pencil className="mr-2 h-4 w-4" />Edit</Button> : null}{access.canAdminister ? <Button variant="danger" onClick={() => setConfirmDelete(true)}><Trash2 className="mr-2 h-4 w-4" />Delete</Button> : null}</>} /><Card><FactGrid facts={[{ label: 'Type', value: account.account_type }, { label: 'Normal balance', value: account.normal_balance }, { label: 'Status', value: <StatusPill status={account.is_active ? 'active' : 'inactive'} /> }, { label: 'Currency', value: account.currency }, { label: 'Cash-flow category', value: account.cash_flow_category ?? 'Unclassified' }, { label: 'Account role', value: account.is_group ? 'Group account' : 'Posting account' }, { label: 'Balance', value: account.balance ? formatMoney(account.balance, account.currency) : 'Open general ledger' }, { label: 'Parent account', value: account.parent ?? 'Root' }, { label: 'Version', value: account.version }]} /></Card>{account.description ? <Card className="p-5"><h2 className="font-semibold">Description</h2><p className="mt-2 text-sm">{account.description}</p></Card> : null}<ActionDialog open={confirmDelete} onOpenChange={setConfirmDelete} title="Delete this account?" consequence="Only unused accounts can be deleted. An account with journal history must be deactivated so its financial evidence remains intact." confirmLabel="Delete account" pending={remove.isPending} onConfirm={() => remove.mutate()} />{remove.error ? <AccountingFailure error={remove.error} /> : null}</main>;
}

type PeriodAction = 'close' | 'reopen' | 'lock';
export function PostingPeriodDetailView() {
  const { id = '' } = useParams(); const navigate = useNavigate(); const access = useAccountingAccess(); const queryClient = useQueryClient(); const [action, setAction] = useState<PeriodAction | null>(null); const detail = useQuery({ queryKey: accountingQueryKeys.period(id), queryFn: () => accountingService.getPostingPeriod(id) });
  const transition = useMutation({ mutationFn: ({ command, reason }: { command: PeriodAction; reason: string }) => { if (!detail.data) throw new Error('Period unavailable'); const payload = { transition_key: createIdempotencyKey(`period.${command}`), version: detail.data.version, reason }; return command === 'close' ? accountingService.closePostingPeriod(id, payload) : command === 'reopen' ? accountingService.reopenPostingPeriod(id, payload) : accountingService.lockPostingPeriod(id, payload); }, onSuccess: (period) => { toast.success(`Period is now ${period.status}`); setAction(null); void queryClient.invalidateQueries({ queryKey: accountingQueryKeys.root }); } });
  if (detail.isLoading) return <AccountingPageSkeleton />; if (detail.error || !detail.data) return <div className="p-8"><AccountingFailure error={detail.error} onRetry={() => void detail.refetch()} /></div>; const period = detail.data;
  return <main className="space-y-6 p-4 sm:p-8"><PageHeader title={period.period_name} description={`${period.start_date} through ${period.end_date}`} actions={<>{access.canAdminister && period.status !== 'locked' ? <Button variant="outline" onClick={() => navigate(`/accounting-finance/periods/${id}/edit`)}><Pencil className="mr-2 h-4 w-4" />Edit</Button> : null}{access.canAdminister && period.status === 'open' ? <Button onClick={() => setAction('close')}>Close period</Button> : null}{access.canAdminister && period.status === 'closed' ? <><Button variant="outline" onClick={() => setAction('reopen')}>Reopen</Button><Button variant="danger" onClick={() => setAction('lock')}>Lock permanently</Button></> : null}</>} /><Card><FactGrid facts={[{ label: 'Status', value: <StatusPill status={period.status} /> }, { label: 'Fiscal year', value: period.fiscal_year }, { label: 'Version', value: period.version }, { label: 'Closed at', value: period.closed_at ?? '—' }, { label: 'Closed by', value: period.closed_by ?? '—' }, { label: 'Locked at', value: period.locked_at ?? '—' }]} /></Card><Card className="p-5"><h2 className="font-semibold">Close checklist</h2><p className="mt-1 text-sm text-muted-foreground">The authoritative close command checks draft journals and registered reconciliation or depreciation evidence. Blockers link back through the server response; missing required evidence fails closed.</p><div className="mt-4 flex flex-wrap gap-2"><Button variant="outline" onClick={() => navigate(`/accounting-finance/journal-entries?posting_period=${period.id}&status=draft`)}>Review draft journals</Button><Button variant="outline" onClick={() => navigate('/accounting-finance/reports/trial-balance')}>Review trial balance</Button></div></Card><History items={period.transition_history} />{action ? <ActionDialog open onOpenChange={(open) => { if (!open) setAction(null); }} title={`${action[0].toUpperCase()}${action.slice(1)} ${period.period_name}?`} consequence={action === 'lock' ? 'Locking is terminal: this period can never be reopened or receive postings.' : action === 'close' ? 'Posting stops after all server-side close prerequisites pass.' : 'Reopening permits posting again and requires a reason with no later locked period.'} confirmLabel={action === 'lock' ? 'Lock permanently' : `${action[0].toUpperCase()}${action.slice(1)} period`} pending={transition.isPending} reasonRequired onConfirm={(reason) => transition.mutate({ command: action, reason })} /> : null}{transition.error ? <AccountingFailure error={transition.error} /> : null}</main>;
}

function JournalLines({ journal }: { journal: JournalEntry }) { return <Card className="overflow-x-auto"><h2 className="border-b p-4 font-semibold">Posting evidence</h2><table className="min-w-[760px] w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">#</th><th className="p-3">Account</th><th className="p-3">Description</th><th className="p-3 text-right">Debit</th><th className="p-3 text-right">Credit</th></tr></thead><tbody>{journal.lines.map((line) => <tr className="border-b" key={line.id}><td className="p-3">{line.line_number}</td><td className="p-3"><Link className="text-primary hover:underline" to={`/accounting-finance/accounts/${line.account}`}>{line.account_code ?? line.account}</Link></td><td className="p-3">{line.description || '—'}</td><td className="p-3 text-right">{formatMoney(line.base_debit_amount, journal.currency)}</td><td className="p-3 text-right">{formatMoney(line.base_credit_amount, journal.currency)}</td></tr>)}</tbody><tfoot><tr className="font-semibold"><td colSpan={3} className="p-3 text-right">Totals</td><td className="p-3 text-right">{formatMoney(journal.debit_total, journal.currency)}</td><td className="p-3 text-right">{formatMoney(journal.credit_total, journal.currency)}</td></tr></tfoot></table></Card>; }
export function JournalEntryDetailView() {
  const { id = '' } = useParams(); const navigate = useNavigate(); const access = useAccountingAccess(); const queryClient = useQueryClient(); const [action, setAction] = useState<'post' | 'reverse' | 'delete' | null>(null); const detail = useQuery({ queryKey: accountingQueryKeys.journal(id), queryFn: () => accountingService.getJournalEntry(id) });
  const transition = useMutation({ mutationFn: ({ command, reason }: { command: 'post' | 'reverse' | 'delete'; reason: string }) => { if (!detail.data) throw new Error('Journal unavailable'); if (command === 'delete') return accountingService.deleteJournalEntry(id).then(() => detail.data); const base = { transition_key: createIdempotencyKey(`journal.${command}`), version: detail.data.version, reason }; return command === 'post' ? accountingService.postJournalEntry(id, base) : accountingService.reverseJournalEntry(id, { ...base, posting_date: new Date().toISOString().slice(0, 10), reason }); }, onSuccess: (journal, variables) => { toast.success(variables.command === 'delete' ? 'Journal draft deleted' : variables.command === 'post' ? 'Journal posted' : 'Reversal posted'); setAction(null); void queryClient.invalidateQueries({ queryKey: accountingQueryKeys.root }); if (variables.command === 'delete') navigate('/accounting-finance/journal-entries', { replace: true }); else if (variables.command === 'reverse') navigate(`/accounting-finance/journal-entries/${journal.id}`); } });
  if (detail.isLoading) return <AccountingPageSkeleton />; if (detail.error || !detail.data) return <div className="p-8"><AccountingFailure error={detail.error} onRetry={() => void detail.refetch()} /></div>; const journal = detail.data;
  return <main className="space-y-6 p-4 sm:p-8"><PageHeader title={`Journal ${journal.entry_number}`} description="Immutable posted evidence with source and reversal traceability." actions={<>{access.canDraft && journal.status === 'draft' ? <Button variant="outline" onClick={() => navigate(`/accounting-finance/journal-entries/${id}/edit`)}><Pencil className="mr-2 h-4 w-4" />Edit</Button> : null}{access.canOperate && journal.status === 'draft' ? <Button onClick={() => setAction('post')}>Post</Button> : null}{access.canAdminister && journal.status === 'posted' ? <Button variant="danger" onClick={() => setAction('reverse')}>Reverse</Button> : null}{access.canDraft && journal.status === 'draft' ? <Button variant="danger" onClick={() => setAction('delete')}>Delete draft</Button> : null}</>} /><Card><FactGrid facts={[{ label: 'Status', value: <StatusPill status={journal.status} /> }, { label: 'Posting date', value: journal.posting_date }, { label: 'Period', value: <Link className="text-primary hover:underline" to={`/accounting-finance/periods/${journal.posting_period}`}>{journal.posting_period}</Link> }, { label: 'Reference', value: journal.reference || '—' }, { label: 'Source', value: journal.source_module ? `${journal.source_module} · ${journal.source_reference}` : 'Manual' }, { label: 'Version', value: journal.version }]} /></Card><JournalLines journal={journal} /><History items={journal.transition_history} />{action ? <ActionDialog open onOpenChange={(open) => { if (!open) setAction(null); }} title={`${action === 'post' ? 'Post' : action === 'reverse' ? 'Reverse' : 'Delete'} journal ${journal.entry_number}?`} consequence={action === 'post' ? 'Posting makes the entry and every line immutable after period, balance, account, currency, dimension, and segregation checks pass.' : action === 'reverse' ? 'A new balanced posted entry will offset this journal. Historical lines will not be edited.' : 'Only a draft with no immutable accounting evidence can be deleted.'} confirmLabel={action === 'post' ? 'Post journal' : action === 'reverse' ? 'Post reversal' : 'Delete draft'} pending={transition.isPending} reasonRequired={action === 'reverse'} onConfirm={(reason) => transition.mutate({ command: action, reason })} /> : null}{transition.error ? <AccountingFailure error={transition.error} /> : null}</main>;
}

function InvoiceLines({ invoice }: { invoice: InvoiceBase }) { return <Card className="overflow-x-auto"><h2 className="border-b p-4 font-semibold">Invoice and GL preview</h2>{invoice.legacy_without_lines ? <p className="p-5 text-sm text-destructive">Legacy header-only invoice: reconcile real lines before any lifecycle command.</p> : <table className="min-w-[760px] w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">#</th><th className="p-3">Description</th><th className="p-3">Account</th><th className="p-3 text-right">Quantity</th><th className="p-3 text-right">Price</th><th className="p-3 text-right">Tax</th><th className="p-3 text-right">Line total</th></tr></thead><tbody>{invoice.lines.map((line) => <tr className="border-b" key={line.id}><td className="p-3">{line.line_number}</td><td className="p-3">{line.description}</td><td className="p-3"><Link className="text-primary hover:underline" to={`/accounting-finance/accounts/${line.account}`}>{line.account_code ?? line.account}</Link></td><td className="p-3 text-right">{line.quantity}</td><td className="p-3 text-right">{formatMoney(line.unit_price, invoice.currency)}</td><td className="p-3 text-right">{formatMoney(line.tax_amount, invoice.currency)}</td><td className="p-3 text-right">{formatMoney(line.line_total, invoice.currency)}</td></tr>)}</tbody></table>}</Card>; }
type InvoiceAction = 'submit' | 'approve' | 'reject' | 'post' | 'cancel' | 'delete';
function InvoiceDetail({ kind }: { kind: 'ap' | 'ar' }) {
  const { id = '' } = useParams(); const navigate = useNavigate(); const access = useAccountingAccess(); const queryClient = useQueryClient(); const [action, setAction] = useState<InvoiceAction | null>(null); const queryKey = kind === 'ap' ? accountingQueryKeys.apInvoice(id) : accountingQueryKeys.arInvoice(id); const detail = useQuery({ queryKey, queryFn: () => kind === 'ap' ? accountingService.getAPInvoice(id) : accountingService.getARInvoice(id) });
  const transition = useMutation({ mutationFn: async ({ command, reason }: { command: InvoiceAction; reason: string }) => { const invoice = detail.data; if (!invoice) throw new Error('Invoice unavailable'); if (command === 'delete') { if (kind === 'ap') await accountingService.deleteAPInvoice(id); else await accountingService.deleteARInvoice(id); return invoice; } const payload = { transition_key: createIdempotencyKey(`${kind}.${command}`), version: invoice.version, reason }; if (kind === 'ap') { if (command === 'submit') return accountingService.submitAPInvoice(id, payload); if (command === 'approve') return accountingService.approveAPInvoice(id, { ...payload, comments: reason }); if (command === 'reject') return accountingService.rejectAPInvoice(id, payload); if (command === 'post') return accountingService.postAPInvoice(id, payload); return accountingService.cancelAPInvoice(id, payload); } if (command === 'post') return accountingService.postARInvoice(id, payload); return accountingService.cancelARInvoice(id, payload); }, onSuccess: (_, variables) => { toast.success(variables.command === 'delete' ? 'Invoice draft deleted' : `Invoice ${variables.command} completed`); setAction(null); void queryClient.invalidateQueries({ queryKey: accountingQueryKeys.root }); if (variables.command === 'delete') navigate(`/accounting-finance/${kind}-invoices`, { replace: true }); } });
  if (detail.isLoading) return <AccountingPageSkeleton />; if (detail.error || !detail.data) return <div className="p-8"><AccountingFailure error={detail.error} onRetry={() => void detail.refetch()} /></div>; const invoice = detail.data; const party = kind === 'ap' && 'supplier_id' in invoice ? invoice.supplier_id : kind === 'ar' && 'customer_id' in invoice ? invoice.customer_id : '—';
  const actions: InvoiceAction[] = kind === 'ap' ? invoice.status === 'draft' ? ['submit', 'delete'] : invoice.status === 'submitted' ? ['approve', 'reject', 'cancel'] : invoice.status === 'approved' ? ['post', 'cancel'] : [] : invoice.status === 'draft' ? ['post', 'cancel', 'delete'] : [];
  return <main className="space-y-6 p-4 sm:p-8"><PageHeader title={`${kind.toUpperCase()} invoice ${invoice.invoice_number}`} description="Party, line, approval, GL, aging, and payment evidence in one audit trail." actions={<>{access.canDraft && invoice.status === 'draft' ? <Button variant="outline" onClick={() => navigate(`/accounting-finance/${kind}-invoices/${id}/edit`)}><Pencil className="mr-2 h-4 w-4" />Edit</Button> : null}{access.canOperate ? actions.map((command) => <Button key={command} variant={['cancel', 'delete', 'reject'].includes(command) ? 'danger' : 'primary'} onClick={() => setAction(command)}>{command[0].toUpperCase()}{command.slice(1)}</Button>) : null}</>} /><Card><FactGrid facts={[{ label: 'Status', value: <StatusPill status={invoice.status} /> }, { label: kind === 'ap' ? 'Supplier' : 'Customer', value: party }, { label: 'Invoice date', value: invoice.invoice_date }, { label: 'Due date', value: invoice.due_date }, { label: 'Total', value: formatMoney(invoice.total_amount, invoice.currency) }, { label: 'Paid', value: formatMoney(invoice.paid_amount, invoice.currency) }, { label: 'Journal entry', value: invoice.journal_entry ? <Link className="text-primary hover:underline" to={`/accounting-finance/journal-entries/${invoice.journal_entry}`}>{invoice.journal_entry}</Link> : 'Not posted' }, { label: 'Version', value: invoice.version }]} /></Card><InvoiceLines invoice={invoice} /><Card className="p-5"><h2 className="font-semibold">Payment history</h2><Link className="mt-3 inline-flex text-sm text-primary hover:underline" to={`/accounting-finance/payments?${kind}_invoice=${invoice.id}`}><FileClock className="mr-2 h-4 w-4" />Open payments for this invoice</Link></Card><History items={invoice.transition_history} />{action ? <ActionDialog open onOpenChange={(open) => { if (!open) setAction(null); }} title={`${action[0].toUpperCase()}${action.slice(1)} invoice ${invoice.invoice_number}?`} consequence={action === 'post' ? 'Posting creates immutable, balanced general-ledger evidence after period and account validation.' : action === 'approve' ? 'Approval is permanently attributed to your identity and segregation-of-duties is enforced.' : action === 'cancel' || action === 'delete' ? 'Cancellation or deletion is allowed only before immutable financial evidence exists.' : `The ${action} transition is recorded in the permanent approval history.`} confirmLabel={`${action[0].toUpperCase()}${action.slice(1)} invoice`} pending={transition.isPending} reasonRequired={['reject', 'cancel'].includes(action)} onConfirm={(reason) => transition.mutate({ command: action, reason })} /> : null}{transition.error ? <AccountingFailure error={transition.error} /> : null}</main>;
}
export function APInvoiceDetailView() { return <InvoiceDetail kind="ap" />; }
export function ARInvoiceDetailView() { return <InvoiceDetail kind="ar" />; }

export function PaymentDetailView() {
  const { id = '' } = useParams(); const navigate = useNavigate(); const access = useAccountingAccess(); const queryClient = useQueryClient(); const [voidOpen, setVoidOpen] = useState(false); const detail = useQuery({ queryKey: accountingQueryKeys.payment(id), queryFn: () => accountingService.getPayment(id) });
  const voidPayment = useMutation({ mutationFn: (reason: string) => { if (!detail.data) throw new Error('Payment unavailable'); return accountingService.voidPayment(id, { transition_key: createIdempotencyKey('payment.void'), version: detail.data.version, reason }); }, onSuccess: () => { toast.success('Payment voided and reversal posted'); setVoidOpen(false); void queryClient.invalidateQueries({ queryKey: accountingQueryKeys.root }); } });
  if (detail.isLoading) return <AccountingPageSkeleton />; if (detail.error || !detail.data) return <div className="p-8"><AccountingFailure error={detail.error} onRetry={() => void detail.refetch()} /></div>; const payment: Payment = detail.data;
  return <main className="space-y-6 p-4 sm:p-8"><PageHeader title={`Payment ${payment.reference_number || payment.id.slice(0, 8)}`} description="Settlement and GL evidence. Financial corrections use void-and-recreate." actions={<>{access.canDraft && payment.status === 'recorded' ? <Button variant="outline" onClick={() => navigate(`/accounting-finance/payments/${id}/edit`)}><Pencil className="mr-2 h-4 w-4" />Correct reference</Button> : null}{access.canOperate && payment.status === 'recorded' ? <Button variant="danger" onClick={() => setVoidOpen(true)}>Void payment</Button> : null}</>} /><Card><FactGrid facts={[{ label: 'Status', value: <StatusPill status={payment.status} /> }, { label: 'Payment date', value: payment.payment_date }, { label: 'Amount', value: formatMoney(payment.amount, payment.currency) }, { label: 'Method', value: payment.payment_method.replaceAll('_', ' ') }, { label: 'Invoice', value: payment.ap_invoice ?? payment.ar_invoice ?? '—' }, { label: 'Created by', value: payment.created_by }, { label: 'Journal entry', value: payment.journal_entry ? <Link className="text-primary hover:underline" to={`/accounting-finance/journal-entries/${payment.journal_entry}`}>{payment.journal_entry}</Link> : '—' }, { label: 'Reversal journal', value: payment.reversal_journal_entry ? <Link className="text-primary hover:underline" to={`/accounting-finance/journal-entries/${payment.reversal_journal_entry}`}>{payment.reversal_journal_entry}</Link> : '—' }]} /></Card>{payment.description ? <Card className="p-5"><h2 className="font-semibold">Description</h2><p className="mt-2 text-sm">{payment.description}</p></Card> : null}<ActionDialog open={voidOpen} onOpenChange={setVoidOpen} title="Void this payment?" consequence="Voiding preserves the payment, posts a balanced reversal, and recomputes the invoice balance. It cannot be undone." confirmLabel="Void and reverse" pending={voidPayment.isPending} reasonRequired onConfirm={(reason) => voidPayment.mutate(reason)} />{voidPayment.error ? <AccountingFailure error={voidPayment.error} /> : null}</main>;
}
