import { useMemo, useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { ArrowLeft, ArrowRight, Check, FileSearch, WandSparkles } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { toast } from 'sonner';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { Input } from '@/components/ui/Input';
import { Textarea } from '@/components/ui/Textarea';
import type { MappingSuggestion, MigrationJobCreate, SourceConfigInput, SourceType, WriteMode } from '../contracts';
import { dataMigrationService } from '../services/data-migration-service';
import { EmptyPanel, FailureState, PageShell, SuccessBanner } from '../components/MigrationUI';

const steps = ['Source', 'Target', 'Inspect', 'Map', 'Validate', 'Review'] as const;
const fieldClass = 'h-10 w-full rounded-md border border-input bg-background px-3 text-sm text-foreground';
const newKey = () => crypto.randomUUID();

function sourceConfig(sourceType: SourceType, connectionId: string, table: string, relativePath: string, batchSize: number): SourceConfigInput {
  switch (sourceType) {
    case 'csv': return { delimiter: ',', encoding: 'utf-8', header_row: 1, batch_size: batchSize };
    case 'excel': return { sheet: 'Sheet1', header_row: 1, batch_size: batchSize };
    case 'json': return { encoding: 'utf-8', json_path: '$', batch_size: batchSize };
    case 'xml': return { encoding: 'utf-8', record_path: '/records/record', batch_size: batchSize };
    case 'database': return { connection_id: connectionId, table, columns: [], filters: [], batch_size: batchSize };
    case 'api': return { connection_id: connectionId, relative_path: relativePath, method: 'GET', query_parameters: [], results_path: '$', page_parameter: 'page', page_size_parameter: 'page_size', page_size: batchSize };
  }
}

export const CreateDataMigrationJobPage = () => {
  const navigate = useNavigate();
  const [step, setStep] = useState(0);
  const [name, setName] = useState(''); const [description, setDescription] = useState('');
  const [sourceType, setSourceType] = useState<SourceType>('csv'); const [artifactId, setArtifactId] = useState('');
  const [connectionId, setConnectionId] = useState(''); const [table, setTable] = useState(''); const [relativePath, setRelativePath] = useState('/');
  const [targetAdapter, setTargetAdapter] = useState(''); const [targetEntity, setTargetEntity] = useState(''); const [writeMode, setWriteMode] = useState<WriteMode>('create'); const [lookupFields, setLookupFields] = useState('');
  const [jobId, setJobId] = useState<string>(); const [profileMessage, setProfileMessage] = useState(''); const [suggestions, setSuggestions] = useState<readonly MappingSuggestion[]>([]);
  const [error, setError] = useState('');
  const connections = useQuery({ queryKey: ['data-migration', 'connections', 'wizard'], queryFn: () => dataMigrationService.connections.list({ page_size: 100 }), enabled: sourceType === 'database' || sourceType === 'api' });
  const activeConnections = useMemo(() => connections.data?.items.filter((item) => item.is_active && (sourceType !== 'api' ? item.kind !== 'http' : item.kind === 'http')) ?? [], [connections.data, sourceType]);

  const create = useMutation({ mutationFn: (payload: MigrationJobCreate) => dataMigrationService.jobs.create(payload), onSuccess: (job) => { setJobId(job.id); setStep(2); toast.success('Draft saved. Source inspection is now available.'); }, onError: (caught) => setError(caught instanceof Error ? caught.message : 'The draft could not be saved.') });
  const inspect = useMutation({ mutationFn: () => dataMigrationService.jobs.inspect(jobId!, { idempotency_key: newKey() }), onSuccess: (accepted) => { setProfileMessage(`Durable inspection ${accepted.async_job_id.slice(0, 8)} accepted with status ${accepted.status}. Refresh-safe preview evidence will appear on the definition.`); }, onError: (caught) => setError(caught instanceof Error ? caught.message : 'Inspection could not be queued.') });
  const suggest = useMutation({ mutationFn: () => dataMigrationService.mappings.suggest(jobId!), onSuccess: (items) => setSuggestions(items), onError: (caught) => setError(caught instanceof Error ? caught.message : 'Suggestions are unavailable.') });
  const apply = useMutation({ mutationFn: () => dataMigrationService.mappings.apply(jobId!, suggestions.filter((item) => !item.pii).map((item) => item.id)), onSuccess: () => { toast.success('Safe suggestions applied'); setStep(4); }, onError: (caught) => setError(caught instanceof Error ? caught.message : 'Suggestions could not be applied.') });
  const validate = useMutation({ mutationFn: () => dataMigrationService.jobs.validate(jobId!), onSuccess: () => setStep(5), onError: (caught) => setError(caught instanceof Error ? caught.message : 'Definition validation failed.') });

  const sourceValid = name.trim().length > 0 && ((sourceType === 'database' || sourceType === 'api') ? connectionId.length > 0 : artifactId.length > 0) && (sourceType !== 'database' || table.trim().length > 0) && (sourceType !== 'api' || relativePath.startsWith('/') && !relativePath.startsWith('//'));
  const targetValid = targetAdapter.trim().length > 0 && targetEntity.trim().length > 0 && (writeMode === 'create' || lookupFields.split(',').some((item) => item.trim()));

  const persistDraft = () => {
    setError('');
    if (!sourceValid || !targetValid) { setError('Complete every required source and target field before inspection.'); return; }
    create.mutate({ name: name.trim(), description: description.trim(), source_type: sourceType, source_artifact_id: sourceType === 'database' || sourceType === 'api' ? null : artifactId, source_config: sourceConfig(sourceType, connectionId, table.trim(), relativePath.trim(), 500), target_adapter: targetAdapter.trim(), target_entity: targetEntity.trim(), write_mode: writeMode, lookup_fields: writeMode === 'upsert' ? lookupFields.split(',').map((item) => item.trim()).filter(Boolean) : [] });
  };

  return <PageShell title="Create migration" description="A guided path from a tenant-owned source to a validated, reversible migration definition.">
    <ol className="grid grid-cols-3 gap-2 sm:grid-cols-6" aria-label="Migration setup progress">{steps.map((label, index) => <li key={label} className={`rounded-md border p-2 text-center text-xs ${index === step ? 'border-primary bg-primary/10 text-primary' : index < step ? 'border-primary/30 text-foreground' : 'border-border text-muted-foreground'}`} aria-current={index === step ? 'step' : undefined}>{index < step ? <Check className="mx-auto mb-1 h-4 w-4" /> : <span className="mb-1 block">{index + 1}</span>}{label}</li>)}</ol>
    {error ? <FailureState title="This step needs attention" message={error} onRetry={() => setError('')} /> : null}
    <Card className="p-5 sm:p-7">
      {step === 0 ? <div className="space-y-5"><div><label className="text-sm font-medium text-foreground" htmlFor="migration-name">Name</label><Input id="migration-name" value={name} onChange={(event) => setName(event.target.value)} placeholder="Customer onboarding import" /><p className="mt-1 text-xs text-muted-foreground">Use a name operators will recognize in audit history.</p></div><div><label className="text-sm font-medium text-foreground" htmlFor="migration-description">Description</label><Textarea id="migration-description" value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Purpose, owner, and expected source" /></div><div><label className="text-sm font-medium text-foreground" htmlFor="source-type">Source type</label><select id="source-type" className={fieldClass} value={sourceType} onChange={(event) => { setSourceType(event.target.value as SourceType); setConnectionId(''); }}><option value="csv">CSV</option><option value="excel">Excel</option><option value="json">JSON</option><option value="xml">XML</option><option value="database">Database</option><option value="api">HTTP API</option></select></div>
        {sourceType === 'database' || sourceType === 'api' ? <><div><label className="text-sm font-medium text-foreground" htmlFor="connection">Named connection</label><select id="connection" className={fieldClass} value={connectionId} onChange={(event) => setConnectionId(event.target.value)} disabled={connections.isLoading}><option value="">Select a safe connection</option>{activeConnections.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><p className="mt-1 text-xs text-muted-foreground">Credentials and destination details are never exposed here.</p></div>{sourceType === 'database' ? <div><label className="text-sm font-medium text-foreground" htmlFor="source-table">Allow-listed table</label><Input id="source-table" value={table} onChange={(event) => setTable(event.target.value)} /></div> : <div><label className="text-sm font-medium text-foreground" htmlFor="relative-path">Relative path</label><Input id="relative-path" value={relativePath} onChange={(event) => setRelativePath(event.target.value)} /><p className="mt-1 text-xs text-muted-foreground">Absolute URLs, headers, bodies, and unsafe methods are intentionally unavailable.</p></div>}</> : <div><label className="text-sm font-medium text-foreground" htmlFor="artifact-id">DMS artifact version ID</label><Input id="artifact-id" value={artifactId} onChange={(event) => setArtifactId(event.target.value)} placeholder="Immutable tenant-owned version UUID" /><p className="mt-1 text-xs text-muted-foreground">Upload files in Document Management, then select their immutable version.</p></div>}
      </div> : null}
      {step === 1 ? <div className="space-y-5"><div><label className="text-sm font-medium text-foreground" htmlFor="target-adapter">Registered target adapter</label><Input id="target-adapter" value={targetAdapter} onChange={(event) => setTargetAdapter(event.target.value)} placeholder="crm.customer" /><p className="mt-1 text-xs text-muted-foreground">Only installed, entitled adapters pass server validation.</p></div><div><label className="text-sm font-medium text-foreground" htmlFor="target-entity">Target entity</label><Input id="target-entity" value={targetEntity} onChange={(event) => setTargetEntity(event.target.value)} placeholder="customer" /></div><div><label className="text-sm font-medium text-foreground" htmlFor="write-mode">Write mode</label><select id="write-mode" className={fieldClass} value={writeMode} onChange={(event) => setWriteMode(event.target.value as WriteMode)}><option value="create">Create only</option><option value="upsert">Upsert existing records</option></select></div>{writeMode === 'upsert' ? <div><label className="text-sm font-medium text-foreground" htmlFor="lookup-fields">Lookup fields</label><Input id="lookup-fields" value={lookupFields} onChange={(event) => setLookupFields(event.target.value)} placeholder="external_id, region" /><p className="mt-1 text-xs text-muted-foreground">Required for conflict-safe upsert identity.</p></div> : null}</div> : null}
      {step === 2 ? <div className="space-y-5 text-center"><FileSearch className="mx-auto h-12 w-12 text-primary" /><h2 className="text-xl font-semibold text-foreground">Inspect before mapping</h2><p className="text-sm text-muted-foreground">Inspection detects fields, types, redacted samples, malformed data, and a stable source checksum without writing target records.</p>{profileMessage ? <SuccessBanner>{profileMessage}</SuccessBanner> : <Button disabled={inspect.isPending} onClick={() => inspect.mutate()}>{inspect.isPending ? 'Queuing inspection…' : 'Inspect source'}</Button>}</div> : null}
      {step === 3 ? <div className="space-y-5"><div className="text-center"><WandSparkles className="mx-auto h-10 w-10 text-primary" /><h2 className="mt-2 text-xl font-semibold text-foreground">Deterministic mapping suggestions</h2><p className="text-sm text-muted-foreground">Suggestions use names, aliases, types, and redacted shapes. PII is never auto-accepted.</p></div>{suggestions.length === 0 ? <Button className="w-full" variant="outline" disabled={suggest.isPending} onClick={() => suggest.mutate()}>{suggest.isPending ? 'Analyzing fields…' : 'Generate suggestions'}</Button> : <div className="space-y-2">{suggestions.map((item) => <div key={item.id} className="flex items-center justify-between rounded-md border border-border p-3 text-sm"><span>{item.source_field} → {item.target_field}</span><span className={item.pii ? 'text-destructive' : 'text-muted-foreground'}>{item.pii ? 'Manual review required' : `${Math.round(item.confidence * 100)}% confidence`}</span></div>)}<Button className="w-full" disabled={apply.isPending} onClick={() => apply.mutate()}>Apply safe suggestions</Button></div>}</div> : null}
      {step === 4 ? <div className="space-y-5"><h2 className="text-xl font-semibold text-foreground">Validate the complete definition</h2><p className="text-sm text-muted-foreground">Server validation checks the source, target adapter, mapping schemas, active rules, limits, permissions, and entitlement. Unknown transforms and rules fail closed.</p><Button disabled={validate.isPending} onClick={() => validate.mutate()}>{validate.isPending ? 'Validating…' : 'Validate definition'}</Button></div> : null}
      {step === 5 ? <div className="space-y-5"><SuccessBanner>The definition passed server validation and is ready for a dry run. No target records have been written.</SuccessBanner><dl className="grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-muted-foreground">Source</dt><dd className="font-medium text-foreground">{sourceType.toUpperCase()}</dd></div><div><dt className="text-muted-foreground">Target</dt><dd className="font-medium text-foreground">{targetAdapter} / {targetEntity}</dd></div><div><dt className="text-muted-foreground">Write mode</dt><dd className="font-medium text-foreground">{writeMode}</dd></div><div><dt className="text-muted-foreground">Rollback</dt><dd className="font-medium text-foreground">Conflict-safe evidence for committed writes</dd></div></dl><Button onClick={() => navigate(`/data-migration/jobs/${jobId}`)}>Review and dry run</Button></div> : null}
      <div className="mt-8 flex justify-between border-t border-border pt-5">{step > 0 && step < 2 ? <Button variant="outline" onClick={() => setStep((value) => value - 1)}><ArrowLeft className="mr-2 h-4 w-4" />Back</Button> : <span />}{step === 0 ? <Button disabled={!sourceValid} onClick={() => setStep(1)}>Target <ArrowRight className="ml-2 h-4 w-4" /></Button> : null}{step === 1 ? <Button disabled={!targetValid || create.isPending} onClick={persistDraft}>{create.isPending ? 'Saving draft…' : 'Save draft and inspect'} <ArrowRight className="ml-2 h-4 w-4" /></Button> : null}{step === 2 && profileMessage ? <Button onClick={() => setStep(3)}>Map fields <ArrowRight className="ml-2 h-4 w-4" /></Button> : null}</div>
    </Card>
  </PageShell>;
};

/** Temporary source compatibility while external links migrate to the named job page. */
export const CreateDataMigrationResourcePage = CreateDataMigrationJobPage;
