import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Download, RotateCcw, Upload } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { toast } from 'sonner';
import { Button } from '@/components/ui/Button'; import { Card } from '@/components/ui/Card'; import { Input } from '@/components/ui/Input'; import { Textarea } from '@/components/ui/Textarea';
import type { ExportDefinitionPayload } from '../contracts';
import { DataMigrationApiError, dataMigrationService } from '../services/data-migration-service';
import { EmptyPanel, FailureState, PageShell, PageSkeleton, SuccessBanner } from '../components/MigrationUI';

export const EditDataMigrationJobPage = () => {
  const { id } = useParams<{ id: string }>(); const navigate = useNavigate(); const client = useQueryClient();
  const job = useQuery({ queryKey: ['data-migration','job',id], queryFn: () => dataMigrationService.jobs.get(id!), enabled: Boolean(id) });
  const versions = useQuery({ queryKey: ['data-migration','versions',id], queryFn: () => dataMigrationService.jobs.versions(id!, { page_size: 100 }), enabled: Boolean(id) });
  const [name,setName]=useState(''); const [description,setDescription]=useState(''); const [targetAdapter,setTargetAdapter]=useState(''); const [targetEntity,setTargetEntity]=useState(''); const [diffVisible,setDiffVisible]=useState(false); const [importDocument,setImportDocument]=useState<ExportDefinitionPayload>();
  useEffect(() => { if (job.data) { setName(job.data.name); setDescription(job.data.description); setTargetAdapter(job.data.target_adapter); setTargetEntity(job.data.target_entity); } }, [job.data]);
  const update = useMutation({ mutationFn: () => dataMigrationService.jobs.update(id!, { name, description, target_adapter: targetAdapter, target_entity: targetEntity, expected_version: job.data!.configuration_version }), onSuccess: async (next) => { toast.success(`Saved configuration v${next.configuration_version}; definition returned to draft.`); setDiffVisible(false); await client.invalidateQueries({ queryKey: ['data-migration','job',id] }); }, onError: (error) => { if (error instanceof DataMigrationApiError && error.status === 409) toast.error('Version conflict: reload to compare the latest configuration before saving.'); else toast.error('Changes could not be saved.'); } });
  const restore = useMutation({ mutationFn: (version: number) => dataMigrationService.jobs.restoreVersion(id!, version, { expected_version: job.data!.configuration_version, change_summary: `Restore version ${version}` }), onSuccess: async () => { toast.success('Version restored as a new immutable version.'); await Promise.all([client.invalidateQueries({ queryKey: ['data-migration','job',id] }), client.invalidateQueries({ queryKey: ['data-migration','versions',id] })]); }, onError: () => toast.error('Version could not be restored. Reload if the definition changed.') });
  const exportFile = async () => { const definition = await dataMigrationService.jobs.export(id!); const url=URL.createObjectURL(new Blob([JSON.stringify(definition,null,2)],{type:'application/json'})); const a=document.createElement('a'); a.href=url;a.download=`${definition.job.name}.migration.json`;a.click();URL.revokeObjectURL(url); };
  const readImport = async (file: File) => { try { const parsed: unknown = JSON.parse(await file.text()); if (!parsed || typeof parsed !== 'object' || !('schema_version' in parsed) || !('checksum' in parsed)) throw new Error(); setImportDocument(parsed as ExportDefinitionPayload); } catch { toast.error('This is not a valid versioned migration document.'); } };
  const applyImport = async () => { if (!importDocument) return; const result=await dataMigrationService.jobs.import({document:importDocument,preview_only:true}); if (!result.checksum_valid) { toast.error('Import checksum is invalid.'); return; } toast.success(`${result.diff.entries.length} semantic changes detected. Import preview is ready for review.`); };
  if (job.isLoading) return <PageSkeleton label="Loading migration editor" />;
  if (!job.data || job.error) return <PageShell title="Edit migration" description="Version-controlled configuration editor."><FailureState message={job.error instanceof Error ? job.error.message : 'Migration unavailable.'} onRetry={() => void job.refetch()} /></PageShell>;
  const changed=name!==job.data.name||description!==job.data.description||targetAdapter!==job.data.target_adapter||targetEntity!==job.data.target_entity;
  return <PageShell title={`Edit ${job.data.name}`} description={`Editing configuration v${job.data.configuration_version}. Saving a ready definition atomically returns it to draft.`} actions={<><Button variant="outline" onClick={() => void exportFile()}><Download className="mr-2 h-4 w-4"/>Export</Button><Button variant="outline" onClick={() => navigate(`/data-migration/jobs/${id}`)}>Cancel</Button></>}>
    {job.data.status==='ready'?<SuccessBanner>Changes require server revalidation before another run can start.</SuccessBanner>:null}
    <div className="grid gap-6 lg:grid-cols-[minmax(0,2fr)_minmax(18rem,1fr)]"><Card className="space-y-5 p-6"><div><label htmlFor="edit-name" className="text-sm font-medium text-foreground">Name</label><Input id="edit-name" value={name} onChange={(e)=>setName(e.target.value)}/></div><div><label htmlFor="edit-description" className="text-sm font-medium text-foreground">Description</label><Textarea id="edit-description" value={description} onChange={(e)=>setDescription(e.target.value)}/></div><div><label htmlFor="edit-adapter" className="text-sm font-medium text-foreground">Registered target adapter</label><Input id="edit-adapter" value={targetAdapter} onChange={(e)=>setTargetAdapter(e.target.value)}/></div><div><label htmlFor="edit-entity" className="text-sm font-medium text-foreground">Target entity</label><Input id="edit-entity" value={targetEntity} onChange={(e)=>setTargetEntity(e.target.value)}/></div>{diffVisible?<div className="rounded-md border border-border bg-muted/40 p-4 text-sm"><h2 className="font-semibold text-foreground">Semantic diff</h2><ul className="mt-2 space-y-1 text-muted-foreground">{name!==job.data.name?<li>Name: {job.data.name} → {name}</li>:null}{targetAdapter!==job.data.target_adapter?<li>Adapter: {job.data.target_adapter} → {targetAdapter}</li>:null}{targetEntity!==job.data.target_entity?<li>Entity: {job.data.target_entity} → {targetEntity}</li>:null}{description!==job.data.description?<li>Description changed</li>:null}</ul><Button className="mt-4" disabled={update.isPending} onClick={()=>update.mutate()}>{update.isPending?'Applying…':'Apply versioned changes'}</Button></div>:<Button disabled={!changed||!name.trim()||!targetAdapter.trim()||!targetEntity.trim()} onClick={()=>setDiffVisible(true)}>Preview changes</Button>}</Card>
      <div className="space-y-6"><Card className="p-5"><h2 className="font-semibold text-foreground">Import definition</h2><p className="mt-1 text-xs text-muted-foreground">Checksum and semantic changes are validated before anything is applied.</p><label className="mt-4 flex cursor-pointer items-center justify-center rounded-md border border-dashed border-border p-4 text-sm text-muted-foreground hover:text-foreground"><Upload className="mr-2 h-4 w-4"/>Choose JSON<input className="sr-only" type="file" accept="application/json" onChange={(e)=>{const file=e.target.files?.[0];if(file)void readImport(file)}}/></label>{importDocument?<Button className="mt-3 w-full" variant="outline" onClick={()=>void applyImport()}>Preview import</Button>:null}</Card><Card className="p-5"><h2 className="font-semibold text-foreground">Configuration history</h2>{versions.data?.items.length? <div className="mt-3 space-y-2">{versions.data.items.map((version)=><div key={version.id} className="flex items-center justify-between rounded-md border border-border p-3 text-sm"><span><strong>v{version.version}</strong><span className="ml-2 text-muted-foreground">{version.change_summary}</span></span>{version.version!==job.data.configuration_version?<Button size="icon" variant="ghost" aria-label={`Restore version ${version.version}`} onClick={()=>{if(window.confirm(`Restore version ${version.version} as a new version?`))restore.mutate(version.version)}}><RotateCcw className="h-4 w-4"/></Button>:null}</div>)}</div>:<EmptyPanel title="No previous versions" description="Every successful configuration change creates an immutable version."/>}</Card></div></div>
  </PageShell>;
};
