import { useState } from 'react';
import { keepPreviousData, useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Ban, Download, RotateCcw, ShieldAlert } from 'lucide-react';
import { useParams } from 'react-router-dom'; import { toast } from 'sonner';
import { Button } from '@/components/ui/Button'; import { Card } from '@/components/ui/Card';
import type { IssueFilters } from '../contracts'; import { DataMigrationApiError, dataMigrationService } from '../services/data-migration-service';
import { EmptyPanel, FailureState, PageShell, PageSkeleton, ProgressBar, StateBadge, SuccessBanner } from '../components/MigrationUI';
const newKey=()=>crypto.randomUUID();
export const MigrationRunDetailPage=()=>{const{id}=useParams<{id:string}>();const client=useQueryClient();const[page,setPage]=useState(1);const[severity,setSeverity]=useState<IssueFilters['severity']>();const[stage,setStage]=useState<IssueFilters['stage']>();const[code,setCode]=useState('');
 const run=useQuery({queryKey:['data-migration','run',id],queryFn:()=>dataMigrationService.runs.get(id!),enabled:Boolean(id),refetchInterval:({state})=>document.visibilityState==='visible'&&(state.data?.status==='queued'||state.data?.status==='running')?3000:false});
 const issues=useQuery({queryKey:['data-migration','issues',id,page,severity,stage,code],queryFn:()=>dataMigrationService.runs.issues(id!,{page,page_size:25,severity,stage,code:code||undefined}),enabled:Boolean(id),placeholderData:keepPreviousData});
 const cancel=useMutation({mutationFn:()=>dataMigrationService.runs.cancel(id!,{transition_key:newKey()}),onSuccess:async()=>{toast.success('Cancellation requested');await client.invalidateQueries({queryKey:['data-migration','run',id]})},onError:()=>toast.error('Cancellation was not accepted.')});
 const rollback=useMutation({mutationFn:()=>dataMigrationService.rollbacks.request(id!,{idempotency_key:newKey()}),onSuccess:async()=>{toast.success('Rollback accepted and will stop on any checksum conflict.');await client.invalidateQueries({queryKey:['data-migration','run',id]})},onError:()=>toast.error('Rollback was not accepted. The run may be ineligible or have a conflict.')});
 if(run.isLoading)return <PageSkeleton label="Loading migration run"/>; if(!run.data||run.error)return <PageShell title="Migration run" description="Durable execution evidence."><FailureState forbidden={run.error instanceof DataMigrationApiError&&run.error.status===403} message={run.error instanceof Error?run.error.message:'Run unavailable.'} onRetry={()=>void run.refetch()}/></PageShell>;
 const value=run.data;const progress=value.total_records?value.processed_records/value.total_records*100:0;const elapsed=value.started_at?(new Date(value.completed_at??Date.now()).getTime()-new Date(value.started_at).getTime())/1000:0;const throughput=elapsed>0?value.processed_records/elapsed:0;const can=(a:NonNullable<typeof value.allowed_actions>[number])=>value.allowed_actions?.includes(a)??false;
 return <PageShell title={`${value.mode==='dry_run'?'Dry run':'Migration run'} ${value.id.slice(0,8)}`} description={`Configuration snapshot ${value.job_version} · correlation ${value.correlation_id}`} actions={<>{can('export_issues')?<a className="inline-flex h-10 items-center rounded-md border border-input bg-background px-4 text-sm font-medium text-foreground hover:bg-accent" href={dataMigrationService.runs.exportIssuesUrl(value.id)}><Download className="mr-2 h-4 w-4"/>Export issues</a>:null}{can('cancel')?<Button variant="outline" disabled={cancel.isPending} onClick={()=>{if(window.confirm('Request cancellation after the current atomic batch?'))cancel.mutate()}}><Ban className="mr-2 h-4 w-4"/>Cancel</Button>:null}{can('rollback')&&value.rollback_eligible?<Button variant="danger" disabled={rollback.isPending} onClick={()=>{if(window.confirm('Rollback this committed run? Reversal stops rather than overwriting any newer target changes.'))rollback.mutate()}}><RotateCcw className="mr-2 h-4 w-4"/>Rollback</Button>:null}</>}>
  {value.mode==='dry_run'?<SuccessBanner>No records written. This run executed mapping and validation only.</SuccessBanner>:null}
  <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Card className="p-4"><span className="text-xs text-muted-foreground">State</span><div className="mt-2"><StateBadge state={value.status}/></div></Card>{[['Processed',value.processed_records],['Succeeded',value.succeeded_records],['Failed',value.failed_records],['Warnings',value.warning_records]].map(([label,count])=><Card key={String(label)} className="p-4"><span className="text-xs text-muted-foreground">{label}</span><p className="mt-1 text-2xl font-semibold text-foreground">{Number(count).toLocaleString()}</p></Card>)}</div>
  <Card className="space-y-3 p-5"><ProgressBar value={progress} label="Durable progress"/><p className="text-xs text-muted-foreground">{throughput.toFixed(1)} rows/second · {value.processed_records.toLocaleString()} of {value.total_records.toLocaleString()}</p>{value.mode==='commit'&&!value.rollback_eligible?<p className="flex items-center gap-2 text-sm text-muted-foreground"><ShieldAlert className="h-4 w-4"/>Rollback is unavailable until a committed run succeeds with complete reversal evidence.</p>:null}</Card>
  <Card className="grid gap-3 p-4 md:grid-cols-3"><label><span className="text-xs text-muted-foreground">Severity</span><select className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={severity??''} onChange={e=>{setSeverity((e.target.value||undefined)as IssueFilters['severity']);setPage(1)}}><option value="">All severities</option><option value="error">Error</option><option value="warning">Warning</option></select></label><label><span className="text-xs text-muted-foreground">Stage</span><select className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={stage??''} onChange={e=>{setStage((e.target.value||undefined)as IssueFilters['stage']);setPage(1)}}><option value="">All stages</option>{['source','mapping','validation','target','system'].map(item=><option key={item}>{item}</option>)}</select></label><label><span className="text-xs text-muted-foreground">Issue code</span><input className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={code} onChange={e=>{setCode(e.target.value);setPage(1)}} placeholder="e.g. required"/></label></Card>
  {issues.isLoading?<PageSkeleton label="Loading run issues"/>:issues.error?<FailureState message={issues.error instanceof Error?issues.error.message:'Issues unavailable.'} onRetry={()=>void issues.refetch()}/>:issues.data?.items.length?<Card className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b border-border bg-muted/40 text-muted-foreground"><tr><th className="p-3">Row</th><th className="p-3">Field</th><th className="p-3">Stage</th><th className="p-3">Code</th><th className="p-3">Issue and remediation</th></tr></thead><tbody>{issues.data.items.map(issue=><tr key={issue.id} className="border-b border-border"><td className="p-3">{issue.row_number??'—'}</td><td className="p-3">{issue.field_name||'—'}</td><td className="p-3">{issue.stage}</td><td className="p-3"><span className={issue.severity==='error'?'text-destructive':'text-muted-foreground'}>{issue.code}</span></td><td className="p-3"><p className="text-foreground">{issue.message}</p><p className="text-xs text-muted-foreground">{issue.remediation??'Correct the source value or mapping, then run a new dry run.'}</p></td></tr>)}</tbody></table><nav className="flex justify-between p-3"><Button variant="outline" disabled={!issues.data.pagination.has_previous} onClick={()=>setPage(v=>Math.max(1,v-1))}>Previous</Button><span className="text-sm text-muted-foreground">Page {issues.data.pagination.page} of {issues.data.pagination.total_pages}</span><Button variant="outline" disabled={!issues.data.pagination.has_next} onClick={()=>setPage(v=>v+1)}>Next</Button></nav></Card>:<EmptyPanel title="No issues recorded" description={value.status==='queued'||value.status==='running'?'Issues appear here as durable batches complete.':'No validation or execution issues matched these filters.'}/>} 
 </PageShell>};
