import { useState } from 'react';
import type { Lead, LeadCreate } from '../contracts';
import { Field, LiveRegion, SubmitButton, fieldClass } from '../components/CrmPage';
import { useDirtyGuard, validEmail, value, type FormErrors } from './form-utils';
export function LeadForm({ initial, pending, serverError, onSubmit, submitLabel = 'Save lead' }: { initial?: Lead; pending: boolean; serverError?: string | null; onSubmit: (payload: LeadCreate) => Promise<void>; submitLabel?: string }) {
  const [errors, setErrors] = useState<FormErrors>({}); const guard = useDirtyGuard();
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const email = value(data, 'email'); const next: FormErrors = {}; if (!value(data, 'last_name')) next.last_name = 'Last name is required.'; if (email && !validEmail(email)) next.email = 'Enter a valid email address.'; setErrors(next); if (Object.keys(next).length) return; await onSubmit({ first_name: value(data, 'first_name'), last_name: value(data, 'last_name'), email: email || null, phone: value(data, 'phone'), company: value(data, 'company'), title: value(data, 'title'), source: value(data, 'source'), owner_id: value(data, 'owner_id') || null }); guard.markClean(); }
  return <form onSubmit={(event) => void submit(event)} onChange={guard.markDirty} className="space-y-5" noValidate><LiveRegion message={serverError}/><div className="grid gap-4 sm:grid-cols-2"><Field id="first_name" label="First name"><input id="first_name" name="first_name" defaultValue={initial?.first_name} className={fieldClass}/></Field><Field id="last_name" label="Last name" required error={errors.last_name}><input id="last_name" name="last_name" defaultValue={initial?.last_name} className={fieldClass} aria-invalid={!!errors.last_name}/></Field><Field id="email" label="Email" error={errors.email}><input id="email" name="email" type="email" defaultValue={initial?.email ?? ''} className={fieldClass} aria-invalid={!!errors.email}/></Field><Field id="phone" label="Phone"><input id="phone" name="phone" type="tel" defaultValue={initial?.phone} className={fieldClass}/></Field><Field id="company" label="Company"><input id="company" name="company" defaultValue={initial?.company} className={fieldClass}/></Field><Field id="title" label="Job title"><input id="title" name="title" defaultValue={initial?.title} className={fieldClass}/></Field><Field id="source" label="Source"><input id="source" name="source" defaultValue={initial?.source} className={fieldClass}/></Field><Field id="owner_id" label="Owner ID"><input id="owner_id" name="owner_id" defaultValue={initial?.owner_id ?? ''} className={fieldClass}/></Field></div>{serverError ? <p role="alert" className="text-sm text-destructive">{serverError}</p> : null}<SubmitButton pending={pending} label={submitLabel}/></form>;
}
