import { lazy } from 'react';
import { BookCheck, ClipboardCheck, FileCheck2, LayoutDashboard, Library } from 'lucide-react';
import type { TenantRoute } from '@/navigation/tenant-route-types';

const modes = ['development', 'self-hosted', 'saas'] as const;
const pages = {
  dashboard: lazy(() => import('./pages/ComplianceDashboardPage').then(({ ComplianceDashboardPage }) => ({ default: ComplianceDashboardPage }))),
  frameworks: lazy(() => import('./pages/FrameworkListPage').then(({ FrameworkListPage }) => ({ default: FrameworkListPage }))), frameworkDetail: lazy(() => import('./pages/FrameworkDetailPage').then(({ FrameworkDetailPage }) => ({ default: FrameworkDetailPage }))), frameworkCreate: lazy(() => import('./pages/CreateFrameworkPage').then(({ CreateFrameworkPage }) => ({ default: CreateFrameworkPage }))), frameworkEdit: lazy(() => import('./pages/EditFrameworkPage').then(({ EditFrameworkPage }) => ({ default: EditFrameworkPage }))),
  requirements: lazy(() => import('./pages/RequirementListPage').then(({ RequirementListPage }) => ({ default: RequirementListPage }))), requirementDetail: lazy(() => import('./pages/RequirementDetailPage').then(({ RequirementDetailPage }) => ({ default: RequirementDetailPage }))), requirementCreate: lazy(() => import('./pages/CreateRequirementPage').then(({ CreateRequirementPage }) => ({ default: CreateRequirementPage }))), requirementEdit: lazy(() => import('./pages/EditRequirementPage').then(({ EditRequirementPage }) => ({ default: EditRequirementPage }))),
  policies: lazy(() => import('./pages/CompliancePolicyListPage').then(({ CompliancePolicyListPage }) => ({ default: CompliancePolicyListPage }))), policyDetail: lazy(() => import('./pages/CompliancePolicyDetailPage').then(({ CompliancePolicyDetailPage }) => ({ default: CompliancePolicyDetailPage }))), policyCreate: lazy(() => import('./pages/CreateCompliancePolicyPage').then(({ CreateCompliancePolicyPage }) => ({ default: CreateCompliancePolicyPage }))), policyEdit: lazy(() => import('./pages/EditCompliancePolicyPage').then(({ EditCompliancePolicyPage }) => ({ default: EditCompliancePolicyPage }))),
  mappings: lazy(() => import('./pages/RequirementMappingPage').then(({ RequirementMappingPage }) => ({ default: RequirementMappingPage }))), assessments: lazy(() => import('./pages/AssessmentHistoryPage').then(({ AssessmentHistoryPage }) => ({ default: AssessmentHistoryPage }))), assessmentCreate: lazy(() => import('./pages/CreateAssessmentPage').then(({ CreateAssessmentPage }) => ({ default: CreateAssessmentPage }))),
  evidence: lazy(() => import('./pages/EvidenceListPage').then(({ EvidenceListPage }) => ({ default: EvidenceListPage }))), evidenceDetail: lazy(() => import('./pages/EvidenceDetailPage').then(({ EvidenceDetailPage }) => ({ default: EvidenceDetailPage }))), evidenceCreate: lazy(() => import('./pages/CreateEvidencePage').then(({ CreateEvidencePage }) => ({ default: CreateEvidencePage }))), evidenceEdit: lazy(() => import('./pages/EditEvidencePage').then(({ EditEvidencePage }) => ({ default: EditEvidencePage }))),
  configuration: lazy(() => import('./pages/ConfigurationListPage').then(({ ConfigurationListPage }) => ({ default: ConfigurationListPage }))), configurationDetail: lazy(() => import('./pages/ConfigurationDetailPage').then(({ ConfigurationDetailPage }) => ({ default: ConfigurationDetailPage }))), configurationEdit: lazy(() => import('./pages/EditConfigurationPage').then(({ EditConfigurationPage }) => ({ default: EditConfigurationPage }))), activity: lazy(() => import('./pages/ComplianceActivityPage').then(({ ComplianceActivityPage }) => ({ default: ComplianceActivityPage }))),
} as const;
const contextual = (id: string, path: string, page: keyof typeof pages, parentRouteId: string, file: string): TenantRoute => ({ id: `compliance-management.${id}`, module: 'compliance_management', path, sourceFile: `modules/compliance_management/pages/${file}`, Page: pages[page], modes, navigation: { type: 'contextual', parentRouteId } });
export const tenantRoutes = [
  { id: 'compliance-management.dashboard', module: 'compliance_management', path: '/compliance-management', sourceFile: 'modules/compliance_management/pages/ComplianceDashboardPage.tsx', Page: pages.dashboard, modes, navigation: { type: 'sidebar', label: 'Overview', icon: LayoutDashboard, order: 300 } },
  { id: 'compliance-management.frameworks.list', module: 'compliance_management', path: '/compliance-management/frameworks', sourceFile: 'modules/compliance_management/pages/FrameworkListPage.tsx', Page: pages.frameworks, modes, navigation: { type: 'sidebar', label: 'Frameworks', icon: Library, order: 310 } },
  contextual('frameworks.create', '/compliance-management/frameworks/new', 'frameworkCreate', 'compliance-management.frameworks.list', 'CreateFrameworkPage.tsx'), contextual('frameworks.detail', '/compliance-management/frameworks/:id', 'frameworkDetail', 'compliance-management.frameworks.list', 'FrameworkDetailPage.tsx'), contextual('frameworks.edit', '/compliance-management/frameworks/:id/edit', 'frameworkEdit', 'compliance-management.frameworks.list', 'EditFrameworkPage.tsx'),
  { id: 'compliance-management.requirements.list', module: 'compliance_management', path: '/compliance-management/requirements', sourceFile: 'modules/compliance_management/pages/RequirementListPage.tsx', Page: pages.requirements, modes, navigation: { type: 'sidebar', label: 'Requirements', icon: ClipboardCheck, order: 320 } },
  contextual('requirements.create', '/compliance-management/requirements/new', 'requirementCreate', 'compliance-management.requirements.list', 'CreateRequirementPage.tsx'), contextual('requirements.detail', '/compliance-management/requirements/:id', 'requirementDetail', 'compliance-management.requirements.list', 'RequirementDetailPage.tsx'), contextual('requirements.edit', '/compliance-management/requirements/:id/edit', 'requirementEdit', 'compliance-management.requirements.list', 'EditRequirementPage.tsx'), contextual('mappings', '/compliance-management/mappings', 'mappings', 'compliance-management.requirements.list', 'RequirementMappingPage.tsx'), contextual('assessments.list', '/compliance-management/assessments', 'assessments', 'compliance-management.requirements.list', 'AssessmentHistoryPage.tsx'), contextual('assessments.create', '/compliance-management/assessments/new', 'assessmentCreate', 'compliance-management.requirements.list', 'CreateAssessmentPage.tsx'),
  { id: 'compliance-management.policies.list', module: 'compliance_management', path: '/compliance-management/policies', sourceFile: 'modules/compliance_management/pages/CompliancePolicyListPage.tsx', Page: pages.policies, modes, navigation: { type: 'sidebar', label: 'Policies', icon: BookCheck, order: 330 } },
  contextual('policies.create', '/compliance-management/policies/new', 'policyCreate', 'compliance-management.policies.list', 'CreateCompliancePolicyPage.tsx'), contextual('policies.detail', '/compliance-management/policies/:id', 'policyDetail', 'compliance-management.policies.list', 'CompliancePolicyDetailPage.tsx'), contextual('policies.edit', '/compliance-management/policies/:id/edit', 'policyEdit', 'compliance-management.policies.list', 'EditCompliancePolicyPage.tsx'),
  { id: 'compliance-management.evidence.list', module: 'compliance_management', path: '/compliance-management/evidence', sourceFile: 'modules/compliance_management/pages/EvidenceListPage.tsx', Page: pages.evidence, modes, navigation: { type: 'sidebar', label: 'Evidence', icon: FileCheck2, order: 340 } },
  contextual('evidence.create', '/compliance-management/evidence/new', 'evidenceCreate', 'compliance-management.evidence.list', 'CreateEvidencePage.tsx'), contextual('evidence.detail', '/compliance-management/evidence/:id', 'evidenceDetail', 'compliance-management.evidence.list', 'EvidenceDetailPage.tsx'), contextual('evidence.edit', '/compliance-management/evidence/:id/edit', 'evidenceEdit', 'compliance-management.evidence.list', 'EditEvidencePage.tsx'), contextual('configuration.list', '/compliance-management/configuration', 'configuration', 'compliance-management.dashboard', 'ConfigurationListPage.tsx'), contextual('configuration.create', '/compliance-management/configuration/new', 'configurationEdit', 'compliance-management.dashboard', 'EditConfigurationPage.tsx'), contextual('configuration.detail', '/compliance-management/configuration/:id', 'configurationDetail', 'compliance-management.dashboard', 'ConfigurationDetailPage.tsx'), contextual('configuration.edit', '/compliance-management/configuration/:id/edit', 'configurationEdit', 'compliance-management.dashboard', 'EditConfigurationPage.tsx'), contextual('activity', '/compliance-management/activity', 'activity', 'compliance-management.dashboard', 'ComplianceActivityPage.tsx'),
] satisfies readonly TenantRoute[];
export default tenantRoutes;
