import { Input } from "@/components/ui/Input";
import { Label } from "@/components/ui/Label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/Select";
import type { NamingConfiguration, NamingStrategy } from "../contracts";
interface Props { strategy: NamingStrategy; config: NamingConfiguration; fields: readonly { key: string; is_required: boolean; is_read_only: boolean }[]; onChange: (strategy: NamingStrategy, config: NamingConfiguration) => void }
export function NamingStrategyEditor({ strategy, config, fields, onChange }: Props) {
  const update = (value: Partial<NamingConfiguration>) => onChange(strategy, { ...config, ...value });
  return <section className="space-y-4" aria-labelledby="naming-title"><div><h2 id="naming-title" className="text-lg font-semibold">Record naming</h2><p className="text-sm text-muted-foreground">Choose a deterministic identifier. Sequence tokens support YYYY, MM, and one numeric token.</p></div><div><Label htmlFor="naming-strategy">Strategy</Label><Select value={strategy} onValueChange={(value: NamingStrategy) => onChange(value, {})}><SelectTrigger id="naming-strategy"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="uuid">UUID</SelectItem><SelectItem value="sequence">Sequence</SelectItem><SelectItem value="field">Immutable field</SelectItem></SelectContent></Select></div>{strategy === "field" && <div><Label htmlFor="naming-field">Required read-only field</Label><Select value={config.field_key ?? ""} onValueChange={(value) => update({ field_key: value })}><SelectTrigger id="naming-field"><SelectValue placeholder="Select a field" /></SelectTrigger><SelectContent>{fields.filter((field) => field.is_required && field.is_read_only).map((field) => <SelectItem key={field.key} value={field.key}>{field.key}</SelectItem>)}</SelectContent></Select></div>}{strategy === "sequence" && <><Input id="prefix-template" label="Prefix template" value={config.prefix_template ?? "REC-{YYYY}-{#####}"} onChange={(event) => update({ prefix_template: event.target.value })} /><Input id="sequence-padding" type="number" min={1} max={12} label="Padding" value={config.padding ?? 5} onChange={(event) => update({ padding: Number(event.target.value) })} /></>}</section>;
}
