import { lazy } from "react";
import { Bell, Cable, FileClock, HeartPulse, Send, Settings2 } from "lucide-react";
import type { TenantRoute } from "@/navigation/tenant-route-types";
import { PATHS } from "./contracts";

const modes = ["development", "self-hosted", "saas"] as const;
const moduleName = "notifications";
const contextual = (parentRouteId: string) => ({ type: "contextual" as const, parentRouteId });

export const tenantRoutes = [
  { id: "notifications.inbox", module: moduleName, path: PATHS.INBOX, title: "Notification inbox", requiredPermission: "notifications.inbox:read", sourceFile: "modules/notifications/pages/NotificationCenterPage.tsx", Page: lazy(() => import("./pages/NotificationCenterPage").then((m) => ({ default: m.NotificationCenterPage }))), modes, navigation: { type: "sidebar", label: "Inbox", icon: Bell, order: 500 } },
  { id: "notifications.detail", module: moduleName, path: PATHS.DETAIL(":id"), title: "Notification details", requiredPermission: "notifications.inbox:read", sourceFile: "modules/notifications/pages/NotificationDetailPage.tsx", Page: lazy(() => import("./pages/NotificationDetailPage").then((m) => ({ default: m.NotificationDetailPage }))), modes, navigation: contextual("notifications.inbox") },
  { id: "notifications.preferences", module: moduleName, path: PATHS.PREFERENCES, title: "Notification preferences", requiredPermission: "notifications.preference:read", sourceFile: "modules/notifications/pages/NotificationPreferencesPage.tsx", Page: lazy(() => import("./pages/NotificationPreferencesPage").then((m) => ({ default: m.NotificationPreferencesPage }))), modes, navigation: contextual("notifications.inbox") },
  { id: "notifications.templates", module: moduleName, path: PATHS.TEMPLATES, title: "Notification templates", requiredPermission: "notifications.template:read", sourceFile: "modules/notifications/pages/TemplateListPage.tsx", Page: lazy(() => import("./pages/TemplateListPage").then((m) => ({ default: m.TemplateListPage }))), modes, navigation: { type: "sidebar", label: "Templates", icon: FileClock, order: 510 } },
  { id: "notifications.template-create", module: moduleName, path: PATHS.TEMPLATE_CREATE, title: "Create notification template", requiredPermission: "notifications.template:create", sourceFile: "modules/notifications/pages/CreateTemplatePage.tsx", Page: lazy(() => import("./pages/CreateTemplatePage").then((m) => ({ default: m.CreateTemplatePage }))), modes, navigation: contextual("notifications.templates") },
  { id: "notifications.template-detail", module: moduleName, path: PATHS.TEMPLATE_DETAIL(":id"), title: "Notification template details", requiredPermission: "notifications.template:read", sourceFile: "modules/notifications/pages/TemplateDetailPage.tsx", Page: lazy(() => import("./pages/TemplateDetailPage").then((m) => ({ default: m.TemplateDetailPage }))), modes, navigation: contextual("notifications.templates") },
  { id: "notifications.template-edit", module: moduleName, path: PATHS.TEMPLATE_EDIT(":id"), title: "Create notification template version", requiredPermission: "notifications.template:update", sourceFile: "modules/notifications/pages/EditTemplatePage.tsx", Page: lazy(() => import("./pages/EditTemplatePage").then((m) => ({ default: m.EditTemplatePage }))), modes, navigation: contextual("notifications.templates") },
  { id: "notifications.deliveries", module: moduleName, path: PATHS.DELIVERIES, title: "Notification deliveries", requiredPermission: "notifications.delivery:read", sourceFile: "modules/notifications/pages/DeliveryListPage.tsx", Page: lazy(() => import("./pages/DeliveryListPage").then((m) => ({ default: m.DeliveryListPage }))), modes, navigation: { type: "sidebar", label: "Deliveries", icon: Send, order: 520 } },
  { id: "notifications.delivery-create", module: moduleName, path: PATHS.DELIVERY_CREATE, title: "Dispatch notification", requiredPermission: "notifications.delivery:dispatch", sourceFile: "modules/notifications/pages/CreateDeliveryPage.tsx", Page: lazy(() => import("./pages/CreateDeliveryPage").then((m) => ({ default: m.CreateDeliveryPage }))), modes, navigation: contextual("notifications.deliveries") },
  { id: "notifications.delivery-detail", module: moduleName, path: PATHS.DELIVERY_DETAIL(":id"), title: "Notification delivery evidence", requiredPermission: "notifications.delivery:read", sourceFile: "modules/notifications/pages/DeliveryDetailPage.tsx", Page: lazy(() => import("./pages/DeliveryDetailPage").then((m) => ({ default: m.DeliveryDetailPage }))), modes, navigation: contextual("notifications.deliveries") },
  { id: "notifications.endpoints", module: moduleName, path: PATHS.ENDPOINTS, title: "Notification endpoints", requiredPermission: "notifications.endpoint:read", sourceFile: "modules/notifications/pages/EndpointListPage.tsx", Page: lazy(() => import("./pages/EndpointListPage").then((m) => ({ default: m.EndpointListPage }))), modes, navigation: { type: "sidebar", label: "Endpoints", icon: Cable, order: 530 } },
  { id: "notifications.endpoint-create", module: moduleName, path: PATHS.ENDPOINT_CREATE, title: "Register notification endpoint", requiredPermission: "notifications.endpoint:create", sourceFile: "modules/notifications/pages/CreateEndpointPage.tsx", Page: lazy(() => import("./pages/CreateEndpointPage").then((m) => ({ default: m.CreateEndpointPage }))), modes, navigation: contextual("notifications.endpoints") },
  { id: "notifications.endpoint-edit", module: moduleName, path: PATHS.ENDPOINT_EDIT(":id"), title: "Edit notification endpoint", requiredPermission: "notifications.endpoint:update", sourceFile: "modules/notifications/pages/EditEndpointPage.tsx", Page: lazy(() => import("./pages/EditEndpointPage").then((m) => ({ default: m.EditEndpointPage }))), modes, navigation: contextual("notifications.endpoints") },
  { id: "notifications.configuration", module: moduleName, path: PATHS.CONFIGURATION, title: "Notification configuration", requiredPermission: "notifications.configuration:read", sourceFile: "modules/notifications/pages/NotificationConfigurationPage.tsx", Page: lazy(() => import("./pages/NotificationConfigurationPage").then((m) => ({ default: m.NotificationConfigurationPage }))), modes, navigation: { type: "sidebar", label: "Configuration", icon: Settings2, order: 540 } },
  { id: "notifications.configuration-history", module: moduleName, path: PATHS.CONFIGURATION_HISTORY, title: "Notification configuration history", requiredPermission: "notifications.configuration:read", sourceFile: "modules/notifications/pages/ConfigurationHistoryPage.tsx", Page: lazy(() => import("./pages/ConfigurationHistoryPage").then((m) => ({ default: m.ConfigurationHistoryPage }))), modes, navigation: contextual("notifications.configuration") },
  { id: "notifications.health", module: moduleName, path: PATHS.HEALTH, title: "Notification health", requiredPermission: "notifications.health:read", sourceFile: "modules/notifications/pages/NotificationHealthPage.tsx", Page: lazy(() => import("./pages/NotificationHealthPage").then((m) => ({ default: m.NotificationHealthPage }))), modes, navigation: { type: "sidebar", label: "Health", icon: HeartPulse, order: 550 } },
] satisfies readonly TenantRoute[];

export default tenantRoutes;
