import { z } from 'zod';
import type { IntegrationPlatformConfigurationDocument, JsonValue } from '../contracts';

export const jsonValueSchema: z.ZodType<JsonValue> = z.lazy(() => z.union([z.null(), z.boolean(), z.number().finite(), z.string(), z.array(jsonValueSchema), z.record(z.string(), jsonValueSchema)]));

export const jsonObjectSchema = z.record(z.string(), jsonValueSchema);
export const connectorTypeSchema = z.enum(['api', 'webhook', 'database', 'file', 'message_queue']);
export const credentialTypeSchema = z.enum(['api_key', 'oauth_token', 'username_password', 'certificate']);
export const integrationCreateSchemaFor = (policy: IntegrationPlatformConfigurationDocument) => z.object({ connector_id: z.string().uuid(), name: z.string().trim().min(1).max(policy.validation.name_max_length), description: z.string().trim().max(policy.validation.description_max_length).optional(), integration_type: connectorTypeSchema, config: jsonObjectSchema });
export const credentialCreateSchemaFor = (policy: IntegrationPlatformConfigurationDocument) => z.object({ credential_type: credentialTypeSchema, plaintext: z.string().min(1).max(policy.validation.credential_max_length), expires_at: z.string().datetime().nullable().optional() });
export const webhookSchemaFor = (policy: IntegrationPlatformConfigurationDocument) => z.object({ name: z.string().trim().min(1).max(policy.validation.name_max_length), direction: z.enum(['inbound', 'outbound']), url: z.string().url().max(policy.validation.url_max_length).optional().or(z.literal('')), events: z.array(z.string().trim().min(1).max(policy.validation.event_name_max_length)).min(1).refine((values) => new Set(values).size === values.length, 'Events must be unique.'), config: jsonObjectSchema.optional(), timeout_seconds: z.number().int().min(policy.webhooks.timeout_seconds_min).max(policy.webhooks.timeout_seconds_max), max_attempts: z.number().int().min(policy.webhooks.max_attempts_min).max(policy.webhooks.max_attempts_max) }).superRefine((value, context) => { if (value.direction === 'outbound' && !value.url) context.addIssue({ code: z.ZodIssueCode.custom, path: ['url'], message: 'Outbound webhooks require a URL.' }); if (value.direction === 'inbound' && value.url) context.addIssue({ code: z.ZodIssueCode.custom, path: ['url'], message: 'Inbound webhooks do not accept an outbound URL.' }); });
export const transformationSchema = z.object({ operation: z.enum(['rename', 'string_case', 'trim', 'number', 'date_format', 'default', 'enum_map']), options: jsonObjectSchema.optional() });
export const mappingSchema = z.object({ integration_id: z.string().uuid(), name: z.string().trim().min(1).max(255), source_field: z.string().trim().min(1).max(255), target_field: z.string().trim().min(1).max(255), transform: transformationSchema, position: z.number().int().nonnegative(), is_required: z.boolean(), default_value: jsonValueSchema.optional() });
