import { lazy } from 'react';
import { BadgeCheck, Boxes, Eye, FileCheck2, FilePlus2, Fingerprint, HeartPulse, Link2, Network, Pencil, Radio, Settings2 } from 'lucide-react';
import type { TenantRoute, TenantRouteIcon } from '@/navigation/tenant-route-types';

const MODULE = 'blockchain_traceability';
// Runtime configuration positions the module; no business ordering is embedded in source.
const navigationOrder = 0;
const sidebar = (label: string, icon: TenantRouteIcon, path?: string) => ({ type: 'sidebar' as const, label, icon, order: navigationOrder, ...(path ? { path } : {}) });

export const tenantRoutes = [
  { id: 'blockchain-traceability.assets.list', module: MODULE, path: '/blockchain-traceability/assets', title: 'Traceability assets', sourceFile: 'modules/blockchain_traceability/pages/TraceabilityAssetListPage.tsx', Page: lazy(() => import('./pages/TraceabilityAssetListPage').then(({ TraceabilityAssetListPage }) => ({ default: TraceabilityAssetListPage }))), navigation: sidebar('Assets', Boxes) },
  { id: 'blockchain-traceability.assets.create', module: MODULE, path: '/blockchain-traceability/assets/new', title: 'Register traceability asset', sourceFile: 'modules/blockchain_traceability/pages/CreateTraceabilityAssetPage.tsx', Page: lazy(() => import('./pages/CreateTraceabilityAssetPage').then(({ CreateTraceabilityAssetPage }) => ({ default: CreateTraceabilityAssetPage }))), navigation: sidebar('Register asset', FilePlus2) },
  { id: 'blockchain-traceability.assets.detail', module: MODULE, path: '/blockchain-traceability/assets/:id', title: 'Traceability asset evidence', sourceFile: 'modules/blockchain_traceability/pages/TraceabilityAssetDetailPage.tsx', Page: lazy(() => import('./pages/TraceabilityAssetDetailPage').then(({ TraceabilityAssetDetailPage }) => ({ default: TraceabilityAssetDetailPage }))), navigation: sidebar('Asset details', Eye, '/blockchain-traceability/assets') },
  { id: 'blockchain-traceability.assets.edit', module: MODULE, path: '/blockchain-traceability/assets/:id/edit', title: 'Edit traceability asset', sourceFile: 'modules/blockchain_traceability/pages/EditTraceabilityAssetPage.tsx', Page: lazy(() => import('./pages/EditTraceabilityAssetPage').then(({ EditTraceabilityAssetPage }) => ({ default: EditTraceabilityAssetPage }))), navigation: sidebar('Edit asset', Pencil, '/blockchain-traceability/assets') },

  { id: 'blockchain-traceability.events.list', module: MODULE, path: '/blockchain-traceability/events', title: 'Traceability events', sourceFile: 'modules/blockchain_traceability/pages/TraceabilityEventListPage.tsx', Page: lazy(() => import('./pages/TraceabilityEventListPage').then(({ TraceabilityEventListPage }) => ({ default: TraceabilityEventListPage }))), navigation: sidebar('Events', Radio) },
  { id: 'blockchain-traceability.events.append', module: MODULE, path: '/blockchain-traceability/events/new', title: 'Append traceability event', sourceFile: 'modules/blockchain_traceability/pages/AppendTraceabilityEventPage.tsx', Page: lazy(() => import('./pages/AppendTraceabilityEventPage').then(({ AppendTraceabilityEventPage }) => ({ default: AppendTraceabilityEventPage }))), navigation: sidebar('Append event', FilePlus2) },
  { id: 'blockchain-traceability.events.detail', module: MODULE, path: '/blockchain-traceability/events/:id', title: 'Traceability event evidence', sourceFile: 'modules/blockchain_traceability/pages/TraceabilityEventDetailPage.tsx', Page: lazy(() => import('./pages/TraceabilityEventDetailPage').then(({ TraceabilityEventDetailPage }) => ({ default: TraceabilityEventDetailPage }))), navigation: sidebar('Event details', Eye, '/blockchain-traceability/events') },

  { id: 'blockchain-traceability.anchors.list', module: MODULE, path: '/blockchain-traceability/anchors', title: 'Ledger anchors', sourceFile: 'modules/blockchain_traceability/pages/LedgerAnchorListPage.tsx', Page: lazy(() => import('./pages/LedgerAnchorListPage').then(({ LedgerAnchorListPage }) => ({ default: LedgerAnchorListPage }))), navigation: sidebar('Anchors', Link2) },
  { id: 'blockchain-traceability.anchors.create', module: MODULE, path: '/blockchain-traceability/anchors/new', title: 'Request ledger anchor', sourceFile: 'modules/blockchain_traceability/pages/CreateLedgerAnchorPage.tsx', Page: lazy(() => import('./pages/CreateLedgerAnchorPage').then(({ CreateLedgerAnchorPage }) => ({ default: CreateLedgerAnchorPage }))), navigation: sidebar('Request anchor', FilePlus2) },
  { id: 'blockchain-traceability.anchors.detail', module: MODULE, path: '/blockchain-traceability/anchors/:id', title: 'Ledger anchor evidence', sourceFile: 'modules/blockchain_traceability/pages/LedgerAnchorDetailPage.tsx', Page: lazy(() => import('./pages/LedgerAnchorDetailPage').then(({ LedgerAnchorDetailPage }) => ({ default: LedgerAnchorDetailPage }))), navigation: sidebar('Anchor details', Eye, '/blockchain-traceability/anchors') },

  { id: 'blockchain-traceability.credentials.list', module: MODULE, path: '/blockchain-traceability/credentials', title: 'Authenticity credentials', sourceFile: 'modules/blockchain_traceability/pages/AuthenticityCredentialListPage.tsx', Page: lazy(() => import('./pages/AuthenticityCredentialListPage').then(({ AuthenticityCredentialListPage }) => ({ default: AuthenticityCredentialListPage }))), navigation: sidebar('Credentials', BadgeCheck) },
  { id: 'blockchain-traceability.credentials.issue', module: MODULE, path: '/blockchain-traceability/credentials/new', title: 'Issue authenticity credential', sourceFile: 'modules/blockchain_traceability/pages/IssueAuthenticityCredentialPage.tsx', Page: lazy(() => import('./pages/IssueAuthenticityCredentialPage').then(({ IssueAuthenticityCredentialPage }) => ({ default: IssueAuthenticityCredentialPage }))), navigation: sidebar('Issue credential', FilePlus2) },
  { id: 'blockchain-traceability.credentials.detail', module: MODULE, path: '/blockchain-traceability/credentials/:id', title: 'Authenticity credential evidence', sourceFile: 'modules/blockchain_traceability/pages/AuthenticityCredentialDetailPage.tsx', Page: lazy(() => import('./pages/AuthenticityCredentialDetailPage').then(({ AuthenticityCredentialDetailPage }) => ({ default: AuthenticityCredentialDetailPage }))), navigation: sidebar('Credential details', Eye, '/blockchain-traceability/credentials') },

  { id: 'blockchain-traceability.compliance.list', module: MODULE, path: '/blockchain-traceability/compliance', title: 'Compliance evidence', sourceFile: 'modules/blockchain_traceability/pages/ComplianceEvidenceListPage.tsx', Page: lazy(() => import('./pages/ComplianceEvidenceListPage').then(({ ComplianceEvidenceListPage }) => ({ default: ComplianceEvidenceListPage }))), navigation: sidebar('Compliance', FileCheck2) },
  { id: 'blockchain-traceability.compliance.create', module: MODULE, path: '/blockchain-traceability/compliance/new', title: 'Create compliance evidence', sourceFile: 'modules/blockchain_traceability/pages/CreateComplianceEvidencePage.tsx', Page: lazy(() => import('./pages/CreateComplianceEvidencePage').then(({ CreateComplianceEvidencePage }) => ({ default: CreateComplianceEvidencePage }))), navigation: sidebar('Create evidence', FilePlus2) },
  { id: 'blockchain-traceability.compliance.detail', module: MODULE, path: '/blockchain-traceability/compliance/:id', title: 'Compliance evidence detail', sourceFile: 'modules/blockchain_traceability/pages/ComplianceEvidenceDetailPage.tsx', Page: lazy(() => import('./pages/ComplianceEvidenceDetailPage').then(({ ComplianceEvidenceDetailPage }) => ({ default: ComplianceEvidenceDetailPage }))), navigation: sidebar('Evidence details', Eye, '/blockchain-traceability/compliance') },
  { id: 'blockchain-traceability.compliance.edit', module: MODULE, path: '/blockchain-traceability/compliance/:id/edit', title: 'Edit compliance evidence', sourceFile: 'modules/blockchain_traceability/pages/EditComplianceEvidencePage.tsx', Page: lazy(() => import('./pages/EditComplianceEvidencePage').then(({ EditComplianceEvidencePage }) => ({ default: EditComplianceEvidencePage }))), navigation: sidebar('Edit evidence', Pencil, '/blockchain-traceability/compliance') },
  { id: 'blockchain-traceability.compliance.supersede', module: MODULE, path: '/blockchain-traceability/compliance/supersede', title: 'Supersede compliance evidence', sourceFile: 'modules/blockchain_traceability/pages/SupersedeComplianceEvidencePage.tsx', Page: lazy(() => import('./pages/SupersedeComplianceEvidencePage').then(({ SupersedeComplianceEvidencePage }) => ({ default: SupersedeComplianceEvidencePage }))), navigation: sidebar('Supersede evidence', FilePlus2) },

  { id: 'blockchain-traceability.verify.center', module: MODULE, path: '/blockchain-traceability/verify', title: 'Traceability verification center', sourceFile: 'modules/blockchain_traceability/pages/VerificationCenterPage.tsx', Page: lazy(() => import('./pages/VerificationCenterPage').then(({ VerificationCenterPage }) => ({ default: VerificationCenterPage }))), navigation: sidebar('Verify', Fingerprint) },
  { id: 'blockchain-traceability.verify.attempts', module: MODULE, path: '/blockchain-traceability/verification-attempts', title: 'Verification attempts', sourceFile: 'modules/blockchain_traceability/pages/VerificationAttemptListPage.tsx', Page: lazy(() => import('./pages/VerificationAttemptListPage').then(({ VerificationAttemptListPage }) => ({ default: VerificationAttemptListPage }))), navigation: sidebar('Verification history', HeartPulse) },
  { id: 'blockchain-traceability.verify.attempt-detail', module: MODULE, path: '/blockchain-traceability/verification-attempts/:id', title: 'Verification attempt evidence', sourceFile: 'modules/blockchain_traceability/pages/VerificationAttemptDetailPage.tsx', Page: lazy(() => import('./pages/VerificationAttemptDetailPage').then(({ VerificationAttemptDetailPage }) => ({ default: VerificationAttemptDetailPage }))), navigation: sidebar('Verification details', Eye, '/blockchain-traceability/verification-attempts') },

  { id: 'blockchain-traceability.networks.list', module: MODULE, path: '/blockchain-traceability/networks', title: 'Ledger networks', sourceFile: 'modules/blockchain_traceability/pages/LedgerNetworkListPage.tsx', Page: lazy(() => import('./pages/LedgerNetworkListPage').then(({ LedgerNetworkListPage }) => ({ default: LedgerNetworkListPage }))), navigation: sidebar('Networks', Network) },
  { id: 'blockchain-traceability.networks.create', module: MODULE, path: '/blockchain-traceability/networks/new', title: 'Configure ledger network', sourceFile: 'modules/blockchain_traceability/pages/CreateLedgerNetworkPage.tsx', Page: lazy(() => import('./pages/CreateLedgerNetworkPage').then(({ CreateLedgerNetworkPage }) => ({ default: CreateLedgerNetworkPage }))), navigation: sidebar('Configure network', FilePlus2) },
  { id: 'blockchain-traceability.networks.detail', module: MODULE, path: '/blockchain-traceability/networks/:id', title: 'Ledger network detail', sourceFile: 'modules/blockchain_traceability/pages/LedgerNetworkDetailPage.tsx', Page: lazy(() => import('./pages/LedgerNetworkDetailPage').then(({ LedgerNetworkDetailPage }) => ({ default: LedgerNetworkDetailPage }))), navigation: sidebar('Network details', Eye, '/blockchain-traceability/networks') },
  { id: 'blockchain-traceability.networks.edit', module: MODULE, path: '/blockchain-traceability/networks/:id/edit', title: 'Edit ledger network', sourceFile: 'modules/blockchain_traceability/pages/EditLedgerNetworkPage.tsx', Page: lazy(() => import('./pages/EditLedgerNetworkPage').then(({ EditLedgerNetworkPage }) => ({ default: EditLedgerNetworkPage }))), navigation: sidebar('Edit network', Pencil, '/blockchain-traceability/networks') },

  { id: 'blockchain-traceability.configuration', module: MODULE, path: '/blockchain-traceability/configuration', title: 'Blockchain traceability configuration', sourceFile: 'modules/blockchain_traceability/pages/ConfigurationPage.tsx', Page: lazy(() => import('./pages/ConfigurationPage').then(({ ConfigurationPage }) => ({ default: ConfigurationPage }))), navigation: sidebar('Configuration', Settings2) },
] satisfies readonly TenantRoute[];

export default tenantRoutes;
