import { lazy } from 'react';
import { BadgeCheck, Boxes, FileCheck2, Fingerprint, Link2, Network, Radio } from 'lucide-react';
import type { TenantRoute } from '@/navigation/tenant-route-types';

const MODULE = 'blockchain_traceability';
const contextual = (parentRouteId: string) => ({ type: 'contextual' as const, parentRouteId });

export const tenantRoutes = [
  { id: 'blockchain-traceability.assets.list', module: MODULE, path: '/blockchain-traceability/assets', sourceFile: 'modules/blockchain_traceability/pages/TraceabilityAssetListPage.tsx', Page: lazy(() => import('./pages/TraceabilityAssetListPage').then(({ TraceabilityAssetListPage }) => ({ default: TraceabilityAssetListPage }))), navigation: { type: 'sidebar', label: 'Assets', icon: Boxes, order: 400 } },
  { id: 'blockchain-traceability.assets.create', module: MODULE, path: '/blockchain-traceability/assets/new', sourceFile: 'modules/blockchain_traceability/pages/CreateTraceabilityAssetPage.tsx', Page: lazy(() => import('./pages/CreateTraceabilityAssetPage').then(({ CreateTraceabilityAssetPage }) => ({ default: CreateTraceabilityAssetPage }))), navigation: contextual('blockchain-traceability.assets.list') },
  { id: 'blockchain-traceability.assets.detail', module: MODULE, path: '/blockchain-traceability/assets/:id', sourceFile: 'modules/blockchain_traceability/pages/TraceabilityAssetDetailPage.tsx', Page: lazy(() => import('./pages/TraceabilityAssetDetailPage').then(({ TraceabilityAssetDetailPage }) => ({ default: TraceabilityAssetDetailPage }))), navigation: contextual('blockchain-traceability.assets.list') },
  { id: 'blockchain-traceability.assets.edit', module: MODULE, path: '/blockchain-traceability/assets/:id/edit', sourceFile: 'modules/blockchain_traceability/pages/EditTraceabilityAssetPage.tsx', Page: lazy(() => import('./pages/EditTraceabilityAssetPage').then(({ EditTraceabilityAssetPage }) => ({ default: EditTraceabilityAssetPage }))), navigation: contextual('blockchain-traceability.assets.list') },

  { id: 'blockchain-traceability.events.list', module: MODULE, path: '/blockchain-traceability/events', sourceFile: 'modules/blockchain_traceability/pages/TraceabilityEventListPage.tsx', Page: lazy(() => import('./pages/TraceabilityEventListPage').then(({ TraceabilityEventListPage }) => ({ default: TraceabilityEventListPage }))), navigation: { type: 'sidebar', label: 'Events', icon: Radio, order: 410 } },
  { id: 'blockchain-traceability.events.append', module: MODULE, path: '/blockchain-traceability/events/new', sourceFile: 'modules/blockchain_traceability/pages/AppendTraceabilityEventPage.tsx', Page: lazy(() => import('./pages/AppendTraceabilityEventPage').then(({ AppendTraceabilityEventPage }) => ({ default: AppendTraceabilityEventPage }))), navigation: contextual('blockchain-traceability.events.list') },
  { id: 'blockchain-traceability.events.detail', module: MODULE, path: '/blockchain-traceability/events/:id', sourceFile: 'modules/blockchain_traceability/pages/TraceabilityEventDetailPage.tsx', Page: lazy(() => import('./pages/TraceabilityEventDetailPage').then(({ TraceabilityEventDetailPage }) => ({ default: TraceabilityEventDetailPage }))), navigation: contextual('blockchain-traceability.events.list') },

  { id: 'blockchain-traceability.anchors.list', module: MODULE, path: '/blockchain-traceability/anchors', sourceFile: 'modules/blockchain_traceability/pages/LedgerAnchorListPage.tsx', Page: lazy(() => import('./pages/LedgerAnchorListPage').then(({ LedgerAnchorListPage }) => ({ default: LedgerAnchorListPage }))), navigation: { type: 'sidebar', label: 'Anchors', icon: Link2, order: 420 } },
  { id: 'blockchain-traceability.anchors.create', module: MODULE, path: '/blockchain-traceability/anchors/new', sourceFile: 'modules/blockchain_traceability/pages/CreateLedgerAnchorPage.tsx', Page: lazy(() => import('./pages/CreateLedgerAnchorPage').then(({ CreateLedgerAnchorPage }) => ({ default: CreateLedgerAnchorPage }))), navigation: contextual('blockchain-traceability.anchors.list') },
  { id: 'blockchain-traceability.anchors.detail', module: MODULE, path: '/blockchain-traceability/anchors/:id', sourceFile: 'modules/blockchain_traceability/pages/LedgerAnchorDetailPage.tsx', Page: lazy(() => import('./pages/LedgerAnchorDetailPage').then(({ LedgerAnchorDetailPage }) => ({ default: LedgerAnchorDetailPage }))), navigation: contextual('blockchain-traceability.anchors.list') },

  { id: 'blockchain-traceability.credentials.list', module: MODULE, path: '/blockchain-traceability/credentials', sourceFile: 'modules/blockchain_traceability/pages/AuthenticityCredentialListPage.tsx', Page: lazy(() => import('./pages/AuthenticityCredentialListPage').then(({ AuthenticityCredentialListPage }) => ({ default: AuthenticityCredentialListPage }))), navigation: { type: 'sidebar', label: 'Credentials', icon: BadgeCheck, order: 430 } },
  { id: 'blockchain-traceability.credentials.issue', module: MODULE, path: '/blockchain-traceability/credentials/new', sourceFile: 'modules/blockchain_traceability/pages/IssueAuthenticityCredentialPage.tsx', Page: lazy(() => import('./pages/IssueAuthenticityCredentialPage').then(({ IssueAuthenticityCredentialPage }) => ({ default: IssueAuthenticityCredentialPage }))), navigation: contextual('blockchain-traceability.credentials.list') },
  { id: 'blockchain-traceability.credentials.detail', module: MODULE, path: '/blockchain-traceability/credentials/:id', sourceFile: 'modules/blockchain_traceability/pages/AuthenticityCredentialDetailPage.tsx', Page: lazy(() => import('./pages/AuthenticityCredentialDetailPage').then(({ AuthenticityCredentialDetailPage }) => ({ default: AuthenticityCredentialDetailPage }))), navigation: contextual('blockchain-traceability.credentials.list') },

  { id: 'blockchain-traceability.compliance.list', module: MODULE, path: '/blockchain-traceability/compliance', sourceFile: 'modules/blockchain_traceability/pages/ComplianceEvidenceListPage.tsx', Page: lazy(() => import('./pages/ComplianceEvidenceListPage').then(({ ComplianceEvidenceListPage }) => ({ default: ComplianceEvidenceListPage }))), navigation: { type: 'sidebar', label: 'Compliance', icon: FileCheck2, order: 440 } },
  { id: 'blockchain-traceability.compliance.create', module: MODULE, path: '/blockchain-traceability/compliance/new', sourceFile: 'modules/blockchain_traceability/pages/CreateComplianceEvidencePage.tsx', Page: lazy(() => import('./pages/CreateComplianceEvidencePage').then(({ CreateComplianceEvidencePage }) => ({ default: CreateComplianceEvidencePage }))), navigation: contextual('blockchain-traceability.compliance.list') },
  { id: 'blockchain-traceability.compliance.detail', module: MODULE, path: '/blockchain-traceability/compliance/:id', sourceFile: 'modules/blockchain_traceability/pages/ComplianceEvidenceDetailPage.tsx', Page: lazy(() => import('./pages/ComplianceEvidenceDetailPage').then(({ ComplianceEvidenceDetailPage }) => ({ default: ComplianceEvidenceDetailPage }))), navigation: contextual('blockchain-traceability.compliance.list') },
  { id: 'blockchain-traceability.compliance.edit', module: MODULE, path: '/blockchain-traceability/compliance/:id/edit', sourceFile: 'modules/blockchain_traceability/pages/EditComplianceEvidencePage.tsx', Page: lazy(() => import('./pages/EditComplianceEvidencePage').then(({ EditComplianceEvidencePage }) => ({ default: EditComplianceEvidencePage }))), navigation: contextual('blockchain-traceability.compliance.list') },

  { id: 'blockchain-traceability.verify.center', module: MODULE, path: '/blockchain-traceability/verify', sourceFile: 'modules/blockchain_traceability/pages/VerificationCenterPage.tsx', Page: lazy(() => import('./pages/VerificationCenterPage').then(({ VerificationCenterPage }) => ({ default: VerificationCenterPage }))), navigation: { type: 'sidebar', label: 'Verify', icon: Fingerprint, order: 450 } },
  { id: 'blockchain-traceability.verify.attempts', module: MODULE, path: '/blockchain-traceability/verification-attempts', sourceFile: 'modules/blockchain_traceability/pages/VerificationAttemptListPage.tsx', Page: lazy(() => import('./pages/VerificationAttemptListPage').then(({ VerificationAttemptListPage }) => ({ default: VerificationAttemptListPage }))), navigation: contextual('blockchain-traceability.verify.center') },
  { id: 'blockchain-traceability.verify.attempt-detail', module: MODULE, path: '/blockchain-traceability/verification-attempts/:id', sourceFile: 'modules/blockchain_traceability/pages/VerificationAttemptDetailPage.tsx', Page: lazy(() => import('./pages/VerificationAttemptDetailPage').then(({ VerificationAttemptDetailPage }) => ({ default: VerificationAttemptDetailPage }))), navigation: contextual('blockchain-traceability.verify.center') },

  { id: 'blockchain-traceability.networks.list', module: MODULE, path: '/blockchain-traceability/networks', sourceFile: 'modules/blockchain_traceability/pages/LedgerNetworkListPage.tsx', Page: lazy(() => import('./pages/LedgerNetworkListPage').then(({ LedgerNetworkListPage }) => ({ default: LedgerNetworkListPage }))), navigation: { type: 'sidebar', label: 'Networks', icon: Network, order: 460 } },
  { id: 'blockchain-traceability.networks.create', module: MODULE, path: '/blockchain-traceability/networks/new', sourceFile: 'modules/blockchain_traceability/pages/CreateLedgerNetworkPage.tsx', Page: lazy(() => import('./pages/CreateLedgerNetworkPage').then(({ CreateLedgerNetworkPage }) => ({ default: CreateLedgerNetworkPage }))), navigation: contextual('blockchain-traceability.networks.list') },
  { id: 'blockchain-traceability.networks.detail', module: MODULE, path: '/blockchain-traceability/networks/:id', sourceFile: 'modules/blockchain_traceability/pages/LedgerNetworkDetailPage.tsx', Page: lazy(() => import('./pages/LedgerNetworkDetailPage').then(({ LedgerNetworkDetailPage }) => ({ default: LedgerNetworkDetailPage }))), navigation: contextual('blockchain-traceability.networks.list') },
  { id: 'blockchain-traceability.networks.edit', module: MODULE, path: '/blockchain-traceability/networks/:id/edit', sourceFile: 'modules/blockchain_traceability/pages/EditLedgerNetworkPage.tsx', Page: lazy(() => import('./pages/EditLedgerNetworkPage').then(({ EditLedgerNetworkPage }) => ({ default: EditLedgerNetworkPage }))), navigation: contextual('blockchain-traceability.networks.list') },
] satisfies readonly TenantRoute[];

export default tenantRoutes;
