import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Edit, Power } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { toast } from 'sonner';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { Dialog } from '@/components/ui/Dialog';
import { Input } from '@/components/ui/Input';
import { useAuthStore } from '@/stores/auth-store';
import { CommandButton, commandAffordance, PageHeader, PageSkeleton, ProblemState, StatusPill, titleCase } from '../components/FixedAssetsUI';
import { fixedAssetQueryKeys, fixedAssetsService } from '../services/fixed-assets-service';

export const AssetCategoryDetailPage = () => {
  const { id = '' } = useParams(); const navigate = useNavigate(); const client = useQueryClient(); const tenantId = useAuthStore((state) => state.user?.tenant_id ?? null); const [open, setOpen] = useState(false); const [confirmation, setConfirmation] = useState('');
  const query = useQuery({ queryKey: fixedAssetQueryKeys.category(tenantId, id), queryFn: () => fixedAssetsService.getCategory(id), enabled: Boolean(id) });
  const deactivate = useMutation({ mutationFn: () => fixedAssetsService.deactivateCategory(id), onSuccess: () => { void client.invalidateQueries({ queryKey: fixedAssetQueryKeys.root(tenantId) }); toast.success('Category deactivated'); setOpen(false); } });
  if (query.isLoading) return <PageSkeleton/>;
  if (query.error || !query.data) return <main className="p-4 sm:p-8"><ProblemState error={query.error ?? new Error('Category unavailable')} onRetry={() => void query.refetch()}/></main>;
  const category = query.data; const mappings = [['Asset', category.asset_account_id], ['Accumulated depreciation', category.accumulated_depreciation_account_id], ['Depreciation expense', category.depreciation_expense_account_id], ['Impairment loss', category.impairment_loss_account_id], ['Disposal gain', category.disposal_gain_account_id], ['Disposal loss', category.disposal_loss_account_id]] as const;
  return <main className="space-y-6 p-4 sm:p-8"><PageHeader title={`${category.code} · ${category.name}`} description={category.description || 'No category description'} backLabel="Categories" onBack={() => navigate('/fixed-assets/categories')} actions={<><StatusPill value={category.is_active ? 'active' : 'inactive'}/><CommandButton affordance={commandAffordance(category.allowed_commands, 'edit', category.denial_reasons)} onClick={() => navigate(`/fixed-assets/categories/${id}/edit`)}><Edit className="mr-2 h-4 w-4"/>Edit</CommandButton><CommandButton affordance={commandAffordance(category.allowed_commands, 'deactivate', category.denial_reasons)} variant="danger" onClick={() => setOpen(true)}><Power className="mr-2 h-4 w-4"/>Deactivate</CommandButton></>}/><section className="grid gap-4 sm:grid-cols-3"><Card className="p-5"><p className="text-xs text-muted-foreground">Default method</p><p className="mt-2 font-semibold">{titleCase(category.default_depreciation_method)}</p></Card><Card className="p-5"><p className="text-xs text-muted-foreground">Useful life</p><p className="mt-2 font-semibold">{category.default_useful_life_months} months</p></Card><Card className="p-5"><p className="text-xs text-muted-foreground">Residual value</p><p className="mt-2 font-semibold">{category.default_residual_value_percent}%</p></Card></section><Card className="p-6"><h2 className="font-semibold">Accounting mappings</h2><p className="mt-1 text-sm text-muted-foreground">Identifiers are validated against the same tenant. Unavailable accounting capability blocks posting without fabricating success.</p><dl className="mt-5 grid gap-4 sm:grid-cols-2">{mappings.map(([label, value]) => <div key={label}><dt className="text-xs uppercase text-muted-foreground">{label}</dt><dd className="mt-1 break-all font-mono text-sm">{value ?? 'Not mapped'}</dd></div>)}</dl></Card><Dialog open={open} onOpenChange={setOpen} title="Deactivate category" description="Existing assets retain this protected category. New drafts cannot use it, and deactivation is blocked if a draft would be left unusable."><Input id="category-confirmation" label={`Type ${category.code} to confirm`} value={confirmation} onChange={(event) => setConfirmation(event.target.value)}/>{deactivate.error && <ProblemState error={deactivate.error}/>}<div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={() => setOpen(false)}>Cancel</Button><Button variant="danger" disabled={confirmation !== category.code || deactivate.isPending} onClick={() => deactivate.mutate()}>{deactivate.isPending ? 'Deactivating…' : 'Deactivate category'}</Button></div></Dialog></main>;
};
