import { useMutation, useQuery } from '@tanstack/react-query';
import { useNavigate, useParams } from 'react-router-dom';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { useAuthStore } from '@/stores/auth-store';
import { CommandButton, commandAffordance, formatDateOnly, formatMoney, PageHeader, PageSkeleton, ProblemState, StatusPill } from '../components/FixedAssetsUI';
import { fixedAssetQueryKeys, fixedAssetsService, shouldPollJob } from '../services/fixed-assets-service';

// eslint-disable-next-line complexity
export const DepreciationLineDetailPage = () => {
  const { id = '' } = useParams(); const navigate = useNavigate(); const tenantId = useAuthStore((state) => state.user?.tenant_id ?? null);
  const query = useQuery({ queryKey: fixedAssetQueryKeys.line(tenantId, id), queryFn: () => fixedAssetsService.getLine(id), enabled: Boolean(id) });
  const post = useMutation({ mutationFn: () => fixedAssetsService.postLine(id, {}, `post-line:${id}`), onSuccess: () => void query.refetch() });
  const jobId = post.data?.id ?? query.data?.posting_job_id ?? ''; const job = useQuery({ queryKey: fixedAssetQueryKeys.job(tenantId, jobId), queryFn: () => fixedAssetsService.getJob(jobId), enabled: Boolean(jobId), refetchInterval: (state) => shouldPollJob(state.state.data) ? 1500 : false });
  if (query.isLoading) return <PageSkeleton/>; if (query.error || !query.data) return <main className="p-4 sm:p-8"><ProblemState error={query.error ?? new Error('Line unavailable')} onRetry={() => void query.refetch()}/></main>;
  const line = query.data; const currency = line.currency ?? 'USD'; const affordance = commandAffordance(line.allowed_commands, line.status === 'failed' ? 'retry' : 'post', line.denial_reasons);
  const schedulePath = `/fixed-assets/depreciation-schedules/${line.schedule_id}${line.posting_job_id ? `?job=${line.posting_job_id}` : ''}`;
  return <main className="space-y-6 p-4 sm:p-8"><PageHeader title={`Depreciation period ${line.sequence}`} description={`${formatDateOnly(line.period_start)} to ${formatDateOnly(line.period_end)}`} backLabel="Schedule" onBack={() => navigate(schedulePath)} actions={<StatusPill value={line.status}/>}/><section className="grid gap-4 sm:grid-cols-3"><Card className="p-5"><p className="text-xs text-muted-foreground">Opening value</p><p className="mt-2 font-semibold">{formatMoney(line.opening_net_book_value, currency)}</p></Card><Card className="p-5"><p className="text-xs text-muted-foreground">Depreciation</p><p className="mt-2 font-semibold">{formatMoney(line.depreciation_amount, currency)}</p></Card><Card className="p-5"><p className="text-xs text-muted-foreground">Closing value</p><p className="mt-2 font-semibold">{formatMoney(line.closing_net_book_value, currency)}</p></Card></section><Card className="grid gap-4 p-6 sm:grid-cols-2"><Field label="Accumulated depreciation" value={formatMoney(line.accumulated_depreciation, currency)}/><Field label="Units consumed" value={line.units_consumed ?? 'Not applicable'}/><Field label="Journal entry" value={line.journal_entry_id ?? 'Not posted'}/><Field label="Posted at" value={line.posted_at ? new Date(line.posted_at).toLocaleString() : 'Not posted'}/>{line.posting_error_code && <Field label="Posting error code" value={line.posting_error_code}/>}</Card>{(line.status === 'planned' || line.status === 'failed') && <CommandButton affordance={affordance} onClick={() => post.mutate()}>{line.status === 'failed' ? 'Retry posting' : 'Post depreciation'}</CommandButton>}{post.error && <ProblemState error={post.error}/>} {job.error && <ProblemState error={job.error} onRetry={() => void job.refetch()}/>} {job.data && <Card className="p-5" role="status"><div className="flex justify-between"><strong>Job {job.data.status}</strong><span>{job.data.progress_percent === null ? "In progress" : `${job.data.progress_percent}%`}</span></div><p className="mt-2 font-mono text-xs text-muted-foreground">Correlation ID: {job.data.correlation_id}</p>{job.data.error_code && <p className="mt-2 text-sm text-destructive">Error code: {job.data.error_code}</p>}<Button className="mt-3" variant="secondary" onClick={() => void job.refetch()}>Refresh status</Button></Card>}</main>;
};
const Field = ({ label, value }: { label: string; value: string }) => <div><p className="text-xs uppercase text-muted-foreground">{label}</p><p className="mt-1 break-all text-sm">{value}</p></div>;
