import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, Eye, X } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import type { TaskOrdering, TaskStatus, WorkflowTaskListDTO } from "../contracts";
import { ROUTES } from "../contracts";
import { WorkflowApiError, workflowService } from "../services/workflow-service";
import { TaskDecisionDialog } from "../components/TaskDecisionDialog";
import { EmptyPanel, PageHeader, PageSkeleton, Pagination, StatusPill, WorkflowProblem } from "../components/WorkflowUI";
import { formatDate, newTransitionKey } from "../workflow-utils";
import { useWorkflowConfiguration } from "../hooks/use-workflow-configuration";

const selectClass = "rounded-md border border-input bg-background px-3 py-2 text-sm";
// State handling covers pending, stale, filtered-empty, and terminal task decisions.
// eslint-disable-next-line complexity
export function TaskInboxPage() {
  const navigate = useNavigate(); const cache = useQueryClient(); const configuration = useWorkflowConfiguration(); const policy = configuration.data?.document; const [page, setPage] = useState(1); const [status, setStatus] = useState<TaskStatus | "">(""); const [overdue, setOverdue] = useState(false); const [ordering, setOrdering] = useState<TaskOrdering | null>(null); const [selected, setSelected] = useState<WorkflowTaskListDTO | null>(null); const [decision, setDecision] = useState<"complete" | "reject">("complete"); const [success, setSuccess] = useState("");
  const resolvedStatus = status || policy?.defaults.task_status;
  const resolvedOrdering = ordering ?? policy?.defaults.task_ordering;
  const filters = { page, page_size: policy?.limits.workflow_page_size, scope: policy?.defaults.task_scope, status: resolvedStatus, overdue: overdue || undefined, ordering: resolvedOrdering };
  const query = useQuery({ queryKey: ["workflow-tasks", filters], queryFn: () => workflowService.tasks.list(filters), enabled: Boolean(policy) });
  const mutation = useMutation({ mutationFn: ({ task, reason }: { task: WorkflowTaskListDTO; reason: string }) => decision === "complete" ? workflowService.tasks.complete(task.id, { meta_data: {}, transition_key: newTransitionKey("complete") }) : workflowService.tasks.reject(task.id, { reason, meta_data: {}, transition_key: newTransitionKey("reject") }), onSuccess: (task) => { setSuccess(`${task.step_name} is now ${task.status}.`); setSelected(null); void cache.invalidateQueries({ queryKey: ["workflow-tasks"] }); } });
  const choose = (task: WorkflowTaskListDTO, next: "complete" | "reject"): void => { setSelected(task); setDecision(next); mutation.reset(); };
  if (query.isLoading) return <PageSkeleton label="Loading workflow task inbox"/>;
  if (query.error) return <WorkflowProblem error={query.error} retry={() => void query.refetch()}/>;
  const stale = mutation.error instanceof WorkflowApiError && mutation.error.status === 409;
  return <main className="space-y-6"><PageHeader title="My tasks" description="Decide assigned work with deadline, workflow, subject, and immutable evidence in view."/>{success ? <div role="status" className="rounded border border-primary/40 bg-primary/5 p-3 text-sm text-primary">{success}</div> : null}{stale ? <div role="alert" className="rounded border border-destructive/40 bg-destructive/5 p-3 text-sm text-destructive">This task changed before your decision was recorded. No duplicate decision was applied. <Button variant="ghost" onClick={() => { setSelected(null); void query.refetch(); }}>Refresh task state</Button></div> : null}
    <Card className="flex flex-wrap gap-3 p-4"><select aria-label="Filter task status" className={selectClass} value={resolvedStatus ?? ""} onChange={(event) => { setStatus(event.target.value as TaskStatus | ""); setPage(1); }}><option value="">All statuses</option>{["pending","completed","rejected","cancelled","expired"].map((value) => <option key={value}>{value}</option>)}</select><label className="flex items-center gap-2 rounded border px-3 text-sm"><input type="checkbox" checked={overdue} onChange={(event) => setOverdue(event.target.checked)}/>Overdue only</label><select aria-label="Order tasks" className={selectClass} value={resolvedOrdering ?? ""} onChange={(event) => setOrdering(event.target.value as TaskOrdering)}><option value="due_date">Due soonest</option><option value="-due_date">Due latest</option><option value="created_at">Oldest assigned</option></select></Card>
    {!query.data?.items.length ? <EmptyPanel title={status || overdue ? "No tasks match these filters" : "All caught up"} description={status || overdue ? "Change the status or overdue filter to view other decisions." : "You have no workflow decisions waiting."} action={status || overdue ? <Button onClick={() => { setStatus(""); setOverdue(false); }}>Clear filters</Button> : undefined}/> : <><div className="grid gap-4">{query.data.items.map((task) => <Card key={task.id} className="p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><StatusPill status={task.status}/>{task.due_date && new Date(task.due_date) < new Date() && task.status === "pending" ? <StatusPill status="overdue"/> : null}</div><button className="mt-2 text-lg font-semibold hover:text-primary" onClick={() => navigate(ROUTES.TASK_DETAIL(task.id))}>{task.step_name}</button><p className="text-sm text-muted-foreground">{task.workflow_name} · v{task.workflow_version}</p><p className="mt-2 text-sm">{task.subject ?? "Workflow decision"}</p><p className="mt-2 text-xs text-muted-foreground">Due {formatDate(task.due_date)} · assigned to {task.assignment_label}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => navigate(ROUTES.TASK_DETAIL(task.id))}><Eye className="mr-2 h-4 w-4"/>Details</Button>{task.allowed_actions.includes("reject") ? <Button size="sm" variant="outline" disabled={mutation.isPending} onClick={() => choose(task, "reject")}><X className="mr-2 h-4 w-4"/>Reject</Button> : null}{task.allowed_actions.includes("complete") ? <Button size="sm" disabled={mutation.isPending} onClick={() => choose(task, "complete")}><Check className="mr-2 h-4 w-4"/>Approve / complete</Button> : null}</div></div></Card>)}</div><Pagination page={query.data.pagination.page} totalPages={query.data.pagination.total_pages} onPage={setPage}/></>}
    <TaskDecisionDialog open={Boolean(selected)} decision={decision} taskName={selected?.step_name ?? "task"} pending={mutation.isPending} error={mutation.error} onOpenChange={(open) => { if (!open) setSelected(null); }} onSubmit={(reason) => { if (selected) mutation.mutate({ task: selected, reason }); }}/>
  </main>;
}
