import { useEffect } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, Copy, Pencil, Play, Send } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { ROUTES } from "../contracts";
import { workflowService } from "../services/workflow-service";
import { PageHeader, PageSkeleton, StatusPill, WorkflowProblem } from "../components/WorkflowUI";
import { formatDate, newTransitionKey } from "../workflow-utils";

export function WorkflowDetailPage() {
  const { id = "" } = useParams(); const navigate = useNavigate(); const cache = useQueryClient();
  const query = useQuery({ queryKey: ["workflow-definition", id], queryFn: () => workflowService.workflows.get(id), enabled: Boolean(id) });
  useEffect(() => { if (query.data) document.title = `${query.data.name} · Workflows · SARAISE`; }, [query.data]);
  const refresh = (): void => { void cache.invalidateQueries({ queryKey: ["workflow-definition", id] }); };
  const publish = useMutation({ mutationFn: () => workflowService.workflows.publish(id, { transition_key: newTransitionKey("publish") }), onSuccess: refresh });
  const archive = useMutation({ mutationFn: () => workflowService.workflows.archive(id, { transition_key: newTransitionKey("archive") }), onSuccess: refresh });
  const clone = useMutation({ mutationFn: () => workflowService.workflows.clone(id), onSuccess: (workflow) => navigate(ROUTES.WORKFLOW_EDIT(workflow.id)) });
  const start = useMutation({ mutationFn: () => workflowService.instances.start({ workflow_id: id, context_data: {}, idempotency_key: newTransitionKey("start") }), onSuccess: (instance) => navigate(ROUTES.INSTANCE_DETAIL(instance.id)) });
  if (query.isLoading) return <PageSkeleton label="Loading workflow definition"/>;
  if (query.error) return <WorkflowProblem error={query.error} retry={() => void query.refetch()}/>;
  const workflow = query.data; if (!workflow) return <WorkflowProblem error={new Error("Workflow not found") } retry={() => void query.refetch()}/>;
  const degraded = workflow.handler_health.filter((handler) => handler.availability === "degraded" || handler.availability === "setup_required");
  return <main className="space-y-6"><PageHeader eyebrow={`${workflow.key} · version ${workflow.version}`} title={workflow.name} description={workflow.description || "No description provided."} actions={<>{workflow.allowed_actions.includes("edit") ? <Button variant="outline" onClick={() => navigate(ROUTES.WORKFLOW_EDIT(workflow.id))}><Pencil className="mr-2 h-4 w-4"/>Edit draft</Button> : null}{workflow.allowed_actions.includes("clone") ? <Button variant="outline" disabled={clone.isPending} onClick={() => clone.mutate()}><Copy className="mr-2 h-4 w-4"/>Clone version</Button> : null}{workflow.allowed_actions.includes("publish") ? <Button disabled={publish.isPending || degraded.length > 0} onClick={() => publish.mutate()}><Send className="mr-2 h-4 w-4"/>Publish</Button> : null}{workflow.allowed_actions.includes("archive") ? <Button variant="outline" disabled={archive.isPending} onClick={() => archive.mutate()}><Archive className="mr-2 h-4 w-4"/>Archive</Button> : null}{workflow.allowed_actions.includes("start") ? <Button disabled={start.isPending || degraded.length > 0} onClick={() => start.mutate()}><Play className="mr-2 h-4 w-4"/>Run</Button> : null}</>}/>
    {workflow.status !== "draft" ? <div className="rounded border bg-muted/40 p-3 text-sm">Published and archived versions are read-only. Clone this version to make a safe change.</div> : null}
    {degraded.length ? <div role="alert" className="rounded border border-amber-500/40 p-4"><h2 className="font-semibold">Required capability needs attention</h2>{degraded.map((handler) => <p key={handler.key} className="mt-1 text-sm">{handler.key}: {handler.reason ?? handler.availability}</p>)}</div> : null}
    <div className="grid gap-4 md:grid-cols-4"><Card className="p-4"><p className="text-xs text-muted-foreground">Status</p><div className="mt-2"><StatusPill status={workflow.status}/></div></Card><Card className="p-4"><p className="text-xs text-muted-foreground">Type / trigger</p><p className="mt-2 font-medium">{workflow.workflow_type} · {workflow.trigger_type}</p></Card><Card className="p-4"><p className="text-xs text-muted-foreground">Executions</p><p className="mt-2 text-2xl font-semibold">{workflow.execution_statistics.total}</p></Card><Card className="p-4"><p className="text-xs text-muted-foreground">Completion rate</p><p className="mt-2 text-2xl font-semibold">{workflow.execution_statistics.completion_rate === null ? "—" : `${Math.round(workflow.execution_statistics.completion_rate * 100)}%`}</p></Card></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,2fr)_minmax(260px,1fr)]"><Card className="p-5"><h2 className="text-lg font-semibold">Step graph</h2><ol className="mt-5 space-y-3">{workflow.steps.map((step) => <li key={step.id} className="relative rounded-lg border p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs text-muted-foreground">{step.order}. {step.key}</p><p className="font-medium">{step.name}</p></div><div className="flex gap-2"><StatusPill status={step.step_type}/>{step.is_terminal ? <StatusPill status="terminal"/> : null}</div></div>{step.timeout_seconds ? <p className="mt-2 text-xs text-muted-foreground">Timeout {step.timeout_seconds}s · {step.timeout_action}</p> : null}</li>)}</ol></Card><div className="space-y-5"><Card className="p-5"><h2 className="font-semibold">Version history</h2><ul className="mt-3 space-y-3">{workflow.versions.map((version) => <li key={version.id}><button className="flex w-full items-center justify-between rounded border p-3 text-left hover:bg-muted" onClick={() => navigate(ROUTES.WORKFLOW_DETAIL(version.id))}><span>Version {version.version}</span><StatusPill status={version.status}/></button></li>)}</ul></Card><Card className="p-5"><h2 className="font-semibold">Validation & evidence</h2><p className="mt-2 text-sm text-muted-foreground">{workflow.steps.length} steps · updated {formatDate(workflow.updated_at)}</p><p className="mt-2 text-sm">{workflow.transition_history.length} immutable definition transitions recorded.</p></Card></div></div>
  </main>;
}
