import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Download, History, RotateCcw, Upload } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';
import { ConfirmDialog } from '@/components/ui/Dialog';
import { Input } from '@/components/ui/Input';
import { GovernedError, SalesPage, newIdempotencyKey, useUnsavedChanges } from '../components/SalesUi';
import type { ConfigurationExport, SalesConfigurationValues } from '../contracts';
import { salesQueryKeys, salesService } from '../services/sales-service';

const isExport=(value:unknown):value is ConfigurationExport=>Boolean(value&&typeof value==='object'&&'schema_version'in value&&(value as {schema_version?:unknown}).schema_version===1&&'values'in value);
export function SalesConfigurationPage(){
 const cache=useQueryClient();const current=useQuery({queryKey:salesQueryKeys.configuration(),queryFn:salesService.getConfiguration});const versions=useQuery({queryKey:salesQueryKeys.configurationVersions(),queryFn:()=>salesService.listConfigurationVersions()});
 const [values,setValues]=useState<SalesConfigurationValues|null>(null);const [reason,setReason]=useState('');const [selectedVersion,setSelectedVersion]=useState<number|null>(null);const [rollbackOpen,setRollbackOpen]=useState(false);const [importDocument,setImportDocument]=useState<ConfigurationExport|null>(null);const [importError,setImportError]=useState('');
 useEffect(()=>{if(current.data&&!values)setValues({default_currency:current.data.default_currency,currency_decimal_places:current.data.currency_decimal_places,rounding_mode:current.data.rounding_mode,quotation_validity_days:current.data.quotation_validity_days,credit_check_enabled:current.data.credit_check_enabled,inventory_confirmation_required:current.data.inventory_confirmation_required,manual_discount_enabled:current.data.manual_discount_enabled,maximum_manual_discount_percent:current.data.maximum_manual_discount_percent,manual_tax_enabled:current.data.manual_tax_enabled,quotation_prefix:current.data.quotation_prefix,order_prefix:current.data.order_prefix,delivery_prefix:current.data.delivery_prefix,sequence_padding:current.data.sequence_padding});},[current.data,values]);
 const dirty=Boolean(values&&current.data&&Object.entries(values).some(([key,value])=>String(current.data?.[key as keyof typeof current.data])!==String(value)));useUnsavedChanges(dirty);
 const preview=useMutation({mutationFn:()=>salesService.previewConfiguration(values??{})});const apply=useMutation({mutationFn:()=>salesService.applyConfiguration({expected_version:current.data?.version??0,values:values??{},reason}),onSuccess:(saved)=>{setReason('');setValues({default_currency:saved.default_currency,currency_decimal_places:saved.currency_decimal_places,rounding_mode:saved.rounding_mode,quotation_validity_days:saved.quotation_validity_days,credit_check_enabled:saved.credit_check_enabled,inventory_confirmation_required:saved.inventory_confirmation_required,manual_discount_enabled:saved.manual_discount_enabled,maximum_manual_discount_percent:saved.maximum_manual_discount_percent,manual_tax_enabled:saved.manual_tax_enabled,quotation_prefix:saved.quotation_prefix,order_prefix:saved.order_prefix,delivery_prefix:saved.delivery_prefix,sequence_padding:saved.sequence_padding});void cache.invalidateQueries({queryKey:salesQueryKeys.all});}});
 const rollback=useMutation({mutationFn:()=>salesService.rollbackConfiguration({target_version:selectedVersion??0,expected_version:current.data?.version??0,reason,idempotency_key:newIdempotencyKey()}),onSuccess:()=>{setRollbackOpen(false);setReason('');void cache.invalidateQueries({queryKey:salesQueryKeys.all});}});
 const importPreview=useMutation({mutationFn:()=>salesService.importConfiguration({expected_version:current.data?.version??0,document:importDocument as ConfigurationExport,dry_run:true,reason:reason||'Validate imported configuration'})});const importApply=useMutation({mutationFn:()=>salesService.importConfiguration({expected_version:current.data?.version??0,document:importDocument as ConfigurationExport,dry_run:false,reason}),onSuccess:()=>{setImportDocument(null);setReason('');void cache.invalidateQueries({queryKey:salesQueryKeys.all});}});
 const selected=useQuery({queryKey:salesQueryKeys.configurationVersion(selectedVersion??0),queryFn:()=>salesService.getConfigurationVersion(selectedVersion??0),enabled:selectedVersion!==null});
 if(current.isLoading)return <SalesPage title="Sales configuration" description="Loading tenant policy…"><div className="h-96 animate-pulse rounded-lg bg-muted"/></SalesPage>;if(current.error||!current.data||!values)return <SalesPage title="Sales configuration" description="Tenant policy unavailable"><GovernedError error={current.error} onRetry={()=>void current.refetch()}/></SalesPage>;
 const set=<K extends keyof SalesConfigurationValues>(key:K,value:SalesConfigurationValues[K])=>setValues((existing)=>existing?{...existing,[key]:value}:existing);const invalid=!/^[A-Z]{3}$/.test(values.default_currency)||values.currency_decimal_places<0||values.currency_decimal_places>4||!['ROUND_HALF_UP','ROUND_HALF_EVEN'].includes(values.rounding_mode)||values.quotation_validity_days<1||values.quotation_validity_days>365||Number(values.maximum_manual_discount_percent)<0||Number(values.maximum_manual_discount_percent)>100||values.sequence_padding<4||values.sequence_padding>12||![values.quotation_prefix,values.order_prefix,values.delivery_prefix].every((prefix)=>/^[A-Z0-9-]{1,12}$/.test(prefix));
 const download=async()=>{const document=await salesService.exportConfiguration();const url=URL.createObjectURL(new Blob([JSON.stringify(document,null,2)],{type:'application/json'}));const anchor=window.document.createElement('a');anchor.href=url;anchor.download=`sales-configuration-${document.environment}.json`;anchor.click();URL.revokeObjectURL(url);};
 return <SalesPage title="Sales configuration" description={`Environment: ${current.data.environment}. Version ${current.data.version}. Every change is validated, previewed, audited, and reversible.`} actions={<Button variant="outline" onClick={()=>void download()}><Download className="mr-2 h-4 w-4"/>Export</Button>}>
  {(preview.error||apply.error||rollback.error||importPreview.error||importApply.error)&&<GovernedError error={preview.error??apply.error??rollback.error??importPreview.error??importApply.error}/>}<Card><CardHeader><CardTitle>Runtime policy</CardTitle><p className="text-sm text-muted-foreground">Changes apply without restart unless the dry-run explicitly reports otherwise.</p></CardHeader><CardContent><form className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3" onSubmit={(e)=>{e.preventDefault();if(!invalid&&reason.trim())apply.mutate();}}><Input label="Default currency" maxLength={3} value={values.default_currency} onChange={(e)=>set('default_currency',e.target.value.toUpperCase())} error={!/^[A-Z]{3}$/.test(values.default_currency)?'Use three uppercase letters.':undefined}/><Input label="Currency decimal places" type="number" min={0} max={4} value={values.currency_decimal_places} onChange={(e)=>set('currency_decimal_places',Number(e.target.value))}/><label className="text-sm font-medium">Rounding mode<select className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3" value={values.rounding_mode} onChange={(e)=>set('rounding_mode',e.target.value as SalesConfigurationValues['rounding_mode'])}><option value="ROUND_HALF_UP">Half up</option><option value="ROUND_HALF_EVEN">Half even</option></select></label><Input label="Quotation validity (days)" type="number" min={1} max={365} value={values.quotation_validity_days} onChange={(e)=>set('quotation_validity_days',Number(e.target.value))}/><Input label="Sequence padding" type="number" min={4} max={12} value={values.sequence_padding} onChange={(e)=>set('sequence_padding',Number(e.target.value))}/>{(['quotation_prefix','order_prefix','delivery_prefix'] as const).map((key)=><Input key={key} label={key.replaceAll('_',' ')} title="Uppercase letters, digits, and hyphens; 1–12 characters." maxLength={12} value={values[key]} onChange={(e)=>set(key,e.target.value.toUpperCase())} error={!/^[A-Z0-9-]{1,12}$/.test(values[key])?'Use 1–12 uppercase letters, digits, or hyphens.':undefined}/>)}
   <label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={values.credit_check_enabled} onChange={(e)=>set('credit_check_enabled',e.target.checked)}/>Enable credit checks <span title="Confirmation rejects orders exceeding configured customer credit policy." aria-label="Credit check guidance">ⓘ</span></label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={values.inventory_confirmation_required} onChange={(e)=>set('inventory_confirmation_required',e.target.checked)}/>Require inventory confirmation <span title="If inventory capability is unavailable, order confirmation fails explicitly." aria-label="Inventory guidance">ⓘ</span></label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={values.manual_tax_enabled} onChange={(e)=>set('manual_tax_enabled',e.target.checked)}/>Allow manual tax</label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={values.manual_discount_enabled} onChange={(e)=>set('manual_discount_enabled',e.target.checked)}/>Allow manual discounts</label><Input label="Maximum manual discount %" type="number" min={0} max={100} disabled={!values.manual_discount_enabled} value={values.maximum_manual_discount_percent} onChange={(e)=>set('maximum_manual_discount_percent',e.target.value)}/><div className="sm:col-span-2 lg:col-span-3"><Input label="Change reason" value={reason} onChange={(e)=>setReason(e.target.value)} maxLength={500} required aria-describedby="reason-help"/><p id="reason-help" className="mt-1 text-xs text-muted-foreground">Required audit evidence for apply, rollback, and import.</p></div><div className="flex flex-wrap gap-3 sm:col-span-2 lg:col-span-3"><Button type="button" variant="outline" disabled={invalid||preview.isPending} onClick={()=>preview.mutate()}>{preview.isPending?'Validating…':'Preview changes'}</Button><Button type="submit" disabled={!dirty||invalid||!reason.trim()||apply.isPending}>{apply.isPending?'Applying…':'Apply configuration'}</Button></div></form></CardContent></Card>
  {preview.data&&<Card><CardHeader><CardTitle>Dry-run diff</CardTitle></CardHeader><CardContent><p className="mb-3 text-sm">{preview.data.restart_required?'A service restart is required after apply.':'No service restart is required.'}</p>{preview.data.diff.length===0?<p className="text-sm text-muted-foreground">No effective changes.</p>:<ul className="space-y-2">{preview.data.diff.map((diff)=><li key={diff.field} className="rounded border border-border p-3 text-sm"><strong>{diff.field}</strong>: {String(diff.before)} → {String(diff.after)}</li>)}</ul>}</CardContent></Card>}
  <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><History className="h-5 w-5"/>Version history</CardTitle></CardHeader><CardContent>{versions.error?<GovernedError error={versions.error}/>:<div className="space-y-2">{versions.data?.data.map((version)=><button key={version.id} type="button" onClick={()=>setSelectedVersion(version.version)} className="w-full rounded-md border border-border p-3 text-left hover:bg-muted"><strong>Version {version.version}</strong><span className="ml-2 text-sm text-muted-foreground">{new Date(version.created_at).toLocaleString()} · {version.change_reason}</span></button>)}{versions.data?.data.length===0&&<p className="text-sm text-muted-foreground">No historical versions yet.</p>}</div>}</CardContent></Card><Card><CardHeader><CardTitle>Version detail</CardTitle></CardHeader><CardContent>{selected.isLoading?<div className="h-24 animate-pulse rounded bg-muted"/>:selected.data?<><pre className="max-h-64 overflow-auto rounded bg-muted p-3 text-xs">{JSON.stringify(selected.data.snapshot,null,2)}</pre><Button className="mt-3" variant="outline" disabled={!reason.trim()} onClick={()=>setRollbackOpen(true)}><RotateCcw className="mr-2 h-4 w-4"/>Rollback to version {selected.data.version}</Button></>:<p className="text-sm text-muted-foreground">Select a version to inspect its immutable snapshot.</p>}</CardContent></Card></div>
  <Card><CardHeader><CardTitle className="flex items-center gap-2"><Upload className="h-5 w-5"/>Import configuration</CardTitle><p className="text-sm text-muted-foreground">Import is first dry-run validated against the same server schema as the UI.</p></CardHeader><CardContent><input type="file" accept="application/json,.json" aria-label="Configuration document" onChange={(event)=>{const file=event.target.files?.[0];if(!file)return;void file.text().then((text)=>{try{const parsed:unknown=JSON.parse(text);if(!isExport(parsed))throw new Error('Invalid configuration document schema.');setImportDocument(parsed);setImportError('');}catch(error){setImportDocument(null);setImportError(error instanceof Error?error.message:'Invalid JSON document.');}});}}/>{importError&&<p role="alert" className="mt-2 text-sm text-destructive">{importError}</p>}<div className="mt-4 flex gap-3"><Button variant="outline" disabled={!importDocument||importPreview.isPending} onClick={()=>importPreview.mutate()}>Validate import</Button><Button disabled={!importDocument||!reason.trim()||!importPreview.data||importApply.isPending} onClick={()=>importApply.mutate()}>Apply import</Button></div>{importPreview.data&&<pre className="mt-4 max-h-48 overflow-auto rounded bg-muted p-3 text-xs">{JSON.stringify(importPreview.data,null,2)}</pre>}</CardContent></Card>
  <ConfirmDialog open={rollbackOpen} onOpenChange={setRollbackOpen} title={`Rollback to version ${selectedVersion}?`} description="Rollback creates a new immutable version; it never edits audit history." confirmLabel={rollback.isPending?'Rolling back…':'Create rollback version'} onConfirm={()=>rollback.mutate()}/>
 </SalesPage>;
}
