import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { ArrowRight, Boxes, FileCheck2, FileText, PlugZap, Users } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';
import { GovernedError, SalesPage, StatusPill } from '../components/SalesUi';
import { SALES_PATHS } from '../contracts';
import { salesQueryKeys, salesService } from '../services/sales-service';

export function SalesDashboardPage() {
  const summary=useQuery({queryKey:[...salesQueryKeys.dashboard(),'summary'],queryFn:salesService.getSummary});
  const capabilities=useQuery({queryKey:[...salesQueryKeys.dashboard(),'capabilities'],queryFn:salesService.getCapabilities});
  const error=summary.error??capabilities.error;
  const fulfillment=summary.data?Object.values(summary.data.fulfillment_stages).reduce((total,count)=>total+count,0):undefined;
  const cards=[{label:'Open quotations',value:summary.data?.open_quotations,Icon:FileText,path:SALES_PATHS.QUOTATIONS},{label:'Confirmed orders',value:summary.data?.confirmed_orders,Icon:Boxes,path:SALES_PATHS.ORDERS},{label:'In fulfillment',value:fulfillment,Icon:FileCheck2,path:SALES_PATHS.ORDERS},{label:'Recent deliveries',value:summary.data?.recent_deliveries.length,Icon:FileCheck2,path:SALES_PATHS.DELIVERIES}];
  return <SalesPage title="Sales overview" description="Authoritative quote-to-delivery workload from the server summary. Unavailable data is never inferred or displayed as zero." actions={<><Link to={`${SALES_PATHS.QUOTATIONS}/new`}><Button>Create quote</Button></Link><Link to={`${SALES_PATHS.ORDERS}/new`}><Button variant="outline">Create order</Button></Link></>}>
    {error?<GovernedError error={error} onRetry={()=>{void summary.refetch();void capabilities.refetch();}}/>:summary.isLoading||capabilities.isLoading?<div aria-label="Loading sales summary" className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map((card)=><div key={card.label} className="h-36 animate-pulse rounded-lg bg-muted"/>)}</div>:<>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(({label,value,Icon,path})=><Card key={label}><CardContent className="pt-6"><div className="flex items-start justify-between"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-bold">{value===undefined?'Unavailable':value}</p></div><Icon className="h-5 w-5 text-primary"/></div><Link to={path} className="mt-4 inline-flex items-center text-sm font-medium text-primary">Open<ArrowRight className="ml-1 h-4 w-4"/></Link></CardContent></Card>)}</div>
      <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Fulfillment stages</CardTitle></CardHeader><CardContent>{summary.data&&Object.keys(summary.data.fulfillment_stages).length>0?<dl className="grid grid-cols-2 gap-3">{Object.entries(summary.data.fulfillment_stages).map(([stage,count])=><div key={stage} className="rounded border border-border p-3"><dt className="text-sm text-muted-foreground">{stage.replaceAll('_',' ')}</dt><dd className="text-xl font-semibold">{count}</dd></div>)}</dl>:<p className="text-sm text-muted-foreground">No orders are currently in fulfillment.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Recent deliveries</CardTitle></CardHeader><CardContent>{summary.data?.recent_deliveries.length?<ul className="space-y-3">{summary.data.recent_deliveries.map((delivery)=><li key={delivery.id} className="flex items-center justify-between"><Link className="font-medium text-primary hover:underline" to={`${SALES_PATHS.DELIVERIES}/${encodeURIComponent(delivery.id)}`}>{delivery.delivery_number}</Link><StatusPill status={delivery.status}/></li>)}</ul>:<p className="text-sm text-muted-foreground">No recent deliveries.</p>}</CardContent></Card></div>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><PlugZap className="h-5 w-5"/>Capability and extension catalogue</CardTitle></CardHeader><CardContent>{capabilities.data?.length?<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{capabilities.data.map((capability)=><article key={capability.capability} className="rounded-md border border-border p-4"><div className="flex items-start justify-between gap-2"><h2 className="font-medium">{capability.capability.replaceAll('_',' ')}</h2><StatusPill status={capability.status}/></div><p className="mt-2 text-sm text-muted-foreground">Reason: {capability.reason_code}</p>{capability.provider_id&&<p className="mt-1 text-xs text-muted-foreground">Provider: {capability.provider_id}{capability.provider_version?` ${capability.provider_version}`:''}</p>}</article>)}</div>:<p className="text-sm text-muted-foreground">The server reported no optional extension capabilities.</p>}</CardContent></Card>
    </>}
    <Card><CardHeader><CardTitle>Fast create</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2"><Link to={`${SALES_PATHS.CUSTOMERS}/new`}><Button className="w-full" variant="outline"><Users className="mr-2 h-4 w-4"/>Customer</Button></Link><Link to={`${SALES_PATHS.DELIVERIES}/new`}><Button className="w-full" variant="outline"><FileCheck2 className="mr-2 h-4 w-4"/>Delivery note</Button></Link></CardContent></Card>
  </SalesPage>;
}
