import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { Button } from '@/components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';
import { ConfirmDialog } from '@/components/ui/Dialog';
import { DetailGrid, GovernedError, SalesPage, StatusPill, Timeline, newIdempotencyKey } from './SalesUi';
import { SALES_PATHS, type DeliveryNote, type Quotation, type SalesOrder } from '../contracts';
import { salesQueryKeys, salesService } from '../services/sales-service';

type Kind='quotation'|'order'|'delivery';type Resource=Quotation|SalesOrder|DeliveryNote;
const commandLabels:Record<string,string>={send:'Send',accept:'Accept',reject:'Reject',expire:'Expire',revise:'Create revision',convert:'Convert to order',confirm:'Confirm',start_picking:'Start picking','start-picking':'Start picking',start_packing:'Start packing','start-packing':'Start packing',mark_ready:'Mark ready','mark-ready':'Mark ready',ship:'Ship',deliver:'Mark delivered',mark_invoiced:'Mark invoiced','mark-invoiced':'Mark invoiced',cancel:'Cancel',complete:'Complete delivery'};
const commandSlug=(value:string)=>value.replaceAll('_','-') as 'send'|'accept'|'reject'|'expire'|'revise'|'convert'|'confirm'|'start-picking'|'start-packing'|'mark-ready'|'ship'|'deliver'|'mark-invoiced'|'cancel'|'complete';

export function DocumentDetail({kind}:{kind:Kind}){
 const {id}=useParams();const cache=useQueryClient();const [pendingCommand,setPendingCommand]=useState<string|null>(null);
 const query=useQuery<Resource>({queryKey:kind==='quotation'?salesQueryKeys.quotation(id??''):kind==='order'?salesQueryKeys.order(id??''):salesQueryKeys.delivery(id??''),queryFn:async()=>kind==='quotation'?await salesService.getQuotation(id??''):kind==='order'?await salesService.getOrder(id??''):await salesService.getDeliveryNote(id??''),enabled:Boolean(id)});
 const command=useMutation({mutationFn:async(name:string)=>{const payload={idempotency_key:newIdempotencyKey(),...(name==='reject'||name==='cancel'?{reason:'Cancelled by an authorized operator.'}:{} )};if(kind==='quotation')return salesService.quotationCommand(id??'',commandSlug(name) as 'send'|'accept'|'reject'|'expire'|'revise'|'convert',payload);if(kind==='order')return salesService.orderCommand(id??'',commandSlug(name) as 'confirm'|'start-picking'|'start-packing'|'mark-ready'|'ship'|'deliver'|'mark-invoiced'|'cancel',payload);return salesService.deliveryCommand(id??'',commandSlug(name) as 'complete'|'cancel',payload);},onSuccess:()=>{void cache.invalidateQueries({queryKey:salesQueryKeys.all});void query.refetch();}});
 const data=query.data as Resource|undefined;const base=kind==='quotation'?SALES_PATHS.QUOTATIONS:kind==='order'?SALES_PATHS.ORDERS:SALES_PATHS.DELIVERIES;const label=kind==='quotation'?'Quotation':kind==='order'?'Sales order':'Delivery note';
 if(query.isLoading)return <SalesPage title={label} description={`Loading ${label.toLowerCase()}…`}><div aria-label="Loading details" className="h-80 animate-pulse rounded-lg bg-muted"/></SalesPage>;
 if(query.error||!data)return <SalesPage title={label} description="Governed sales record"><GovernedError error={query.error} onRetry={()=>void query.refetch()}/></SalesPage>;
 const number=kind==='quotation'?(data as Quotation).quotation_number:kind==='order'?(data as SalesOrder).order_number:(data as DeliveryNote).delivery_number;
 const entries: Array<[string,React.ReactNode]>=kind==='quotation'?[['Customer',(data as Quotation).customer_name??(data as Quotation).customer],['Quotation date',(data as Quotation).quotation_date],['Valid until',(data as Quotation).valid_until],['Revision',(data as Quotation).revision_number],['Currency',(data as Quotation).currency],['Record version',data.lock_version]]:kind==='order'?[['Customer',(data as SalesOrder).customer_name??(data as SalesOrder).customer],['Order date',(data as SalesOrder).order_date],['Delivery date',(data as SalesOrder).delivery_date],['Linked quotation',(data as SalesOrder).quotation?<Link className="text-primary hover:underline" to={`${SALES_PATHS.QUOTATIONS}/${encodeURIComponent((data as SalesOrder).quotation??'')}`}>Open quotation</Link>:'Direct order'],['Currency',(data as SalesOrder).currency],['Record version',data.lock_version]]:[['Sales order',<Link className="text-primary hover:underline" to={`${SALES_PATHS.ORDERS}/${encodeURIComponent((data as DeliveryNote).sales_order)}`}>{(data as DeliveryNote).order_number??'Open order'}</Link>],['Delivery date',(data as DeliveryNote).delivery_date],['Carrier',(data as DeliveryNote).carrier_name],['Tracking',(data as DeliveryNote).tracking_number],['Warehouse',(data as DeliveryNote).warehouse_id],['Record version',data.lock_version]];
 const lines=kind==='quotation'?(data as Quotation).lines:kind==='order'?(data as SalesOrder).lines:(data as DeliveryNote).lines;
 return <SalesPage title={`${label} ${number}`} description="Tenant-scoped document, calculated evidence, and permitted workflow actions." actions={<Link to={`${base}/${encodeURIComponent(data.id)}/edit`}><Button variant="outline" disabled={data.status!=='draft'}>Edit draft</Button></Link>}>
  <Card><CardHeader><div className="flex flex-wrap items-center gap-3"><CardTitle>Document summary</CardTitle><StatusPill status={data.status}/></div></CardHeader><CardContent><DetailGrid entries={entries}/>{kind!=='delivery'&&<div className="mt-6 grid gap-3 border-t border-border pt-5 sm:grid-cols-4"><p className="text-sm">Subtotal<br/><strong>{(data as Quotation|SalesOrder).subtotal_amount}</strong></p><p className="text-sm">Discount<br/><strong>{(data as Quotation|SalesOrder).discount_amount}</strong></p><p className="text-sm">Tax<br/><strong>{(data as Quotation|SalesOrder).tax_amount}</strong></p><p className="text-sm">Total<br/><strong>{(data as Quotation|SalesOrder).total_amount}</strong></p></div>}</CardContent></Card>
  <Card><CardHeader><CardTitle>{kind==='order'?'Order lines and delivery progress':'Document lines'}</CardTitle></CardHeader><CardContent>{lines.length===0?<p className="text-sm text-muted-foreground">No active lines.</p>:<div className="overflow-x-auto"><table className="min-w-full divide-y divide-border"><thead><tr><th className="py-2 text-left">Line</th><th className="py-2 text-left">Item</th><th className="py-2 text-right">Quantity</th>{kind==='order'&&<th className="py-2 text-right">Delivered</th>}<th className="py-2 text-right">Amount</th></tr></thead><tbody className="divide-y divide-border">{lines.map((line)=><tr key={line.id}><td className="py-3">{line.line_number}</td><td className="py-3">{'item_name'in line?line.item_name:line.sales_order_line}</td><td className="py-3 text-right">{'quantity'in line?line.quantity:line.quantity_delivered}</td>{kind==='order'&&<td className="py-3 text-right">{'delivered_quantity'in line?line.delivered_quantity:'—'}</td>}<td className="py-3 text-right">{'line_total'in line?line.line_total:'total_price'in line?line.total_price:'—'}</td></tr>)}</tbody></table></div>}</CardContent></Card>
  {kind==='order'&&<Card><CardHeader><CardTitle>Delivery notes</CardTitle></CardHeader><CardContent>{((data as SalesOrder).delivery_notes??[]).length===0?<p className="text-sm text-muted-foreground">No delivery notes are linked yet.</p>:(data as SalesOrder).delivery_notes?.map((note)=><Link key={note.id} className="block text-primary hover:underline" to={`${SALES_PATHS.DELIVERIES}/${encodeURIComponent(note.id)}`}>{note.delivery_number}</Link>)}</CardContent></Card>}
  <Timeline records={data.transition_history}/><Card><CardHeader><CardTitle>Available actions</CardTitle></CardHeader><CardContent>{data.allowed_commands.length===0?<p className="text-sm text-muted-foreground">No commands are permitted in the current state.</p>:<div className="flex flex-wrap gap-2">{data.allowed_commands.map((name)=><Button key={name} variant={['reject','cancel','expire'].includes(name)?'danger':'primary'} onClick={()=>setPendingCommand(name)}>{commandLabels[name]??name.replaceAll('_',' ')}</Button>)}</div>}</CardContent></Card>
  {command.error&&<GovernedError error={command.error}/>}<ConfirmDialog open={pendingCommand!==null} onOpenChange={(open)=>{if(!open)setPendingCommand(null);}} title={`Confirm ${pendingCommand?commandLabels[pendingCommand]??pendingCommand:'action'}?`} description="This command is server-authorized, idempotent, and recorded in transition evidence." confirmLabel={command.isPending?'Working…':'Confirm'} variant={pendingCommand&&['reject','cancel','expire'].includes(pendingCommand)?'danger':'default'} onConfirm={()=>{if(pendingCommand)command.mutate(pendingCommand);}}/>
 </SalesPage>;
}
