import { useMutation } from "@tanstack/react-query";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { Textarea } from "@/components/ui/Textarea";
import { GovernedError, PageHeader, Surface } from "../components/CustomizationUI";
import { TargetContractSelector } from "../components/TargetContractSelector";
import { asObject, parseJSON } from "../components/customization-utils";
import { useUnsavedChanges } from "../components/useUnsavedChanges";
import { ROUTES, type FieldDataType, type FieldDefinitionCreateRequest, type JSONObject } from "../contracts";
import { customizationFrameworkService as service } from "../services/customization-framework-service";

export function CreateFieldDefinitionPage() {
  const navigate = useNavigate(); const [step, setStep] = useState(1); const [label, setLabel] = useState(""); const [key, setKey] = useState(""); const [description, setDescription] = useState(""); const [module, setModule] = useState(""); const [resource, setResource] = useState(""); const [version, setVersion] = useState("1.0"); const [dataType, setDataType] = useState<FieldDataType>("text"); const [schema, setSchema] = useState('{"maxLength":160}'); const [error, setError] = useState("");
  useUnsavedChanges(Boolean(label || key || description));
  const mutation = useMutation({ mutationFn: (request: FieldDefinitionCreateRequest) => service.createField(request), onSuccess: (result) => navigate(ROUTES.FIELD_DETAIL(result.data.id)) });
  function request(): FieldDefinitionCreateRequest | null { if (!label.trim() || !/^[a-z0-9]+(?:-[a-z0-9]+)*$/u.test(key) || !module || !resource) { setError("Label, lowercase slug key, module, and resource are required."); return null; } try { const validation_schema: JSONObject = asObject(parseJSON(schema)); setError(""); return { key, label, description, owner_module: module, target_resource: resource, target_contract_version: version, data_type: dataType, validation_schema, presentation_schema: { label } }; } catch (caught) { setError(caught instanceof Error ? caught.message : "Invalid JSON schema."); return null; } }
  return <main className="space-y-6"><PageHeader title="Create custom field" description="Choose a registered target, define a safe field contract, validate it, then review before creation."/><nav aria-label="Creation steps" className="flex gap-2">{["Target","Definition","Review"].map((item, index) => <Button key={item} type="button" variant={step === index + 1 ? "primary" : "outline"} onClick={() => setStep(index + 1)}>{index + 1}. {item}</Button>)}</nav>
    <Surface>{step === 1 ? <div className="grid gap-5 sm:grid-cols-2"><TargetContractSelector value={module ? `${module}/${resource}@${version}` : ""} onSelect={(contract) => { setModule(contract.module); setResource(contract.resource); setVersion(contract.version); if (!contract.custom_field_types.includes(dataType)) setDataType(contract.custom_field_types[0] ?? "text"); }}/><p className="sm:col-span-2 text-sm text-muted-foreground">Targets are explicitly registered and versioned. Unavailable paid capabilities remain visible without fabricated enablement.</p></div> : step === 2 ? <div className="space-y-5"><div className="grid gap-5 sm:grid-cols-2"><Input id="field-label" label="Label" required value={label} onChange={(event) => { setLabel(event.target.value); if (!key) setKey(event.target.value.toLowerCase().replace(/[^a-z0-9]+/gu, "-").replace(/^-|-$/gu, "")); }}/><Input id="field-key" label="Stable key" required value={key} onChange={(event) => setKey(event.target.value)}/><label className="grid gap-1 text-sm font-medium">Data type<select className="h-10 rounded-md border bg-background px-3" value={dataType} onChange={(event) => setDataType(event.target.value as FieldDataType)}>{["text","long_text","integer","decimal","boolean","date","datetime","uuid","choice","multi_choice","json"].map((type) => <option key={type}>{type}</option>)}</select></label></div><Textarea id="field-description" aria-label="Description" value={description} onChange={(event) => setDescription(event.target.value)} placeholder="How administrators and users should understand this field"/><Textarea id="validation-schema" aria-label="Validation schema" rows={8} value={schema} onChange={(event) => setSchema(event.target.value)}/><p className="text-xs text-muted-foreground">Declarative JSON Schema only. Scripts, functions, network calls, and executable expressions are prohibited.</p></div> : <div><h2 className="font-semibold">Review contract</h2><pre className="mt-4 overflow-auto rounded-lg bg-muted p-4 text-xs">{JSON.stringify({ module, resource, version, key, label, dataType, schema }, null, 2)}</pre><p className="mt-4 text-sm text-muted-foreground">The new field starts as draft. Activate only after validation and dependency review.</p></div>}{error ? <p id="field-form-error" role="alert" className="mt-4 text-sm text-destructive">{error}</p> : null}</Surface>
    {mutation.error ? <GovernedError error={mutation.error}/> : null}<div className="flex justify-between"><Button variant="ghost" onClick={() => navigate(ROUTES.FIELDS)}>Cancel</Button><div className="flex gap-2">{step > 1 ? <Button variant="outline" onClick={() => setStep(step - 1)}>Back</Button> : null}{step < 3 ? <Button onClick={() => { if (step === 2 && !request()) return; setStep(step + 1); }}>Continue</Button> : <Button disabled={mutation.isPending} onClick={() => { const value = request(); if (value) mutation.mutate(value); }}>{mutation.isPending ? "Creating…" : "Create draft field"}</Button>}</div></div></main>;
}
