/* eslint-disable complexity -- lifecycle, impact, governed capability, and evidence states are explicit. */
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, Edit, GitBranch } from "lucide-react";
import { useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { Button } from "@/components/ui/Button";
import { CapabilityNotice, ConfirmAction, Detail, DetailGrid, GovernedError, PageHeader, PageSkeleton, StatusChip, Surface } from "../components/CustomizationUI";
import { formatDate } from "../components/customization-utils";
import { ROUTES, type FieldStatus } from "../contracts";
import { customizationFrameworkService as service } from "../services/customization-framework-service";

export function FieldDefinitionDetailPage() {
  const { id = "" } = useParams(); const navigate = useNavigate(); const client = useQueryClient(); const [command, setCommand] = useState<"activate"|"deprecate"|"retire"|null>(null);
  const field = useQuery({ queryKey: ["customization", "field", id], queryFn: () => service.getField(id), enabled: Boolean(id) });
  const impact = useQuery({ queryKey: ["customization", "field-impact", id], queryFn: () => service.getFieldImpact(id), enabled: Boolean(id) });
  const transition = useMutation({ mutationFn: (next: "activate"|"deprecate"|"retire") => service.transitionField(id, next, { transition_key: crypto.randomUUID() }), onSuccess: () => { setCommand(null); void client.invalidateQueries({ queryKey: ["customization", "field", id] }); } });
  if (field.isLoading) return <PageSkeleton/>; if (field.error) return <GovernedError error={field.error} retry={() => void field.refetch()}/>; if (!field.data) return <GovernedError error={new Error("Field not found.")}/>;
  const item = field.data.data; const next: Partial<Record<FieldStatus, "activate"|"deprecate"|"retire">> = { draft: "activate", active: "deprecate", deprecated: "retire" };
  return <main className="space-y-6"><PageHeader title={item.label} description={`${item.owner_module} · ${item.target_resource} · contract ${item.target_contract_version}`} actions={<><Button variant="outline" onClick={() => navigate(ROUTES.FIELD_IMPACT(item.id))}><GitBranch className="mr-2 h-4 w-4"/>Impact</Button><Button variant="outline" onClick={() => navigate(ROUTES.FIELD_EDIT(item.id))}><Edit className="mr-2 h-4 w-4"/>Edit</Button>{next[item.status] ? <Button disabled={item.capability_state === "capability_unavailable"} onClick={() => setCommand(next[item.status] ?? null)}>{next[item.status]}</Button> : null}</>}/><CapabilityNotice state={item.capability_state}/>
    <Surface><DetailGrid><Detail label="Stable key"><span className="font-mono">{item.key}</span></Detail><Detail label="Data type">{item.data_type}</Detail><Detail label="Status"><StatusChip status={item.status}/></Detail><Detail label="Required">{item.required ? "Yes" : "No"}</Detail><Detail label="Searchable">{item.searchable ? "Yes" : "No"}</Detail><Detail label="Lock revision">{item.lock_version}</Detail></DetailGrid></Surface>
    <div className="grid gap-6 lg:grid-cols-2"><Surface><h2 className="font-semibold">Schema and default</h2><p className="mt-2 text-sm text-muted-foreground">{item.description || "No description"}</p><pre className="mt-4 max-h-72 overflow-auto rounded-lg bg-muted p-3 text-xs">{JSON.stringify({ validation: item.validation_schema, presentation: item.presentation_schema, default: item.default_value }, null, 2)}</pre></Surface><Surface><h2 className="flex items-center gap-2 font-semibold"><Activity className="h-4 w-4"/>Usage and impact</h2><div className="mt-4 grid grid-cols-3 gap-3 text-center"><div><strong className="block text-2xl">{impact.data?.data.value_count ?? "—"}</strong><span className="text-xs text-muted-foreground">stored values</span></div><div><strong className="block text-2xl">{impact.data?.data.dependency_count ?? "—"}</strong><span className="text-xs text-muted-foreground">dependencies</span></div><div><strong className="block text-2xl">{impact.data ? (impact.data.data.blocking ? "Yes" : "No") : "—"}</strong><span className="text-xs text-muted-foreground">change blocked</span></div></div></Surface></div>
    <Surface><h2 className="font-semibold">Lifecycle evidence</h2>{item.transition_history.length ? <ol className="mt-4 space-y-3">{item.transition_history.map((entry, index) => <li key={`${entry.occurred_at}-${index}`} className="flex flex-wrap justify-between gap-2 border-l-2 pl-3 text-sm"><span>{entry.from} → <strong>{entry.to}</strong> via {entry.command}</span><span className="text-muted-foreground">{formatDate(entry.occurred_at)}</span></li>)}</ol> : <p className="mt-2 text-sm text-muted-foreground">No transitions yet.</p>}</Surface>
    <ConfirmAction open={command !== null} title={`${command ?? "Change"} field?`} description="This governed lifecycle change is audited and may affect dependent forms and rules." confirmLabel={command ?? "Confirm"} pending={transition.isPending} onOpenChange={(open) => { if (!open) setCommand(null); }} onConfirm={() => { if (command) transition.mutate(command); }}/>{transition.error ? <GovernedError error={transition.error}/> : null}</main>;
}
