import { useQuery } from "@tanstack/react-query";
import { Plus, Search } from "lucide-react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { ROUTES, type FieldDataType, type FieldOrdering, type FieldStatus } from "../contracts";
import { customizationFrameworkService as service } from "../services/customization-framework-service";
import { EmptyPanel, GovernedError, PageHeader, PageSkeleton, Pagination, StatusChip } from "../components/CustomizationUI";

export function FieldDefinitionListPage() {
  const navigate = useNavigate(); const [params, setParams] = useSearchParams();
  const page = Number(params.get("page") ?? "1"); const search = params.get("search") ?? "";
  const status = (params.get("status") ?? "") as FieldStatus | ""; const dataType = (params.get("data_type") ?? "") as FieldDataType | "";
  const ordering = (params.get("ordering") ?? "-updated_at") as FieldOrdering;
  const query = useQuery({ queryKey: ["customization", "fields", page, search, status, dataType, ordering], queryFn: () => service.listFields({ page, page_size: 25, search: search || undefined, status: status || undefined, data_type: dataType || undefined, ordering }) });
  const update = (key: string, value: string) => { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); if (key !== "page") next.delete("page"); setParams(next); };
  if (query.isLoading) return <PageSkeleton rows={7}/>; if (query.error) return <GovernedError error={query.error} retry={() => void query.refetch()}/>;
  const envelope = query.data; if (!envelope) return <GovernedError error={new Error("No governed field response was received.")} retry={() => void query.refetch()}/>;
  const filtered = Boolean(search || status || dataType);
  return <main className="space-y-6"><PageHeader title="Custom fields" description="Extend registered resources with tenant-owned, schema-validated fields—without executable code." actions={<Button onClick={() => navigate(ROUTES.FIELD_CREATE)}><Plus className="mr-2 h-4 w-4"/>Create field</Button>}/>
    <section aria-label="Field filters" className="grid gap-3 rounded-xl border bg-card p-4 md:grid-cols-[minmax(220px,1fr)_180px_180px_200px]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input aria-label="Search fields" className="pl-9" value={search} placeholder="Search key, label, description" onChange={(event) => update("search", event.target.value)}/></div><select aria-label="Filter by status" className="rounded-md border bg-background px-3 text-sm" value={status} onChange={(event) => update("status", event.target.value)}><option value="">All statuses</option>{["draft","active","deprecated","retired"].map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Filter by data type" className="rounded-md border bg-background px-3 text-sm" value={dataType} onChange={(event) => update("data_type", event.target.value)}><option value="">All data types</option>{["text","long_text","integer","decimal","boolean","date","datetime","uuid","choice","multi_choice","json"].map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Order fields" className="rounded-md border bg-background px-3 text-sm" value={ordering} onChange={(event) => update("ordering", event.target.value)}><option value="-updated_at">Recently updated</option><option value="label">Label A–Z</option><option value="key">Key A–Z</option><option value="status">Lifecycle status</option></select></section>
    {envelope.data.length === 0 ? <EmptyPanel filtered={filtered} noun="fields" create={() => navigate(ROUTES.FIELD_CREATE)}/> : <section className="overflow-hidden rounded-xl border bg-card"><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-sm"><thead className="bg-muted/50 text-left text-xs uppercase text-muted-foreground"><tr><th className="px-4 py-3">Field</th><th className="px-4 py-3">Target</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Dependencies</th><th className="px-4 py-3">Updated</th></tr></thead><tbody className="divide-y">{envelope.data.map((field) => <tr key={field.id} className="hover:bg-muted/30"><td className="px-4 py-4"><button className="font-medium text-primary hover:underline" onClick={() => navigate(ROUTES.FIELD_DETAIL(field.id))}>{field.label}</button><p className="font-mono text-xs text-muted-foreground">{field.key}</p></td><td className="px-4 py-4">{field.owner_module} · {field.target_resource}</td><td className="px-4 py-4">{field.data_type.replaceAll("_", " ")}</td><td className="px-4 py-4"><StatusChip status={field.status}/></td><td className="px-4 py-4">{field.dependency_count}</td><td className="px-4 py-4">{new Date(field.updated_at).toLocaleDateString()}</td></tr>)}</tbody></table></div><Pagination meta={envelope.meta.pagination} onPage={(next) => update("page", String(next))}/></section>}{query.isFetching ? <p role="status" className="text-xs text-muted-foreground">Refreshing fields…</p> : null}</main>;
}
