/* eslint-disable @typescript-eslint/no-unused-expressions -- compact URL state setter uses a conditional mutation. */
import { useQuery } from "@tanstack/react-query";
import { Plus, Search } from "lucide-react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { Button } from "@/components/ui/Button"; import { Input } from "@/components/ui/Input";
import { EmptyPanel, GovernedError, PageHeader, PageSkeleton, Pagination, StatusChip } from "../components/CustomizationUI";
import { useRuntimeConfiguration } from "../components/useRuntimeConfiguration";
import { ROUTES, type FormOrdering, type FormStatus } from "../contracts"; import { customizationFrameworkService as service } from "../services/customization-framework-service";

export function FormListPage() { const navigate = useNavigate(); const [params,setParams] = useSearchParams(); const configuration=useRuntimeConfiguration(); const search=params.get("search")??""; const status=(params.get("status")??"") as FormStatus|""; const ordering=(params.get("ordering")??configuration.data?.document.list_preferences.form_ordering??"") as FormOrdering|""; const page=Number(params.get("page")??"1"); const pageSize=configuration.data?.document.list_preferences.page_size; const update=(key:string,value:string)=>{const next=new URLSearchParams(params); value?next.set(key,value):next.delete(key); if(key!=="page")next.delete("page"); setParams(next);}; const query=useQuery({queryKey:["customization","forms",search,status,ordering,page,pageSize],queryFn:()=>service.listForms({search:search||undefined,status:status||undefined,ordering:ordering||undefined,page,page_size:pageSize}),enabled:pageSize!==undefined&&Boolean(ordering)}); if(configuration.isLoading||query.isLoading)return <PageSkeleton/>; if(configuration.error)return <GovernedError error={configuration.error} retry={()=>void configuration.refetch()}/>; if(query.error)return <GovernedError error={query.error} retry={()=>void query.refetch()}/>; if(!query.data)return <GovernedError error={new Error("No governed form response was received.")}/>; const filtered=Boolean(search||status);
 return <main className="space-y-6"><PageHeader title="Forms" description="Design accessible, versioned layouts over registered resource contracts." actions={<Button onClick={()=>navigate(ROUTES.FORM_CREATE)}><Plus className="mr-2 h-4 w-4"/>Create form</Button>}/><section aria-label="Form filters" className="grid gap-3 rounded-xl border bg-card p-4 md:grid-cols-[1fr_180px_200px]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input aria-label="Search forms" className="pl-9" value={search} onChange={(event)=>update("search",event.target.value)} placeholder="Search key, name, description"/></div><select aria-label="Filter form status" className="rounded-md border bg-background px-3" value={status} onChange={(event)=>update("status",event.target.value)}><option value="">All statuses</option>{["draft","published","archived"].map(item=><option key={item}>{item}</option>)}</select><select aria-label="Order forms" className="rounded-md border bg-background px-3" value={ordering} onChange={(event)=>update("ordering",event.target.value)}><option value="-updated_at">Recently updated</option><option value="name">Name A–Z</option><option value="status">Publication state</option></select></section>{query.data.data.length===0?<EmptyPanel filtered={filtered} noun="forms" create={()=>navigate(ROUTES.FORM_CREATE)}/>:<section className="overflow-hidden rounded-xl border bg-card"><div className="grid gap-4 p-4 md:grid-cols-2 xl:grid-cols-3">{query.data.data.map(form=><button key={form.id} className="rounded-lg border p-4 text-left transition hover:border-primary hover:shadow-sm" onClick={()=>navigate(ROUTES.FORM_DETAIL(form.id))}><div className="flex justify-between gap-3"><h2 className="font-semibold">{form.name}</h2><StatusChip status={form.status}/></div><p className="mt-2 font-mono text-xs text-muted-foreground">{form.key}</p><p className="mt-4 text-sm">{form.owner_module} · {form.target_resource}</p><p className="mt-3 text-xs text-muted-foreground">{form.published_version ? `Published v${form.published_version}`:"No published version"} · {form.dependency_count} dependencies</p></button>)}</div><Pagination meta={query.data.meta.pagination} onPage={(next)=>update("page",String(next))}/></section>}</main>; }
