/* eslint-disable @typescript-eslint/unbound-method, @typescript-eslint/consistent-type-imports -- Vitest verifies calls on mocked object methods and preserves the real error class. */
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { ApiError, apiClient } from '@/services/api-client';
import { ENDPOINTS } from '../contracts';
import { buildQuery, emailMarketingService, unwrapEnvelope, unwrapPage } from './email-marketing-service';
vi.mock('@/services/api-client', async () => { const actual = await vi.importActual<typeof import('@/services/api-client')>('@/services/api-client'); return { ...actual, apiClient: { get: vi.fn(), post: vi.fn(), patch: vi.fn(), delete: vi.fn() } }; });
const meta = { correlation_id: 'corr-1', timestamp: '2026-07-22T00:00:00Z' };
const pagination = { count: 1, page: 1, page_size: 25, total_pages: 1, has_next: false, has_previous: false };
const campaign = { id: 'c1', campaign_code: 'WELCOME', campaign_name: 'Welcome', campaign_type: 'broadcast', subject: 'Hello', status: 'draft', template_id: null, scheduled_at: null, timezone: 'UTC', resolved_recipient_count: 0, sent_count: 0, delivered_count: 0, opened_count: 0, clicked_count: 0, bounced_count: 0, failed_count: 0, created_at: meta.timestamp, updated_at: meta.timestamp };
describe('email marketing service', () => {
  beforeEach(() => vi.clearAllMocks());
  it('preserves list metadata and encodes filters', async () => { vi.mocked(apiClient.get).mockResolvedValue({ data: [campaign], meta: { ...meta, pagination } }); const result = await emailMarketingService.campaigns.list({ search: 'summer & sale', status: 'draft', page: 2 }); expect(result.correlationId).toBe('corr-1'); expect(result.pagination.count).toBe(1); expect(apiClient.get).toHaveBeenCalledWith(expect.stringContaining('search=summer+%26+sale')); expect(apiClient.get).toHaveBeenCalledWith(expect.stringContaining('page=2')); });
  it('throws instead of converting malformed or legacy lists to empty', () => { const validUnknown = (value: unknown): value is unknown => value !== undefined; expect(() => unwrapPage([], validUnknown)).toThrow(ApiError); expect(() => unwrapPage({ results: [] }, validUnknown)).toThrow('pagination'); expect(() => unwrapEnvelope({ data: campaign }, validUnknown)).toThrow(ApiError); });
  it('uses PATCH and explicit lifecycle endpoints', async () => { const detail = { ...campaign, description: '', preview_text: '', from_name: 'SARAISE', from_email: 'sender@example.com', reply_to_email: null, audience_definition: {}, audience_snapshot_at: null, queue_started_at: null, send_started_at: null, completed_at: null, content_snapshot_subject: '', content_snapshot_html: '', content_snapshot_text: '', template_version_snapshot: null, unique_opened_count: 0, unique_clicked_count: 0, unsubscribed_count: 0, complaint_count: 0, transition_history: [], last_error_code: '', last_error_detail: '', is_deleted: false, created_by: null, updated_by: null }; vi.mocked(apiClient.patch).mockResolvedValue({ data: detail, meta }); await emailMarketingService.campaigns.update('c1', { subject: 'Updated' }); expect(apiClient.patch).toHaveBeenCalledWith(ENDPOINTS.CAMPAIGNS.UPDATE('c1'), { subject: 'Updated' }); vi.mocked(apiClient.post).mockResolvedValue({ data: { id: 'j1', job_type: 'email_marketing.send_campaign', status: 'queued', idempotency_key: 'key', created_at: meta.timestamp, correlation_id: 'corr-1' }, meta }); await emailMarketingService.campaigns.send('c1', { idempotency_key: 'key', preflight_receipt: 'signed-receipt' }); expect(apiClient.post).toHaveBeenCalledWith(ENDPOINTS.CAMPAIGNS.SEND('c1'), { idempotency_key: 'key', preflight_receipt: 'signed-receipt' }); });
  it('builds query strings without undefined values', () => { expect(buildQuery('/items/', { page: 1, search: '', status: undefined, active: false })).toBe('/items/?page=1&active=false'); });
});
