import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/Button";
import type { ExecutionState } from "../contracts";
import { ROUTES } from "../contracts";
import { aiAgentService } from "../services/ai-agent-service";
import { EmptyState, GovernedError, PageHeader, PageSkeleton, Pagination, StatusPill, formatDate } from "../components/AgentUI";

const activeStates: readonly ExecutionState[] = ["created", "validated", "queued", "running", "paused"];
export const ExecutionListPage = () => { const [state, setState] = useState<ExecutionState | "">(""); const [page, setPage] = useState(1); const query = useQuery({ queryKey: ["ai-executions", state, page], queryFn: () => aiAgentService.listExecutions({ state: state || undefined, ordering: "-created_at", page, page_size: 25 }), refetchInterval: (current) => current.state.data?.items.some((item) => activeStates.includes(item.state)) ? 5000 : false, placeholderData: (previous) => previous }); if (query.isLoading) return <PageSkeleton/>; if (query.error) return <GovernedError error={query.error} retry={() => void query.refetch()}/>; if (!query.data) return <GovernedError error={new Error("No execution response was received.")}/>; return <main className="space-y-6"><PageHeader title="Execution monitor" description="Inspect durable runtime state. Polling runs only while the visible page contains active work." actions={<Button variant="outline" onClick={() => void query.refetch()}>Refresh evidence</Button>}/><section className="rounded-xl border bg-card p-4"><label htmlFor="execution-state" className="mr-3 text-sm font-medium">State</label><select id="execution-state" className="rounded-md border bg-background px-3 py-2 text-sm" value={state} onChange={(event) => { setState(event.target.value as ExecutionState | ""); setPage(1); }}><option value="">All states</option>{["created", "validated", "queued", "running", "paused", "completed", "failed", "terminated", "timed_out"].map((item) => <option key={item}>{item}</option>)}</select></section>{query.data.items.length === 0 ? <EmptyState title="No execution evidence" description={state ? "No executions match the selected state." : "Executions appear after a governed agent request is durably accepted."}/> : <section className="overflow-hidden rounded-xl border bg-card"><div className="overflow-x-auto"><table className="w-full min-w-[860px] text-sm"><thead className="bg-muted/50 text-left"><tr><th className="p-4">Execution</th><th className="p-4">Agent</th><th className="p-4">State</th><th className="p-4">Job</th><th className="p-4">Started</th><th className="p-4">Completed</th></tr></thead><tbody className="divide-y">{query.data.items.map((item) => <tr key={item.id}><td className="p-4"><Link className="font-mono text-xs text-primary hover:underline" to={ROUTES.EXECUTION_DETAIL(item.id)}>{item.id}</Link></td><td className="p-4">{item.agent_name ?? item.agent_id}</td><td className="p-4"><StatusPill status={item.state}/></td><td className="p-4 font-mono text-xs">{item.async_job_id}</td><td className="p-4">{formatDate(item.started_at)}</td><td className="p-4">{formatDate(item.completed_at)}</td></tr>)}</tbody></table></div><Pagination value={query.data.pagination} onPage={setPage}/></section>}{query.isFetching ? <p role="status" className="text-xs text-muted-foreground">Refreshing active execution state…</p> : null}</main>; };
