import { useState, type FormEvent } from 'react';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import type { PolicyWriteRequest } from '../contracts';
import { fieldError } from '../services/compliance-service';

const blank: PolicyWriteRequest = { code: '', title: '', summary: '', category: '', owner_id: null, review_frequency_days: 365, effective_date: null, expiry_date: null };
export function PolicyForm({ initial, pending, error, submitLabel, onSubmit, onCancel }: { readonly initial?: PolicyWriteRequest; readonly pending: boolean; readonly error?: unknown; readonly submitLabel: string; readonly onSubmit: (value: PolicyWriteRequest) => void; readonly onCancel: () => void }) {
  const [value, setValue] = useState<PolicyWriteRequest>(initial ?? blank);
  const [localError, setLocalError] = useState('');
  const submit = (event: FormEvent) => { event.preventDefault(); setLocalError(''); if (!value.code.trim() || !value.title.trim() || !value.category.trim()) { setLocalError('Code, title, and category are required.'); return; } const frequency = value.review_frequency_days ?? 365; if (frequency < 1 || frequency > 3650) { setLocalError('Review frequency must be between 1 and 3,650 days.'); return; } if (value.effective_date && value.expiry_date && value.expiry_date <= value.effective_date) { setLocalError('Expiry date must be later than effective date.'); return; } onSubmit(value); };
  const set = <K extends keyof PolicyWriteRequest>(key: K, next: PolicyWriteRequest[K]) => setValue((current) => ({ ...current, [key]: next }));
  return <form onSubmit={submit} className="space-y-5" noValidate>{localError ? <p role="alert" className="rounded border border-destructive p-3 text-sm text-destructive">{localError}</p> : null}<div className="grid gap-4 sm:grid-cols-2"><Input id="policy-code" label="Policy code" required value={value.code} error={fieldError(error, 'code')} onChange={(event) => set('code', event.target.value)}/><Input id="policy-title" label="Title" required value={value.title} error={fieldError(error, 'title')} onChange={(event) => set('title', event.target.value)}/><Input id="policy-category" label="Category" required value={value.category} error={fieldError(error, 'category')} onChange={(event) => set('category', event.target.value)}/><Input id="policy-owner" label="Owner ID" value={value.owner_id ?? ''} error={fieldError(error, 'owner_id')} onChange={(event) => set('owner_id', event.target.value || null)}/><Input id="policy-review" label="Review frequency (days)" type="number" min={1} max={3650} required value={value.review_frequency_days ?? 365} error={fieldError(error, 'review_frequency_days')} onChange={(event) => set('review_frequency_days', Number(event.target.value))}/><Input id="policy-effective" label="Effective date" type="date" value={value.effective_date ?? ''} onChange={(event) => set('effective_date', event.target.value || null)}/><Input id="policy-expiry" label="Expiry date" type="date" value={value.expiry_date ?? ''} error={fieldError(error, 'expiry_date')} onChange={(event) => set('expiry_date', event.target.value || null)}/></div><label htmlFor="policy-summary" className="block text-sm font-medium">Summary<textarea id="policy-summary" className="mt-1 min-h-28 w-full rounded-md border bg-background p-3" value={value.summary ?? ''} onChange={(event) => set('summary', event.target.value)}/></label><div className="flex gap-3"><Button type="submit" disabled={pending}>{pending ? 'Saving…' : submitLabel}</Button><Button type="button" variant="outline" disabled={pending} onClick={onCancel}>Cancel</Button></div></form>;
}
