import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { ApiError } from '@/services/api-client';
import type { EmailMarketingConfigurationDocument } from '../contracts';
import { CampaignForm } from '../components/CampaignForm';
import { GovernedError, PreflightPanel } from '../components/EmailMarketingUI';
import { emailMarketingService } from '../services/email-marketing-service';
import { EmailCampaignListPage } from './EmailCampaignListPage';
import { EmailTemplateListPage } from './EmailTemplateListPage';
import { AudienceDeliveryListPage } from './AudienceDeliveryListPage';
import { SuppressionListPage } from './SuppressionListPage';
import { ConsentListPage } from './ConsentListPage';

vi.mock('../services/email-marketing-service', () => {
  const fn = () => vi.fn();
  return { EMAIL_MARKETING_QUERY_KEYS: { all: ['email-marketing'], campaigns: (f = {}) => ['email-marketing','campaigns',f], campaign: (id: string) => ['email-marketing','campaign',id], analytics: (id: string) => ['email-marketing','analytics',id], templates: (f = {}) => ['email-marketing','templates',f], template: (id: string) => ['email-marketing','template',id], recipients: (f = {}) => ['email-marketing','recipients',f], recipient: (id: string) => ['email-marketing','recipient',id], deliveries: (f = {}) => ['email-marketing','deliveries',f], delivery: (id: string) => ['email-marketing','delivery',id], suppressions: (f = {}) => ['email-marketing','suppressions',f], suppression: (id: string) => ['email-marketing','suppression',id], consents: (f = {}) => ['email-marketing','consents',f], consent: (id: string) => ['email-marketing','consent',id], configuration: ['email-marketing','configuration'], configurationHistory: ['email-marketing','configuration','history'], health: ['email-marketing','health'] }, emailMarketingService: { campaigns: { list: fn(), get: fn(), create: fn(), update: fn(), delete: fn(), resolveAudience: fn(), schedule: fn(), unschedule: fn(), send: fn(), pause: fn(), resume: fn(), cancel: fn(), analytics: fn() }, templates: { list: fn(), get: fn(), create: fn(), update: fn(), delete: fn(), activate: fn(), archive: fn(), clone: fn(), preview: fn() }, recipients: { list: fn(), get: fn(), retry: fn() }, deliveries: { list: fn(), get: fn() }, suppressions: { list: fn(), get: fn(), create: fn(), deactivate: fn() }, consents: { list: fn(), get: fn(), create: fn(), revoke: fn() }, configuration: { current: fn(), update: fn(), preview: fn(), history: fn(), rollback: fn(), importDocument: fn(), exportDocument: fn() }, health: fn() } };
});

const pagination = { count: 0, page: 1, page_size: 25, total_pages: 0, has_next: false, has_previous: false };
const empty = { items: [], pagination, correlationId: 'corr-list', timestamp: '2026-07-22T00:00:00Z' };
const configurationDocument: EmailMarketingConfigurationDocument = {
  schema_version: 1,
  defaults: { template_category: 'general', campaign_type: 'broadcast', audience_resolver: 'manual', delivery_gateway: 'django', timezone: 'UTC', audience_schema_version: 1, consent_purpose: 'marketing' },
  limits: { json_max_depth: 8, json_max_keys: 128, evidence_json_max_bytes: 16384, evidence_json_max_depth: 6, evidence_json_max_keys: 96, template_design_max_bytes: 131072, audience_definition_max_bytes: 32768, consent_evidence_max_bytes: 32768, personalization_max_bytes: 65536, serializer_json_max_bytes: 32768, serializer_json_max_depth: 8, serializer_json_max_keys: 100, json_key_max_length: 128, personalization_max_keys: 100, recipient_count_max: 100000, max_recipients: 100000, recipient_key_max_length: 255, display_name_max_length: 255, subject_max_length: 500, preview_text_max_length: 255, search_max_length: 100 },
  pagination: { default_page_size: 25, max_page_size: 100, page_size_options: [25, 50, 100] },
  workflows: { campaign_types: ['broadcast'], audience_resolver_keys: ['manual', 'inline'], audience_schema_versions: [1], campaign_editable_states: ['draft'], campaign_archivable_states: ['draft', 'failed'], campaign_physical_delete_protected_states: ['sent', 'cancelled'], campaign_archive_blocking_recipient_states: ['queued', 'sending', 'accepted'], template_editable_states: ['draft'], recipient_initial_states: ['resolved', 'suppressed'], terminal_recipient_states: ['delivered', 'bounced', 'complained', 'unsubscribed'], preflight_blocking_codes: ['CONTENT_INVALID', 'SENDER_INVALID'], provider_acknowledgement_mapping: { accepted: 'accepted', delivered: 'delivered', failed: 'failed', bounced: 'bounced' }, provider_event_recipient_mapping: { accepted: 'accepted', delivered: 'delivered', bounced: 'bounced', complained: 'complained', unsubscribed: 'unsubscribed' }, provider_event_command_mapping: { accepted: 'accepted', delivered: 'delivered', bounced: 'bounce', complained: 'complain', unsubscribed: 'unsubscribe' }, transitions: { campaign: ['schedule:draft:scheduled'], template: ['activate:draft:active'], recipient: ['queue:resolved:queued'] } },
  compliance: { suppression_scopes: ['marketing', 'all'], suppression_reasons: ['unsubscribe', 'hard_bounce', 'complaint', 'manual', 'legal'], suppression_sources: ['user', 'provider_event', 'administrator', 'migration'], permanent_suppression_reasons: ['unsubscribe', 'complaint', 'legal'], protected_overwrite_reasons: ['hard_bounce', 'complaint'], automatic_suppression_events: ['bounced', 'complained', 'unsubscribed'], automatic_suppression_reasons: { bounced: 'hard_bounce', complained: 'complaint', unsubscribed: 'unsubscribe' }, consent_sources: ['form', 'import', 'api', 'crm_event', 'administrator', 'unsubscribe'], consent_lawful_bases: ['consent', 'legitimate_interest', 'contractual'], consent_required_status: 'granted', suppression_scopes_by_purpose: { marketing: ['all', 'marketing'], default: ['all'] } },
  resilience: { delivery_timeout_seconds: 10, circuit_failure_threshold: 3, circuit_reset_seconds: 60, retry_max_attempts: 3, retry_base_delay_seconds: 0.25, retry_max_delay_seconds: 4, retry_jitter_seconds: 0.25, webhook_replay_window_seconds: 300 },
  tokens: { preflight_receipt_seconds: 900, tracking_token_days: 90, unsubscribe_token_days: 365 },
  integrations: { allowed_delivery_backends: ['django.core.mail.backends.smtp.EmailBackend'], simulated_delivery_backends: ['django.core.mail.backends.locmem.EmailBackend'], gateway_keys: ['django'] },
  filters: { default_ordering_by_resource: { campaigns: '-created_at', templates: '-updated_at', recipients: '-created_at', deliveries: '-created_at', suppressions: '-suppressed_at', consents: '-captured_at' }, search_fields_by_resource: { campaigns: ['campaign_code'], templates: ['template_code'], recipients: ['email'], deliveries: ['error_code'], suppressions: ['email'], consents: ['email'] } },
  health: { outbox_freshness_seconds: 300, probe_staleness_seconds: 30 },
  rate_limits: { public_per_minute: 30 },
  quotas: { api_reads: 100000, api_writes: 10000, audience_resolutions: 1000, monthly_recipients: 10000 },
  feature_flags: { enabled: true, roles: [], cohorts: [], rollout_percentage: 100 },
  display: { status_semantics: { delivered: 'success', accepted: 'success', active: 'success', failed: 'error', bounced: 'error', cancelled: 'error', paused: 'warning', draft: 'neutral' } },
};
function renderPage(element: React.ReactElement, path = '/') { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[path]}><Routes><Route path="*" element={element}/></Routes></MemoryRouter></QueryClientProvider>); }

describe('email marketing page families', () => {
  beforeEach(() => { vi.clearAllMocks(); vi.mocked(emailMarketingService.configuration.current).mockResolvedValue({ data: { id: 'config-id', environment: 'development', version: 1, document: configurationDocument, updated_at: '2026-07-22T00:00:00Z', updated_by: null }, correlationId: 'corr-config', timestamp: '2026-07-22T00:00:00Z' }); vi.mocked(emailMarketingService.campaigns.list).mockResolvedValue(empty); vi.mocked(emailMarketingService.templates.list).mockResolvedValue(empty); vi.mocked(emailMarketingService.recipients.list).mockResolvedValue(empty); vi.mocked(emailMarketingService.deliveries.list).mockResolvedValue(empty); vi.mocked(emailMarketingService.suppressions.list).mockResolvedValue(empty); vi.mocked(emailMarketingService.consents.list).mockResolvedValue(empty); });
  it('renders an accessible skeleton then the campaign first-use empty state', async () => { renderPage(<EmailCampaignListPage/>); expect(screen.getByLabelText('Loading campaigns')).toHaveAttribute('aria-busy', 'true'); expect(await screen.findByText('No campaigns yet')).toBeInTheDocument(); expect(screen.getAllByRole('button', { name: /create campaign/iu })).toHaveLength(2); });
  it('keeps URL filters distinct from first-use empty', async () => { renderPage(<EmailCampaignListPage/>, '/email-marketing/campaigns?search=missing'); expect(await screen.findByText('No campaigns match these filters')).toBeInTheDocument(); await userEvent.click(screen.getByRole('button', { name: 'Reset filters' })); expect(screen.getByLabelText('Search campaigns')).toHaveValue(''); });
  it('renders template, delivery, suppression, and consent empty states without fabricated rows', async () => { const cases = [[<EmailTemplateListPage/>, 'No templates yet'], [<AudienceDeliveryListPage/>, 'No recipients yet'], [<SuppressionListPage/>, 'No suppressions yet'], [<ConsentListPage/>, 'No consent records yet']] as const; for (const [page, text] of cases) { const rendered = renderPage(page); expect(await screen.findByText(text)).toBeInTheDocument(); rendered.unmount(); } });
  it('retains campaign form values after validation and prevents invalid submit', async () => { const submit = vi.fn(); renderPage(<CampaignForm pending={false} serverError={null} onSubmit={submit}/>); await userEvent.type(screen.getByLabelText('Campaign code'), 'WELCOME'); await userEvent.type(screen.getByLabelText('Campaign name'), 'Welcome'); await userEvent.type(screen.getByLabelText('Subject'), 'Hello'); await userEvent.type(screen.getByLabelText('From name'), 'SARAISE'); await userEvent.type(screen.getByLabelText('From email'), 'sender@example.com'); await userEvent.clear(screen.getByLabelText('Audience definition')); await userEvent.type(screen.getByLabelText('Audience definition'), 'not-json'); await userEvent.click(screen.getByRole('button', { name: 'Create draft' })); expect(await screen.findByRole('alert')).toHaveTextContent('Audience definition must be valid JSON.'); expect(screen.getByLabelText('Campaign code')).toHaveValue('WELCOME'); expect(submit).not.toHaveBeenCalled(); });
  it('explains the exact preflight send consequence', () => { renderPage(<PreflightPanel campaignStatus="draft" value={{ content_valid: true, receipt: 'preflight-receipt', rendered: true, resolved_count: 10, eligible_count: 8, suppressed_count: 2, consent_failure_count: 1, suppression_failure_count: 1, sender_healthy: true, sender_detail: 'Verified sender', quota_required: 8, quota_remaining: 100, scheduled_at: null, timezone: 'UTC', blocking_reasons: ['Resolve consent failures'] }}/>); expect(screen.getByText(/8 eligible · 2 suppressed/iu)).toBeInTheDocument(); expect(screen.getByText(/durably queues eligible recipients/iu)).toBeInTheDocument(); expect(screen.getByText('Resolve consent failures')).toBeInTheDocument(); });
  it('distinguishes permission, conflict, quota, and dependency failures with correlation evidence', () => { const errors = [[403, 'Access or entitlement denied'], [409, 'State conflict'], [429, 'Quota or rate limit reached'], [503, 'Delivery dependency unavailable']] as const; for (const [status, title] of errors) { const rendered = renderPage(<GovernedError error={new ApiError('failed', status, undefined, 'DENIED', 'corr-test')}/>); expect(screen.getByText(title)).toBeInTheDocument(); expect(screen.getByText(/corr-test/iu)).toBeInTheDocument(); rendered.unmount(); } });
});
