import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { ApiError } from '@/services/api-client';
import { CampaignForm } from '../components/CampaignForm';
import { GovernedError, PreflightPanel } from '../components/EmailMarketingUI';
import { emailMarketingService } from '../services/email-marketing-service';
import { EmailCampaignListPage } from './EmailCampaignListPage';
import { EmailTemplateListPage } from './EmailTemplateListPage';
import { AudienceDeliveryListPage } from './AudienceDeliveryListPage';
import { SuppressionListPage } from './SuppressionListPage';
import { ConsentListPage } from './ConsentListPage';

vi.mock('../services/email-marketing-service', () => {
  const fn = () => vi.fn();
  return { EMAIL_MARKETING_QUERY_KEYS: { all: ['email-marketing'], campaigns: (f = {}) => ['email-marketing','campaigns',f], campaign: (id: string) => ['email-marketing','campaign',id], analytics: (id: string) => ['email-marketing','analytics',id], templates: (f = {}) => ['email-marketing','templates',f], template: (id: string) => ['email-marketing','template',id], recipients: (f = {}) => ['email-marketing','recipients',f], recipient: (id: string) => ['email-marketing','recipient',id], deliveries: (f = {}) => ['email-marketing','deliveries',f], delivery: (id: string) => ['email-marketing','delivery',id], suppressions: (f = {}) => ['email-marketing','suppressions',f], suppression: (id: string) => ['email-marketing','suppression',id], consents: (f = {}) => ['email-marketing','consents',f], consent: (id: string) => ['email-marketing','consent',id], health: ['email-marketing','health'] }, emailMarketingService: { campaigns: { list: fn(), get: fn(), create: fn(), update: fn(), delete: fn(), resolveAudience: fn(), schedule: fn(), unschedule: fn(), send: fn(), pause: fn(), resume: fn(), cancel: fn(), analytics: fn() }, templates: { list: fn(), get: fn(), create: fn(), update: fn(), delete: fn(), activate: fn(), archive: fn(), clone: fn(), preview: fn() }, recipients: { list: fn(), get: fn(), retry: fn() }, deliveries: { list: fn(), get: fn() }, suppressions: { list: fn(), get: fn(), create: fn(), deactivate: fn() }, consents: { list: fn(), get: fn(), create: fn(), revoke: fn() }, health: fn() } };
});

const pagination = { count: 0, page: 1, page_size: 25, total_pages: 0, has_next: false, has_previous: false };
const empty = { items: [], pagination, correlationId: 'corr-list', timestamp: '2026-07-22T00:00:00Z' };
function renderPage(element: React.ReactElement, path = '/') { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[path]}><Routes><Route path="*" element={element}/></Routes></MemoryRouter></QueryClientProvider>); }

describe('email marketing page families', () => {
  beforeEach(() => { vi.clearAllMocks(); vi.mocked(emailMarketingService.campaigns.list).mockResolvedValue(empty); vi.mocked(emailMarketingService.templates.list).mockResolvedValue(empty); vi.mocked(emailMarketingService.recipients.list).mockResolvedValue(empty); vi.mocked(emailMarketingService.deliveries.list).mockResolvedValue(empty); vi.mocked(emailMarketingService.suppressions.list).mockResolvedValue(empty); vi.mocked(emailMarketingService.consents.list).mockResolvedValue(empty); });
  it('renders an accessible skeleton then the campaign first-use empty state', async () => { renderPage(<EmailCampaignListPage/>); expect(screen.getByLabelText('Loading campaigns')).toHaveAttribute('aria-busy', 'true'); expect(await screen.findByText('No campaigns yet')).toBeInTheDocument(); expect(screen.getAllByRole('button', { name: /create campaign/iu })).toHaveLength(2); });
  it('keeps URL filters distinct from first-use empty', async () => { renderPage(<EmailCampaignListPage/>, '/email-marketing/campaigns?search=missing'); expect(await screen.findByText('No campaigns match these filters')).toBeInTheDocument(); await userEvent.click(screen.getByRole('button', { name: 'Reset filters' })); expect(screen.getByLabelText('Search campaigns')).toHaveValue(''); });
  it('renders template, delivery, suppression, and consent empty states without fabricated rows', async () => { const cases = [[<EmailTemplateListPage/>, 'No templates yet'], [<AudienceDeliveryListPage/>, 'No recipients yet'], [<SuppressionListPage/>, 'No suppressions yet'], [<ConsentListPage/>, 'No consent records yet']] as const; for (const [page, text] of cases) { const rendered = renderPage(page); expect(await screen.findByText(text)).toBeInTheDocument(); rendered.unmount(); } });
  it('retains campaign form values after validation and prevents invalid submit', async () => { const submit = vi.fn(); renderPage(<CampaignForm pending={false} serverError={null} onSubmit={submit}/>); await userEvent.type(screen.getByLabelText('Campaign code'), 'WELCOME'); await userEvent.type(screen.getByLabelText('Campaign name'), 'Welcome'); await userEvent.type(screen.getByLabelText('Subject'), 'Hello'); await userEvent.type(screen.getByLabelText('From name'), 'SARAISE'); await userEvent.type(screen.getByLabelText('From email'), 'sender@example.com'); await userEvent.clear(screen.getByLabelText('Audience definition')); await userEvent.type(screen.getByLabelText('Audience definition'), 'not-json'); await userEvent.click(screen.getByRole('button', { name: 'Create draft' })); expect(await screen.findByRole('alert')).toHaveTextContent('Audience definition must be valid JSON.'); expect(screen.getByLabelText('Campaign code')).toHaveValue('WELCOME'); expect(submit).not.toHaveBeenCalled(); });
  it('explains the exact preflight send consequence', () => { renderPage(<PreflightPanel campaignStatus="draft" value={{ content_valid: true, rendered: true, resolved_count: 10, eligible_count: 8, suppressed_count: 2, consent_failure_count: 1, suppression_failure_count: 1, sender_healthy: true, sender_detail: 'Verified sender', quota_required: 8, quota_remaining: 100, scheduled_at: null, timezone: 'UTC', blocking_reasons: ['Resolve consent failures'] }}/>); expect(screen.getByText(/8 eligible · 2 suppressed/iu)).toBeInTheDocument(); expect(screen.getByText(/durably queues eligible recipients/iu)).toBeInTheDocument(); expect(screen.getByText('Resolve consent failures')).toBeInTheDocument(); });
  it('distinguishes permission, conflict, quota, and dependency failures with correlation evidence', () => { const errors = [[403, 'Access or entitlement denied'], [409, 'State conflict'], [429, 'Quota or rate limit reached'], [503, 'Delivery dependency unavailable']] as const; for (const [status, title] of errors) { const rendered = renderPage(<GovernedError error={new ApiError('failed', status, undefined, 'DENIED', 'corr-test')}/>); expect(screen.getByText(title)).toBeInTheDocument(); expect(screen.getByText(/corr-test/iu)).toBeInTheDocument(); rendered.unmount(); } });
});
