import { useEffect, type ReactNode } from 'react';
import { AlertTriangle, RefreshCw, WalletCards } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { Card, CardContent } from '@/components/ui/Card';
import { Skeleton } from '@/components/ui/Skeleton';
import { BudgetManagementApiError } from '../services/budget-service';
import type { BudgetStatus, DecimalString, PaginationMeta } from '../contracts';

export function usePageTitle(title: string): void { useEffect(() => { document.title = `${title} · SARAISE`; }, [title]); }
export function PageHeader({ title, description, actions }: { readonly title: string; readonly description: string; readonly actions?: ReactNode }) {
  return <header className="flex flex-col gap-4 border-b pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Budget management</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{description}</p></div>{actions ? <div className="flex flex-wrap gap-2">{actions}</div> : null}</header>;
}
export function PageSkeleton({ rows = 6 }: { readonly rows?: number }) { return <main className="space-y-5 p-4 sm:p-8" aria-label="Loading budget data" aria-busy="true"><Skeleton className="h-10 w-72"/><Skeleton className="h-24 w-full"/>{Array.from({ length: rows }, (_, index) => <Skeleton key={index} className="h-16 w-full"/>)}</main>; }
export function RefreshIndicator({ active }: { readonly active: boolean }) { return active ? <span role="status" className="inline-flex items-center gap-2 text-xs text-muted-foreground"><RefreshCw className="h-3.5 w-3.5 animate-spin"/>Refreshing</span> : null; }
export function GovernedError({ error, onRetry }: { readonly error: Error; readonly onRetry?: () => void }) {
  const governed = error instanceof BudgetManagementApiError ? error : undefined;
  const title = governed?.status === 403 ? 'Permission required' : governed?.status === 404 ? 'Budget data not found' : governed?.status === 409 ? 'The record changed' : governed?.status === 503 ? 'Capability unavailable' : 'Budget data unavailable';
  const message = governed?.status === 404 ? 'This record does not exist or is outside your tenant boundary.' : governed?.message ?? error.message;
  return <Card role="alert" className="border-destructive/40"><CardContent className="flex min-h-64 flex-col items-center justify-center p-8 text-center"><AlertTriangle className="mb-4 h-10 w-10 text-destructive"/><h2 className="text-xl font-semibold">{title}</h2><p className="mt-2 max-w-xl text-sm text-muted-foreground">{message}</p>{governed?.correlationId ? <p className="mt-2 font-mono text-xs text-muted-foreground">Correlation: {governed.correlationId}</p> : null}{onRetry ? <Button className="mt-5" variant="outline" onClick={onRetry}><RefreshCw className="mr-2 h-4 w-4"/>Try again</Button> : null}</CardContent></Card>;
}
export function MutationError({ error }: { readonly error: Error }) { return <GovernedError error={error}/>; }
export function EmptyPanel({ title, description, action }: { readonly title: string; readonly description: string; readonly action: ReactNode }) { return <Card><CardContent className="flex min-h-64 flex-col items-center justify-center p-8 text-center"><span className="rounded-2xl bg-primary/10 p-3 text-primary"><WalletCards/></span><h2 className="mt-4 text-xl font-semibold">{title}</h2><p className="mt-2 max-w-lg text-sm text-muted-foreground">{description}</p><div className="mt-5">{action}</div></CardContent></Card>; }
const statusColors: Record<BudgetStatus, string> = { draft: 'bg-slate-100 text-slate-800 dark:bg-slate-800 dark:text-slate-100', pending_approval: 'bg-amber-100 text-amber-900 dark:bg-amber-950 dark:text-amber-100', approved: 'bg-emerald-100 text-emerald-900 dark:bg-emerald-950 dark:text-emerald-100', rejected: 'bg-red-100 text-red-900 dark:bg-red-950 dark:text-red-100', revision: 'bg-blue-100 text-blue-900 dark:bg-blue-950 dark:text-blue-100', closed: 'bg-zinc-200 text-zinc-900 dark:bg-zinc-800 dark:text-zinc-100' };
export function StatusPill({ status }: { readonly status: BudgetStatus }) { return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-medium ${statusColors[status]}`}>{status.replaceAll('_', ' ')}</span>; }
export function Money({ value, currency }: { readonly value: DecimalString | number; readonly currency: string }) { const amount = typeof value === 'number' ? value : Number(value); return <>{Number.isFinite(amount) ? new Intl.NumberFormat(undefined, { style: 'currency', currency }).format(amount) : `— ${currency}`}</>; }
export function formatDate(value: string | null | undefined): string { if (!value) return '—'; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? '—' : new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: value.includes('T') ? 'short' : undefined }).format(parsed); }
export function Pagination({ value, onPage }: { readonly value: PaginationMeta; readonly onPage: (page: number) => void }) { return <nav aria-label="Pagination" className="flex flex-col items-center justify-between gap-3 border-t p-4 sm:flex-row"><span className="text-sm text-muted-foreground">Page {value.page} of {Math.max(value.total_pages, 1)} · {value.count} budgets</span><div className="flex gap-2"><Button size="sm" variant="outline" disabled={!value.has_previous} onClick={() => onPage(value.page - 1)}>Previous</Button><Button size="sm" variant="outline" disabled={!value.has_next} onClick={() => onPage(value.page + 1)}>Next</Button></div></nav>; }
export function newIdempotencyKey(command: string): string { return `${command}:${crypto.randomUUID()}`; }
