import { useState, type FormEvent } from 'react';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import type { BudgetCreateRequest, BudgetDetail, BudgetType } from '../contracts';

export type BudgetFormValue = BudgetCreateRequest;
type Errors = Partial<Record<keyof BudgetFormValue, string>>;
function validate(value: BudgetFormValue): Errors {
  const errors: Errors = {};
  if (!value.budget_code.trim()) errors.budget_code = 'Code is required.';
  if (!value.budget_name.trim()) errors.budget_name = 'Name is required.';
  if (value.fiscal_year < 1900 || value.fiscal_year > 9999) errors.fiscal_year = 'Enter a four-digit fiscal year.';
  if (!value.start_date) errors.start_date = 'Start date is required.';
  if (!value.end_date) errors.end_date = 'End date is required.';
  if (value.start_date && value.end_date && value.start_date > value.end_date) errors.end_date = 'End date must not precede the start date.';
  if (!/^[A-Z]{3}$/u.test(value.currency)) errors.currency = 'Use a three-letter uppercase ISO currency code.';
  if (value.budget_type === 'departmental' && !value.department_id) errors.department_id = 'Department UUID is required for a departmental budget.';
  if (value.budget_type === 'project' && !value.project_id) errors.project_id = 'Project UUID is required for a project budget.';
  if (value.budget_ceiling && (!/^\d+(\.\d{1,2})?$/u.test(value.budget_ceiling) || Number(value.budget_ceiling) < 0)) errors.budget_ceiling = 'Enter a non-negative amount with at most two decimal places.';
  return errors;
}
export function initialBudgetValue(source?: BudgetDetail): BudgetFormValue { const year = new Date().getFullYear(); return source ? { budget_code: source.budget_code, budget_name: source.budget_name, fiscal_year: source.fiscal_year, start_date: source.start_date, end_date: source.end_date, budget_type: source.budget_type, currency: source.currency, budget_ceiling: source.budget_ceiling, department_id: source.department_id, project_id: source.project_id } : { budget_code: '', budget_name: '', fiscal_year: year, start_date: `${year}-01-01`, end_date: `${year}-12-31`, budget_type: 'operating', currency: 'USD', budget_ceiling: null, department_id: null, project_id: null }; }
export function BudgetForm({ initial, serverErrors, busy, submitLabel, onSubmit, onCancel }: { readonly initial: BudgetFormValue; readonly serverErrors?: Readonly<Record<string, readonly string[]>>; readonly busy: boolean; readonly submitLabel: string; readonly onSubmit: (value: BudgetFormValue) => void; readonly onCancel: () => void }) {
  const [value, setValue] = useState(initial); const [errors, setErrors] = useState<Errors>({});
  const update = <K extends keyof BudgetFormValue>(key: K, next: BudgetFormValue[K]) => setValue((current) => ({ ...current, [key]: next }));
  const error = (key: keyof BudgetFormValue) => errors[key] ?? serverErrors?.[key]?.[0];
  const submit = (event: FormEvent) => { event.preventDefault(); const nextErrors = validate(value); setErrors(nextErrors); if (Object.keys(nextErrors).length === 0) onSubmit({ ...value, budget_code: value.budget_code.trim().toUpperCase(), budget_name: value.budget_name.trim(), currency: value.currency.trim().toUpperCase(), budget_ceiling: value.budget_ceiling || null, department_id: value.budget_type === 'departmental' ? value.department_id : null, project_id: value.budget_type === 'project' ? value.project_id : null }); };
  return <form className="space-y-6" onSubmit={submit} noValidate><div className="grid gap-5 sm:grid-cols-2"><Input id="budget-code" label="Budget code" required autoFocus value={value.budget_code} error={error('budget_code')} onChange={(event) => update('budget_code', event.target.value)} placeholder="FY27-OPS"/><Input id="budget-name" label="Budget name" required value={value.budget_name} error={error('budget_name')} onChange={(event) => update('budget_name', event.target.value)} placeholder="Global operations"/><Input id="fiscal-year" label="Fiscal year" required type="number" min={1900} max={9999} value={value.fiscal_year} error={error('fiscal_year')} onChange={(event) => update('fiscal_year', Number(event.target.value))}/><label className="text-sm font-medium" htmlFor="budget-type">Budget type<select id="budget-type" value={value.budget_type} onChange={(event) => update('budget_type', event.target.value as BudgetType)} className="mt-1 block h-10 w-full rounded-md border bg-background px-3"><option value="operating">Operating</option><option value="capital">Capital</option><option value="project">Project</option><option value="departmental">Departmental</option></select></label><Input id="start-date" label="Start date" required type="date" value={value.start_date} error={error('start_date')} onChange={(event) => update('start_date', event.target.value)}/><Input id="end-date" label="End date" required type="date" value={value.end_date} error={error('end_date')} onChange={(event) => update('end_date', event.target.value)}/><Input id="currency" label="Currency" required maxLength={3} value={value.currency} error={error('currency')} onChange={(event) => update('currency', event.target.value.toUpperCase())} placeholder="USD"/><Input id="ceiling" label="Budget ceiling (optional)" inputMode="decimal" value={value.budget_ceiling ?? ''} error={error('budget_ceiling')} onChange={(event) => update('budget_ceiling', event.target.value || null)} placeholder="0.00"/>{value.budget_type === 'departmental' ? <Input id="department-id" className="font-mono" label="Department UUID" required value={value.department_id ?? ''} error={error('department_id')} onChange={(event) => update('department_id', event.target.value || null)}/> : null}{value.budget_type === 'project' ? <Input id="project-id" className="font-mono" label="Project UUID" required value={value.project_id ?? ''} error={error('project_id')} onChange={(event) => update('project_id', event.target.value || null)}/> : null}</div><div className="flex justify-end gap-3"><Button type="button" variant="outline" onClick={onCancel}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? 'Saving…' : submitLabel}</Button></div></form>;
}
