import { useMemo, useState } from 'react';
import { z } from 'zod';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/Button';
import { GovernedError, PageSkeleton, Surface, useUnsavedChanges } from './EmailMarketingUI';
import { ROUTES, type CampaignCreateInput, type EmailCampaignDetail, type EmailMarketingConfigurationDocument } from '../contracts';
import { useEmailMarketingConfiguration } from '../hooks/use-email-marketing-configuration';

type Values = { campaign_code: string; campaign_name: string; subject: string; from_name: string; from_email: string; reply_to_email: string; timezone: string; audience: string; description: string; preview_text: string; campaign_type: string; template_id: string };
const initialValues = (configuration: EmailMarketingConfigurationDocument, initial?: EmailCampaignDetail): Values => ({ campaign_code: initial?.campaign_code ?? '', campaign_name: initial?.campaign_name ?? '', description: initial?.description ?? '', campaign_type: initial?.campaign_type ?? configuration.defaults.campaign_type, template_id: initial?.template_id ?? '', subject: initial?.subject ?? '', preview_text: initial?.preview_text ?? '', from_name: initial?.from_name ?? '', from_email: initial?.from_email ?? '', reply_to_email: initial?.reply_to_email ?? '', timezone: initial?.timezone ?? configuration.defaults.timezone, audience: JSON.stringify(initial?.audience_definition ?? { version: configuration.defaults.audience_schema_version, resolver: configuration.defaults.audience_resolver, recipients: [] }, null, 2) });

export function CampaignForm({ initial, pending, serverError, onSubmit }: { readonly initial?: EmailCampaignDetail; readonly pending: boolean; readonly serverError: unknown; readonly onSubmit: (input: CampaignCreateInput) => void }) {
  const configuration = useEmailMarketingConfiguration();
  if (configuration.isLoading) return <PageSkeleton label="Loading campaign configuration"/>;
  if (configuration.error) return <GovernedError error={configuration.error} retry={() => void configuration.refetch()}/>;
  if (!configuration.data) return <GovernedError error={new Error('No governed email marketing configuration was received.')} retry={() => void configuration.refetch()}/>;
  return <ConfiguredCampaignForm configuration={configuration.data.data.document} initial={initial} pending={pending} serverError={serverError} onSubmit={onSubmit}/>;
}

function ConfiguredCampaignForm({ configuration, initial, pending, serverError, onSubmit }: { readonly configuration: EmailMarketingConfigurationDocument; readonly initial?: EmailCampaignDetail; readonly pending: boolean; readonly serverError: unknown; readonly onSubmit: (input: CampaignCreateInput) => void }) {
  const schema = useMemo(() => z.object({ campaign_code: z.string().trim().min(1).max(50).regex(/^[A-Za-z0-9_-]+$/u, 'Use letters, numbers, hyphens, or underscores.'), campaign_name: z.string().trim().min(1).max(255), subject: z.string().trim().min(1).max(configuration.limits.subject_max_length), from_name: z.string().trim().min(1).max(configuration.limits.display_name_max_length), from_email: z.string().email(), reply_to_email: z.union([z.literal(''), z.string().email()]), timezone: z.string().min(1), audience: z.string().min(2) }), [configuration]);
  const navigate = useNavigate(); const baseline = useMemo(() => initialValues(configuration, initial), [configuration, initial]); const [values, setValues] = useState(baseline); const [error, setError] = useState(''); const dirty = JSON.stringify(values) !== JSON.stringify(baseline); useUnsavedChanges(dirty);
  const field = (name: keyof Values) => ({ value: values[name], onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => setValues((current) => ({ ...current, [name]: event.target.value })) });
  const inputClass = 'mt-1 block w-full rounded-md border bg-background px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring';
  return <form className="space-y-6" onSubmit={(event) => { event.preventDefault(); const checked = schema.safeParse(values); if (!checked.success) { setError(checked.error.issues[0]?.message ?? 'Review the form.'); return; } let audience: unknown; try { audience = JSON.parse(values.audience); } catch { setError('Audience definition must be valid JSON.'); return; } if (!audience || typeof audience !== 'object' || Array.isArray(audience)) { setError('Audience definition must be a versioned JSON object.'); return; } setError(''); onSubmit({ campaign_code: values.campaign_code.trim().toUpperCase(), campaign_name: values.campaign_name.trim(), description: values.description, campaign_type: values.campaign_type, template_id: values.template_id || null, subject: values.subject.trim(), preview_text: values.preview_text, from_name: values.from_name.trim(), from_email: values.from_email.trim(), reply_to_email: values.reply_to_email || null, audience_definition: audience as Readonly<Record<string, unknown>>, timezone: values.timezone }); }}>
    <Surface title="Campaign identity and sender" description="Lifecycle state and delivery counters are server-controlled."><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Campaign code<input aria-label="Campaign code" disabled={Boolean(initial)} maxLength={50} required className={inputClass} {...field('campaign_code')}/></label><label className="text-sm font-medium">Campaign name<input aria-label="Campaign name" maxLength={255} required className={inputClass} {...field('campaign_name')}/></label><label className="text-sm font-medium">Campaign type<select aria-label="Campaign type" className={inputClass} {...field('campaign_type')}>{configuration.workflows.campaign_types.map((value) => <option value={value} key={value}>{value.replaceAll('_', ' ')}</option>)}</select></label><label className="text-sm font-medium">Template ID (optional)<input aria-label="Template ID" className={inputClass} placeholder="Tenant-owned template UUID" {...field('template_id')}/></label><label className="text-sm font-medium">From name<input aria-label="From name" required maxLength={configuration.limits.display_name_max_length} className={inputClass} {...field('from_name')}/></label><label className="text-sm font-medium">From email<input aria-label="From email" type="email" required className={inputClass} {...field('from_email')}/></label><label className="text-sm font-medium">Reply-to email<input aria-label="Reply-to email" type="email" className={inputClass} {...field('reply_to_email')}/></label><label className="text-sm font-medium">Timezone<input aria-label="Timezone" required className={inputClass} {...field('timezone')}/></label></div><label className="mt-4 block text-sm font-medium">Description<textarea aria-label="Description" rows={3} className={inputClass} {...field('description')}/></label></Surface>
    <Surface title="Content"><label className="block text-sm font-medium">Subject<input aria-label="Subject" required maxLength={configuration.limits.subject_max_length} className={inputClass} {...field('subject')}/></label><label className="mt-4 block text-sm font-medium">Preview text<input aria-label="Preview text" maxLength={configuration.limits.preview_text_max_length} className={inputClass} {...field('preview_text')}/></label><p className="mt-3 text-xs text-muted-foreground">Template content is snapshotted by the server when send is requested; editing the template later cannot change queued messages.</p></Surface>
    <Surface title="Versioned audience definition" description="Resolvers deduplicate normalized addresses and apply consent and suppression before queueing."><textarea aria-label="Audience definition" rows={9} spellCheck={false} className={`${inputClass} font-mono`} {...field('audience')}/></Surface>
    {error ? <p role="alert" className="text-sm text-destructive">{error}</p> : null}{serverError ? <GovernedError error={serverError}/> : null}<p aria-live="polite" className="sr-only">{pending ? 'Saving campaign' : ''}</p><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => { if (!dirty || window.confirm('Discard unsaved campaign changes?')) navigate(initial ? ROUTES.CAMPAIGN_DETAIL(initial.id) : ROUTES.CAMPAIGNS); }}>Cancel</Button><Button type="submit" disabled={pending}>{pending ? 'Validating and saving…' : initial ? 'Save draft' : 'Create draft'}</Button></div>
  </form>;
}
