/* eslint-disable react-refresh/only-export-components */
import { keepPreviousData, useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Activity, Edit3, KeyRound, Plus, RefreshCw, Search, Trash2 } from 'lucide-react';
import { useEffect, useState, type FormEvent } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { toast } from 'sonner';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { Input } from '@/components/ui/Input';
import { Textarea } from '@/components/ui/Textarea';
import type { ConnectorType, CredentialType, IntegrationCreateRequest, IntegrationFilters, JsonObject } from '../contracts';
import { ROUTE_PATHS } from '../contracts';
import { SchemaFields } from '../components/SchemaFields';
import { BackgroundRefresh, Definition, DefinitionGrid, EmptyPanel, EvidenceCard, formatDate, GovernedError, newOperationKey, PageHeader, PageSkeleton, Pagination, StatusBadge, SuccessEvidence, useCanManageIntegrations } from '../components/IntegrationPlatformUI';
import { credentialCreateSchema, integrationCreateSchema, jsonObjectSchema } from '../schemas/integration-platform-schemas';
import { integrationPlatformService as service } from '../services/integration-platform-service';

function positive(value: string | null): number { const number = Number(value ?? '1'); return Number.isInteger(number) && number > 0 ? number : 1; }
function formText(form: FormData, key: string): string { const value = form.get(key); return typeof value === 'string' ? value.trim() : ''; }
function requiredRouteId(name: string, value?: string): string { if (!value) throw new Error(`${name} route requires an identifier.`); return value; }

// eslint-disable-next-line complexity
export function IntegrationListPage() {
  const navigate = useNavigate(); const canManage = useCanManageIntegrations(); const [params, setParams] = useSearchParams();
  const filters: IntegrationFilters = { page: positive(params.get('page')), page_size: 25, search: params.get('search') ?? undefined, status: (params.get('status') ?? undefined) as IntegrationFilters['status'], integration_type: (params.get('type') ?? undefined) as ConnectorType | undefined, connector_id: params.get('connector') ?? undefined, ordering: (params.get('ordering') ?? '-updated_at') as IntegrationFilters['ordering'] };
  const query = useQuery({ queryKey: ['integration-platform', 'integrations', params.toString()], queryFn: () => service.listIntegrations(filters), placeholderData: keepPreviousData });
  const connectors = useQuery({ queryKey: ['integration-platform', 'connectors', 'filter'], queryFn: () => service.listConnectors({ page_size: 100 }) });
  const update = (key: string, value: string) => { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); if (key !== 'page') next.set('page', '1'); setParams(next); };
  const filtered = ['search', 'status', 'type', 'connector'].some((key) => params.has(key));
  if (query.isLoading) return <PageSkeleton label="Loading integrations" />;
  if (query.error || !query.data) return <main className="p-4 sm:p-8"><GovernedError error={query.error} retry={() => { void query.refetch(); }} /></main>;
  return <main className="space-y-6 p-4 sm:p-8"><PageHeader title="Integrations" description="Governed connector instances with durable test, synchronization, and audit evidence." actions={canManage ? <Button onClick={() => navigate(ROUTE_PATHS.INTEGRATION_CREATE)}><Plus className="mr-2 h-4 w-4" />New integration</Button> : undefined} />
    <BackgroundRefresh active={query.isFetching && !query.isLoading} />
    <Card className="p-4"><form className="grid gap-3 lg:grid-cols-6" role="search" onSubmit={(event) => { event.preventDefault(); update('search', formText(new FormData(event.currentTarget), 'search')); }}><Input name="search" aria-label="Search integrations" defaultValue={params.get('search') ?? ''} placeholder="Search integrations…" /><select aria-label="Filter by status" className="rounded-md border bg-background px-3 py-2" value={params.get('status') ?? ''} onChange={(event) => update('status', event.target.value)}><option value="">All statuses</option>{['inactive', 'testing', 'active', 'error'].map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Filter by integration type" className="rounded-md border bg-background px-3 py-2" value={params.get('type') ?? ''} onChange={(event) => update('type', event.target.value)}><option value="">All types</option>{['api', 'webhook', 'database', 'file', 'message_queue'].map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Filter by connector" className="rounded-md border bg-background px-3 py-2" value={params.get('connector') ?? ''} onChange={(event) => update('connector', event.target.value)}><option value="">All connectors</option>{connectors.data?.items.map((connector) => <option value={connector.id} key={connector.id}>{connector.name}</option>)}</select><select aria-label="Sort integrations" className="rounded-md border bg-background px-3 py-2" value={params.get('ordering') ?? '-updated_at'} onChange={(event) => update('ordering', event.target.value)}><option value="-updated_at">Recently updated</option><option value="name">Name A–Z</option><option value="-created_at">Newest</option><option value="status">Status</option></select><Button type="submit" variant="secondary"><Search className="mr-2 h-4 w-4" />Search</Button></form></Card>
    {query.data.items.length === 0 ? <EmptyPanel filtered={filtered} title="integrations" description="Start by selecting a connector and verifying its real adapter." reset={() => setParams(new URLSearchParams())} action={canManage ? <Button onClick={() => navigate(ROUTE_PATHS.INTEGRATION_CREATE)}>Set up an integration</Button> : undefined} /> : <Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b bg-muted/50"><tr><th className="p-4">Integration</th><th className="p-4">Status</th><th className="p-4">Last test</th><th className="p-4">Last sync</th><th className="p-4">Updated</th></tr></thead><tbody>{query.data.items.map((item) => <tr key={item.id} className="border-b hover:bg-muted/30"><td className="p-4"><Link className="font-semibold text-primary" to={ROUTE_PATHS.INTEGRATION_DETAIL(item.id)}>{item.name}</Link><p className="text-xs text-muted-foreground">{item.connector_name} · {item.integration_type.replaceAll('_', ' ')}</p></td><td className="p-4"><StatusBadge status={item.status} /></td><td className="p-4">{formatDate(item.last_tested_at)}{item.last_test_job_id && <p className="font-mono text-xs text-muted-foreground">{item.last_test_job_id.slice(0, 8)}</p>}</td><td className="p-4">{item.last_sync_job_id ? <span className="font-mono text-xs">{item.last_sync_job_id.slice(0, 8)}</span> : 'Not yet'}</td><td className="p-4">{formatDate(item.updated_at)}</td></tr>)}</tbody></table></div><Pagination meta={query.data.meta} changePage={(page) => update('page', String(page))} /></Card>}
  </main>;
}

// Guided setup coordinates connector, schema, credential, integration, and durable-job states.
// eslint-disable-next-line complexity
export function CreateIntegrationPage({ connectorId }: { connectorId?: string }) {
  const navigate = useNavigate(); const [selectedId, setSelectedId] = useState(connectorId ?? ''); const [config, setConfig] = useState<JsonObject>({}); const [error, setError] = useState<string | null>(null); const [receipt, setReceipt] = useState<string | null>(null);
  const connectors = useQuery({ queryKey: ['integration-platform', 'connectors', 'setup'], queryFn: () => service.listConnectors({ page_size: 100 }) });
  const connector = connectors.data?.items.find((entry) => entry.id === selectedId);
  const schema = useQuery({ queryKey: ['integration-platform', 'connector-schema', selectedId], queryFn: () => service.getConnectorSchema(selectedId), enabled: Boolean(selectedId) });
  const create = useMutation({ mutationFn: async (form: FormData) => { if (!connector) throw new Error('Select an available connector.'); const request: IntegrationCreateRequest = { connector_id: connector.id, name: formText(form, 'name'), description: formText(form, 'description'), integration_type: connector.connector_type, config }; const parsed = integrationCreateSchema.safeParse(request); if (!parsed.success) throw new Error(parsed.error.issues[0]?.message ?? 'Integration configuration is invalid.'); const integration = await service.createIntegration(request); const plaintext = formText(form, 'plaintext'); if (plaintext) { const credentialRequest = { credential_type: formText(form, 'credential_type') as CredentialType, plaintext }; const validCredential = credentialCreateSchema.safeParse(credentialRequest); if (!validCredential.success) throw new Error(validCredential.error.issues[0]?.message ?? 'Credential is invalid.'); await service.createCredential(integration.id, credentialRequest); } const job = await service.testIntegration(integration.id, { idempotency_key: newOperationKey('setup-test') }); return { integration, job }; }, onSuccess: ({ integration, job }) => { setReceipt(job.correlation_id); toast.success('Integration created; a real connection test is queued.', { description: `Correlation ${job.correlation_id}` }); window.setTimeout(() => navigate(ROUTE_PATHS.INTEGRATION_DETAIL(integration.id)), 500); }, onError: (failure: Error) => setError(failure.message) });
  if (connectors.isLoading) return <PageSkeleton label="Loading connector setup" />;
  if (connectors.error || !connectors.data) return <main className="p-4 sm:p-8"><GovernedError error={connectors.error} retry={() => { void connectors.refetch(); }} /></main>;
  return <main className="space-y-6 p-4 sm:p-8"><PageHeader title="Set up an integration" description="Connector-first guided setup. Configuration stays non-secret; credentials are encrypted server-side." backTo={{ label: 'Integrations', path: ROUTE_PATHS.INTEGRATIONS }} />
    <ol className="grid gap-2 text-sm sm:grid-cols-4" aria-label="Setup steps">{['1. Connector', '2. Configuration', '3. Credential', '4. Review & test'].map((step) => <li className="rounded-lg border bg-card p-3" key={step}>{step}</li>)}</ol>{error && <Card className="border-destructive p-4 text-sm text-destructive" role="alert">{error}</Card>}{receipt && <SuccessEvidence title="Test accepted" correlationId={receipt} />}
    <form className="space-y-6" aria-busy={create.isPending} onSubmit={(event) => { event.preventDefault(); setError(null); create.mutate(new FormData(event.currentTarget)); }}><EvidenceCard title="1. Choose a connector"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{connectors.data.items.map((entry) => <button type="button" key={entry.id} aria-pressed={selectedId === entry.id} disabled={!entry.adapter_available || !entry.is_entitled} className={`rounded-lg border p-4 text-left focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-60 ${selectedId === entry.id ? 'border-primary bg-primary/5' : ''}`} onClick={() => { setSelectedId(entry.id); setConfig({}); }}><span className="font-semibold">{entry.name}</span><p className="mt-1 text-xs text-muted-foreground">{entry.capabilities.join(' · ') || 'No capabilities declared'}</p>{!entry.adapter_available && <p className="mt-2 text-xs text-destructive">Adapter unavailable</p>}{!entry.is_entitled && <p className="mt-2 text-xs text-amber-700">Locked: {entry.entitlement_reason ?? entry.required_entitlement}</p>}</button>)}</div></EvidenceCard>
      {selectedId && <EvidenceCard title="2. Non-secret configuration"><div className="mb-5 grid gap-4 md:grid-cols-2"><Input id="integration-name" name="name" label="Integration name" required maxLength={255} /><Textarea id="integration-description" name="description" label="Description" /></div>{schema.isLoading ? <p role="status">Loading governed connector schema…</p> : schema.error || !schema.data ? <GovernedError error={schema.error} retry={() => { void schema.refetch(); }} /> : <SchemaFields schema={schema.data.config_schema} values={config} disabled={create.isPending} onChange={setConfig} />}</EvidenceCard>}
      {schema.data && <EvidenceCard title="3. Credential (optional when the connector allows it)"><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium" htmlFor="credential-type">Credential type<select id="credential-type" name="credential_type" className="mt-1 block w-full rounded-md border bg-background px-3 py-2"><option value="api_key">API key</option><option value="oauth_token">OAuth token</option><option value="username_password">Username/password bundle</option><option value="certificate">Certificate</option></select></label><Input id="credential-plaintext" name="plaintext" label="Credential value" type="password" autoComplete="new-password" /><p className="text-xs text-muted-foreground md:col-span-2">The value is sent once over the governed session, encrypted by the server, and never returned.</p></div></EvidenceCard>}
      {connector && <EvidenceCard title="4. Review and run a real test"><DefinitionGrid><Definition label="Connector">{connector.name}</Definition><Definition label="Type">{connector.connector_type}</Definition><Definition label="Adapter">{connector.adapter_available ? 'Registered' : 'Unavailable'}</Definition><Definition label="Entitlement">{connector.is_entitled ? 'Granted' : 'Locked'}</Definition><Definition label="Capabilities">{connector.capabilities.join(', ')}</Definition><Definition label="Configuration fields">{Object.keys(config).length}</Definition></DefinitionGrid></EvidenceCard>}
      <div className="flex justify-end gap-3"><Button type="button" variant="secondary" disabled={create.isPending} onClick={() => navigate(ROUTE_PATHS.INTEGRATIONS)}>Cancel</Button><Button type="submit" disabled={create.isPending || !connector || !schema.data}>{create.isPending ? 'Creating and queuing test…' : 'Create & test connection'}</Button></div></form>
  </main>;
}

// eslint-disable-next-line complexity
export function IntegrationDetailPage() {
  const id = requiredRouteId('Integration', useParams().id); const navigate = useNavigate(); const canManage = useCanManageIntegrations(); const queryClient = useQueryClient(); const [evidence, setEvidence] = useState<{ title: string; correlation?: string } | null>(null);
  const integration = useQuery({ queryKey: ['integration-platform', 'integration', id], queryFn: () => service.getIntegration(id), refetchInterval: (query) => query.state.data?.status === 'testing' ? 2500 : false });
  const credentials = useQuery({ queryKey: ['integration-platform', 'credentials', id], queryFn: () => service.listCredentials(id) });
  const mappings = useQuery({ queryKey: ['integration-platform', 'mappings', id], queryFn: () => service.listMappings({ integration_id: id, page_size: 100 }) });
  const refresh = async () => { await queryClient.invalidateQueries({ queryKey: ['integration-platform'] }); };
  const action = useMutation({ mutationFn: async (kind: 'test' | 'sync' | 'activate' | 'deactivate' | 'delete') => { if (kind === 'test') return service.testIntegration(id, { idempotency_key: newOperationKey('test') }); if (kind === 'sync') return service.syncIntegration(id, { direction: 'pull', mapping_ids: mappings.data?.items.map((item) => item.id) ?? [], idempotency_key: newOperationKey('sync') }); if (kind === 'activate') return service.activateIntegration(id, { transition_key: newOperationKey('activate') }); if (kind === 'deactivate') return service.deactivateIntegration(id, { transition_key: newOperationKey('deactivate') }); await service.deleteIntegration(id); return null; }, onSuccess: (result, kind) => { if (kind === 'delete') { toast.success('Integration deleted with audit evidence.'); navigate(ROUTE_PATHS.INTEGRATIONS); return; } const correlation = result && 'correlation_id' in result ? result.correlation_id : undefined; setEvidence({ title: kind === 'test' || kind === 'sync' ? `${kind} job accepted` : `Integration ${kind}d`, correlation }); toast.success(`Integration ${kind} accepted.`, { description: correlation ? `Correlation ${correlation}` : undefined }); void refresh(); }, onError: (failure: Error) => toast.error(failure.message) });
  if (integration.isLoading) return <PageSkeleton label="Loading integration evidence" />;
  if (integration.error || !integration.data) return <main className="p-4 sm:p-8"><GovernedError error={integration.error} retry={() => { void integration.refetch(); }} /></main>;
  const item = integration.data;
  const remove = () => { if (item.status !== 'inactive') { toast.error('Deactivate the integration before deleting it.'); return; } const confirmation = window.prompt(`Type ${item.name} to confirm deletion.`); if (confirmation === item.name) action.mutate('delete'); };
  return <main className="space-y-6 p-4 sm:p-8"><PageHeader title={item.name} description={item.description || `${item.connector_name} integration`} backTo={{ label: 'Integrations', path: ROUTE_PATHS.INTEGRATIONS }} actions={canManage ? <><Button variant="secondary" onClick={() => navigate(ROUTE_PATHS.INTEGRATION_EDIT(id))}><Edit3 className="mr-2 h-4 w-4" />Edit</Button><Button disabled={action.isPending} onClick={() => action.mutate('test')}><Activity className="mr-2 h-4 w-4" />Test</Button><Button disabled={action.isPending || item.status !== 'active'} onClick={() => action.mutate('sync')}><RefreshCw className="mr-2 h-4 w-4" />Sync</Button>{item.status === 'active' ? <Button disabled={action.isPending} variant="secondary" onClick={() => action.mutate('deactivate')}>Deactivate</Button> : <Button disabled={action.isPending || item.status === 'testing'} variant="secondary" onClick={() => action.mutate('activate')}>Activate</Button>}<Button disabled={action.isPending || item.status !== 'inactive'} variant="danger" onClick={remove}><Trash2 className="mr-2 h-4 w-4" />Delete</Button></> : undefined} />
    <BackgroundRefresh active={integration.isFetching && !integration.isLoading} />{evidence && <SuccessEvidence title={evidence.title} correlationId={evidence.correlation} />}
    <EvidenceCard title="Overview"><DefinitionGrid><Definition label="Status"><StatusBadge status={item.status} /></Definition><Definition label="Connector">{item.connector_name}</Definition><Definition label="Type">{item.integration_type}</Definition><Definition label="Last tested">{formatDate(item.last_tested_at)}</Definition><Definition label="Credentials">{item.credentials_count}</Definition><Definition label="Mappings">{item.mappings_count}</Definition></DefinitionGrid>{item.last_error_message && <p className="mt-4 rounded-md bg-destructive/10 p-3 text-sm text-destructive">{item.last_error_code}: {item.last_error_message}</p>}</EvidenceCard>
    <div className="grid gap-6 lg:grid-cols-2"><EvidenceCard title="Credential metadata"><div className="mb-4 flex justify-end"><Button size="sm" variant="secondary" onClick={() => navigate(ROUTE_PATHS.INTEGRATION_CREDENTIALS(id))}><KeyRound className="mr-2 h-4 w-4" />Manage credentials</Button></div>{credentials.isLoading ? <p role="status">Loading credential metadata…</p> : credentials.data?.length ? <ul className="space-y-2">{credentials.data.map((credential) => <li className="flex items-center justify-between rounded-lg border p-3" key={credential.id}><span>{credential.credential_type.replaceAll('_', ' ')} · {credential.display_hint || 'redacted'}</span><StatusBadge status={credential.status} /></li>)}</ul> : <p className="text-sm text-muted-foreground">No credential metadata. Secret values are never readable.</p>}</EvidenceCard><EvidenceCard title="Data mappings"><div className="mb-4 flex justify-end"><Button size="sm" variant="secondary" onClick={() => navigate(`${ROUTE_PATHS.MAPPING_CREATE}?integration=${id}`)}>Add mapping</Button></div>{mappings.isLoading ? <p role="status">Loading mappings…</p> : mappings.data?.items.length ? <ul className="space-y-2">{mappings.data.items.map((mapping) => <li key={mapping.id}><Link className="block rounded-lg border p-3 hover:bg-muted/30" to={ROUTE_PATHS.MAPPING_DETAIL(mapping.id)}>{mapping.source_field} → {mapping.target_field}<span className="float-right text-xs">{mapping.transform.operation}</span></Link></li>)}</ul> : <p className="text-sm text-muted-foreground">No mappings configured.</p>}</EvidenceCard></div>
    <EvidenceCard title="Durable job evidence"><div className="grid gap-4 md:grid-cols-2">{item.latest_test_evidence ? <DefinitionGrid><Definition label="Test outcome"><StatusBadge status={item.latest_test_evidence.outcome} /></Definition><Definition label="Correlation ID"><span className="font-mono text-xs">{item.latest_test_evidence.correlation_id}</span></Definition><Definition label="Duration">{item.latest_test_evidence.duration_ms ?? '—'} ms</Definition></DefinitionGrid> : <p className="text-sm text-muted-foreground">No completed test evidence.</p>}{item.latest_sync_evidence ? <DefinitionGrid><Definition label="Sync outcome"><StatusBadge status={item.latest_sync_evidence.outcome} /></Definition><Definition label="Correlation ID"><span className="font-mono text-xs">{item.latest_sync_evidence.correlation_id}</span></Definition><Definition label="Verified records">{item.latest_sync_evidence.records_written ?? 0}</Definition></DefinitionGrid> : <p className="text-sm text-muted-foreground">No completed sync evidence.</p>}</div></EvidenceCard>
    <EvidenceCard title="Configuration (non-secret)"><pre className="overflow-auto rounded-lg bg-muted/40 p-4 text-xs">{JSON.stringify(item.config, null, 2)}</pre></EvidenceCard>
  </main>;
}

export function EditIntegrationPage() {
  const id = requiredRouteId('Integration', useParams().id); const navigate = useNavigate(); const [config, setConfig] = useState<JsonObject>({}); const [dirty, setDirty] = useState(false); const integration = useQuery({ queryKey: ['integration-platform', 'integration', id], queryFn: () => service.getIntegration(id) }); const schema = useQuery({ queryKey: ['integration-platform', 'connector-schema-edit', integration.data?.connector_id], queryFn: () => service.getConnectorSchema(integration.data?.connector_id ?? ''), enabled: Boolean(integration.data?.connector_id) });
  useEffect(() => { if (integration.data) setConfig(integration.data.config); }, [integration.data]); useEffect(() => { const prevent = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; window.addEventListener('beforeunload', prevent); return () => window.removeEventListener('beforeunload', prevent); }, [dirty]);
  const update = useMutation({ mutationFn: (form: FormData) => service.updateIntegration(id, { name: formText(form, 'name'), description: formText(form, 'description'), config }), onSuccess: () => { setDirty(false); toast.success('Integration configuration updated.'); navigate(ROUTE_PATHS.INTEGRATION_DETAIL(id)); }, onError: (failure: Error) => toast.error(failure.message) });
  if (integration.isLoading || schema.isLoading) return <PageSkeleton label="Loading integration editor" />; if (integration.error || !integration.data) return <main className="p-4 sm:p-8"><GovernedError error={integration.error} retry={() => { void integration.refetch(); }} /></main>; if (schema.error || !schema.data) return <main className="p-4 sm:p-8"><GovernedError error={schema.error} retry={() => { void schema.refetch(); }} /></main>;
  return <main className="space-y-6 p-4 sm:p-8"><PageHeader title={`Edit ${integration.data.name}`} description="Schema-aware, non-secret configuration. Unsaved changes are protected." backTo={{ label: integration.data.name, path: ROUTE_PATHS.INTEGRATION_DETAIL(id) }} /><form className="space-y-6" aria-busy={update.isPending} onChange={() => setDirty(true)} onSubmit={(event) => { event.preventDefault(); const parsed = jsonObjectSchema.safeParse(config); if (!parsed.success) { toast.error('Configuration is not valid JSON data.'); return; } update.mutate(new FormData(event.currentTarget)); }}><EvidenceCard title="Identity"><div className="grid gap-4 md:grid-cols-2"><Input name="name" label="Name" defaultValue={integration.data.name} required /><Textarea name="description" label="Description" defaultValue={integration.data.description} /></div></EvidenceCard><EvidenceCard title="Connector configuration"><SchemaFields schema={schema.data.config_schema} values={config} disabled={update.isPending} onChange={(value) => { setConfig(value); setDirty(true); }} /></EvidenceCard><div className="flex justify-end gap-3"><Button type="button" variant="secondary" disabled={update.isPending} onClick={() => { if (!dirty || window.confirm('Discard unsaved changes?')) navigate(ROUTE_PATHS.INTEGRATION_DETAIL(id)); }}>Cancel</Button><Button type="submit" disabled={update.isPending}>{update.isPending ? 'Saving…' : 'Save changes'}</Button></div></form></main>;
}

export function CredentialMetadataPage() {
  const integrationId = requiredRouteId('Integration', useParams().id); const navigate = useNavigate(); const query = useQuery({ queryKey: ['integration-platform', 'credentials', integrationId], queryFn: () => service.listCredentials(integrationId) }); const revoke = useMutation({ mutationFn: (credentialId: string) => service.revokeCredential(credentialId, { transition_key: newOperationKey('revoke') }), onSuccess: (credential) => { toast.success('Credential revoked.', { description: `Version ${credential.version}; ciphertext remained server-side.` }); void query.refetch(); }, onError: (failure: Error) => toast.error(failure.message) });
  if (query.isLoading) return <PageSkeleton label="Loading credential metadata" />; if (query.error || !query.data) return <main className="p-4 sm:p-8"><GovernedError error={query.error} retry={() => { void query.refetch(); }} /></main>;
  return <main className="space-y-6 p-4 sm:p-8"><PageHeader title="Credential metadata" description="Secret plaintext and ciphertext are write-only and never exposed here." backTo={{ label: 'Integration', path: ROUTE_PATHS.INTEGRATION_DETAIL(integrationId) }} actions={<Button onClick={() => navigate(ROUTE_PATHS.CREDENTIAL_CREATE(integrationId))}><Plus className="mr-2 h-4 w-4" />Add credential</Button>} />{query.data.length === 0 ? <EmptyPanel filtered={false} title="credentials" description="Add a credential if the connector requires one." action={<Button onClick={() => navigate(ROUTE_PATHS.CREDENTIAL_CREATE(integrationId))}>Add credential</Button>} /> : <Card className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b bg-muted/50"><tr><th className="p-4">Type</th><th className="p-4">Hint</th><th className="p-4">Version</th><th className="p-4">Status</th><th className="p-4">Expires</th><th className="p-4">Actions</th></tr></thead><tbody>{query.data.map((credential) => <tr key={credential.id} className="border-b"><td className="p-4">{credential.credential_type.replaceAll('_', ' ')}</td><td className="p-4">{credential.display_hint || 'redacted'}</td><td className="p-4">{credential.version}</td><td className="p-4"><StatusBadge status={credential.status} /></td><td className="p-4">{formatDate(credential.expires_at)}</td><td className="p-4"><div className="flex gap-2"><Button size="sm" variant="secondary" disabled={credential.status !== 'active'} onClick={() => navigate(ROUTE_PATHS.CREDENTIAL_ROTATE(integrationId, credential.id))}>Rotate</Button><Button size="sm" variant="danger" disabled={credential.status !== 'active' || revoke.isPending} onClick={() => revoke.mutate(credential.id)}>Revoke</Button></div></td></tr>)}</tbody></table></Card>}</main>;
}

function CredentialForm({ rotate }: { rotate: boolean }) {
  const integrationId = requiredRouteId('Integration', useParams().id); const credentialId = useParams().credentialId; const navigate = useNavigate(); const credential = useQuery({ queryKey: ['integration-platform', 'credential', credentialId], queryFn: () => service.getCredential(credentialId ?? ''), enabled: rotate && Boolean(credentialId) });
  const mutation = useMutation({ mutationFn: (form: FormData) => { const request = { credential_type: formText(form, 'credential_type') as CredentialType, plaintext: formText(form, 'plaintext'), expires_at: formText(form, 'expires_at') || null }; const parsed = credentialCreateSchema.safeParse(request); if (!parsed.success) throw new Error(parsed.error.issues[0]?.message ?? 'Invalid credential.'); return rotate ? service.rotateCredential(requiredRouteId('Credential', credentialId), { plaintext: request.plaintext, expires_at: request.expires_at, idempotency_key: newOperationKey('rotate') }) : service.createCredential(integrationId, request); }, onSuccess: (result) => { toast.success(rotate ? 'Credential rotated atomically.' : 'Credential encrypted and stored.', { description: `Metadata only: version ${result.version}.` }); navigate(ROUTE_PATHS.INTEGRATION_CREDENTIALS(integrationId)); }, onError: (failure: Error) => toast.error(failure.message) });
  if (rotate && credential.isLoading) return <PageSkeleton label="Loading credential rotation" />; if (credential.error) return <main className="p-4 sm:p-8"><GovernedError error={credential.error} retry={() => { void credential.refetch(); }} /></main>;
  return <main className="space-y-6 p-4 sm:p-8"><PageHeader title={rotate ? 'Rotate credential' : 'Add credential'} description={rotate ? 'The active version is revoked atomically only when the new encrypted version is created.' : 'The value is write-only and encrypted by the server.'} backTo={{ label: 'Credential metadata', path: ROUTE_PATHS.INTEGRATION_CREDENTIALS(integrationId) }} /><form className="space-y-6" aria-busy={mutation.isPending} onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); mutation.mutate(new FormData(event.currentTarget)); }}><Card className="grid gap-5 p-6 md:grid-cols-2"><label className="text-sm font-medium" htmlFor="credential-form-type">Credential type<select id="credential-form-type" name="credential_type" disabled={rotate} defaultValue={credential.data?.credential_type ?? 'api_key'} className="mt-1 block w-full rounded-md border bg-background px-3 py-2"><option value="api_key">API key</option><option value="oauth_token">OAuth token</option><option value="username_password">Username/password</option><option value="certificate">Certificate</option></select></label><Input id="credential-expiry" name="expires_at" label="Expires at (optional)" type="datetime-local" /><div className="md:col-span-2"><Textarea id="credential-value" name="plaintext" label="New credential value" required autoComplete="new-password" /><p className="mt-2 text-xs text-muted-foreground">This field is never prefilled and cannot be recovered after submission.</p></div></Card><div className="flex justify-end gap-3"><Button type="button" variant="secondary" onClick={() => navigate(ROUTE_PATHS.INTEGRATION_CREDENTIALS(integrationId))}>Cancel</Button><Button type="submit" disabled={mutation.isPending}>{mutation.isPending ? 'Encrypting…' : rotate ? 'Rotate credential' : 'Create credential'}</Button></div></form></main>;
}
export function CreateCredentialPage() { return <CredentialForm rotate={false} />; }
export function RotateCredentialPage() { return <CredentialForm rotate />; }
