import { keepPreviousData, useMutation, useQuery } from '@tanstack/react-query';
import { ArrowRight, CheckCircle2, Edit3, Plus, Search, Trash2, WandSparkles } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { toast } from 'sonner';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { Input } from '@/components/ui/Input';
import { Textarea } from '@/components/ui/Textarea';
import type { DataMappingCreateRequest, MappingFilters, MappingPreviewResult, TransformationOperation } from '../contracts';
import { ROUTE_PATHS } from '../contracts';
import { BackgroundRefresh, Definition, DefinitionGrid, EmptyPanel, EvidenceCard, GovernedError, PageHeader, PageSkeleton, Pagination, RedactedJsonViewer, SuccessEvidence, useCanManageIntegrations } from '../components/IntegrationPlatformUI';
import { jsonObjectSchema, jsonValueSchema, mappingSchema } from '../schemas/integration-platform-schemas';
import { integrationPlatformService as service } from '../services/integration-platform-service';

function positive(value: string | null): number { const parsed = Number(value ?? '1'); return Number.isInteger(parsed) && parsed > 0 ? parsed : 1; }
function formText(form: FormData, name: string): string { const value = form.get(name); return typeof value === 'string' ? value.trim() : ''; }
function requiredId(value?: string): string { if (!value) throw new Error('Mapping route requires an identifier.'); return value; }
function sampleRecord(raw: string) { return jsonObjectSchema.parse(JSON.parse(raw || '{}')); }

// eslint-disable-next-line complexity
export function MappingListPage() {
  const [params, setParams] = useSearchParams(); const canManage = useCanManageIntegrations(); const filters: MappingFilters = { page: positive(params.get('page')), page_size: 25, search: params.get('search') ?? undefined, integration_id: params.get('integration') ?? undefined, source_field: params.get('source') ?? undefined, target_field: params.get('target') ?? undefined }; const query = useQuery({ queryKey: ['integration-platform', 'mappings', params.toString()], queryFn: () => service.listMappings(filters), placeholderData: keepPreviousData }); const update = (key: string, value: string) => { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); if (key !== 'page') next.set('page', '1'); setParams(next); };
  if (query.isLoading) return <PageSkeleton label="Loading data mappings" />; if (query.error || !query.data) return <main className="p-4 sm:p-8"><GovernedError error={query.error} retry={() => { void query.refetch(); }} /></main>;
  return <main className="space-y-6 p-4 sm:p-8"><PageHeader title="Data Mappings" description="Deterministic source-to-target transforms with a bounded DSL and verified previews." actions={canManage ? <Link to={ROUTE_PATHS.MAPPING_CREATE}><Button><Plus className="mr-2 h-4 w-4" />New mapping</Button></Link> : undefined} /><BackgroundRefresh active={query.isFetching && !query.isLoading} /><Card className="p-4"><form role="search" className="grid gap-3 md:grid-cols-5" onSubmit={(event) => { event.preventDefault(); update('search', formText(new FormData(event.currentTarget), 'search')); }}><Input name="search" aria-label="Search mappings" defaultValue={params.get('search') ?? ''} placeholder="Search mappings…" /><Input aria-label="Filter integration ID" value={params.get('integration') ?? ''} onChange={(event) => update('integration', event.target.value)} placeholder="Integration ID" /><Input aria-label="Filter source field" value={params.get('source') ?? ''} onChange={(event) => update('source', event.target.value)} placeholder="Source field" /><Input aria-label="Filter target field" value={params.get('target') ?? ''} onChange={(event) => update('target', event.target.value)} placeholder="Target field" /><Button type="submit" variant="secondary"><Search className="mr-2 h-4 w-4" />Search</Button></form></Card>{query.data.items.length === 0 ? <EmptyPanel filtered={params.toString().length > 0} title="mappings" description="Create a visual field mapping. Executable code is deliberately unsupported." reset={() => setParams(new URLSearchParams())} action={canManage ? <Link to={ROUTE_PATHS.MAPPING_CREATE}><Button>Create mapping</Button></Link> : undefined} /> : <Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b bg-muted/50"><tr><th className="p-4">Mapping</th><th className="p-4">Integration</th><th className="p-4">Field path</th><th className="p-4">Transformation</th><th className="p-4">Position</th></tr></thead><tbody>{query.data.items.map((mapping) => <tr className="border-b" key={mapping.id}><td className="p-4"><Link className="font-semibold text-primary" to={ROUTE_PATHS.MAPPING_DETAIL(mapping.id)}>{mapping.name}</Link></td><td className="p-4">{mapping.integration_name}</td><td className="p-4"><span className="inline-flex items-center gap-2"><code>{mapping.source_field}</code><ArrowRight className="h-4 w-4" /><code>{mapping.target_field}</code></span></td><td className="p-4">{mapping.transform.operation.replaceAll('_', ' ')}</td><td className="p-4">{mapping.position}</td></tr>)}</tbody></table></div><Pagination meta={query.data.meta} changePage={(page) => update('page', String(page))} /></Card>}</main>;
}

// Mapping validation intentionally coordinates local schema, governed validation, persistence, and preview.
// eslint-disable-next-line complexity
function MappingForm({ edit }: { edit: boolean }) {
  const id = useParams().id; const navigate = useNavigate(); const [preview, setPreview] = useState<MappingPreviewResult | null>(null); const [validated, setValidated] = useState(false); const existing = useQuery({ queryKey: ['integration-platform', 'mapping-edit', id], queryFn: () => service.getMapping(id ?? ''), enabled: edit && Boolean(id) }); const queryIntegration = new URLSearchParams(window.location.search).get('integration') ?? '';
  const mutation = useMutation({ mutationFn: async (form: FormData) => {
    const integrationId = formText(form, 'integration_id'); const operation = formText(form, 'operation') as TransformationOperation;
    const optionsValue = jsonObjectSchema.parse(JSON.parse(formText(form, 'options') || '{}')); const defaultRaw = formText(form, 'default_value');
    const request: DataMappingCreateRequest = { integration_id: integrationId, name: formText(form, 'name'), source_field: formText(form, 'source_field'), target_field: formText(form, 'target_field'), transform: { operation, options: optionsValue }, position: Number(formText(form, 'position') || '0'), is_required: form.get('is_required') === 'on', default_value: defaultRaw ? jsonValueSchema.parse(JSON.parse(defaultRaw)) : null };
    const parsed = mappingSchema.safeParse(request); if (!parsed.success) throw new Error(parsed.error.issues[0]?.message ?? 'Mapping is invalid.');
    const schemaProperty = { type: 'string' as const }; const validation = await service.validateMappings({ integration_id: integrationId, mappings: [request], source_schema: { type: 'object', properties: { [request.source_field]: schemaProperty }, required: request.is_required ? [request.source_field] : [] }, target_schema: { type: 'object', properties: { [request.target_field]: schemaProperty } } });
    if (!validation.valid) throw new Error(validation.errors[0]?.message ?? 'Server validation rejected this mapping.'); setValidated(true);
    const saved = edit ? await service.updateMapping(requiredId(id), request) : await service.createMapping(request);
    const result = await service.previewMappings({ integration_id: integrationId, mapping_ids: [saved.id], sample: sampleRecord(formText(form, 'sample')) }); return { saved, result };
  }, onSuccess: ({ saved, result }) => { setPreview(result); toast.success('Mapping saved and validated.'); if (result.records.length === 0) window.setTimeout(() => navigate(ROUTE_PATHS.MAPPING_DETAIL(saved.id)), 400); }, onError: (failure: Error) => toast.error(failure.message) });
  const loaded = existing.data; if (edit && existing.isLoading) return <PageSkeleton label="Loading mapping editor" />; if (existing.error) return <main className="p-4 sm:p-8"><GovernedError error={existing.error} retry={() => { void existing.refetch(); }} /></main>;
  return <main className="space-y-6 p-4 sm:p-8"><PageHeader title={edit ? `Edit ${loaded?.name ?? 'mapping'}` : 'Create data mapping'} description="Map fields visually using registered deterministic transformations. No executable code editor is provided." backTo={{ label: 'Data Mappings', path: ROUTE_PATHS.MAPPINGS }} />{validated && <SuccessEvidence title="Server-side field validation passed" />}{preview && <EvidenceCard title="Sample preview"><div className="grid gap-6 lg:grid-cols-2"><RedactedJsonViewer label="Transformed records" value={preview.records} /><div><h3 className="font-medium">Per-field failures</h3>{preview.failures.length === 0 ? <p className="mt-3 flex items-center gap-2 text-sm text-emerald-700"><CheckCircle2 className="h-4 w-4" />No transformation failures.</p> : <ul className="mt-3 space-y-2">{preview.failures.map((failure) => <li className="rounded-lg border border-destructive/30 p-3 text-sm" key={`${failure.record_index}-${failure.mapping_id}`}>Record {failure.record_index}, {failure.source_field} → {failure.target_field}: {failure.message}</li>)}</ul>}</div></div><div className="mt-4 flex justify-end"><Button onClick={() => navigate(ROUTE_PATHS.MAPPING_DETAIL(mutation.data?.saved.id ?? ''))}>Continue to mapping</Button></div></EvidenceCard>}
    <form className="space-y-6" aria-busy={mutation.isPending} onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); mutation.mutate(new FormData(event.currentTarget)); }}><EvidenceCard title="Source → target"><div className="grid items-end gap-4 md:grid-cols-[1fr_auto_1fr]"><div className="space-y-4"><Input name="integration_id" label="Integration ID" required defaultValue={loaded?.integration_id ?? queryIntegration} /><Input name="source_field" label="Source field" required defaultValue={loaded?.source_field} /></div><ArrowRight className="mb-3 hidden h-6 w-6 text-muted-foreground md:block" /><div className="space-y-4"><Input name="name" label="Mapping name" required defaultValue={loaded?.name} /><Input name="target_field" label="Target field" required defaultValue={loaded?.target_field} /></div></div></EvidenceCard><EvidenceCard title="Registered transformation"><div className="grid gap-5 md:grid-cols-2"><label className="text-sm font-medium" htmlFor="mapping-operation">Operation<select id="mapping-operation" name="operation" defaultValue={loaded?.transform.operation ?? 'rename'} className="mt-1 block w-full rounded-md border bg-background px-3 py-2">{['rename', 'string_case', 'trim', 'number', 'date_format', 'default', 'enum_map'].map((operation) => <option key={operation}>{operation}</option>)}</select></label><Input name="position" label="Position" type="number" min={0} defaultValue={loaded?.position ?? 0} /><div className="md:col-span-2"><Textarea name="options" label="Operation options (JSON)" defaultValue={JSON.stringify(loaded?.transform.options ?? {}, null, 2)} rows={5} /></div><Input name="default_value" label="Default value (JSON, optional)" defaultValue={loaded?.default_value === null ? '' : JSON.stringify(loaded?.default_value)} /><label className="flex items-center gap-3 self-end rounded-lg border p-3 text-sm"><input name="is_required" type="checkbox" defaultChecked={loaded?.is_required} />Source field is required</label></div></EvidenceCard><EvidenceCard title="Sample-data preview"><Textarea name="sample" label="Sample record (JSON object)" rows={8} defaultValue={'{\n  "source_field": "sample"\n}'} /><p className="mt-2 text-xs text-muted-foreground">Preview is deterministic and side-effect-free. Samples are submitted to the governed preview endpoint, not executed as code.</p></EvidenceCard><div className="flex justify-end gap-3"><Button type="button" variant="secondary" onClick={() => navigate(edit && id ? ROUTE_PATHS.MAPPING_DETAIL(id) : ROUTE_PATHS.MAPPINGS)}>Cancel</Button><Button type="submit" disabled={mutation.isPending}><WandSparkles className="mr-2 h-4 w-4" />{mutation.isPending ? 'Validating and previewing…' : 'Validate, save & preview'}</Button></div></form>
  </main>;
}
export function CreateMappingPage() { return <MappingForm edit={false} />; }
export function EditMappingPage() { return <MappingForm edit />; }

export function MappingDetailPage() {
  const id = requiredId(useParams().id); const navigate = useNavigate(); const canManage = useCanManageIntegrations(); const [sample, setSample] = useState('{"source_field":"sample"}'); const query = useQuery({ queryKey: ['integration-platform', 'mapping', id], queryFn: () => service.getMapping(id) }); const preview = useMutation({ mutationFn: () => { if (!query.data) throw new Error('Mapping is unavailable.'); return service.previewMappings({ integration_id: query.data.integration_id, mapping_ids: [id], sample: sampleRecord(sample) }); }, onError: (failure: Error) => toast.error(failure.message) }); const remove = useMutation({ mutationFn: () => service.deleteMapping(id), onSuccess: () => { toast.success('Mapping deleted.'); navigate(ROUTE_PATHS.MAPPINGS); }, onError: (failure: Error) => toast.error(failure.message) });
  if (query.isLoading) return <PageSkeleton label="Loading mapping details" />; if (query.error || !query.data) return <main className="p-4 sm:p-8"><GovernedError error={query.error} retry={() => { void query.refetch(); }} /></main>; const mapping = query.data;
  return <main className="space-y-6 p-4 sm:p-8"><PageHeader title={mapping.name} description={`${mapping.source_field} → ${mapping.target_field}`} backTo={{ label: 'Data Mappings', path: ROUTE_PATHS.MAPPINGS }} actions={canManage ? <><Button variant="secondary" onClick={() => navigate(ROUTE_PATHS.MAPPING_EDIT(id))}><Edit3 className="mr-2 h-4 w-4" />Edit</Button><Button variant="danger" disabled={remove.isPending} onClick={() => remove.mutate()}><Trash2 className="mr-2 h-4 w-4" />Delete</Button></> : undefined} /><EvidenceCard title="Field mapping"><div className="grid items-center gap-4 text-center sm:grid-cols-[1fr_auto_1fr]"><Card className="p-6"><p className="text-xs uppercase text-muted-foreground">Source</p><code className="mt-2 block text-lg">{mapping.source_field}</code></Card><ArrowRight className="mx-auto h-8 w-8 text-primary" /><Card className="p-6"><p className="text-xs uppercase text-muted-foreground">Target</p><code className="mt-2 block text-lg">{mapping.target_field}</code></Card></div><DefinitionGrid><Definition label="Integration">{mapping.integration_name}</Definition><Definition label="Operation">{mapping.transform.operation}</Definition><Definition label="Position">{mapping.position}</Definition><Definition label="Required">{mapping.is_required ? 'Yes' : 'No'}</Definition><Definition label="Default">{JSON.stringify(mapping.default_value)}</Definition></DefinitionGrid></EvidenceCard><EvidenceCard title="Deterministic preview"><Textarea aria-label="Sample record" value={sample} onChange={(event) => setSample(event.target.value)} rows={6} /><Button className="mt-3" disabled={preview.isPending} onClick={() => preview.mutate()}><WandSparkles className="mr-2 h-4 w-4" />{preview.isPending ? 'Previewing…' : 'Run preview'}</Button>{preview.data && <div className="mt-5 grid gap-6 lg:grid-cols-2"><RedactedJsonViewer label="Transformed records" value={preview.data.records} /><div><h3 className="font-medium">Per-field validation</h3>{preview.data.failures.length === 0 ? <p className="mt-3 text-sm text-emerald-700">All sample fields transformed successfully.</p> : <ul className="mt-3 space-y-2">{preview.data.failures.map((failure) => <li key={`${failure.record_index}-${failure.mapping_id}`} className="rounded-lg border p-3 text-sm">Record {failure.record_index}, {failure.source_field} → {failure.target_field}: {failure.message}</li>)}</ul>}</div></div>}</EvidenceCard></main>;
}
