import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Check, Clipboard, Plus, RadioTower } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';
import { Input } from '@/components/ui/Input';
import { performanceMonitoringService } from '../services/performance-monitoring-service';
import type { TelemetrySourceCreate } from '../contracts';
import { EmptyTelemetry, MonitoringPage, OperationalError, PageSkeleton, StatusPill, formatNumber, formatTime } from '../components/MonitoringPage';

const initialSource: TelemetrySourceCreate = { name: '', source_type: 'otlp', sampling_rate: 1, retention_days: 30, daily_event_quota: 1_000_000, redaction_fields: ['authorization', 'cookie', 'set-cookie'] };

export function InstrumentationSetupPage() {
  const client = useQueryClient();
  const [showCreate, setShowCreate] = useState(false);
  const [draft, setDraft] = useState<TelemetrySourceCreate>(initialSource);
  const sources = useQuery({ queryKey: ['performance-monitoring', 'sources'], queryFn: () => performanceMonitoringService.listTelemetrySources({ page_size: 100, ordering: 'name' }) });
  const create = useMutation({ mutationFn: (payload: TelemetrySourceCreate) => performanceMonitoringService.createTelemetrySource(payload), onSuccess: () => { toast.success('Telemetry source registered'); setDraft(initialSource); setShowCreate(false); void client.invalidateQueries({ queryKey: ['performance-monitoring', 'sources'] }); }, onError: () => toast.error('Telemetry source could not be registered') });
  return <MonitoringPage title="Instrumentation setup" description="Register governed telemetry sources, apply redaction and connect OpenTelemetry-compatible workloads." actions={<Button onClick={() => setShowCreate((value) => !value)}><Plus className="mr-2 h-4 w-4" />Register source</Button>}>
    {showCreate ? <SourceForm draft={draft} setDraft={setDraft} pending={create.isPending} onCancel={() => setShowCreate(false)} onSubmit={() => create.mutate(draft)} /> : null}
    {sources.isPending ? <PageSkeleton /> : sources.isError ? <OperationalError error={sources.error} onRetry={() => { void sources.refetch(); }} /> : <div className="grid gap-6 xl:grid-cols-[1.1fr_1fr]">
      <Card><CardHeader><CardTitle className="text-lg">Connected sources</CardTitle></CardHeader><CardContent className="space-y-3">{sources.data.items.length === 0 ? <EmptyTelemetry title="No telemetry sources" description="Register a source before configuring an SDK or collector. Credentials are resolved by approved secret storage and are never shown here." action={<Button onClick={() => setShowCreate(true)}>Register first source</Button>} /> : sources.data.items.map((source) => <div key={source.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-medium text-foreground">{source.name}</h2><p className="mt-1 text-xs uppercase tracking-wide text-muted-foreground">{source.source_type}</p></div><StatusPill status={source.status} /></div><dl className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-muted-foreground">Last seen</dt><dd className="mt-1 font-medium">{formatTime(source.last_seen_at)}</dd></div><div><dt className="text-muted-foreground">Sampling</dt><dd className="mt-1 font-medium">{formatNumber(source.sampling_rate, { style: 'percent', maximumFractionDigits: 1 })}</dd></div><div><dt className="text-muted-foreground">State</dt><dd className="mt-1 font-medium">{source.is_active ? 'Enabled' : 'Disabled'}</dd></div><div><dt className="text-muted-foreground">Registered</dt><dd className="mt-1 font-medium">{formatTime(source.created_at)}</dd></div></dl></div>)}</CardContent></Card>
      <QuickStart />
    </div>}
  </MonitoringPage>;
}

function SourceForm({ draft, setDraft, pending, onCancel, onSubmit }: { draft: TelemetrySourceCreate; setDraft: (draft: TelemetrySourceCreate) => void; pending: boolean; onCancel: () => void; onSubmit: () => void }) {
  const valid = Boolean(draft.name.trim() && (draft.sampling_rate ?? 0) > 0 && (draft.sampling_rate ?? 0) <= 1);
  return <Card><CardHeader><CardTitle className="text-lg">Register telemetry source</CardTitle></CardHeader><CardContent><form className="grid gap-4 md:grid-cols-4" onSubmit={(event) => { event.preventDefault(); if (valid) onSubmit(); }}><label className="text-sm font-medium md:col-span-2">Source name<Input className="mt-1" value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} placeholder="Production OTLP collector" /></label><label className="text-sm font-medium">Source type<select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={draft.source_type} onChange={(event) => setDraft({ ...draft, source_type: event.target.value as TelemetrySourceCreate['source_type'] })}>{['otlp', 'prometheus', 'application', 'webhook', 'import'].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-sm font-medium">Sampling rate<Input className="mt-1" type="number" min="0.0001" max="1" step="0.01" value={draft.sampling_rate} onChange={(event) => setDraft({ ...draft, sampling_rate: Number(event.target.value) })} /></label><label className="text-sm font-medium">Retention days<Input className="mt-1" type="number" min="1" value={draft.retention_days} onChange={(event) => setDraft({ ...draft, retention_days: Number(event.target.value) })} /></label><label className="text-sm font-medium">Daily event quota<Input className="mt-1" type="number" min="1" value={draft.daily_event_quota} onChange={(event) => setDraft({ ...draft, daily_event_quota: Number(event.target.value) })} /></label><label className="text-sm font-medium md:col-span-2">Redacted attributes<Input className="mt-1" value={draft.redaction_fields?.join(', ')} onChange={(event) => setDraft({ ...draft, redaction_fields: event.target.value.split(',').map((item) => item.trim()).filter(Boolean) })} /><span className="mt-1 block text-xs font-normal text-muted-foreground">Comma-separated attribute names removed during ingestion.</span></label><div className="flex gap-2 md:col-span-4"><Button type="submit" disabled={!valid || pending}>{pending ? 'Registering…' : 'Register source'}</Button><Button type="button" variant="outline" onClick={onCancel}>Cancel</Button></div></form></CardContent></Card>;
}

function QuickStart() {
  const [copied, setCopied] = useState(false);
  const snippet = `# Use your deployment's governed OTLP endpoint\nOTEL_SERVICE_NAME=your-service\nOTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf\nOTEL_RESOURCE_ATTRIBUTES=deployment.environment.name=production`;
  const copy = async () => { try { await navigator.clipboard.writeText(snippet); setCopied(true); setTimeout(() => setCopied(false), 2000); } catch { toast.error('Clipboard access is unavailable'); } };
  return <Card><CardHeader><div className="flex items-center gap-3"><span className="rounded-lg bg-primary/10 p-2"><RadioTower className="h-5 w-5 text-primary" /></span><div><CardTitle className="text-lg">OpenTelemetry quick start</CardTitle><p className="mt-1 text-sm text-muted-foreground">Vendor-neutral setup for applications and collectors.</p></div></div></CardHeader><CardContent className="space-y-4"><ol className="list-decimal space-y-2 pl-5 text-sm text-muted-foreground"><li>Register the telemetry source and retain its generated identifier.</li><li>Resolve the tenant's OTLP endpoint and credentials through deployment secret management.</li><li>Configure resource attributes for service and environment identity.</li><li>Send a test span, metric and log; source status changes only after verified ingestion.</li></ol><div className="relative"><pre className="overflow-x-auto rounded-xl bg-slate-950 p-4 pr-14 text-xs leading-6 text-slate-100"><code>{snippet}</code></pre><Button size="icon" variant="ghost" className="absolute right-2 top-2 text-slate-100 hover:bg-slate-800" onClick={() => { void copy(); }} aria-label="Copy OpenTelemetry configuration">{copied ? <Check className="h-4 w-4" /> : <Clipboard className="h-4 w-4" />}</Button></div><p className="text-xs text-muted-foreground">This page intentionally does not display tokens, credentials, or a fabricated collector URL.</p></CardContent></Card>;
}
