import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { FileBarChart, Plus } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';
import { Input } from '@/components/ui/Input';
import { performanceMonitoringService } from '../services/performance-monitoring-service';
import type { SLADefinitionCreate, SLAWindow } from '../contracts';
import { EmptyTelemetry, MonitoringPage, OperationalError, PageSkeleton, StateBanner, StatusPill, formatNumber, formatTime } from '../components/MonitoringPage';

const emptySLA: SLADefinitionCreate = { service_name: '', metric_name: '', comparison: 'lte', target: 1, window: 'rolling_24h', expected_interval_seconds: 60 };

export function SLAManagementPage() {
  const client = useQueryClient();
  const [showCreate, setShowCreate] = useState(false);
  const [draft, setDraft] = useState<SLADefinitionCreate>(emptySLA);
  const slas = useQuery({ queryKey: ['performance-monitoring', 'sla'], queryFn: () => performanceMonitoringService.listSLAs({ page_size: 100, ordering: 'name' }) });
  const compliance = useQuery({ queryKey: ['performance-monitoring', 'compliance'], queryFn: () => performanceMonitoringService.listComplianceRecords({ page_size: 100, ordering: '-period_end' }) });
  const create = useMutation({ mutationFn: (payload: SLADefinitionCreate) => performanceMonitoringService.createSLA(payload), onSuccess: () => { toast.success('SLA definition created'); setShowCreate(false); setDraft(emptySLA); void client.invalidateQueries({ queryKey: ['performance-monitoring', 'sla'] }); }, onError: () => toast.error('SLA definition could not be created') });
  const evaluate = useMutation({ mutationFn: (id: string) => performanceMonitoringService.evaluateSLA(id), onSuccess: () => { toast.success('Compliance evaluated from persisted samples'); void client.invalidateQueries({ queryKey: ['performance-monitoring', 'compliance'] }); }, onError: () => toast.error('Compliance could not be evaluated') });
  const report = useMutation({ mutationFn: (id: string) => performanceMonitoringService.generateSLAReport({ sla_id: id, period: 'calendar_month', format: 'json' }), onSuccess: () => toast.success('SLA report submitted'), onError: () => toast.error('SLA report could not be submitted') });
  const latestBySla = new Map(compliance.data?.items.map((record) => [record.sla, record]));

  return <MonitoringPage title="SLO & SLA management" description="Measure objectives from durable samples, preserve versioned targets and track error-budget evidence." actions={<Button onClick={() => setShowCreate((value) => !value)}><Plus className="mr-2 h-4 w-4" />Define SLA</Button>}>
    {showCreate ? <SLAForm draft={draft} setDraft={setDraft} pending={create.isPending} onCancel={() => setShowCreate(false)} onSubmit={() => create.mutate(draft)} /> : null}
    {compliance.isError && !slas.isError ? <StateBanner state="degraded">SLA definitions are available, but compliance evidence could not be loaded.</StateBanner> : null}
    {slas.isPending ? <PageSkeleton rows={5} /> : slas.isError ? <OperationalError error={slas.error} onRetry={() => { void slas.refetch(); }} /> : slas.data.items.length === 0 ? <EmptyTelemetry title="No service-level agreements" description="Define an SLA over a metric and expected sampling cadence. Compliance is marked insufficient when sample density is too low." action={<Button onClick={() => setShowCreate(true)}>Define first SLA</Button>} /> : <div className="grid gap-4 lg:grid-cols-2">{slas.data.items.map((sla) => { const record = latestBySla.get(sla.id); return <Card key={sla.id}><CardContent className="p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold text-foreground">{sla.name || `${sla.service_name} ${sla.metric_name}`}</h2><p className="mt-1 text-xs text-muted-foreground">Version {sla.version} · {sla.window.replaceAll('_', ' ')}</p></div>{record ? <StatusPill status={record.status} /> : <span className="text-xs text-muted-foreground">Not evaluated</span>}</div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-xs text-muted-foreground">Objective</dt><dd className="mt-1 font-medium">{sla.metric_name} {sla.comparison} {formatNumber(sla.target)}</dd></div><div><dt className="text-xs text-muted-foreground">Latest compliance</dt><dd className="mt-1 font-medium">{record?.compliance_percentage === null || !record ? 'Insufficient data' : `${formatNumber(record.compliance_percentage, { maximumFractionDigits: 2 })}%`}</dd></div><div><dt className="text-xs text-muted-foreground">Sample density</dt><dd className="mt-1 font-medium">{record && record.expected_samples > 0 ? formatNumber(record.observed_samples / record.expected_samples, { style: 'percent', maximumFractionDigits: 1 }) : 'Unavailable'}</dd></div><div><dt className="text-xs text-muted-foreground">Effective</dt><dd className="mt-1 font-medium">{formatTime(sla.effective_from)}</dd></div></dl><div className="mt-5 flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={evaluate.isPending} onClick={() => evaluate.mutate(sla.id)}>Evaluate now</Button><Button size="sm" variant="ghost" disabled={report.isPending} onClick={() => report.mutate(sla.id)}><FileBarChart className="mr-1 h-4 w-4" />Generate report</Button></div></CardContent></Card>; })}</div>}
  </MonitoringPage>;
}

export const SLOMonitoringPage = SLAManagementPage;

function SLAForm({ draft, setDraft, pending, onCancel, onSubmit }: { draft: SLADefinitionCreate; setDraft: (draft: SLADefinitionCreate) => void; pending: boolean; onCancel: () => void; onSubmit: () => void }) {
  const valid = Boolean(draft.service_name.trim() && draft.metric_name.trim() && draft.target > 0);
  return <Card><CardHeader><CardTitle className="text-lg">Define service-level agreement</CardTitle></CardHeader><CardContent><form className="grid gap-4 md:grid-cols-3" onSubmit={(event) => { event.preventDefault(); if (valid) onSubmit(); }}><label className="text-sm font-medium">Service name<Input className="mt-1" value={draft.service_name} onChange={(event) => setDraft({ ...draft, service_name: event.target.value })} /></label><label className="text-sm font-medium">Metric name<Input className="mt-1" value={draft.metric_name} onChange={(event) => setDraft({ ...draft, metric_name: event.target.value.toLowerCase() })} /></label><label className="text-sm font-medium">Comparison<select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={draft.comparison} onChange={(event) => setDraft({ ...draft, comparison: event.target.value as 'gte' | 'lte' })}><option value="gte">At least (gte)</option><option value="lte">At most (lte)</option></select></label><label className="text-sm font-medium">Target<Input className="mt-1" type="number" min="0.0001" step="any" value={draft.target} onChange={(event) => setDraft({ ...draft, target: Number(event.target.value) })} /></label><label className="text-sm font-medium">Window<select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={draft.window} onChange={(event) => setDraft({ ...draft, window: event.target.value as SLAWindow })}>{['rolling_1h', 'rolling_24h', 'calendar_month'].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-sm font-medium">Expected sample cadence (seconds)<Input className="mt-1" type="number" min={1} value={draft.expected_interval_seconds} onChange={(event) => setDraft({ ...draft, expected_interval_seconds: Number(event.target.value) })} /></label><div className="flex items-end gap-2 md:col-span-2"><Button type="submit" disabled={!valid || pending}>{pending ? 'Creating…' : 'Create SLA'}</Button><Button type="button" variant="outline" onClick={onCancel}>Cancel</Button></div></form></CardContent></Card>;
}
