import { lazy } from "react";
import { BookLock, ClipboardList, Filter, KeyRound, LockKeyhole, SearchCheck, Settings2, Shield, ShieldCheck, UsersRound } from "lucide-react";
import type { TenantRoute } from "@/navigation/tenant-route-types";

const localModes = ["development", "self-hosted"] as const;
const allModes = ["development", "self-hosted", "saas"] as const;

const securityRouteDefinitions = [
  { id: "security-access-control.roles.list", module: "security_access_control", path: "/security-access-control/roles", sourceFile: "modules/security_access_control/pages/RolesPage.tsx", Page: lazy(() => import("./pages/RolesPage").then(({ RolesPage }) => ({ default: RolesPage }))), modes: localModes, navigation: { type: "sidebar", label: "Roles", icon: Shield, order: 120 } },
  { id: "security-access-control.roles.create", module: "security_access_control", path: "/security-access-control/roles/create", sourceFile: "modules/security_access_control/pages/RolesPage.tsx", Page: lazy(() => import("./pages/RolesPage").then(({ RoleCreatePage }) => ({ default: RoleCreatePage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.roles.list" } },
  { id: "security-access-control.roles.detail", module: "security_access_control", path: "/security-access-control/roles/:id", sourceFile: "modules/security_access_control/pages/RolesPage.tsx", Page: lazy(() => import("./pages/RolesPage").then(({ RoleDetailPage }) => ({ default: RoleDetailPage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.roles.list" } },
  { id: "security-access-control.roles.edit", module: "security_access_control", path: "/security-access-control/roles/:id/edit", sourceFile: "modules/security_access_control/pages/RolesPage.tsx", Page: lazy(() => import("./pages/RolesPage").then(({ RoleEditPage }) => ({ default: RoleEditPage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.roles.list" } },

  { id: "security-access-control.permissions.list", module: "security_access_control", path: "/security-access-control/permissions", sourceFile: "modules/security_access_control/pages/PermissionsPage.tsx", Page: lazy(() => import("./pages/PermissionsPage").then(({ PermissionsPage }) => ({ default: PermissionsPage }))), modes: localModes, navigation: { type: "sidebar", label: "Permissions", icon: BookLock, order: 121 } },
  { id: "security-access-control.permissions.detail", module: "security_access_control", path: "/security-access-control/permissions/:id", sourceFile: "modules/security_access_control/pages/PermissionsPage.tsx", Page: lazy(() => import("./pages/PermissionsPage").then(({ PermissionDetailPage }) => ({ default: PermissionDetailPage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.permissions.list" } },

  { id: "security-access-control.assignments.list", module: "security_access_control", path: "/security-access-control/assignments", sourceFile: "modules/security_access_control/pages/AssignmentsPage.tsx", Page: lazy(() => import("./pages/AssignmentsPage").then(({ AssignmentsPage }) => ({ default: AssignmentsPage }))), modes: localModes, navigation: { type: "sidebar", label: "Assignments", icon: UsersRound, order: 122 } },
  { id: "security-access-control.assignments.create", module: "security_access_control", path: "/security-access-control/assignments/create", sourceFile: "modules/security_access_control/pages/AssignmentsPage.tsx", Page: lazy(() => import("./pages/AssignmentsPage").then(({ UserRoleCreatePage }) => ({ default: UserRoleCreatePage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.assignments.list" } },
  { id: "security-access-control.assignments.detail", module: "security_access_control", path: "/security-access-control/assignments/:id", sourceFile: "modules/security_access_control/pages/AssignmentsPage.tsx", Page: lazy(() => import("./pages/AssignmentsPage").then(({ UserRoleDetailPage }) => ({ default: UserRoleDetailPage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.assignments.list" } },
  { id: "security-access-control.assignments.edit", module: "security_access_control", path: "/security-access-control/assignments/:id/edit", sourceFile: "modules/security_access_control/pages/AssignmentsPage.tsx", Page: lazy(() => import("./pages/AssignmentsPage").then(({ UserRoleEditPage }) => ({ default: UserRoleEditPage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.assignments.list" } },

  { id: "security-access-control.permission-sets.list", module: "security_access_control", path: "/security-access-control/permission-sets", sourceFile: "modules/security_access_control/pages/PermissionSetsPage.tsx", Page: lazy(() => import("./pages/PermissionSetsPage").then(({ PermissionSetsPage }) => ({ default: PermissionSetsPage }))), modes: localModes, navigation: { type: "sidebar", label: "Permission sets", icon: KeyRound, order: 123 } },
  { id: "security-access-control.permission-sets.create", module: "security_access_control", path: "/security-access-control/permission-sets/create", sourceFile: "modules/security_access_control/pages/PermissionSetsPage.tsx", Page: lazy(() => import("./pages/PermissionSetsPage").then(({ PermissionSetCreatePage }) => ({ default: PermissionSetCreatePage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.permission-sets.list" } },
  { id: "security-access-control.permission-sets.detail", module: "security_access_control", path: "/security-access-control/permission-sets/:id", sourceFile: "modules/security_access_control/pages/PermissionSetsPage.tsx", Page: lazy(() => import("./pages/PermissionSetsPage").then(({ PermissionSetDetailPage }) => ({ default: PermissionSetDetailPage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.permission-sets.list" } },
  { id: "security-access-control.permission-sets.edit", module: "security_access_control", path: "/security-access-control/permission-sets/:id/edit", sourceFile: "modules/security_access_control/pages/PermissionSetsPage.tsx", Page: lazy(() => import("./pages/PermissionSetsPage").then(({ PermissionSetEditPage }) => ({ default: PermissionSetEditPage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.permission-sets.list" } },

  { id: "security-access-control.permission-set-grants.list", module: "security_access_control", path: "/security-access-control/assignments/permission-set-grants", sourceFile: "modules/security_access_control/pages/UserPermissionSetsPage.tsx", Page: lazy(() => import("./pages/UserPermissionSetsPage").then(({ UserPermissionSetsPage }) => ({ default: UserPermissionSetsPage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.assignments.list" } },
  { id: "security-access-control.permission-set-grants.create", module: "security_access_control", path: "/security-access-control/assignments/permission-set-grants/create", sourceFile: "modules/security_access_control/pages/UserPermissionSetsPage.tsx", Page: lazy(() => import("./pages/UserPermissionSetsPage").then(({ UserPermissionSetCreatePage }) => ({ default: UserPermissionSetCreatePage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.assignments.list" } },
  { id: "security-access-control.permission-set-grants.detail", module: "security_access_control", path: "/security-access-control/assignments/permission-set-grants/:id", sourceFile: "modules/security_access_control/pages/UserPermissionSetsPage.tsx", Page: lazy(() => import("./pages/UserPermissionSetsPage").then(({ UserPermissionSetDetailPage }) => ({ default: UserPermissionSetDetailPage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.assignments.list" } },
  { id: "security-access-control.permission-set-grants.edit", module: "security_access_control", path: "/security-access-control/assignments/permission-set-grants/:id/edit", sourceFile: "modules/security_access_control/pages/UserPermissionSetsPage.tsx", Page: lazy(() => import("./pages/UserPermissionSetsPage").then(({ UserPermissionSetEditPage }) => ({ default: UserPermissionSetEditPage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.assignments.list" } },

  { id: "security-access-control.field-security.list", module: "security_access_control", path: "/security-access-control/field-security", sourceFile: "modules/security_access_control/pages/FieldSecurityPage.tsx", Page: lazy(() => import("./pages/FieldSecurityPage").then(({ FieldSecurityPage }) => ({ default: FieldSecurityPage }))), modes: localModes, navigation: { type: "sidebar", label: "Field security", icon: LockKeyhole, order: 124 } },
  { id: "security-access-control.field-security.create", module: "security_access_control", path: "/security-access-control/field-security/create", sourceFile: "modules/security_access_control/pages/FieldSecurityPage.tsx", Page: lazy(() => import("./pages/FieldSecurityPage").then(({ FieldSecurityCreatePage }) => ({ default: FieldSecurityCreatePage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.field-security.list" } },
  { id: "security-access-control.field-security.detail", module: "security_access_control", path: "/security-access-control/field-security/:id", sourceFile: "modules/security_access_control/pages/FieldSecurityPage.tsx", Page: lazy(() => import("./pages/FieldSecurityPage").then(({ FieldSecurityDetailPage }) => ({ default: FieldSecurityDetailPage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.field-security.list" } },
  { id: "security-access-control.field-security.edit", module: "security_access_control", path: "/security-access-control/field-security/:id/edit", sourceFile: "modules/security_access_control/pages/FieldSecurityPage.tsx", Page: lazy(() => import("./pages/FieldSecurityPage").then(({ FieldSecurityEditPage }) => ({ default: FieldSecurityEditPage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.field-security.list" } },

  { id: "security-access-control.row-security.list", module: "security_access_control", path: "/security-access-control/row-security", sourceFile: "modules/security_access_control/pages/RowSecurityPage.tsx", Page: lazy(() => import("./pages/RowSecurityPage").then(({ RowSecurityPage }) => ({ default: RowSecurityPage }))), modes: localModes, navigation: { type: "sidebar", label: "Row security", icon: Filter, order: 125 } },
  { id: "security-access-control.row-security.create", module: "security_access_control", path: "/security-access-control/row-security/create", sourceFile: "modules/security_access_control/pages/RowSecurityPage.tsx", Page: lazy(() => import("./pages/RowSecurityPage").then(({ RowSecurityCreatePage }) => ({ default: RowSecurityCreatePage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.row-security.list" } },
  { id: "security-access-control.row-security.detail", module: "security_access_control", path: "/security-access-control/row-security/:id", sourceFile: "modules/security_access_control/pages/RowSecurityPage.tsx", Page: lazy(() => import("./pages/RowSecurityPage").then(({ RowSecurityDetailPage }) => ({ default: RowSecurityDetailPage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.row-security.list" } },
  { id: "security-access-control.row-security.edit", module: "security_access_control", path: "/security-access-control/row-security/:id/edit", sourceFile: "modules/security_access_control/pages/RowSecurityPage.tsx", Page: lazy(() => import("./pages/RowSecurityPage").then(({ RowSecurityEditPage }) => ({ default: RowSecurityEditPage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.row-security.list" } },

  { id: "security-access-control.profiles.list", module: "security_access_control", path: "/security-access-control/security-profiles", sourceFile: "modules/security_access_control/pages/SecurityProfilesPage.tsx", Page: lazy(() => import("./pages/SecurityProfilesPage").then(({ SecurityProfilesPage }) => ({ default: SecurityProfilesPage }))), modes: localModes, navigation: { type: "sidebar", label: "Security profiles", icon: ShieldCheck, order: 126 } },
  { id: "security-access-control.profiles.create", module: "security_access_control", path: "/security-access-control/security-profiles/create", sourceFile: "modules/security_access_control/pages/SecurityProfilesPage.tsx", Page: lazy(() => import("./pages/SecurityProfilesPage").then(({ SecurityProfileCreatePage }) => ({ default: SecurityProfileCreatePage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.profiles.list" } },
  { id: "security-access-control.profiles.detail", module: "security_access_control", path: "/security-access-control/security-profiles/:id", sourceFile: "modules/security_access_control/pages/SecurityProfilesPage.tsx", Page: lazy(() => import("./pages/SecurityProfilesPage").then(({ SecurityProfileDetailPage }) => ({ default: SecurityProfileDetailPage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.profiles.list" } },
  { id: "security-access-control.profiles.edit", module: "security_access_control", path: "/security-access-control/security-profiles/:id/edit", sourceFile: "modules/security_access_control/pages/SecurityProfilesPage.tsx", Page: lazy(() => import("./pages/SecurityProfilesPage").then(({ SecurityProfileEditPage }) => ({ default: SecurityProfileEditPage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.profiles.list" } },

  { id: "security-access-control.profile-assignments.list", module: "security_access_control", path: "/security-access-control/assignments/profile-assignments", sourceFile: "modules/security_access_control/pages/ProfileAssignmentsPage.tsx", Page: lazy(() => import("./pages/ProfileAssignmentsPage").then(({ ProfileAssignmentsPage }) => ({ default: ProfileAssignmentsPage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.assignments.list" } },
  { id: "security-access-control.profile-assignments.create", module: "security_access_control", path: "/security-access-control/assignments/profile-assignments/create", sourceFile: "modules/security_access_control/pages/ProfileAssignmentsPage.tsx", Page: lazy(() => import("./pages/ProfileAssignmentsPage").then(({ ProfileAssignmentCreatePage }) => ({ default: ProfileAssignmentCreatePage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.assignments.list" } },
  { id: "security-access-control.profile-assignments.detail", module: "security_access_control", path: "/security-access-control/assignments/profile-assignments/:id", sourceFile: "modules/security_access_control/pages/ProfileAssignmentsPage.tsx", Page: lazy(() => import("./pages/ProfileAssignmentsPage").then(({ ProfileAssignmentDetailPage }) => ({ default: ProfileAssignmentDetailPage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.assignments.list" } },
  { id: "security-access-control.profile-assignments.edit", module: "security_access_control", path: "/security-access-control/assignments/profile-assignments/:id/edit", sourceFile: "modules/security_access_control/pages/ProfileAssignmentsPage.tsx", Page: lazy(() => import("./pages/ProfileAssignmentsPage").then(({ ProfileAssignmentEditPage }) => ({ default: ProfileAssignmentEditPage }))), modes: localModes, navigation: { type: "contextual", parentRouteId: "security-access-control.assignments.list" } },

  { id: "security-access-control.audit.list", module: "security_access_control", path: "/security-access-control/audit-logs", sourceFile: "modules/security_access_control/pages/AuditLogPage.tsx", Page: lazy(() => import("./pages/AuditLogPage").then(({ AuditLogPage }) => ({ default: AuditLogPage }))), modes: allModes, navigation: { type: "sidebar", label: "Audit logs", icon: ClipboardList, order: 127 } },
  { id: "security-access-control.audit.detail", module: "security_access_control", path: "/security-access-control/audit-logs/:id", sourceFile: "modules/security_access_control/pages/AuditLogPage.tsx", Page: lazy(() => import("./pages/AuditLogPage").then(({ AuditLogDetailPage }) => ({ default: AuditLogDetailPage }))), modes: allModes, navigation: { type: "contextual", parentRouteId: "security-access-control.audit.list" } },
  { id: "security-access-control.simulator", module: "security_access_control", path: "/security-access-control/access-simulator", sourceFile: "modules/security_access_control/pages/AccessSimulatorPage.tsx", Page: lazy(() => import("./pages/AccessSimulatorPage").then(({ AccessSimulatorPage }) => ({ default: AccessSimulatorPage }))), modes: allModes, navigation: { type: "sidebar", label: "Access simulator", icon: SearchCheck, order: 128 } },
  { id: "security-access-control.configuration", module: "security_access_control", path: "/security-access-control/configuration", sourceFile: "modules/security_access_control/pages/SecurityConfigurationPage.tsx", Page: lazy(() => import("./pages/SecurityConfigurationPage").then(({ SecurityConfigurationPage }) => ({ default: SecurityConfigurationPage }))), modes: allModes, requiredPermission: "security.configuration:read", navigation: { type: "sidebar", label: "Configuration", icon: Settings2, order: 129 } },
] satisfies readonly TenantRoute[];

const routeTitleByKind: Readonly<Record<string, string>> = {
  list: "Security administration",
  create: "Create security policy",
  detail: "Security policy detail",
  edit: "Edit security policy",
  simulator: "Access simulator",
  configuration: "Security configuration",
};

export const tenantRoutes = securityRouteDefinitions.map((route) => {
  const kind = route.id.split(".").at(-1) ?? "detail";
  return { ...route, title: routeTitleByKind[kind] ?? "Security & Access Control" };
}) satisfies readonly TenantRoute[];

export default tenantRoutes;
