import { QueryClient, QueryClientProvider } from '@tanstack/react-query'; import { render, screen, waitFor } from '@testing-library/react'; import userEvent from '@testing-library/user-event'; import { MemoryRouter, Route, Routes } from 'react-router-dom'; import { afterEach, describe, expect, it, vi } from 'vitest'; import { ROUTES } from '../contracts'; import type { Employee } from '../contracts'; import { EmployeeListPage } from '../pages/EmployeeListPage'; import { EmployeeDetailPage } from '../pages/EmployeeDetailPage'; import { HrApiError, hrService } from '../services/hr-service';
const pagination = { count: 0, page: 1, page_size: 25, total_pages: 0, has_next: false, has_previous: false };
const employee: Employee = { id: 'employee-1', tenant_id: 'tenant-1', created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z', created_by: 'actor', updated_by: 'actor', deleted_at: null, deleted_by: '', employee_number: 'EMP-1', first_name: 'Ada', last_name: 'Lovelace', full_name: 'Ada Lovelace', email: 'ada@example.test', phone: '', department: null, department_name: null, manager: null, manager_name: null, position: 'Engineer', hire_date: '2026-01-01', employment_type: 'full_time', employment_status: 'active', is_active: true, termination_date: null, termination_reason: '', transition_history: [] };
function renderAt(element: React.ReactNode, path: string, route = path) { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[path]}><Routes><Route path={route} element={element} /></Routes></MemoryRouter></QueryClientProvider>); }
describe('Human Resources pages', () => {
  afterEach(() => vi.restoreAllMocks());
  it('renders a layout-preserving skeleton then a permission-aware empty state', async () => {
    vi.spyOn(hrService, 'listEmployees').mockResolvedValue({ items: [], pagination, correlationId: 'corr-1', capabilities: [] }); renderAt(<EmployeeListPage />, ROUTES.EMPLOYEES);
    expect(screen.getByRole('status', { name: 'Loading Human Resources' })).toBeInTheDocument(); expect(await screen.findByText('No employees found')).toBeInTheDocument(); expect(screen.queryByRole('button', { name: /new employee/i })).not.toBeInTheDocument();
    expect(screen.getByText(/explicit/i)).toBeInTheDocument();
  });
  it('shows a create action only with an explicit capability', async () => {
    vi.spyOn(hrService, 'listEmployees').mockResolvedValue({ items: [], pagination, correlationId: 'corr-1', capabilities: ['hr.employee:create'] }); renderAt(<EmployeeListPage />, ROUTES.EMPLOYEES); expect(await screen.findByRole('button', { name: /new employee/i })).toBeInTheDocument();
  });
  it('shows governed correlation IDs and supports retry', async () => {
    const list = vi.spyOn(hrService, 'listEmployees').mockRejectedValueOnce(new HrApiError('Unavailable', 'unavailable', 503, 'capability_unavailable', 'corr-recovery')).mockResolvedValueOnce({ items: [], pagination, correlationId: 'corr-2', capabilities: [] }); renderAt(<EmployeeListPage />, ROUTES.EMPLOYEES); expect(await screen.findByText(/corr-recovery/)).toBeInTheDocument(); await userEvent.click(screen.getByRole('button', { name: /try again/i })); await waitFor(() => expect(screen.getByText('No employees found')).toBeInTheDocument()); expect(list).toHaveBeenCalledTimes(2);
  });
  it('offers lifecycle actions only when the transition capability is returned', async () => {
    vi.spyOn(hrService, 'getEmployee').mockResolvedValue({ data: employee, correlationId: 'corr-1', capabilities: ['hr.employee:transition'] }); vi.spyOn(hrService, 'getReportingTree').mockResolvedValue({ data: { id: employee.id, employee_number: employee.employee_number, full_name: employee.full_name, position: employee.position, employment_status: employee.employment_status, direct_reports: [] }, correlationId: 'corr-1', capabilities: [] }); vi.spyOn(hrService, 'listAttendances').mockResolvedValue({ items: [], pagination, correlationId: 'corr-1', capabilities: [] }); vi.spyOn(hrService, 'listLeaveBalances').mockResolvedValue({ items: [], pagination, correlationId: 'corr-1', capabilities: [] }); vi.spyOn(hrService, 'listLeaveRequests').mockResolvedValue({ items: [], pagination, correlationId: 'corr-1', capabilities: [] }); renderAt(<EmployeeDetailPage />, ROUTES.EMPLOYEE_DETAIL(employee.id), `${ROUTES.EMPLOYEES}/:id`); expect(await screen.findByRole('button', { name: 'place on leave' })).toBeInTheDocument(); await userEvent.click(screen.getByRole('button', { name: 'place on leave' })); expect(screen.getByRole('dialog')).toHaveTextContent('place on leave employee');
  });
});
