import { QueryClient, QueryClientProvider } from '@tanstack/react-query'; import { render, screen, waitFor } from '@testing-library/react'; import userEvent from '@testing-library/user-event'; import { MemoryRouter, Route, Routes } from 'react-router-dom'; import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'; import { ROUTES } from '../contracts'; import type { Employee, HumanResourcesConfiguration } from '../contracts'; import { EmployeeListPage } from '../pages/EmployeeListPage'; import { EmployeeDetailPage } from '../pages/EmployeeDetailPage'; import { HrApiError, hrService } from '../services/hr-service';
const pagination = { count: 0, page: 1, page_size: 25, total_pages: 0, has_next: false, has_previous: false };
const employee: Employee = { id: 'employee-1', created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z', employee_number: 'EMP-1', first_name: 'Ada', last_name: 'Lovelace', full_name: 'Ada Lovelace', email: 'ada@example.test', phone: '', department: null, department_name: null, manager: null, manager_name: null, position: 'Engineer', hire_date: '2026-01-01', employment_type: 'full_time', employment_status: 'active', is_active: true, termination_date: null, termination_reason: '', transition_history: [] };
const configuration: HumanResourcesConfiguration = { id: 'config-1', environment: 'default', version: 1, updated_at: '2026-01-01T00:00:00Z', document: {
  schema_version: 1,
  allowed_values: { employment_types: ['full_time', 'part_time', 'contractor', 'temporary'], employment_statuses: ['active', 'on_leave', 'inactive', 'terminated'], attendance_statuses: ['present', 'absent', 'late', 'half_day', 'on_leave'], attendance_sources: ['manual', 'clock', 'import'], leave_types: ['annual', 'sick', 'personal', 'maternity', 'paternity', 'unpaid'], leave_states: ['pending', 'approved', 'rejected', 'cancelled'], leave_scopes: ['all', 'self', 'team', 'approval_queue'] },
  limits: { actor_identifier_max_length: 255, idempotency_key_max_length: 255, department_code_max_length: 50, department_name_max_length: 255, employee_number_max_length: 50, employee_name_max_length: 100, employee_email_max_length: 255, employee_phone_max_length: 50, employee_position_max_length: 100, hierarchy_max_depth: 100, reporting_tree_default_depth: 5, reporting_tree_max_depth: 20, department_tree_max_nodes: 500, max_hours_per_day: '24.00', leave_amount_minimum: '0.01', list_page_size: 25, lookup_page_size: 100, leave_input_minimum: '0.00', leave_input_step: '0.25', decimal_quantum: '0.01' },
  defaults: { department_active: true, employment_type: 'full_time', employment_status: 'active', attendance_hours: '0.00', attendance_status: 'present', attendance_source: 'manual', leave_type: 'annual', leave_request_status: 'pending', leave_entitled_days: '0.00', leave_carried_days: '0.00', leave_adjustment_version: 1, leave_adjustment_note: 'Initial allocation', leave_scope: 'all', department_ordering: 'department_code', event_schema_version: 1 },
  policies: { manager_eligible_statuses: ['active', 'on_leave'], employee_active_statuses: ['active', 'on_leave'], attendance_eligible_statuses: ['active', 'on_leave'], clock_in_eligible_statuses: ['active'], leave_eligible_statuses: ['active', 'on_leave'], attendance_zero_work_statuses: ['absent', 'on_leave'], leave_overlap_blocking_statuses: ['pending', 'approved'], department_deactivation_blocks_active_children: true, department_deactivation_blocks_active_employees: true, employee_inactivation_requires_no_managed_departments: true, employee_archive_statuses: ['terminated'], employee_archive_blocks_pending_leave: true, leave_balance_enforce_capacity: true, leave_submission_blocks_insufficient_balance: true, allow_future_employee_transitions: false, approved_leave_cancel_before_start_only: true, leave_duration_calendar: 'inclusive', one_attendance_per_employee_date: true },
  workflows: { employee_terminal_states: ['terminated'], employee_transitions: [['place_on_leave', 'active', 'on_leave'], ['return_from_leave', 'on_leave', 'active'], ['deactivate', 'active', 'inactive'], ['deactivate', 'on_leave', 'inactive'], ['activate', 'inactive', 'active'], ['terminate', 'active', 'terminated']], leave_terminal_states: ['rejected', 'cancelled'], leave_transitions: [['approve', 'pending', 'approved'], ['reject', 'pending', 'rejected'], ['cancel', 'pending', 'cancelled'], ['cancel', 'approved', 'cancelled']] },
  feature_rollout: { enabled: true, percentage: 100, roles: [], cohorts: [] },
  visual: { positive_status_token: 'status-positive', warning_status_token: 'status-warning' },
  operations: { health_staleness_seconds: 30 },
} };
function renderAt(element: React.ReactNode, path: string, route = path) { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[path]}><Routes><Route path={route} element={element} /></Routes></MemoryRouter></QueryClientProvider>); }
describe('Human Resources pages', () => {
  beforeEach(() => {
    vi.spyOn(hrService, 'getConfiguration').mockResolvedValue({ data: configuration, correlationId: 'corr-config', capabilities: ['hr.configuration:read'] });
  });
  afterEach(() => vi.restoreAllMocks());
  it('renders a layout-preserving skeleton then a permission-aware empty state', async () => {
    vi.spyOn(hrService, 'listEmployees').mockResolvedValue({ items: [], pagination, correlationId: 'corr-1', capabilities: [] }); renderAt(<EmployeeListPage />, ROUTES.EMPLOYEES);
    expect(screen.getByRole('status', { name: 'Loading Human Resources' })).toBeInTheDocument(); expect(await screen.findByText('No employees found')).toBeInTheDocument(); expect(screen.queryByRole('button', { name: /new employee/i })).not.toBeInTheDocument();
    expect(screen.getByText(/explicit/i)).toBeInTheDocument();
  });
  it('shows a create action only with an explicit capability', async () => {
    vi.spyOn(hrService, 'listEmployees').mockResolvedValue({ items: [], pagination, correlationId: 'corr-1', capabilities: ['hr.employee:create'] }); renderAt(<EmployeeListPage />, ROUTES.EMPLOYEES); expect(await screen.findByRole('button', { name: /new employee/i })).toBeInTheDocument();
  });
  it('shows governed correlation IDs and supports retry', async () => {
    const list = vi.spyOn(hrService, 'listEmployees').mockRejectedValueOnce(new HrApiError('Unavailable', 'unavailable', 503, 'capability_unavailable', 'corr-recovery')).mockResolvedValueOnce({ items: [], pagination, correlationId: 'corr-2', capabilities: [] }); renderAt(<EmployeeListPage />, ROUTES.EMPLOYEES); expect(await screen.findByText(/corr-recovery/)).toBeInTheDocument(); await userEvent.click(screen.getByRole('button', { name: /try again/i })); await waitFor(() => expect(screen.getByText('No employees found')).toBeInTheDocument()); expect(list).toHaveBeenCalledTimes(2);
  });
  it('offers lifecycle actions only when the transition capability is returned', async () => {
    vi.spyOn(hrService, 'getEmployee').mockResolvedValue({ data: employee, correlationId: 'corr-1', capabilities: ['hr.employee:transition'] }); vi.spyOn(hrService, 'getReportingTree').mockResolvedValue({ data: { id: employee.id, employee_number: employee.employee_number, full_name: employee.full_name, position: employee.position, employment_status: employee.employment_status, direct_reports: [] }, correlationId: 'corr-1', capabilities: [] }); vi.spyOn(hrService, 'listAttendances').mockResolvedValue({ items: [], pagination, correlationId: 'corr-1', capabilities: [] }); vi.spyOn(hrService, 'listLeaveBalances').mockResolvedValue({ items: [], pagination, correlationId: 'corr-1', capabilities: [] }); vi.spyOn(hrService, 'listLeaveRequests').mockResolvedValue({ items: [], pagination, correlationId: 'corr-1', capabilities: [] }); renderAt(<EmployeeDetailPage />, ROUTES.EMPLOYEE_DETAIL(employee.id), `${ROUTES.EMPLOYEES}/:id`); expect(await screen.findByRole('button', { name: 'place on leave' })).toBeInTheDocument(); await userEvent.click(screen.getByRole('button', { name: 'place on leave' })); expect(screen.getByRole('dialog')).toHaveTextContent('place on leave employee');
  });
});
