import { lazy } from "react";
import { Activity, FileInput, ListChecks, Settings2, SlidersHorizontal, TextCursorInput } from "lucide-react";
import type { TenantRoute } from "@/navigation/tenant-route-types";
import { ROUTES } from "./contracts";

const modes = ["development", "self-hosted", "saas"] as const;
const contextual = (parentRouteId: string, label: string, icon: typeof SlidersHorizontal) => ({ type: "contextual" as const, parentRouteId, label, icon });
const sidebar = (label: string, icon: typeof SlidersHorizontal) => ({ type: "sidebar" as const, label, icon, order: 0 });

export const tenantRoutes = [
  { id: "customization-framework.fields.list", module: "customization_framework", path: ROUTES.FIELDS, title: "Custom fields · SARAISE", sourceFile: "modules/customization_framework/pages/FieldDefinitionListPage.tsx", Page: lazy(() => import("./pages/FieldDefinitionListPage").then(module => ({ default: module.FieldDefinitionListPage }))), modes, navigation: sidebar("Fields", SlidersHorizontal) },
  { id: "customization-framework.fields.create", module: "customization_framework", path: ROUTES.FIELD_CREATE, title: "Create custom field · SARAISE", sourceFile: "modules/customization_framework/pages/CreateFieldDefinitionPage.tsx", Page: lazy(() => import("./pages/CreateFieldDefinitionPage").then(module => ({ default: module.CreateFieldDefinitionPage }))), modes, navigation: contextual("customization-framework.fields.list", "Create field", SlidersHorizontal) },
  { id: "customization-framework.fields.detail", module: "customization_framework", path: ROUTES.FIELD_DETAIL(":id"), title: "Custom field details · SARAISE", sourceFile: "modules/customization_framework/pages/FieldDefinitionDetailPage.tsx", Page: lazy(() => import("./pages/FieldDefinitionDetailPage").then(module => ({ default: module.FieldDefinitionDetailPage }))), modes, navigation: contextual("customization-framework.fields.list", "Field details", SlidersHorizontal) },
  { id: "customization-framework.fields.edit", module: "customization_framework", path: ROUTES.FIELD_EDIT(":id"), title: "Edit custom field · SARAISE", sourceFile: "modules/customization_framework/pages/EditFieldDefinitionPage.tsx", Page: lazy(() => import("./pages/EditFieldDefinitionPage").then(module => ({ default: module.EditFieldDefinitionPage }))), modes, navigation: contextual("customization-framework.fields.list", "Edit field", SlidersHorizontal) },
  { id: "customization-framework.fields.impact", module: "customization_framework", path: ROUTES.FIELD_IMPACT(":id"), title: "Custom field impact · SARAISE", sourceFile: "modules/customization_framework/pages/ImpactPage.tsx", Page: lazy(() => import("./pages/ImpactPage").then(module => ({ default: module.FieldImpactPage }))), modes, navigation: contextual("customization-framework.fields.list", "Field impact", SlidersHorizontal) },

  { id: "customization-framework.field-values.list", module: "customization_framework", path: ROUTES.FIELD_VALUES, title: "Custom field values · SARAISE", sourceFile: "modules/customization_framework/pages/FieldValuePages.tsx", Page: lazy(() => import("./pages/FieldValuePages").then(module => ({ default: module.FieldValueListPage }))), modes, navigation: sidebar("Field values", TextCursorInput) },
  { id: "customization-framework.field-values.create", module: "customization_framework", path: ROUTES.FIELD_VALUE_CREATE, title: "Create custom field value · SARAISE", sourceFile: "modules/customization_framework/pages/FieldValuePages.tsx", Page: lazy(() => import("./pages/FieldValuePages").then(module => ({ default: module.CreateFieldValuePage }))), modes, navigation: contextual("customization-framework.field-values.list", "Create field value", TextCursorInput) },
  { id: "customization-framework.field-values.detail", module: "customization_framework", path: ROUTES.FIELD_VALUE_DETAIL(":id"), title: "Custom field value details · SARAISE", sourceFile: "modules/customization_framework/pages/FieldValuePages.tsx", Page: lazy(() => import("./pages/FieldValuePages").then(module => ({ default: module.FieldValueDetailPage }))), modes, navigation: contextual("customization-framework.field-values.list", "Field value details", TextCursorInput) },
  { id: "customization-framework.field-values.edit", module: "customization_framework", path: ROUTES.FIELD_VALUE_EDIT(":id"), title: "Edit custom field value · SARAISE", sourceFile: "modules/customization_framework/pages/FieldValuePages.tsx", Page: lazy(() => import("./pages/FieldValuePages").then(module => ({ default: module.EditFieldValuePage }))), modes, navigation: contextual("customization-framework.field-values.list", "Edit field value", TextCursorInput) },

  { id: "customization-framework.forms.list", module: "customization_framework", path: ROUTES.FORMS, title: "Customization forms · SARAISE", sourceFile: "modules/customization_framework/pages/FormListPage.tsx", Page: lazy(() => import("./pages/FormListPage").then(module => ({ default: module.FormListPage }))), modes, navigation: sidebar("Forms", FileInput) },
  { id: "customization-framework.forms.create", module: "customization_framework", path: ROUTES.FORM_CREATE, title: "Create customization form · SARAISE", sourceFile: "modules/customization_framework/pages/CreateFormPage.tsx", Page: lazy(() => import("./pages/CreateFormPage").then(module => ({ default: module.CreateFormPage }))), modes, navigation: contextual("customization-framework.forms.list", "Create form", FileInput) },
  { id: "customization-framework.forms.detail", module: "customization_framework", path: ROUTES.FORM_DETAIL(":id"), title: "Customization form details · SARAISE", sourceFile: "modules/customization_framework/pages/FormDetailPage.tsx", Page: lazy(() => import("./pages/FormDetailPage").then(module => ({ default: module.FormDetailPage }))), modes, navigation: contextual("customization-framework.forms.list", "Form details", FileInput) },
  { id: "customization-framework.forms.designer", module: "customization_framework", path: ROUTES.FORM_EDIT(":id"), title: "Customization form designer · SARAISE", sourceFile: "modules/customization_framework/pages/EditFormPage.tsx", Page: lazy(() => import("./pages/EditFormPage").then(module => ({ default: module.EditFormPage }))), modes, navigation: contextual("customization-framework.forms.list", "Form designer", FileInput) },
  { id: "customization-framework.forms.version", module: "customization_framework", path: ROUTES.FORM_VERSION(":id", ":versionId"), title: "Customization form version · SARAISE", sourceFile: "modules/customization_framework/pages/FormVersionDetailPage.tsx", Page: lazy(() => import("./pages/FormVersionDetailPage").then(module => ({ default: module.FormVersionDetailPage }))), modes, navigation: contextual("customization-framework.forms.list", "Form version", FileInput) },
  { id: "customization-framework.forms.impact", module: "customization_framework", path: ROUTES.FORM_IMPACT(":id"), title: "Customization form impact · SARAISE", sourceFile: "modules/customization_framework/pages/ImpactPage.tsx", Page: lazy(() => import("./pages/ImpactPage").then(module => ({ default: module.FormImpactPage }))), modes, navigation: contextual("customization-framework.forms.list", "Form impact", FileInput) },

  { id: "customization-framework.rules.list", module: "customization_framework", path: ROUTES.RULES, title: "Business rules · SARAISE", sourceFile: "modules/customization_framework/pages/RuleListPage.tsx", Page: lazy(() => import("./pages/RuleListPage").then(module => ({ default: module.RuleListPage }))), modes, navigation: sidebar("Rules", ListChecks) },
  { id: "customization-framework.rules.create", module: "customization_framework", path: ROUTES.RULE_CREATE, title: "Create business rule · SARAISE", sourceFile: "modules/customization_framework/pages/CreateRulePage.tsx", Page: lazy(() => import("./pages/CreateRulePage").then(module => ({ default: module.CreateRulePage }))), modes, navigation: contextual("customization-framework.rules.list", "Create rule", ListChecks) },
  { id: "customization-framework.rules.detail", module: "customization_framework", path: ROUTES.RULE_DETAIL(":id"), title: "Business rule details · SARAISE", sourceFile: "modules/customization_framework/pages/RuleDetailPage.tsx", Page: lazy(() => import("./pages/RuleDetailPage").then(module => ({ default: module.RuleDetailPage }))), modes, navigation: contextual("customization-framework.rules.list", "Rule details", ListChecks) },
  { id: "customization-framework.rules.edit", module: "customization_framework", path: ROUTES.RULE_EDIT(":id"), title: "Edit business rule · SARAISE", sourceFile: "modules/customization_framework/pages/EditRulePage.tsx", Page: lazy(() => import("./pages/EditRulePage").then(module => ({ default: module.EditRulePage }))), modes, navigation: contextual("customization-framework.rules.list", "Edit rule", ListChecks) },
  { id: "customization-framework.rules.version", module: "customization_framework", path: ROUTES.RULE_VERSION(":id", ":versionId"), title: "Business rule version · SARAISE", sourceFile: "modules/customization_framework/pages/RuleVersionDetailPage.tsx", Page: lazy(() => import("./pages/RuleVersionDetailPage").then(module => ({ default: module.RuleVersionDetailPage }))), modes, navigation: contextual("customization-framework.rules.list", "Rule version", ListChecks) },
  { id: "customization-framework.rules.impact", module: "customization_framework", path: ROUTES.RULE_IMPACT(":id"), title: "Business rule impact · SARAISE", sourceFile: "modules/customization_framework/pages/ImpactPage.tsx", Page: lazy(() => import("./pages/ImpactPage").then(module => ({ default: module.RuleImpactPage }))), modes, navigation: contextual("customization-framework.rules.list", "Rule impact", ListChecks) },

  { id: "customization-framework.executions.list", module: "customization_framework", path: ROUTES.EXECUTIONS, title: "Rule executions · SARAISE", sourceFile: "modules/customization_framework/pages/RuleExecutionListPage.tsx", Page: lazy(() => import("./pages/RuleExecutionListPage").then(module => ({ default: module.RuleExecutionListPage }))), modes, navigation: sidebar("Executions", Activity) },
  { id: "customization-framework.executions.detail", module: "customization_framework", path: ROUTES.EXECUTION_DETAIL(":id"), title: "Rule execution details · SARAISE", sourceFile: "modules/customization_framework/pages/RuleExecutionDetailPage.tsx", Page: lazy(() => import("./pages/RuleExecutionDetailPage").then(module => ({ default: module.RuleExecutionDetailPage }))), modes, navigation: contextual("customization-framework.executions.list", "Execution details", Activity) },

  { id: "customization-framework.configuration", module: "customization_framework", path: ROUTES.CONFIGURATION, title: "Customization configuration · SARAISE", sourceFile: "modules/customization_framework/pages/RuntimeConfigurationPage.tsx", Page: lazy(() => import("./pages/RuntimeConfigurationPage").then(module => ({ default: module.RuntimeConfigurationPage }))), modes, navigation: sidebar("Configuration", Settings2) },
] satisfies readonly TenantRoute[];

export default tenantRoutes;
