import { lazy } from "react";
import { Activity, FileInput, ListChecks, SlidersHorizontal } from "lucide-react";
import type { TenantRoute } from "@/navigation/tenant-route-types";
import { ROUTES } from "./contracts";

const modes = ["development", "self-hosted", "saas"] as const;
const contextual = (parentRouteId: string) => ({ type: "contextual" as const, parentRouteId });

export const tenantRoutes = [
  { id: "customization-framework.fields.list", module: "customization_framework", path: ROUTES.FIELDS, sourceFile: "modules/customization_framework/pages/FieldDefinitionListPage.tsx", Page: lazy(() => import("./pages/FieldDefinitionListPage").then(module => ({ default: module.FieldDefinitionListPage }))), modes, navigation: { type: "sidebar", label: "Fields", icon: SlidersHorizontal, order: 70 } },
  { id: "customization-framework.fields.create", module: "customization_framework", path: ROUTES.FIELD_CREATE, sourceFile: "modules/customization_framework/pages/CreateFieldDefinitionPage.tsx", Page: lazy(() => import("./pages/CreateFieldDefinitionPage").then(module => ({ default: module.CreateFieldDefinitionPage }))), modes, navigation: contextual("customization-framework.fields.list") },
  { id: "customization-framework.fields.detail", module: "customization_framework", path: ROUTES.FIELD_DETAIL(":id"), sourceFile: "modules/customization_framework/pages/FieldDefinitionDetailPage.tsx", Page: lazy(() => import("./pages/FieldDefinitionDetailPage").then(module => ({ default: module.FieldDefinitionDetailPage }))), modes, navigation: contextual("customization-framework.fields.list") },
  { id: "customization-framework.fields.edit", module: "customization_framework", path: ROUTES.FIELD_EDIT(":id"), sourceFile: "modules/customization_framework/pages/EditFieldDefinitionPage.tsx", Page: lazy(() => import("./pages/EditFieldDefinitionPage").then(module => ({ default: module.EditFieldDefinitionPage }))), modes, navigation: contextual("customization-framework.fields.list") },
  { id: "customization-framework.fields.impact", module: "customization_framework", path: ROUTES.FIELD_IMPACT(":id"), sourceFile: "modules/customization_framework/pages/ImpactPage.tsx", Page: lazy(() => import("./pages/ImpactPage").then(module => ({ default: module.FieldImpactPage }))), modes, navigation: contextual("customization-framework.fields.list") },
  { id: "customization-framework.forms.list", module: "customization_framework", path: ROUTES.FORMS, sourceFile: "modules/customization_framework/pages/FormListPage.tsx", Page: lazy(() => import("./pages/FormListPage").then(module => ({ default: module.FormListPage }))), modes, navigation: { type: "sidebar", label: "Forms", icon: FileInput, order: 71 } },
  { id: "customization-framework.forms.create", module: "customization_framework", path: ROUTES.FORM_CREATE, sourceFile: "modules/customization_framework/pages/CreateFormPage.tsx", Page: lazy(() => import("./pages/CreateFormPage").then(module => ({ default: module.CreateFormPage }))), modes, navigation: contextual("customization-framework.forms.list") },
  { id: "customization-framework.forms.detail", module: "customization_framework", path: ROUTES.FORM_DETAIL(":id"), sourceFile: "modules/customization_framework/pages/FormDetailPage.tsx", Page: lazy(() => import("./pages/FormDetailPage").then(module => ({ default: module.FormDetailPage }))), modes, navigation: contextual("customization-framework.forms.list") },
  { id: "customization-framework.forms.designer", module: "customization_framework", path: ROUTES.FORM_EDIT(":id"), sourceFile: "modules/customization_framework/pages/EditFormPage.tsx", Page: lazy(() => import("./pages/EditFormPage").then(module => ({ default: module.EditFormPage }))), modes, navigation: contextual("customization-framework.forms.list") },
  { id: "customization-framework.forms.version", module: "customization_framework", path: ROUTES.FORM_VERSION(":id", ":versionId"), sourceFile: "modules/customization_framework/pages/FormVersionDetailPage.tsx", Page: lazy(() => import("./pages/FormVersionDetailPage").then(module => ({ default: module.FormVersionDetailPage }))), modes, navigation: contextual("customization-framework.forms.list") },
  { id: "customization-framework.forms.impact", module: "customization_framework", path: ROUTES.FORM_IMPACT(":id"), sourceFile: "modules/customization_framework/pages/ImpactPage.tsx", Page: lazy(() => import("./pages/ImpactPage").then(module => ({ default: module.FormImpactPage }))), modes, navigation: contextual("customization-framework.forms.list") },
  { id: "customization-framework.rules.list", module: "customization_framework", path: ROUTES.RULES, sourceFile: "modules/customization_framework/pages/RuleListPage.tsx", Page: lazy(() => import("./pages/RuleListPage").then(module => ({ default: module.RuleListPage }))), modes, navigation: { type: "sidebar", label: "Rules", icon: ListChecks, order: 72 } },
  { id: "customization-framework.rules.create", module: "customization_framework", path: ROUTES.RULE_CREATE, sourceFile: "modules/customization_framework/pages/CreateRulePage.tsx", Page: lazy(() => import("./pages/CreateRulePage").then(module => ({ default: module.CreateRulePage }))), modes, navigation: contextual("customization-framework.rules.list") },
  { id: "customization-framework.rules.detail", module: "customization_framework", path: ROUTES.RULE_DETAIL(":id"), sourceFile: "modules/customization_framework/pages/RuleDetailPage.tsx", Page: lazy(() => import("./pages/RuleDetailPage").then(module => ({ default: module.RuleDetailPage }))), modes, navigation: contextual("customization-framework.rules.list") },
  { id: "customization-framework.rules.edit", module: "customization_framework", path: ROUTES.RULE_EDIT(":id"), sourceFile: "modules/customization_framework/pages/EditRulePage.tsx", Page: lazy(() => import("./pages/EditRulePage").then(module => ({ default: module.EditRulePage }))), modes, navigation: contextual("customization-framework.rules.list") },
  { id: "customization-framework.rules.version", module: "customization_framework", path: ROUTES.RULE_VERSION(":id", ":versionId"), sourceFile: "modules/customization_framework/pages/RuleVersionDetailPage.tsx", Page: lazy(() => import("./pages/RuleVersionDetailPage").then(module => ({ default: module.RuleVersionDetailPage }))), modes, navigation: contextual("customization-framework.rules.list") },
  { id: "customization-framework.rules.impact", module: "customization_framework", path: ROUTES.RULE_IMPACT(":id"), sourceFile: "modules/customization_framework/pages/ImpactPage.tsx", Page: lazy(() => import("./pages/ImpactPage").then(module => ({ default: module.RuleImpactPage }))), modes, navigation: contextual("customization-framework.rules.list") },
  { id: "customization-framework.executions.list", module: "customization_framework", path: ROUTES.EXECUTIONS, sourceFile: "modules/customization_framework/pages/RuleExecutionListPage.tsx", Page: lazy(() => import("./pages/RuleExecutionListPage").then(module => ({ default: module.RuleExecutionListPage }))), modes, navigation: { type: "sidebar", label: "Executions", icon: Activity, order: 73 } },
  { id: "customization-framework.executions.detail", module: "customization_framework", path: ROUTES.EXECUTION_DETAIL(":id"), sourceFile: "modules/customization_framework/pages/RuleExecutionDetailPage.tsx", Page: lazy(() => import("./pages/RuleExecutionDetailPage").then(module => ({ default: module.RuleExecutionDetailPage }))), modes, navigation: contextual("customization-framework.executions.list") },
] satisfies readonly TenantRoute[];

export default tenantRoutes;
