import {useEffect,useState,type ReactNode} from 'react';
import {useMutation,useQuery} from '@tanstack/react-query';
import {Link,useNavigate,useParams,useSearchParams} from 'react-router-dom';
import {AlertTriangle} from 'lucide-react';
import type{ListFilters,Project,ProjectMember,ProjectMilestone,Task,TimeEntry}from'../contracts';
import{ProjectForm,TaskForm,MemberForm,TimeEntryForm,MilestoneForm}from'../components/ProjectForms';
import{projectService,createIdempotencyKey}from'../services/project-service';import{taskService}from'../services/task-service';import{memberService}from'../services/member-service';import{timeEntryService}from'../services/time-entry-service';import{milestoneService}from'../services/milestone-service';import{configurationService}from'../services/configuration-service';import{ProjectManagementApiError,type PageResult}from'../services/client';
import{activityService}from'../services/activity-service';

const button='inline-flex items-center justify-center rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:opacity-50';
const card='rounded-xl border border-border bg-card p-4 text-card-foreground shadow-sm';
function useTitle(title:string){useEffect(()=>{document.title=`${title} | SARAISE`},[title])}
function State({loading,error,empty,onRetry,children}:{loading:boolean;error:Error|null;empty:boolean;onRetry:()=>void;children:ReactNode}){if(loading)return <div aria-label="Loading" className="grid gap-3">{[1,2,3].map(i=><div key={i} className="h-20 animate-pulse rounded-xl bg-muted"/>)}</div>;if(error){const e=error instanceof ProjectManagementApiError?error:null;return <div role="alert" className={card}><h2 className="font-semibold">Could not load this view</h2><p className="text-sm text-muted-foreground">{error.message}</p>{e?.correlationId&&<p className="text-xs">Correlation: {e.correlationId}</p>}<button className={button} onClick={onRetry}>Retry</button></div>}if(empty)return <div className={card}><h2 className="font-semibold">Nothing here yet</h2><p className="text-sm text-muted-foreground">Create the first record to start the workflow.</p></div>;return <>{children}</>}
type Named={readonly id:string;readonly archived_at:string|null};
function ListView<T extends Named>({title,newPath,queryKey,query,name,subtitle}:{title:string;newPath:string;queryKey:string;query:(f:ListFilters)=>Promise<PageResult<T>>;name:(r:T)=>string;subtitle:(r:T)=>string}){useTitle(title);const[search,setSearch]=useSearchParams();const filters={page:Number(search.get('page')??1),search:search.get('search')??undefined,ordering:search.get('ordering')??undefined};const result=useQuery({queryKey:[queryKey,filters],queryFn:()=>query(filters)});return <main className="mx-auto grid max-w-6xl gap-5 p-4 sm:p-6"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold">{title}</h1><p className="text-sm text-muted-foreground">Tenant-safe, auditable execution records.</p></div><Link className={button} to={newPath}>Create</Link></header><label className="grid max-w-md gap-1 text-sm">Search<input className="rounded-md border border-border bg-background px-3 py-2" defaultValue={filters.search} onKeyDown={e=>{if(e.key==='Enter')setSearch({search:e.currentTarget.value})}}/></label><State loading={result.isLoading} error={result.error} empty={!result.data?.items.length} onRetry={()=>void result.refetch()}>{<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{result.data?.items.map(row=><Link key={row.id} to={row.id} className={`${card} transition hover:border-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring`}><h2 className="font-semibold">{name(row)}</h2><p className="mt-1 text-sm text-muted-foreground">{subtitle(row)}</p>{row.archived_at&&<span className="mt-2 inline-block rounded bg-muted px-2 py-1 text-xs">Archived</span>}</Link>)}</div>}</State></main>}
function DetailView<T>({title,queryKey,query,render}:{title:string;queryKey:string;query:(id:string)=>Promise<T>;render:(value:T)=>ReactNode}){useTitle(title);const{id=''}=useParams();const result=useQuery({queryKey:[queryKey,id],queryFn:()=>query(id),enabled:Boolean(id)});return <main className="mx-auto max-w-5xl p-4 sm:p-6"><State loading={result.isLoading} error={result.error} empty={!result.data} onRetry={()=>void result.refetch()}>{result.data&&render(result.data)}</State></main>}

export function ProjectListPage(){return <ListView title="Projects" newPath="/project-management/projects/new" queryKey="projects" query={projectService.list} name={r=>`${r.project_code} · ${r.project_name}`} subtitle={r=>`${r.status.replace('_',' ')} · ${r.currency} ${r.budget??'No budget'}`}/>}
export function TaskListPage(){return <ListView title="Tasks" newPath="/project-management/tasks/new" queryKey="tasks" query={taskService.list} name={r=>`${r.task_code} · ${r.task_name}`} subtitle={r=>`${r.status.replace('_',' ')} · ${r.priority} · ${r.percent_complete}%`}/>}
export function ProjectMemberListPage(){return <ListView title="Project team" newPath="/project-management/members/new" queryKey="members" query={memberService.list} name={r=>r.employee_id} subtitle={r=>`${r.project_code} · ${r.role.replace('_',' ')} · ${r.allocation_percentage}%`}/>}
export function TimeEntryListPage(){return <ListView title="Time entries" newPath="/project-management/time-entries/new" queryKey="time" query={timeEntryService.list} name={r=>`${r.entry_date} · ${r.hours_worked} hours`} subtitle={r=>`${r.project_code}${r.task_code?` · ${r.task_code}`:''}${r.billable?' · Billable':''}`}/>}
export function MilestoneListPage(){return <ListView title="Milestones" newPath="/project-management/milestones/new" queryKey="milestones" query={milestoneService.list} name={r=>r.milestone_name} subtitle={r=>`${r.project_code} · due ${r.target_date}`}/>}

export function ProjectDetailPage(){const{id=''}=useParams();useTitle('Project workspace');const project=useQuery({queryKey:['project',id],queryFn:()=>projectService.get(id)});const summary=useQuery({queryKey:['project-summary',id],queryFn:()=>projectService.summary(id),enabled:Boolean(project.data)});const[tabs,setTabs]=useSearchParams();const active=tabs.get('tab')??'tasks';const related={tasks:useQuery({queryKey:['tasks',id],queryFn:()=>taskService.list({project_id:id})}),milestones:useQuery({queryKey:['milestones',id],queryFn:()=>milestoneService.list({project_id:id})}),team:useQuery({queryKey:['members',id],queryFn:()=>memberService.list({project_id:id})}),time:useQuery({queryKey:['time',id],queryFn:()=>timeEntryService.list({project_id:id})}),activity:useQuery({queryKey:['activity',id],queryFn:()=>activityService.listForProject(id)})};return <main className="mx-auto grid max-w-6xl gap-5 p-4 sm:p-6"><State loading={project.isLoading} error={project.error} empty={!project.data} onRetry={()=>void project.refetch()}>{project.data&&<><header className={card}><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm text-muted-foreground">{project.data.project_code}</p><h1 className="text-3xl font-semibold">{project.data.project_name}</h1><p>{project.data.description||'No description provided.'}</p></div><Link className={button} to="edit">Edit</Link></div><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-5"><Metric label="Status" value={project.data.status.replace('_',' ')}/><Metric label="Progress" value={`${summary.data?.progress_percentage??'—'}%`}/><Metric label="Tasks" value={`${summary.data?.completed_task_count??0}/${summary.data?.task_count??0}`}/><Metric label="Hours" value={summary.data?.time_hours??'—'}/><Metric label="Next due" value={summary.data?.next_due_date??'—'}/></div></header><nav aria-label="Project workspace" className="flex gap-2 overflow-x-auto">{Object.keys(related).map(tab=><button key={tab} onClick={()=>setTabs({tab})} className={`rounded-md px-3 py-2 capitalize ${active===tab?'bg-primary text-primary-foreground':'bg-muted text-muted-foreground'}`}>{tab}</button>)}</nav><div className={card}><State loading={related[active as keyof typeof related].isLoading} error={related[active as keyof typeof related].error} empty={!related[active as keyof typeof related].data?.items.length} onRetry={()=>void related[active as keyof typeof related].refetch()}><ul className="divide-y divide-border">{related[active as keyof typeof related].data?.items.map(item=><li className="py-3" key={item.id}>{'task_name' in item?item.task_name:'milestone_name' in item?item.milestone_name:'hours_worked' in item?`${item.entry_date} · ${item.hours_worked}h`:'action' in item?`${item.action} · ${item.correlation_id}`:item.employee_id}</li>)}</ul></State></div></>}</State></main>}
const Metric=({label,value}:{label:string;value:string|number})=><div className="rounded-lg bg-muted p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="font-semibold capitalize">{value}</p></div>;
export function TaskDetailPage(){return <DetailView title="Task" queryKey="task" query={taskService.get} render={(r:Task)=><article className={card}><h1 className="text-2xl font-semibold">{r.task_code} · {r.task_name}</h1><p className="mt-2 text-muted-foreground">{r.description||'No description.'}</p><dl className="mt-4 grid grid-cols-2 gap-3"><Metric label="Status" value={r.status}/><Metric label="Priority" value={r.priority}/><Metric label="Progress" value={`${r.percent_complete}%`}/><Metric label="Actual hours" value={r.actual_hours}/></dl></article>}/>}
export function ProjectMemberDetailPage(){return <DetailView title="Project member" queryKey="member" query={memberService.get} render={(r:ProjectMember)=><article className={card}><h1 className="text-2xl font-semibold">Team member</h1><p>{r.employee_id}</p><Metric label="Allocation" value={`${r.allocation_percentage}%`}/></article>}/>}
export function TimeEntryDetailPage(){return <DetailView title="Time entry" queryKey="time-entry" query={timeEntryService.get} render={(r:TimeEntry)=><article className={card}><h1 className="text-2xl font-semibold">{r.hours_worked} hours on {r.entry_date}</h1><p>{r.description}</p></article>}/>}
export function MilestoneDetailPage(){return <DetailView title="Milestone" queryKey="milestone" query={milestoneService.get} render={(r:ProjectMilestone)=><article className={card}><h1 className="text-2xl font-semibold">{r.milestone_name}</h1><p>Target {r.target_date}</p><p>{r.description}</p></article>}/>}

function CreateShell({kind}:{kind:'project'|'task'|'member'|'time'|'milestone'}){const navigate=useNavigate();const mutation=useMutation({mutationFn:async(data:object)=>{const key=createIdempotencyKey(kind);if(kind==='project')return projectService.create(data as Parameters<typeof projectService.create>[0],key);if(kind==='task')return taskService.create(data as Parameters<typeof taskService.create>[0],key);if(kind==='member')return memberService.create(data as Parameters<typeof memberService.create>[0],key);if(kind==='time')return timeEntryService.create(data as Parameters<typeof timeEntryService.create>[0],key);return milestoneService.create(data as Parameters<typeof milestoneService.create>[0],key)},onSuccess:value=>navigate(`/project-management/${kind==='project'?'projects':kind==='task'?'tasks':kind==='member'?'members':kind==='time'?'time-entries':'milestones'}/${value.id}`)});const props={pending:mutation.isPending,error:mutation.error?.message};if(kind==='project')return <ProjectForm {...props} onSave={d=>mutation.mutate(d)}/>;if(kind==='task')return <TaskForm {...props} onSave={d=>mutation.mutate(d)}/>;if(kind==='member')return <MemberForm {...props} onSave={d=>mutation.mutate(d)}/>;if(kind==='time')return <TimeEntryForm {...props} onSave={d=>mutation.mutate(d)}/>;return <MilestoneForm {...props} onSave={d=>mutation.mutate(d)}/>}
export function CreateProjectPage(){useTitle('Create project');return <main className="p-4 sm:p-6"><CreateShell kind="project"/></main>}export function CreateTaskPage(){useTitle('Create task');return <main className="p-4 sm:p-6"><CreateShell kind="task"/></main>}export function CreateProjectMemberPage(){useTitle('Add project member');return <main className="p-4 sm:p-6"><CreateShell kind="member"/></main>}export function CreateTimeEntryPage(){useTitle('Log time');return <main className="p-4 sm:p-6"><CreateShell kind="time"/></main>}export function CreateMilestonePage(){useTitle('Create milestone');return <main className="p-4 sm:p-6"><CreateShell kind="milestone"/></main>}

export function EditProjectPage(){const{id=''}=useParams();const nav=useNavigate();const q=useQuery({queryKey:['project',id],queryFn:()=>projectService.get(id)});const m=useMutation({mutationFn:(data:Parameters<typeof projectService.create>[0])=>projectService.update(id,{...data,version:q.data?.version??0,idempotency_key:createIdempotencyKey('project-update')}),onSuccess:()=>nav(`/project-management/projects/${id}`)});useTitle('Edit project');return <main className="p-4 sm:p-6"><State loading={q.isLoading} error={q.error} empty={!q.data} onRetry={()=>void q.refetch()}>{q.data&&<ProjectForm initial={q.data} pending={m.isPending} error={m.error?.message} onSave={d=>m.mutate(d)}/>}</State></main>}
function SimpleEditor({title,load,initialLabel,save}:{title:string;load:(id:string)=>Promise<{readonly id:string;readonly version?:number}>;initialLabel:(value:{readonly id:string;readonly version?:number})=>string;save:(id:string,value:string,version:number)=>Promise<{id:string}>}){useTitle(title);const{id=''}=useParams();const nav=useNavigate();const q=useQuery({queryKey:['edit',title,id],queryFn:()=>load(id)});const[value,setValue]=useState('');useEffect(()=>{if(q.data)setValue(initialLabel(q.data))},[q.data,initialLabel]);const m=useMutation({mutationFn:()=>save(id,value,q.data?.version??1),onSuccess:()=>nav('..')});return <main className="p-4 sm:p-6"><State loading={q.isLoading} error={q.error} empty={!q.data} onRetry={()=>void q.refetch()}>{q.data&&<form className={`${card} mx-auto grid max-w-xl gap-4`} onSubmit={e=>{e.preventDefault();m.mutate()}}><h1 className="text-2xl font-semibold">{title}</h1><label className="grid gap-1">Value<input required className="rounded-md border border-border bg-background px-3 py-2" value={value} onChange={e=>setValue(e.target.value)}/></label>{m.error&&<p role="alert" className="text-destructive">{m.error.message}</p>}<button className={button} disabled={m.isPending}>{m.isPending?'Saving…':'Save changes'}</button></form>}</State></main>}
export function EditTaskPage(){return <SimpleEditor title="Edit task" load={taskService.get} initialLabel={v=>(v as Task).task_name} save={(id,value,version)=>taskService.update(id,{task_name:value,version,idempotency_key:createIdempotencyKey('task-update')})}/>}export function EditProjectMemberPage(){return <SimpleEditor title="Edit project member" load={memberService.get} initialLabel={v=>(v as ProjectMember).allocation_percentage} save={(id,value)=>memberService.update(id,{allocation_percentage:value,idempotency_key:createIdempotencyKey('member-update')})}/>}export function EditTimeEntryPage(){return <SimpleEditor title="Edit time entry" load={timeEntryService.get} initialLabel={v=>(v as TimeEntry).description} save={(id,value,version)=>timeEntryService.update(id,{description:value,version,idempotency_key:createIdempotencyKey('time-update')})}/>}export function EditMilestonePage(){return <SimpleEditor title="Edit milestone" load={milestoneService.get} initialLabel={v=>(v as ProjectMilestone).milestone_name} save={(id,value,version)=>milestoneService.update(id,{milestone_name:value,version,idempotency_key:createIdempotencyKey('milestone-update')})}/>} 

export function ProjectDashboardPage(){useTitle('Project dashboard');const summary=useQuery({queryKey:['portfolio-dashboard'],queryFn:projectService.dashboard});const projects=useQuery({queryKey:['projects','dashboard'],queryFn:()=>projectService.list({page_size:6})});return <main className="mx-auto grid max-w-6xl gap-5 p-4 sm:p-6"><h1 className="text-3xl font-semibold">Project dashboard</h1><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Metric label="Projects" value={summary.data?.project_count??'—'}/><Metric label="Active" value={summary.data?.active_project_count??'—'}/><Metric label="Overdue tasks" value={summary.data?.overdue_task_count??'—'}/><Metric label="Upcoming milestones" value={summary.data?.upcoming_milestone_count??'—'}/></div><State loading={projects.isLoading||summary.isLoading} error={projects.error||summary.error} empty={!projects.data?.items.length} onRetry={()=>{void projects.refetch();void summary.refetch()}}><div className="grid gap-3 md:grid-cols-2">{projects.data?.items.map(p=><Link className={card} key={p.id} to={`/project-management/projects/${p.id}`}><h2 className="font-semibold">{p.project_name}</h2><p className="text-sm text-muted-foreground">{p.status}</p></Link>)}</div></State></main>}
export function MyWorkPage(){useTitle('My work');return <main className="mx-auto max-w-5xl p-4 sm:p-6"><h1 className="text-3xl font-semibold">My work</h1><div className={`${card} mt-5`}><AlertTriangle className="mb-2"/><h2 className="font-semibold">Employee identity is not linked</h2><p className="text-sm text-muted-foreground">My Work becomes available when the optional HR module provides a tenant-safe employee link. No assignments are guessed from your user ID.</p></div></main>}
export function ProjectManagementSettingsPage(){useTitle('Project management settings');const env='development' as const;const q=useQuery({queryKey:['configuration',env],queryFn:()=>configurationService.active(env)});const[summary,setSummary]=useState('Operational policy update');const m=useMutation({mutationFn:()=>configurationService.draft({environment:env,values:q.data?{max_daily_hours:q.data.max_daily_hours,max_allocation_percentage:q.data.max_allocation_percentage}: {},change_summary:summary})});return <main className="mx-auto max-w-4xl p-4 sm:p-6"><h1 className="text-3xl font-semibold">Project management settings</h1><State loading={q.isLoading} error={q.error} empty={!q.data} onRetry={()=>void q.refetch()}>{q.data&&<div className={`${card} mt-5 grid gap-4`}><Metric label="Active version" value={q.data.version}/><Metric label="Maximum daily hours" value={q.data.max_daily_hours}/><Metric label="Maximum allocation" value={`${q.data.max_allocation_percentage}%`}/><label className="grid gap-1">Change summary<input className="rounded-md border border-border bg-background px-3 py-2" value={summary} onChange={e=>setSummary(e.target.value)}/></label><button className={button} disabled={m.isPending} onClick={()=>m.mutate()}>Create draft and preview</button>{m.data&&<Link className={button} to="history">Review version history</Link>}</div>}</State></main>}
export function ConfigurationHistoryPage(){useTitle('Configuration history');const q=useQuery({queryKey:['configuration-history'],queryFn:()=>configurationService.versions()});return <main className="mx-auto max-w-4xl p-4 sm:p-6"><h1 className="text-3xl font-semibold">Configuration history</h1><State loading={q.isLoading} error={q.error} empty={!q.data?.items.length} onRetry={()=>void q.refetch()}><div className="mt-5 grid gap-3">{q.data?.items.map(v=><article className={card} key={v.id}><div className="flex justify-between"><h2 className="font-semibold">Version {v.version}</h2><span className="rounded bg-muted px-2 py-1 text-xs">{v.state}</span></div><p>{v.change_summary}</p><p className="text-xs text-muted-foreground">{v.created_at} · {v.created_by_id}</p></article>)}</div></State></main>}
