import { lazy } from 'react';
import { Activity, BookOpen, DatabaseBackup, FilePlus2, FolderOpen, LayoutDashboard, Pencil, RotateCcw, Settings, TestTube2 } from 'lucide-react';
import type { TenantRoute } from '@/navigation/tenant-route-types';

export const tenantRoutes = [
  { id: 'backup_disaster_recovery.overview', module: 'backup_disaster_recovery', path: '/backup-disaster-recovery', sourceFile: 'modules/backup_disaster_recovery/pages/DisasterRecoveryDashboardPage.tsx', Page: lazy(() => import('./pages/DisasterRecoveryDashboardPage').then(({ DisasterRecoveryDashboardPage }) => ({ default: DisasterRecoveryDashboardPage }))), navigation: { type: 'sidebar', label: 'Overview', icon: LayoutDashboard, order: 500 } },
  { id: 'backup_disaster_recovery.backups.create', module: 'backup_disaster_recovery', path: '/backup-disaster-recovery/backups/new', sourceFile: 'modules/backup_disaster_recovery/pages/BackupExecutionCreatePage.tsx', Page: lazy(() => import('./pages/BackupExecutionCreatePage').then(({ BackupExecutionCreatePage }) => ({ default: BackupExecutionCreatePage }))), navigation: { type: 'sidebar', label: 'Request backup', icon: FilePlus2, order: 505 } },
  { id: 'backup_disaster_recovery.recovery_points.list', module: 'backup_disaster_recovery', path: '/backup-disaster-recovery/recovery-points', sourceFile: 'modules/backup_disaster_recovery/pages/RecoveryPointListPage.tsx', Page: lazy(() => import('./pages/RecoveryPointListPage').then(({ RecoveryPointListPage }) => ({ default: RecoveryPointListPage }))), navigation: { type: 'sidebar', label: 'Recovery points', icon: DatabaseBackup, order: 510 } },
  { id: 'backup_disaster_recovery.recovery_points.open', module: 'backup_disaster_recovery', path: '/backup-disaster-recovery/recovery-points/open', sourceFile: 'modules/backup_disaster_recovery/pages/RecoveryPointDetailPage.tsx', Page: lazy(() => import('./pages/RecoveryPointDetailPage').then(({ RecoveryPointDetailPage }) => ({ default: RecoveryPointDetailPage }))), navigation: { type: 'sidebar', label: 'Open recovery point', icon: FolderOpen, order: 515 } },
  { id: 'backup_disaster_recovery.recovery_points.detail', module: 'backup_disaster_recovery', path: '/backup-disaster-recovery/recovery-points/:id', sourceFile: 'modules/backup_disaster_recovery/pages/RecoveryPointDetailPage.tsx', Page: lazy(() => import('./pages/RecoveryPointDetailPage').then(({ RecoveryPointDetailPage }) => ({ default: RecoveryPointDetailPage }))), navigation: { type: 'contextual', parentRouteId: 'backup_disaster_recovery.recovery_points.list' } },
  { id: 'backup_disaster_recovery.restores.list', module: 'backup_disaster_recovery', path: '/backup-disaster-recovery/restores', sourceFile: 'modules/backup_disaster_recovery/pages/RestoreRunListPage.tsx', Page: lazy(() => import('./pages/RestoreRunListPage').then(({ RestoreRunListPage }) => ({ default: RestoreRunListPage }))), navigation: { type: 'sidebar', label: 'Restores', icon: RotateCcw, order: 520 } },
  { id: 'backup_disaster_recovery.restores.create', module: 'backup_disaster_recovery', path: '/backup-disaster-recovery/restores/new', sourceFile: 'modules/backup_disaster_recovery/pages/RestoreRunCreatePage.tsx', Page: lazy(() => import('./pages/RestoreRunCreatePage').then(({ RestoreRunCreatePage }) => ({ default: RestoreRunCreatePage }))), navigation: { type: 'sidebar', label: 'Plan restore', icon: RotateCcw, order: 525 } },
  { id: 'backup_disaster_recovery.restores.open', module: 'backup_disaster_recovery', path: '/backup-disaster-recovery/restores/open', sourceFile: 'modules/backup_disaster_recovery/pages/RestoreRunDetailPage.tsx', Page: lazy(() => import('./pages/RestoreRunDetailPage').then(({ RestoreRunDetailPage }) => ({ default: RestoreRunDetailPage }))), navigation: { type: 'sidebar', label: 'Open restore run', icon: FolderOpen, order: 526 } },
  { id: 'backup_disaster_recovery.restores.detail', module: 'backup_disaster_recovery', path: '/backup-disaster-recovery/restores/:id', sourceFile: 'modules/backup_disaster_recovery/pages/RestoreRunDetailPage.tsx', Page: lazy(() => import('./pages/RestoreRunDetailPage').then(({ RestoreRunDetailPage }) => ({ default: RestoreRunDetailPage }))), navigation: { type: 'contextual', parentRouteId: 'backup_disaster_recovery.restores.list' } },
  { id: 'backup_disaster_recovery.runbooks.list', module: 'backup_disaster_recovery', path: '/backup-disaster-recovery/runbooks', sourceFile: 'modules/backup_disaster_recovery/pages/DRRunbookListPage.tsx', Page: lazy(() => import('./pages/DRRunbookListPage').then(({ DRRunbookListPage }) => ({ default: DRRunbookListPage }))), navigation: { type: 'sidebar', label: 'Runbooks', icon: BookOpen, order: 530 } },
  { id: 'backup_disaster_recovery.runbooks.create', module: 'backup_disaster_recovery', path: '/backup-disaster-recovery/runbooks/new', sourceFile: 'modules/backup_disaster_recovery/pages/DRRunbookCreatePage.tsx', Page: lazy(() => import('./pages/DRRunbookCreatePage').then(({ DRRunbookCreatePage }) => ({ default: DRRunbookCreatePage }))), navigation: { type: 'sidebar', label: 'Create runbook', icon: FilePlus2, order: 535 } },
  { id: 'backup_disaster_recovery.runbooks.open', module: 'backup_disaster_recovery', path: '/backup-disaster-recovery/runbooks/open', sourceFile: 'modules/backup_disaster_recovery/pages/DRRunbookDetailPage.tsx', Page: lazy(() => import('./pages/DRRunbookDetailPage').then(({ DRRunbookDetailPage }) => ({ default: DRRunbookDetailPage }))), navigation: { type: 'sidebar', label: 'Open runbook', icon: FolderOpen, order: 536 } },
  { id: 'backup_disaster_recovery.runbooks.open_edit', module: 'backup_disaster_recovery', path: '/backup-disaster-recovery/runbooks/open/edit', sourceFile: 'modules/backup_disaster_recovery/pages/DRRunbookEditPage.tsx', Page: lazy(() => import('./pages/DRRunbookEditPage').then(({ DRRunbookEditPage }) => ({ default: DRRunbookEditPage }))), navigation: { type: 'sidebar', label: 'Edit runbook', icon: Pencil, order: 537 } },
  { id: 'backup_disaster_recovery.runbooks.detail', module: 'backup_disaster_recovery', path: '/backup-disaster-recovery/runbooks/:id', sourceFile: 'modules/backup_disaster_recovery/pages/DRRunbookDetailPage.tsx', Page: lazy(() => import('./pages/DRRunbookDetailPage').then(({ DRRunbookDetailPage }) => ({ default: DRRunbookDetailPage }))), navigation: { type: 'contextual', parentRouteId: 'backup_disaster_recovery.runbooks.list' } },
  { id: 'backup_disaster_recovery.runbooks.edit', module: 'backup_disaster_recovery', path: '/backup-disaster-recovery/runbooks/:id/edit', sourceFile: 'modules/backup_disaster_recovery/pages/DRRunbookEditPage.tsx', Page: lazy(() => import('./pages/DRRunbookEditPage').then(({ DRRunbookEditPage }) => ({ default: DRRunbookEditPage }))), navigation: { type: 'contextual', parentRouteId: 'backup_disaster_recovery.runbooks.list' } },
  { id: 'backup_disaster_recovery.exercises.list', module: 'backup_disaster_recovery', path: '/backup-disaster-recovery/exercises', sourceFile: 'modules/backup_disaster_recovery/pages/DRExerciseListPage.tsx', Page: lazy(() => import('./pages/DRExerciseListPage').then(({ DRExerciseListPage }) => ({ default: DRExerciseListPage }))), navigation: { type: 'sidebar', label: 'Exercises', icon: TestTube2, order: 540 } },
  { id: 'backup_disaster_recovery.exercises.create', module: 'backup_disaster_recovery', path: '/backup-disaster-recovery/exercises/new', sourceFile: 'modules/backup_disaster_recovery/pages/DRExerciseCreatePage.tsx', Page: lazy(() => import('./pages/DRExerciseCreatePage').then(({ DRExerciseCreatePage }) => ({ default: DRExerciseCreatePage }))), navigation: { type: 'sidebar', label: 'Schedule exercise', icon: FilePlus2, order: 545 } },
  { id: 'backup_disaster_recovery.exercises.open', module: 'backup_disaster_recovery', path: '/backup-disaster-recovery/exercises/open', sourceFile: 'modules/backup_disaster_recovery/pages/DRExerciseDetailPage.tsx', Page: lazy(() => import('./pages/DRExerciseDetailPage').then(({ DRExerciseDetailPage }) => ({ default: DRExerciseDetailPage }))), navigation: { type: 'sidebar', label: 'Open exercise', icon: FolderOpen, order: 546 } },
  { id: 'backup_disaster_recovery.exercises.open_edit', module: 'backup_disaster_recovery', path: '/backup-disaster-recovery/exercises/open/edit', sourceFile: 'modules/backup_disaster_recovery/pages/DRExerciseEditPage.tsx', Page: lazy(() => import('./pages/DRExerciseEditPage').then(({ DRExerciseEditPage }) => ({ default: DRExerciseEditPage }))), navigation: { type: 'sidebar', label: 'Edit exercise', icon: Pencil, order: 547 } },
  { id: 'backup_disaster_recovery.exercises.detail', module: 'backup_disaster_recovery', path: '/backup-disaster-recovery/exercises/:id', sourceFile: 'modules/backup_disaster_recovery/pages/DRExerciseDetailPage.tsx', Page: lazy(() => import('./pages/DRExerciseDetailPage').then(({ DRExerciseDetailPage }) => ({ default: DRExerciseDetailPage }))), navigation: { type: 'contextual', parentRouteId: 'backup_disaster_recovery.exercises.list' } },
  { id: 'backup_disaster_recovery.exercises.edit', module: 'backup_disaster_recovery', path: '/backup-disaster-recovery/exercises/:id/edit', sourceFile: 'modules/backup_disaster_recovery/pages/DRExerciseEditPage.tsx', Page: lazy(() => import('./pages/DRExerciseEditPage').then(({ DRExerciseEditPage }) => ({ default: DRExerciseEditPage }))), navigation: { type: 'contextual', parentRouteId: 'backup_disaster_recovery.exercises.list' } },
  { id: 'backup_disaster_recovery.reports.objectives', module: 'backup_disaster_recovery', path: '/backup-disaster-recovery/reports/objectives', sourceFile: 'modules/backup_disaster_recovery/pages/RecoveryObjectivesReportPage.tsx', Page: lazy(() => import('./pages/RecoveryObjectivesReportPage').then(({ RecoveryObjectivesReportPage }) => ({ default: RecoveryObjectivesReportPage }))), navigation: { type: 'sidebar', label: 'Recovery objectives', icon: Activity, order: 550 } },
  { id: 'backup_disaster_recovery.configuration', module: 'backup_disaster_recovery', path: '/backup-disaster-recovery/configuration', sourceFile: 'modules/backup_disaster_recovery/pages/BackupDisasterRecoveryConfigurationPage.tsx', Page: lazy(() => import('./pages/BackupDisasterRecoveryConfigurationPage').then(({ BackupDisasterRecoveryConfigurationPage }) => ({ default: BackupDisasterRecoveryConfigurationPage }))), navigation: { type: 'sidebar', label: 'Configuration', icon: Settings, order: 560 } },
] satisfies readonly TenantRoute[];

export default tenantRoutes;
