import { useMemo, useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { PATHS, type EndpointDeviceType, type EndpointKind, type EndpointRegisterInput } from "../contracts";
import { notificationService } from "../services/notification-service";
import { MutationError, PageShell, fieldClass, labelClass, submitForm } from "../components/NotificationUI";

const approvedSecretReference = /^(?:vault|aws-secrets|gcp-secrets|azure-keyvault):\/\/[A-Za-z0-9_./-]+$/u;

export function CreateEndpointPage() {
  const navigate = useNavigate(); const [kind, setKind] = useState<EndpointKind>("push"); const [device, setDevice] = useState<EndpointDeviceType>("web"); const [address, setAddress] = useState(""); const [name, setName] = useState(""); const [secretRef, setSecretRef] = useState("");
  const validation = useMemo(() => { if (!name.trim()) return "A display name is required."; if (!address.trim()) return "The endpoint address is required."; if (kind === "webhook") { try { const url = new URL(address); if (url.protocol !== "https:") return "Webhooks require HTTPS."; } catch { return "Enter a valid webhook URL."; } if (!approvedSecretReference.test(secretRef)) return "Webhook signing requires an approved vault or cloud secret-manager URI."; } return null; }, [address, kind, name, secretRef]);
  const create = useMutation({ mutationFn: (input: EndpointRegisterInput) => notificationService.endpoints.register(input), onSuccess: () => navigate(PATHS.ENDPOINTS) });
  return <PageShell title="Register notification endpoint" description="Sensitive addresses are encrypted by the server and never returned in full." back={{ label: "Endpoints", to: PATHS.ENDPOINTS }}><Card className="mx-auto max-w-2xl p-5"><form className="space-y-5" onSubmit={submitForm(() => { if (!validation) create.mutate({ kind, device_type: kind === "push" ? device : "", address, display_name: name.trim(), secret_ref: secretRef || undefined }); })}><MutationError error={create.error}/>{validation ? <p role="status" className="rounded-md bg-muted p-3 text-sm text-muted-foreground">{validation}</p> : null}<label className={labelClass}>Kind<select className={fieldClass} value={kind} onChange={(event) => setKind(event.target.value as EndpointKind)}><option value="push">Push device</option><option value="webhook">Webhook</option></select></label>{kind === "push" ? <label className={labelClass}>Device type<select className={fieldClass} value={device} onChange={(event) => setDevice(event.target.value as EndpointDeviceType)}><option value="web">Web</option><option value="android">Android</option><option value="ios">iOS</option></select></label> : null}<label className={labelClass}>Display name<input className={fieldClass} value={name} onChange={(event) => setName(event.target.value)}/></label><label className={labelClass}>{kind === "push" ? "Push token" : "Webhook HTTPS URL"}<input className={fieldClass} type={kind === "push" ? "password" : "url"} autoComplete="off" value={address} onChange={(event) => setAddress(event.target.value)}/><span className="block text-xs font-normal text-muted-foreground">This value is sent once over TLS and then masked.</span></label>{kind === "webhook" ? <label className={labelClass}>Signing secret reference<input className={fieldClass} placeholder="vault://notifications/webhook" value={secretRef} onChange={(event) => setSecretRef(event.target.value)}/></label> : null}<div className="flex justify-end"><Button type="submit" disabled={Boolean(validation) || create.isPending}>{create.isPending ? "Registering…" : "Register endpoint"}</Button></div></form></Card></PageShell>;
}
