import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { RotateCcw, Save } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import type { DigestMode, PreferenceUpsertInput } from "../contracts";
import { NOTIFICATION_QUERY_KEYS, notificationService } from "../services/notification-service";
import { GovernedError, MutationError, PageShell, PageSkeleton, fieldClass } from "../components/NotificationUI";

export function NotificationPreferencesPage() {
  const client = useQueryClient(); const query = useQuery({ queryKey: NOTIFICATION_QUERY_KEYS.preferences, queryFn: ({ signal }) => notificationService.preferences.get(signal) });
  const [draft, setDraft] = useState<readonly PreferenceUpsertInput[]>([]);
  useEffect(() => { if (query.data) setDraft(query.data.preferences.map(({ channel, category, enabled, digest_mode, quiet_hours_start, quiet_hours_end, timezone }) => ({ channel, category, enabled, digest_mode, quiet_hours_start, quiet_hours_end, timezone }))); }, [query.data]);
  const save = useMutation({ mutationFn: () => notificationService.preferences.replace({ preferences: draft }), onSuccess: (value) => client.setQueryData(NOTIFICATION_QUERY_KEYS.preferences, value) });
  const reset = useMutation({ mutationFn: () => notificationService.preferences.reset(), onSuccess: (value) => { client.setQueryData(NOTIFICATION_QUERY_KEYS.preferences, value); setDraft(value.preferences.map(({ channel, category, enabled, digest_mode, quiet_hours_start, quiet_hours_end, timezone }) => ({ channel, category, enabled, digest_mode, quiet_hours_start, quiet_hours_end, timezone }))); } });
  const update = (index: number, patch: Partial<PreferenceUpsertInput>) => setDraft((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item));
  if (query.isLoading) return <PageSkeleton/>; if (query.error || !query.data) return <PageShell title="Notification preferences" description="Control how and when you receive alerts."><GovernedError error={query.error} retry={() => void query.refetch()} subject="Preferences"/></PageShell>;
  return <PageShell title="Notification preferences" description="Choose delivery by channel and category. Mandatory security notifications remain locked by policy." actions={<><Button variant="outline" disabled={save.isPending || reset.isPending} onClick={() => reset.mutate()}><RotateCcw className="mr-2 h-4 w-4"/>Reset to defaults</Button><Button disabled={save.isPending || reset.isPending} onClick={() => save.mutate()}><Save className="mr-2 h-4 w-4"/>{save.isPending ? "Saving…" : "Save preferences"}</Button></>}>
    <MutationError error={save.error ?? reset.error}/><Card className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><caption className="sr-only">Channel and category preference matrix</caption><thead className="border-b bg-muted/50 text-left"><tr><th className="p-4">Category</th><th className="p-4">Channel</th><th className="p-4">Enabled</th><th className="p-4">Digest</th><th className="p-4">Quiet hours</th><th className="p-4">Timezone</th></tr></thead><tbody className="divide-y">{draft.map((item, index) => { const source = query.data.preferences[index]; return <tr key={`${item.channel}:${item.category}`}><td className="p-4 font-medium">{item.category.replaceAll("_", " ")}{source?.mandatory ? <span className="ml-2 rounded-full bg-muted px-2 py-0.5 text-xs">Mandatory</span> : null}</td><td className="p-4 capitalize">{item.channel.replace("_", " ")}</td><td className="p-4"><input aria-label={`Enable ${item.category} ${item.channel}`} type="checkbox" checked={item.enabled} disabled={source?.mandatory} onChange={(event) => update(index, { enabled: event.target.checked })}/></td><td className="p-4"><select aria-label={`Digest for ${item.category} ${item.channel}`} className={fieldClass} value={item.digest_mode} onChange={(event) => update(index, { digest_mode: event.target.value as DigestMode })}><option value="immediate">Immediate</option><option value="hourly">Hourly</option><option value="daily">Daily</option><option value="weekly">Weekly</option></select></td><td className="p-4"><div className="flex gap-2"><input aria-label="Quiet start" type="time" className={fieldClass} value={item.quiet_hours_start ?? ""} onChange={(event) => update(index, { quiet_hours_start: event.target.value || null })}/><input aria-label="Quiet end" type="time" className={fieldClass} value={item.quiet_hours_end ?? ""} onChange={(event) => update(index, { quiet_hours_end: event.target.value || null })}/></div></td><td className="p-4"><input aria-label="Timezone" className={fieldClass} value={item.timezone} onChange={(event) => update(index, { timezone: event.target.value })}/></td></tr>; })}</tbody></table></Card>
  </PageShell>;
}
