import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, Copy, Plus, Search } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { PATHS, type TemplateQuery, type TemplateStatus } from "../contracts";
import { NOTIFICATION_QUERY_KEYS, notificationService } from "../services/notification-service";
import { EmptyPanel, GovernedError, MutationError, PageShell, PageSkeleton, Pagination, PERMISSIONS, StatusPill, can, fieldClass, formatDate, transitionKey } from "../components/NotificationUI";

export function TemplateListPage() {
  const client = useQueryClient(); const [filters, setFilters] = useState<TemplateQuery>({ page: 1, page_size: 25 }); const query = useQuery({ queryKey: NOTIFICATION_QUERY_KEYS.templates(filters), queryFn: ({ signal }) => notificationService.templates.list(filters, signal) });
  const archive = useMutation({ mutationFn: (id: string) => notificationService.templates.archive(id, { transition_key: transitionKey("archive") }), onSuccess: () => client.invalidateQueries({ queryKey: ["notifications", "templates"] }) });
  const clone = useMutation({ mutationFn: async (id: string) => { const source = await notificationService.templates.get(id); const version = source.latest_version ?? source.active_version; if (!version) throw new Error("Template has no version to clone."); return notificationService.templates.create({ code: `${source.code}.copy.${Date.now()}`, name: `${source.name} copy`, category: source.category, channel: source.channel, locale: source.locale, subject_template: version.subject_template, body_template: version.body_template, variables_schema: version.variables_schema, content_type: version.content_type }); }, onSuccess: () => client.invalidateQueries({ queryKey: ["notifications", "templates"] }) });
  if (query.isLoading) return <PageSkeleton/>; if (query.error) return <PageShell title="Notification templates" description="Versioned, sandboxed message content."><GovernedError error={query.error} retry={() => void query.refetch()} subject="Templates"/></PageShell>;
  const items = query.data?.items ?? []; const caps = query.data?.capabilities;
  return <PageShell title="Notification templates" description="Create reusable, locale-aware templates and promote only reviewed versions." actions={can(caps, PERMISSIONS.templateCreate) ? <Link className="inline-flex rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground" to={PATHS.TEMPLATE_CREATE}><Plus className="mr-2 h-4 w-4"/>New template</Link> : undefined}><MutationError error={archive.error ?? clone.error}/><Card className="grid gap-3 p-4 sm:grid-cols-[1fr_180px]"><label className="relative"><span className="sr-only">Search templates</span><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><input className={`${fieldClass} pl-9`} placeholder="Search code or name" value={filters.search ?? ""} onChange={(e) => setFilters({ ...filters, page: 1, search: e.target.value || undefined })}/></label><select aria-label="Template status" className={fieldClass} value={filters.status ?? ""} onChange={(e) => setFilters({ ...filters, page: 1, status: (e.target.value || undefined) as TemplateStatus | undefined })}><option value="">All statuses</option><option value="draft">Draft</option><option value="active">Active</option><option value="archived">Archived</option></select></Card>{!items.length ? <EmptyPanel title="No templates found" description="Create the first governed template or change the active filters." action={can(caps, PERMISSIONS.templateCreate) ? { label: "Create template", to: PATHS.TEMPLATE_CREATE } : undefined}/> : <Card className="overflow-hidden"><ul className="divide-y">{items.map((item) => <li key={item.id} className="flex flex-col gap-4 p-4 sm:flex-row sm:items-center sm:justify-between"><div><Link className="font-semibold text-primary hover:underline" to={PATHS.TEMPLATE_DETAIL(item.id)}>{item.name}</Link><p className="mt-1 font-mono text-xs text-muted-foreground">{item.code} · {item.channel} · {item.locale}</p><div className="mt-2 flex items-center gap-2"><StatusPill value={item.status}/><span className="text-xs text-muted-foreground">Updated {formatDate(item.updated_at)}</span></div></div><div className="flex gap-2">{can(caps, PERMISSIONS.templateCreate) ? <Button variant="outline" size="sm" disabled={clone.isPending} onClick={() => clone.mutate(item.id)}><Copy className="mr-1 h-4 w-4"/>Clone</Button> : null}{item.status !== "archived" && can(caps, PERMISSIONS.templateArchive) ? <Button variant="outline" size="sm" disabled={archive.isPending} onClick={() => archive.mutate(item.id)}><Archive className="mr-1 h-4 w-4"/>Archive</Button> : null}</div></li>)}</ul><Pagination page={query.data?.pagination.page ?? 1} totalPages={query.data?.pagination.total_pages ?? 1} onPage={(page) => setFilters({ ...filters, page })}/></Card>}</PageShell>;
}
