import { lazy } from 'react';
import { BrainCircuit, FileSearch, LayoutTemplate, Tags } from 'lucide-react';
import type { TenantRoute } from '@/navigation/tenant-route-types';

export const tenantRoutes = [
  { id: 'document-intelligence.extractions.list', module: 'document_intelligence', path: '/document-intelligence/extractions', sourceFile: 'modules/document_intelligence/pages/ExtractionDashboardPage.tsx', Page: lazy(() => import('./pages/ExtractionDashboardPage').then(({ ExtractionDashboardPage }) => ({ default: ExtractionDashboardPage }))), navigation: { type: 'sidebar', label: 'Extractions', icon: FileSearch, order: 300 } },
  { id: 'document-intelligence.extractions.create', module: 'document_intelligence', path: '/document-intelligence/extractions/new', sourceFile: 'modules/document_intelligence/pages/CreateExtractionPage.tsx', Page: lazy(() => import('./pages/CreateExtractionPage').then(({ CreateExtractionPage }) => ({ default: CreateExtractionPage }))), navigation: { type: 'contextual', parentRouteId: 'document-intelligence.extractions.list' } },
  { id: 'document-intelligence.extractions.detail', module: 'document_intelligence', path: '/document-intelligence/extractions/:id', sourceFile: 'modules/document_intelligence/pages/ExtractionDetailPage.tsx', Page: lazy(() => import('./pages/ExtractionDetailPage').then(({ ExtractionDetailPage }) => ({ default: ExtractionDetailPage }))), navigation: { type: 'contextual', parentRouteId: 'document-intelligence.extractions.list' } },
  { id: 'document-intelligence.classifications.list', module: 'document_intelligence', path: '/document-intelligence/classifications', sourceFile: 'modules/document_intelligence/pages/ClassificationOverviewPage.tsx', Page: lazy(() => import('./pages/ClassificationOverviewPage').then(({ ClassificationOverviewPage }) => ({ default: ClassificationOverviewPage }))), navigation: { type: 'sidebar', label: 'Classifications', icon: Tags, order: 310 } },
  { id: 'document-intelligence.classifications.detail', module: 'document_intelligence', path: '/document-intelligence/classifications/:id', sourceFile: 'modules/document_intelligence/pages/ClassificationDetailPage.tsx', Page: lazy(() => import('./pages/ClassificationDetailPage').then(({ ClassificationDetailPage }) => ({ default: ClassificationDetailPage }))), navigation: { type: 'contextual', parentRouteId: 'document-intelligence.classifications.list' } },
  { id: 'document-intelligence.templates.list', module: 'document_intelligence', path: '/document-intelligence/templates', sourceFile: 'modules/document_intelligence/pages/TemplateListPage.tsx', Page: lazy(() => import('./pages/TemplateListPage').then(({ TemplateListPage }) => ({ default: TemplateListPage }))), navigation: { type: 'sidebar', label: 'Templates', icon: LayoutTemplate, order: 320 } },
  { id: 'document-intelligence.templates.create', module: 'document_intelligence', path: '/document-intelligence/templates/new', sourceFile: 'modules/document_intelligence/pages/CreateTemplatePage.tsx', Page: lazy(() => import('./pages/CreateTemplatePage').then(({ CreateTemplatePage }) => ({ default: CreateTemplatePage }))), navigation: { type: 'contextual', parentRouteId: 'document-intelligence.templates.list' } },
  { id: 'document-intelligence.templates.detail', module: 'document_intelligence', path: '/document-intelligence/templates/:id', sourceFile: 'modules/document_intelligence/pages/TemplateDetailPage.tsx', Page: lazy(() => import('./pages/TemplateDetailPage').then(({ TemplateDetailPage }) => ({ default: TemplateDetailPage }))), navigation: { type: 'contextual', parentRouteId: 'document-intelligence.templates.list' } },
  { id: 'document-intelligence.templates.edit', module: 'document_intelligence', path: '/document-intelligence/templates/:id/edit', sourceFile: 'modules/document_intelligence/pages/EditTemplatePage.tsx', Page: lazy(() => import('./pages/EditTemplatePage').then(({ EditTemplatePage }) => ({ default: EditTemplatePage }))), navigation: { type: 'contextual', parentRouteId: 'document-intelligence.templates.list' } },
  { id: 'document-intelligence.training.list', module: 'document_intelligence', path: '/document-intelligence/training', sourceFile: 'modules/document_intelligence/pages/TrainingModelPage.tsx', Page: lazy(() => import('./pages/TrainingModelPage').then(({ TrainingModelPage }) => ({ default: TrainingModelPage }))), navigation: { type: 'sidebar', label: 'Training & models', icon: BrainCircuit, order: 330 } },
  { id: 'document-intelligence.training.create', module: 'document_intelligence', path: '/document-intelligence/training/new', sourceFile: 'modules/document_intelligence/pages/CreateTrainingJobPage.tsx', Page: lazy(() => import('./pages/CreateTrainingJobPage').then(({ CreateTrainingJobPage }) => ({ default: CreateTrainingJobPage }))), navigation: { type: 'contextual', parentRouteId: 'document-intelligence.training.list' } },
  { id: 'document-intelligence.training.detail', module: 'document_intelligence', path: '/document-intelligence/training/:id', sourceFile: 'modules/document_intelligence/pages/TrainingJobDetailPage.tsx', Page: lazy(() => import('./pages/TrainingJobDetailPage').then(({ TrainingJobDetailPage }) => ({ default: TrainingJobDetailPage }))), navigation: { type: 'contextual', parentRouteId: 'document-intelligence.training.list' } },
] satisfies readonly TenantRoute[];

export default tenantRoutes;
