import{lazy,type ComponentType}from'react';import{FolderKanban,Gauge,ListTodo,Settings,Clock,UserCheck}from'lucide-react';import type{TenantRoute}from'@/navigation/tenant-route-types';
const modes=['development','self-hosted','saas']as const;const contextual=(parentRouteId:string)=>({type:'contextual' as const,parentRouteId});
type Pages=typeof import('./pages/ModulePages');type PageName={ [K in keyof Pages]:Pages[K] extends ComponentType ? K:never}[keyof Pages];
const page=(file:string,name:PageName)=>{void file;return lazy(async()=>{const module=await import('./pages/ModulePages');return{default:module[name] as ComponentType}})};
export const tenantRoutes=[
{id:'project_management.dashboard',module:'project_management',path:'/project-management/dashboard',title:'Project dashboard',sourceFile:'modules/project_management/pages/ProjectDashboardPage.tsx',Page:page('ProjectDashboardPage','ProjectDashboardPage'),modes,navigation:{type:'sidebar',label:'Dashboard',icon:Gauge,order:430}},
{id:'project_management.projects.list',module:'project_management',path:'/project-management/projects',title:'Projects',sourceFile:'modules/project_management/pages/ProjectListPage.tsx',Page:page('ProjectListPage','ProjectListPage'),modes,navigation:{type:'sidebar',label:'Projects',icon:FolderKanban,order:431}},
{id:'project_management.projects.create',module:'project_management',path:'/project-management/projects/new',title:'Create project',sourceFile:'modules/project_management/pages/CreateProjectPage.tsx',Page:page('CreateProjectPage','CreateProjectPage'),modes,navigation:contextual('project_management.projects.list')},
{id:'project_management.projects.detail',module:'project_management',path:'/project-management/projects/:id',title:'Project workspace',sourceFile:'modules/project_management/pages/ProjectDetailPage.tsx',Page:page('ProjectDetailPage','ProjectDetailPage'),modes,navigation:contextual('project_management.projects.list')},
{id:'project_management.projects.edit',module:'project_management',path:'/project-management/projects/:id/edit',title:'Edit project',sourceFile:'modules/project_management/pages/EditProjectPage.tsx',Page:page('EditProjectPage','EditProjectPage'),modes,navigation:contextual('project_management.projects.list')},
{id:'project_management.tasks.list',module:'project_management',path:'/project-management/tasks',title:'Tasks',sourceFile:'modules/project_management/pages/TaskListPage.tsx',Page:page('TaskListPage','TaskListPage'),modes,navigation:{type:'sidebar',label:'Tasks',icon:ListTodo,order:432}},
{id:'project_management.tasks.create',module:'project_management',path:'/project-management/tasks/new',title:'Create task',sourceFile:'modules/project_management/pages/CreateTaskPage.tsx',Page:page('CreateTaskPage','CreateTaskPage'),modes,navigation:contextual('project_management.tasks.list')},
{id:'project_management.tasks.detail',module:'project_management',path:'/project-management/tasks/:id',title:'Task',sourceFile:'modules/project_management/pages/TaskDetailPage.tsx',Page:page('TaskDetailPage','TaskDetailPage'),modes,navigation:contextual('project_management.tasks.list')},
{id:'project_management.tasks.edit',module:'project_management',path:'/project-management/tasks/:id/edit',title:'Edit task',sourceFile:'modules/project_management/pages/EditTaskPage.tsx',Page:page('EditTaskPage','EditTaskPage'),modes,navigation:contextual('project_management.tasks.list')},
{id:'project_management.my_work',module:'project_management',path:'/project-management/my-work',title:'My work',sourceFile:'modules/project_management/pages/MyWorkPage.tsx',Page:page('MyWorkPage','MyWorkPage'),modes,navigation:{type:'sidebar',label:'My Work',icon:UserCheck,order:433}},
{id:'project_management.time.list',module:'project_management',path:'/project-management/time-entries',title:'Time entries',sourceFile:'modules/project_management/pages/TimeEntryListPage.tsx',Page:page('TimeEntryListPage','TimeEntryListPage'),modes,navigation:{type:'sidebar',label:'Time',icon:Clock,order:434}},
{id:'project_management.time.create',module:'project_management',path:'/project-management/time-entries/new',title:'Log time',sourceFile:'modules/project_management/pages/CreateTimeEntryPage.tsx',Page:page('CreateTimeEntryPage','CreateTimeEntryPage'),modes,navigation:contextual('project_management.time.list')},
{id:'project_management.time.detail',module:'project_management',path:'/project-management/time-entries/:id',title:'Time entry',sourceFile:'modules/project_management/pages/TimeEntryDetailPage.tsx',Page:page('TimeEntryDetailPage','TimeEntryDetailPage'),modes,navigation:contextual('project_management.time.list')},
{id:'project_management.time.edit',module:'project_management',path:'/project-management/time-entries/:id/edit',title:'Edit time entry',sourceFile:'modules/project_management/pages/EditTimeEntryPage.tsx',Page:page('EditTimeEntryPage','EditTimeEntryPage'),modes,navigation:contextual('project_management.time.list')},
{id:'project_management.members.list',module:'project_management',path:'/project-management/members',title:'Project team',sourceFile:'modules/project_management/pages/ProjectMemberListPage.tsx',Page:page('ProjectMemberListPage','ProjectMemberListPage'),modes,navigation:contextual('project_management.projects.list')},
{id:'project_management.members.create',module:'project_management',path:'/project-management/members/new',title:'Add project member',sourceFile:'modules/project_management/pages/CreateProjectMemberPage.tsx',Page:page('CreateProjectMemberPage','CreateProjectMemberPage'),modes,navigation:contextual('project_management.projects.list')},
{id:'project_management.members.detail',module:'project_management',path:'/project-management/members/:id',title:'Project member',sourceFile:'modules/project_management/pages/ProjectMemberDetailPage.tsx',Page:page('ProjectMemberDetailPage','ProjectMemberDetailPage'),modes,navigation:contextual('project_management.projects.list')},
{id:'project_management.members.edit',module:'project_management',path:'/project-management/members/:id/edit',title:'Edit project member',sourceFile:'modules/project_management/pages/EditProjectMemberPage.tsx',Page:page('EditProjectMemberPage','EditProjectMemberPage'),modes,navigation:contextual('project_management.projects.list')},
{id:'project_management.milestones.list',module:'project_management',path:'/project-management/milestones',title:'Milestones',sourceFile:'modules/project_management/pages/MilestoneListPage.tsx',Page:page('MilestoneListPage','MilestoneListPage'),modes,navigation:contextual('project_management.projects.list')},
{id:'project_management.milestones.create',module:'project_management',path:'/project-management/milestones/new',title:'Create milestone',sourceFile:'modules/project_management/pages/CreateMilestonePage.tsx',Page:page('CreateMilestonePage','CreateMilestonePage'),modes,navigation:contextual('project_management.projects.list')},
{id:'project_management.milestones.detail',module:'project_management',path:'/project-management/milestones/:id',title:'Milestone',sourceFile:'modules/project_management/pages/MilestoneDetailPage.tsx',Page:page('MilestoneDetailPage','MilestoneDetailPage'),modes,navigation:contextual('project_management.projects.list')},
{id:'project_management.milestones.edit',module:'project_management',path:'/project-management/milestones/:id/edit',title:'Edit milestone',sourceFile:'modules/project_management/pages/EditMilestonePage.tsx',Page:page('EditMilestonePage','EditMilestonePage'),modes,navigation:contextual('project_management.projects.list')},
{id:'project_management.settings',module:'project_management',path:'/project-management/settings',title:'Project management settings',sourceFile:'modules/project_management/pages/ProjectManagementSettingsPage.tsx',Page:page('ProjectManagementSettingsPage','ProjectManagementSettingsPage'),modes,permission:'project_management.configuration:read',entitlement:'project_management.core',navigation:{type:'sidebar',label:'Settings',icon:Settings,order:435}},
{id:'project_management.settings.history',module:'project_management',path:'/project-management/settings/history',title:'Configuration history',sourceFile:'modules/project_management/pages/ConfigurationHistoryPage.tsx',Page:page('ConfigurationHistoryPage','ConfigurationHistoryPage'),modes,permission:'project_management.configuration:read',entitlement:'project_management.core',navigation:contextual('project_management.settings')}
]satisfies readonly TenantRoute[];export default tenantRoutes;
