import { useState, type FormEvent } from 'react';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { Input } from '@/components/ui/Input';
import type { DepreciationMethod, DepreciationSchedule, FixedAsset, ScheduleCreateRequest, ScheduleUpdateRequest } from '../contracts';
import { FixedAssetsApiError } from '../services/fixed-assets-service';
import { ProblemState, UnsavedChangesDialog, useUnsavedChanges } from './FixedAssetsUI';

// eslint-disable-next-line complexity
export function ScheduleForm({ schedule, assets, defaultAssetId, pending, error, onCancel, onSubmit }: { schedule?: DepreciationSchedule; assets: readonly FixedAsset[]; defaultAssetId?: string; pending: boolean; error: unknown; onCancel: () => void; onSubmit: (data: ScheduleCreateRequest | ScheduleUpdateRequest) => void }) {
  const [form, setForm] = useState<ScheduleCreateRequest>({ asset_id: schedule?.asset.id ?? defaultAssetId ?? '', method: schedule?.method, start_date: schedule?.start_date, end_date: schedule?.end_date, residual_value: schedule?.residual_value, declining_balance_rate: schedule?.declining_balance_rate, expected_total_units: schedule?.expected_total_units });
  const [dirty, setDirty] = useState(false); const [cancelOpen, setCancelOpen] = useState(false); useUnsavedChanges(dirty); const apiError = error instanceof FixedAssetsApiError ? error : undefined;
  const set = <K extends keyof ScheduleCreateRequest>(key: K, value: ScheduleCreateRequest[K]) => { setDirty(true); setForm((current) => ({ ...current, [key]: value })); };
  const submit = (event: FormEvent) => { event.preventDefault(); onSubmit(schedule ? { ...form, expected_version: schedule.version } : form); };
  return <form className="space-y-6" onSubmit={submit}>{error ? <ProblemState error={error}/> : null}<Card className="grid gap-5 p-6 md:grid-cols-2"><div><label htmlFor="schedule-asset" className="mb-1 block text-sm font-medium">Asset</label><select id="schedule-asset" className="h-10 w-full rounded-md border bg-background px-3" disabled={Boolean(schedule)} required value={form.asset_id} onChange={(event) => set('asset_id', event.target.value)}><option value="">Select capitalized asset</option>{assets.map((asset) => <option key={asset.id} value={asset.id}>{asset.asset_code} — {asset.asset_name}</option>)}</select></div><div><label htmlFor="schedule-method" className="mb-1 block text-sm font-medium">Method</label><select id="schedule-method" className="h-10 w-full rounded-md border bg-background px-3" value={form.method ?? ''} onChange={(event) => set('method', (event.target.value || undefined) as DepreciationMethod | undefined)}><option value="">Use asset method</option><option value="straight_line">Straight line</option><option value="declining_balance">Declining balance</option><option value="units_of_production">Units of production</option></select></div><Input id="schedule-start" type="date" label="Start date (optional override)" value={form.start_date ?? ''} error={apiError?.fieldError('start_date')} onChange={(event) => set('start_date', event.target.value || undefined)}/><Input id="schedule-end" type="date" label="End date (optional override)" value={form.end_date ?? ''} error={apiError?.fieldError('end_date')} onChange={(event) => set('end_date', event.target.value || undefined)}/><Input id="schedule-residual" label="Residual value override" inputMode="decimal" value={form.residual_value ?? ''} onChange={(event) => set('residual_value', event.target.value || undefined)}/>{form.method === 'declining_balance' && <Input id="schedule-rate" label="Annual declining rate" required value={form.declining_balance_rate ?? ''} onChange={(event) => set('declining_balance_rate', event.target.value)}/>} {form.method === 'units_of_production' && <Input id="schedule-units" label="Expected total units" required value={form.expected_total_units ?? ''} onChange={(event) => set('expected_total_units', event.target.value)}/>}</Card><p className="text-sm text-muted-foreground">Calculation creates an immutable preview. Posted history is never rewritten; later recalculation creates a new revision.</p><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => dirty ? setCancelOpen(true) : onCancel()}>Cancel</Button><Button type="submit" disabled={pending || !form.asset_id}>{pending ? 'Saving…' : schedule ? 'Save assumptions' : 'Create draft schedule'}</Button></div><UnsavedChangesDialog open={cancelOpen} onOpenChange={setCancelOpen} onDiscard={onCancel}/></form>;
}
