import { Input } from '@/components/ui/Input';
import type { DepreciationStrategyDescriptor, StrategyParameterValue } from '../contracts';

/** Stable, schema-driven editor boundary for namespaced paid depreciation strategies. */
export function StrategyParameterFields({ descriptor, values, disabled = false, onChange }: { descriptor: DepreciationStrategyDescriptor; values: readonly StrategyParameterValue[]; disabled?: boolean; onChange: (values: readonly StrategyParameterValue[]) => void }) {
  const current = (key: string) => values.find((item) => item.key === key)?.value ?? '';
  const update = (key: string, value: string) => onChange([...values.filter((item) => item.key !== key), { key, value }]);
  return <fieldset disabled={disabled} className="grid gap-4 rounded-md border p-4 sm:grid-cols-2"><legend className="px-2 text-sm font-semibold">{descriptor.label} · schema {descriptor.schema_version}</legend>{descriptor.parameters.map((parameter) => <div key={parameter.key}>{parameter.input_type === 'select' ? <><label htmlFor={`strategy-${parameter.key}`} className="mb-1 block text-sm font-medium">{parameter.label}</label><select id={`strategy-${parameter.key}`} className="h-10 w-full rounded-md border bg-background px-3" required={parameter.required} value={current(parameter.key)} onChange={(event) => update(parameter.key, event.target.value)}><option value="">Select</option>{parameter.options?.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></> : <Input id={`strategy-${parameter.key}`} label={parameter.label} required={parameter.required} type={parameter.input_type === 'date' ? 'date' : parameter.input_type === 'integer' || parameter.input_type === 'decimal' ? 'number' : 'text'} step={parameter.input_type === 'decimal' ? 'any' : undefined} value={current(parameter.key)} onChange={(event) => update(parameter.key, event.target.value)}/>}<p className="mt-1 text-xs text-muted-foreground">{parameter.help_text}</p></div>)}</fieldset>;
}
