import { lazy } from 'react';
import { Building2, GitCompareArrows, Layers3, ReceiptText, Settings2, Tags } from 'lucide-react';
import type { TenantRoute } from '@/navigation/tenant-route-types';

const modes = ['development', 'self-hosted', 'saas'] as const;
const contextual = (parentRouteId: string) => ({ type: 'contextual' as const, parentRouteId });

export const tenantRoutes = [
  { id: 'multi-company.companies.list', module: 'multi_company', path: '/multi-company/companies', title: 'Companies · SARAISE', sourceFile: 'modules/multi_company/pages/CompanyListPage.tsx', Page: lazy(() => import('./pages/CompanyListPage').then(({ CompanyListPage }) => ({ default: CompanyListPage }))), modes, navigation: { type: 'sidebar', label: 'Companies', icon: Building2, order: 5000 } },
  { id: 'multi-company.transactions.list', module: 'multi_company', path: '/multi-company/transactions', title: 'Intercompany Transactions · SARAISE', sourceFile: 'modules/multi_company/pages/TransactionListPage.tsx', Page: lazy(() => import('./pages/TransactionListPage').then(({ TransactionListPage }) => ({ default: TransactionListPage }))), modes, navigation: { type: 'sidebar', label: 'Transactions', icon: ReceiptText, order: 5010 } },
  { id: 'multi-company.reconciliation', module: 'multi_company', path: '/multi-company/reconciliation', title: 'Intercompany Reconciliation · SARAISE', sourceFile: 'modules/multi_company/pages/ReconciliationPage.tsx', Page: lazy(() => import('./pages/ReconciliationPage').then(({ ReconciliationPage }) => ({ default: ReconciliationPage }))), modes, navigation: { type: 'sidebar', label: 'Reconciliation', icon: GitCompareArrows, order: 5020 } },
  { id: 'multi-company.consolidations.list', module: 'multi_company', path: '/multi-company/consolidations', title: 'Consolidations · SARAISE', sourceFile: 'modules/multi_company/pages/ConsolidationRunListPage.tsx', Page: lazy(() => import('./pages/ConsolidationRunListPage').then(({ ConsolidationRunListPage }) => ({ default: ConsolidationRunListPage }))), modes, navigation: { type: 'sidebar', label: 'Consolidations', icon: Layers3, order: 5030 } },
  { id: 'multi-company.pricing.list', module: 'multi_company', path: '/multi-company/transfer-pricing', title: 'Transfer Pricing · SARAISE', sourceFile: 'modules/multi_company/pages/TransferPricingRuleListPage.tsx', Page: lazy(() => import('./pages/TransferPricingRuleListPage').then(({ TransferPricingRuleListPage }) => ({ default: TransferPricingRuleListPage }))), modes, navigation: { type: 'sidebar', label: 'Transfer Pricing', icon: Tags, order: 5040 } },
  { id: 'multi-company.settings.list', module: 'multi_company', path: '/multi-company/settings', title: 'Multi-Company Settings · SARAISE', sourceFile: 'modules/multi_company/pages/ConfigurationVersionListPage.tsx', Page: lazy(() => import('./pages/ConfigurationVersionListPage').then(({ ConfigurationVersionListPage }) => ({ default: ConfigurationVersionListPage }))), modes, navigation: { type: 'sidebar', label: 'Settings', icon: Settings2, order: 5050 } },

  { id: 'multi-company.companies.create', module: 'multi_company', path: '/multi-company/companies/new', title: 'Create Company · SARAISE', sourceFile: 'modules/multi_company/pages/CreateCompanyPage.tsx', Page: lazy(() => import('./pages/CreateCompanyPage').then(({ CreateCompanyPage }) => ({ default: CreateCompanyPage }))), modes, navigation: contextual('multi-company.companies.list') },
  { id: 'multi-company.companies.detail', module: 'multi_company', path: '/multi-company/companies/:id', title: 'Company Details · SARAISE', sourceFile: 'modules/multi_company/pages/CompanyDetailPage.tsx', Page: lazy(() => import('./pages/CompanyDetailPage').then(({ CompanyDetailPage }) => ({ default: CompanyDetailPage }))), modes, navigation: contextual('multi-company.companies.list') },
  { id: 'multi-company.companies.edit', module: 'multi_company', path: '/multi-company/companies/:id/edit', title: 'Edit Company · SARAISE', sourceFile: 'modules/multi_company/pages/EditCompanyPage.tsx', Page: lazy(() => import('./pages/EditCompanyPage').then(({ EditCompanyPage }) => ({ default: EditCompanyPage }))), modes, navigation: contextual('multi-company.companies.list') },
  { id: 'multi-company.companies.hierarchy', module: 'multi_company', path: '/multi-company/hierarchy', title: 'Company Hierarchy · SARAISE', sourceFile: 'modules/multi_company/pages/CompanyHierarchyPage.tsx', Page: lazy(() => import('./pages/CompanyHierarchyPage').then(({ CompanyHierarchyPage }) => ({ default: CompanyHierarchyPage }))), modes, navigation: contextual('multi-company.companies.list') },
  { id: 'multi-company.companies.access', module: 'multi_company', path: '/multi-company/companies/:id/access', title: 'Company Access · SARAISE', sourceFile: 'modules/multi_company/pages/CompanyAccessPage.tsx', Page: lazy(() => import('./pages/CompanyAccessPage').then(({ CompanyAccessPage }) => ({ default: CompanyAccessPage }))), modes, navigation: contextual('multi-company.companies.list') },

  { id: 'multi-company.transactions.create', module: 'multi_company', path: '/multi-company/transactions/new', title: 'Create Intercompany Transaction · SARAISE', sourceFile: 'modules/multi_company/pages/CreateTransactionPage.tsx', Page: lazy(() => import('./pages/CreateTransactionPage').then(({ CreateTransactionPage }) => ({ default: CreateTransactionPage }))), modes, navigation: contextual('multi-company.transactions.list') },
  { id: 'multi-company.transactions.detail', module: 'multi_company', path: '/multi-company/transactions/:id', title: 'Transaction Details · SARAISE', sourceFile: 'modules/multi_company/pages/TransactionDetailPage.tsx', Page: lazy(() => import('./pages/TransactionDetailPage').then(({ TransactionDetailPage }) => ({ default: TransactionDetailPage }))), modes, navigation: contextual('multi-company.transactions.list') },
  { id: 'multi-company.transactions.edit', module: 'multi_company', path: '/multi-company/transactions/:id/edit', title: 'Edit Transaction Draft · SARAISE', sourceFile: 'modules/multi_company/pages/EditTransactionPage.tsx', Page: lazy(() => import('./pages/EditTransactionPage').then(({ EditTransactionPage }) => ({ default: EditTransactionPage }))), modes, navigation: contextual('multi-company.transactions.list') },

  { id: 'multi-company.consolidations.create', module: 'multi_company', path: '/multi-company/consolidations/new', title: 'Create Consolidation · SARAISE', sourceFile: 'modules/multi_company/pages/CreateConsolidationRunPage.tsx', Page: lazy(() => import('./pages/CreateConsolidationRunPage').then(({ CreateConsolidationRunPage }) => ({ default: CreateConsolidationRunPage }))), modes, navigation: contextual('multi-company.consolidations.list') },
  { id: 'multi-company.consolidations.detail', module: 'multi_company', path: '/multi-company/consolidations/:id', title: 'Consolidation Details · SARAISE', sourceFile: 'modules/multi_company/pages/ConsolidationRunDetailPage.tsx', Page: lazy(() => import('./pages/ConsolidationRunDetailPage').then(({ ConsolidationRunDetailPage }) => ({ default: ConsolidationRunDetailPage }))), modes, navigation: contextual('multi-company.consolidations.list') },
  { id: 'multi-company.consolidations.edit', module: 'multi_company', path: '/multi-company/consolidations/:id/edit', title: 'Edit Consolidation · SARAISE', sourceFile: 'modules/multi_company/pages/EditConsolidationRunPage.tsx', Page: lazy(() => import('./pages/EditConsolidationRunPage').then(({ EditConsolidationRunPage }) => ({ default: EditConsolidationRunPage }))), modes, navigation: contextual('multi-company.consolidations.list') },
  { id: 'multi-company.eliminations.list', module: 'multi_company', path: '/multi-company/consolidations/:id/eliminations', title: 'Elimination Entries · SARAISE', sourceFile: 'modules/multi_company/pages/EliminationListPage.tsx', Page: lazy(() => import('./pages/EliminationListPage').then(({ EliminationListPage }) => ({ default: EliminationListPage }))), modes, navigation: contextual('multi-company.consolidations.list') },
  { id: 'multi-company.eliminations.create', module: 'multi_company', path: '/multi-company/consolidations/:id/eliminations/new', title: 'Create Manual Elimination · SARAISE', sourceFile: 'modules/multi_company/pages/CreateManualEliminationPage.tsx', Page: lazy(() => import('./pages/CreateManualEliminationPage').then(({ CreateManualEliminationPage }) => ({ default: CreateManualEliminationPage }))), modes, navigation: contextual('multi-company.consolidations.list') },
  { id: 'multi-company.eliminations.detail', module: 'multi_company', path: '/multi-company/eliminations/:id', title: 'Elimination Evidence · SARAISE', sourceFile: 'modules/multi_company/pages/EliminationDetailPage.tsx', Page: lazy(() => import('./pages/EliminationDetailPage').then(({ EliminationDetailPage }) => ({ default: EliminationDetailPage }))), modes, navigation: contextual('multi-company.consolidations.list') },

  { id: 'multi-company.pricing.create', module: 'multi_company', path: '/multi-company/transfer-pricing/new', title: 'Create Transfer-Pricing Rule · SARAISE', sourceFile: 'modules/multi_company/pages/CreateTransferPricingRulePage.tsx', Page: lazy(() => import('./pages/CreateTransferPricingRulePage').then(({ CreateTransferPricingRulePage }) => ({ default: CreateTransferPricingRulePage }))), modes, navigation: contextual('multi-company.pricing.list') },
  { id: 'multi-company.pricing.detail', module: 'multi_company', path: '/multi-company/transfer-pricing/:id', title: 'Transfer-Pricing Rule · SARAISE', sourceFile: 'modules/multi_company/pages/TransferPricingRuleDetailPage.tsx', Page: lazy(() => import('./pages/TransferPricingRuleDetailPage').then(({ TransferPricingRuleDetailPage }) => ({ default: TransferPricingRuleDetailPage }))), modes, navigation: contextual('multi-company.pricing.list') },
  { id: 'multi-company.pricing.edit', module: 'multi_company', path: '/multi-company/transfer-pricing/:id/edit', title: 'Edit Transfer-Pricing Rule · SARAISE', sourceFile: 'modules/multi_company/pages/EditTransferPricingRulePage.tsx', Page: lazy(() => import('./pages/EditTransferPricingRulePage').then(({ EditTransferPricingRulePage }) => ({ default: EditTransferPricingRulePage }))), modes, navigation: contextual('multi-company.pricing.list') },
  { id: 'multi-company.pricing.simulator', module: 'multi_company', path: '/multi-company/transfer-pricing/simulator', title: 'Transfer-Pricing Simulator · SARAISE', sourceFile: 'modules/multi_company/pages/TransferPricingSimulatorPage.tsx', Page: lazy(() => import('./pages/TransferPricingSimulatorPage').then(({ TransferPricingSimulatorPage }) => ({ default: TransferPricingSimulatorPage }))), modes, navigation: contextual('multi-company.pricing.list') },

  { id: 'multi-company.settings.create', module: 'multi_company', path: '/multi-company/settings/new', title: 'Create Multi-Company Configuration · SARAISE', sourceFile: 'modules/multi_company/pages/CreateConfigurationVersionPage.tsx', Page: lazy(() => import('./pages/CreateConfigurationVersionPage').then(({ CreateConfigurationVersionPage }) => ({ default: CreateConfigurationVersionPage }))), modes, navigation: contextual('multi-company.settings.list') },
  { id: 'multi-company.settings.detail', module: 'multi_company', path: '/multi-company/settings/:id', title: 'Configuration Details · SARAISE', sourceFile: 'modules/multi_company/pages/ConfigurationVersionDetailPage.tsx', Page: lazy(() => import('./pages/ConfigurationVersionDetailPage').then(({ ConfigurationVersionDetailPage }) => ({ default: ConfigurationVersionDetailPage }))), modes, navigation: contextual('multi-company.settings.list') },
  { id: 'multi-company.settings.edit', module: 'multi_company', path: '/multi-company/settings/:id/edit', title: 'Edit Configuration Draft · SARAISE', sourceFile: 'modules/multi_company/pages/EditConfigurationVersionPage.tsx', Page: lazy(() => import('./pages/EditConfigurationVersionPage').then(({ EditConfigurationVersionPage }) => ({ default: EditConfigurationVersionPage }))), modes, navigation: contextual('multi-company.settings.list') },
] satisfies readonly TenantRoute[];

export default tenantRoutes;
