import { lazy } from 'react';
import { Cable, PlugZap, Route, Send, Settings, Webhook } from 'lucide-react';
import type { TenantRoute } from '@/navigation/tenant-route-types';

const MODULE = 'integration_platform';
const modes = ['development', 'self-hosted', 'saas'] as const;
const contextual = (parentRouteId: string, label: string) => ({ type: 'contextual' as const, parentRouteId, label, order: 0 });

export const tenantRoutes = [
  { id: 'integration-platform.integrations.list', module: MODULE, path: '/integration-platform', title: 'Integrations', sourceFile: 'modules/integration_platform/pages/IntegrationPages.tsx', Page: lazy(() => import('./pages/IntegrationPages').then(({ IntegrationListPage }) => ({ default: IntegrationListPage }))), modes, navigation: { type: 'sidebar', label: 'Integrations', icon: Cable, order: 0 } },
  { id: 'integration-platform.integrations.create', module: MODULE, path: '/integration-platform/new', title: 'New integration', sourceFile: 'modules/integration_platform/pages/IntegrationPages.tsx', Page: lazy(() => import('./pages/IntegrationPages').then(({ CreateIntegrationPage }) => ({ default: CreateIntegrationPage }))), modes, navigation: contextual('integration-platform.integrations.list', 'New integration') },
  { id: 'integration-platform.integrations.detail', module: MODULE, path: '/integration-platform/:id', title: 'Integration details', sourceFile: 'modules/integration_platform/pages/IntegrationPages.tsx', Page: lazy(() => import('./pages/IntegrationPages').then(({ IntegrationDetailPage }) => ({ default: IntegrationDetailPage }))), modes, navigation: contextual('integration-platform.integrations.list', 'Integration details') },
  { id: 'integration-platform.integrations.edit', module: MODULE, path: '/integration-platform/:id/edit', title: 'Edit integration', sourceFile: 'modules/integration_platform/pages/IntegrationPages.tsx', Page: lazy(() => import('./pages/IntegrationPages').then(({ EditIntegrationPage }) => ({ default: EditIntegrationPage }))), modes, navigation: contextual('integration-platform.integrations.list', 'Edit integration') },
  { id: 'integration-platform.credentials.metadata', module: MODULE, path: '/integration-platform/:id/credentials', title: 'Credential metadata', sourceFile: 'modules/integration_platform/pages/IntegrationPages.tsx', Page: lazy(() => import('./pages/IntegrationPages').then(({ CredentialMetadataPage }) => ({ default: CredentialMetadataPage }))), modes, navigation: contextual('integration-platform.integrations.list', 'Credential metadata') },
  { id: 'integration-platform.credentials.create', module: MODULE, path: '/integration-platform/:id/credentials/new', title: 'Add credential', sourceFile: 'modules/integration_platform/pages/IntegrationPages.tsx', Page: lazy(() => import('./pages/IntegrationPages').then(({ CreateCredentialPage }) => ({ default: CreateCredentialPage }))), modes, navigation: contextual('integration-platform.integrations.list', 'Add credential') },
  { id: 'integration-platform.credentials.rotate', module: MODULE, path: '/integration-platform/:id/credentials/:credentialId/rotate', title: 'Rotate credential', sourceFile: 'modules/integration_platform/pages/IntegrationPages.tsx', Page: lazy(() => import('./pages/IntegrationPages').then(({ RotateCredentialPage }) => ({ default: RotateCredentialPage }))), modes, navigation: contextual('integration-platform.integrations.list', 'Rotate credential') },

  { id: 'integration-platform.connectors.list', module: MODULE, path: '/integration-platform/connectors', title: 'Connector catalog', sourceFile: 'modules/integration_platform/pages/ConnectorPages.tsx', Page: lazy(() => import('./pages/ConnectorPages').then(({ ConnectorCatalogPage }) => ({ default: ConnectorCatalogPage }))), modes, navigation: { type: 'sidebar', label: 'Connector Catalog', icon: PlugZap, order: 0 } },
  { id: 'integration-platform.connectors.detail', module: MODULE, path: '/integration-platform/connectors/:id', title: 'Connector details', sourceFile: 'modules/integration_platform/pages/ConnectorPages.tsx', Page: lazy(() => import('./pages/ConnectorPages').then(({ ConnectorDetailPage }) => ({ default: ConnectorDetailPage }))), modes, navigation: contextual('integration-platform.connectors.list', 'Connector details') },
  { id: 'integration-platform.connectors.setup', module: MODULE, path: '/integration-platform/connectors/:id/setup', title: 'Connector setup', sourceFile: 'modules/integration_platform/pages/ConnectorPages.tsx', Page: lazy(() => import('./pages/ConnectorPages').then(({ ConnectorSetupPage }) => ({ default: ConnectorSetupPage }))), modes, navigation: contextual('integration-platform.connectors.list', 'Connector setup') },

  { id: 'integration-platform.webhooks.list', module: MODULE, path: '/integration-platform/webhooks', title: 'Webhooks', sourceFile: 'modules/integration_platform/pages/WebhookPages.tsx', Page: lazy(() => import('./pages/WebhookPages').then(({ WebhookListPage }) => ({ default: WebhookListPage }))), modes, navigation: { type: 'sidebar', label: 'Webhooks', icon: Webhook, order: 0 } },
  { id: 'integration-platform.webhooks.create', module: MODULE, path: '/integration-platform/webhooks/new', title: 'New webhook', sourceFile: 'modules/integration_platform/pages/WebhookPages.tsx', Page: lazy(() => import('./pages/WebhookPages').then(({ CreateWebhookPage }) => ({ default: CreateWebhookPage }))), modes, navigation: contextual('integration-platform.webhooks.list', 'New webhook') },
  { id: 'integration-platform.webhooks.detail', module: MODULE, path: '/integration-platform/webhooks/:id', title: 'Webhook details', sourceFile: 'modules/integration_platform/pages/WebhookPages.tsx', Page: lazy(() => import('./pages/WebhookPages').then(({ WebhookDetailPage }) => ({ default: WebhookDetailPage }))), modes, navigation: contextual('integration-platform.webhooks.list', 'Webhook details') },
  { id: 'integration-platform.webhooks.edit', module: MODULE, path: '/integration-platform/webhooks/:id/edit', title: 'Edit webhook', sourceFile: 'modules/integration_platform/pages/WebhookPages.tsx', Page: lazy(() => import('./pages/WebhookPages').then(({ EditWebhookPage }) => ({ default: EditWebhookPage }))), modes, navigation: contextual('integration-platform.webhooks.list', 'Edit webhook') },

  { id: 'integration-platform.deliveries.list', module: MODULE, path: '/integration-platform/deliveries', title: 'Webhook deliveries', sourceFile: 'modules/integration_platform/pages/DeliveryPages.tsx', Page: lazy(() => import('./pages/DeliveryPages').then(({ DeliveryListPage }) => ({ default: DeliveryListPage }))), modes, navigation: { type: 'sidebar', label: 'Deliveries', icon: Send, order: 0 } },
  { id: 'integration-platform.deliveries.detail', module: MODULE, path: '/integration-platform/deliveries/:id', title: 'Delivery evidence', sourceFile: 'modules/integration_platform/pages/DeliveryPages.tsx', Page: lazy(() => import('./pages/DeliveryPages').then(({ DeliveryDetailPage }) => ({ default: DeliveryDetailPage }))), modes, navigation: contextual('integration-platform.deliveries.list', 'Delivery evidence') },

  { id: 'integration-platform.mappings.list', module: MODULE, path: '/integration-platform/mappings', title: 'Data mappings', sourceFile: 'modules/integration_platform/pages/MappingPages.tsx', Page: lazy(() => import('./pages/MappingPages').then(({ MappingListPage }) => ({ default: MappingListPage }))), modes, navigation: { type: 'sidebar', label: 'Data Mappings', icon: Route, order: 0 } },
  { id: 'integration-platform.mappings.create', module: MODULE, path: '/integration-platform/mappings/new', title: 'New data mapping', sourceFile: 'modules/integration_platform/pages/MappingPages.tsx', Page: lazy(() => import('./pages/MappingPages').then(({ CreateMappingPage }) => ({ default: CreateMappingPage }))), modes, navigation: contextual('integration-platform.mappings.list', 'New data mapping') },
  { id: 'integration-platform.mappings.detail', module: MODULE, path: '/integration-platform/mappings/:id', title: 'Data mapping details', sourceFile: 'modules/integration_platform/pages/MappingPages.tsx', Page: lazy(() => import('./pages/MappingPages').then(({ MappingDetailPage }) => ({ default: MappingDetailPage }))), modes, navigation: contextual('integration-platform.mappings.list', 'Mapping details') },
  { id: 'integration-platform.mappings.edit', module: MODULE, path: '/integration-platform/mappings/:id/edit', title: 'Edit data mapping', sourceFile: 'modules/integration_platform/pages/MappingPages.tsx', Page: lazy(() => import('./pages/MappingPages').then(({ EditMappingPage }) => ({ default: EditMappingPage }))), modes, navigation: contextual('integration-platform.mappings.list', 'Edit mapping') },
  { id: 'integration-platform.configuration', module: MODULE, path: '/integration-platform/configuration', title: 'Integration Platform configuration', sourceFile: 'modules/integration_platform/pages/ConfigurationPage.tsx', Page: lazy(() => import('./pages/ConfigurationPage').then(({ ConfigurationPage }) => ({ default: ConfigurationPage }))), modes, requiredPermission: 'integration_platform.integration:read', navigation: { type: 'sidebar', label: 'Configuration', icon: Settings, order: 0 } },
] satisfies readonly TenantRoute[];

export default tenantRoutes;
