import { lazy } from 'react';
import { Cable, PlugZap, Route, Send, Webhook } from 'lucide-react';
import type { TenantRoute } from '@/navigation/tenant-route-types';

const MODULE = 'integration_platform';
const modes = ['development', 'self-hosted', 'saas'] as const;
const contextual = (parentRouteId: string) => ({ type: 'contextual' as const, parentRouteId });

export const tenantRoutes = [
  { id: 'integration-platform.integrations.list', module: MODULE, path: '/integration-platform', sourceFile: 'modules/integration_platform/pages/IntegrationPages.tsx', Page: lazy(() => import('./pages/IntegrationPages').then(({ IntegrationListPage }) => ({ default: IntegrationListPage }))), modes, navigation: { type: 'sidebar', label: 'Integrations', icon: Cable, order: 300 } },
  { id: 'integration-platform.integrations.create', module: MODULE, path: '/integration-platform/new', sourceFile: 'modules/integration_platform/pages/IntegrationPages.tsx', Page: lazy(() => import('./pages/IntegrationPages').then(({ CreateIntegrationPage }) => ({ default: CreateIntegrationPage }))), modes, navigation: contextual('integration-platform.integrations.list') },
  { id: 'integration-platform.integrations.detail', module: MODULE, path: '/integration-platform/:id', sourceFile: 'modules/integration_platform/pages/IntegrationPages.tsx', Page: lazy(() => import('./pages/IntegrationPages').then(({ IntegrationDetailPage }) => ({ default: IntegrationDetailPage }))), modes, navigation: contextual('integration-platform.integrations.list') },
  { id: 'integration-platform.integrations.edit', module: MODULE, path: '/integration-platform/:id/edit', sourceFile: 'modules/integration_platform/pages/IntegrationPages.tsx', Page: lazy(() => import('./pages/IntegrationPages').then(({ EditIntegrationPage }) => ({ default: EditIntegrationPage }))), modes, navigation: contextual('integration-platform.integrations.list') },
  { id: 'integration-platform.credentials.metadata', module: MODULE, path: '/integration-platform/:id/credentials', sourceFile: 'modules/integration_platform/pages/IntegrationPages.tsx', Page: lazy(() => import('./pages/IntegrationPages').then(({ CredentialMetadataPage }) => ({ default: CredentialMetadataPage }))), modes, navigation: contextual('integration-platform.integrations.list') },
  { id: 'integration-platform.credentials.create', module: MODULE, path: '/integration-platform/:id/credentials/new', sourceFile: 'modules/integration_platform/pages/IntegrationPages.tsx', Page: lazy(() => import('./pages/IntegrationPages').then(({ CreateCredentialPage }) => ({ default: CreateCredentialPage }))), modes, navigation: contextual('integration-platform.integrations.list') },
  { id: 'integration-platform.credentials.rotate', module: MODULE, path: '/integration-platform/:id/credentials/:credentialId/rotate', sourceFile: 'modules/integration_platform/pages/IntegrationPages.tsx', Page: lazy(() => import('./pages/IntegrationPages').then(({ RotateCredentialPage }) => ({ default: RotateCredentialPage }))), modes, navigation: contextual('integration-platform.integrations.list') },

  { id: 'integration-platform.connectors.list', module: MODULE, path: '/integration-platform/connectors', sourceFile: 'modules/integration_platform/pages/ConnectorPages.tsx', Page: lazy(() => import('./pages/ConnectorPages').then(({ ConnectorCatalogPage }) => ({ default: ConnectorCatalogPage }))), modes, navigation: { type: 'sidebar', label: 'Connector Catalog', icon: PlugZap, order: 301 } },
  { id: 'integration-platform.connectors.detail', module: MODULE, path: '/integration-platform/connectors/:id', sourceFile: 'modules/integration_platform/pages/ConnectorPages.tsx', Page: lazy(() => import('./pages/ConnectorPages').then(({ ConnectorDetailPage }) => ({ default: ConnectorDetailPage }))), modes, navigation: contextual('integration-platform.connectors.list') },
  { id: 'integration-platform.connectors.setup', module: MODULE, path: '/integration-platform/connectors/:id/setup', sourceFile: 'modules/integration_platform/pages/ConnectorPages.tsx', Page: lazy(() => import('./pages/ConnectorPages').then(({ ConnectorSetupPage }) => ({ default: ConnectorSetupPage }))), modes, navigation: contextual('integration-platform.connectors.list') },

  { id: 'integration-platform.webhooks.list', module: MODULE, path: '/integration-platform/webhooks', sourceFile: 'modules/integration_platform/pages/WebhookPages.tsx', Page: lazy(() => import('./pages/WebhookPages').then(({ WebhookListPage }) => ({ default: WebhookListPage }))), modes, navigation: { type: 'sidebar', label: 'Webhooks', icon: Webhook, order: 302 } },
  { id: 'integration-platform.webhooks.create', module: MODULE, path: '/integration-platform/webhooks/new', sourceFile: 'modules/integration_platform/pages/WebhookPages.tsx', Page: lazy(() => import('./pages/WebhookPages').then(({ CreateWebhookPage }) => ({ default: CreateWebhookPage }))), modes, navigation: contextual('integration-platform.webhooks.list') },
  { id: 'integration-platform.webhooks.detail', module: MODULE, path: '/integration-platform/webhooks/:id', sourceFile: 'modules/integration_platform/pages/WebhookPages.tsx', Page: lazy(() => import('./pages/WebhookPages').then(({ WebhookDetailPage }) => ({ default: WebhookDetailPage }))), modes, navigation: contextual('integration-platform.webhooks.list') },
  { id: 'integration-platform.webhooks.edit', module: MODULE, path: '/integration-platform/webhooks/:id/edit', sourceFile: 'modules/integration_platform/pages/WebhookPages.tsx', Page: lazy(() => import('./pages/WebhookPages').then(({ EditWebhookPage }) => ({ default: EditWebhookPage }))), modes, navigation: contextual('integration-platform.webhooks.list') },

  { id: 'integration-platform.deliveries.list', module: MODULE, path: '/integration-platform/deliveries', sourceFile: 'modules/integration_platform/pages/DeliveryPages.tsx', Page: lazy(() => import('./pages/DeliveryPages').then(({ DeliveryListPage }) => ({ default: DeliveryListPage }))), modes, navigation: { type: 'sidebar', label: 'Deliveries', icon: Send, order: 303 } },
  { id: 'integration-platform.deliveries.detail', module: MODULE, path: '/integration-platform/deliveries/:id', sourceFile: 'modules/integration_platform/pages/DeliveryPages.tsx', Page: lazy(() => import('./pages/DeliveryPages').then(({ DeliveryDetailPage }) => ({ default: DeliveryDetailPage }))), modes, navigation: contextual('integration-platform.deliveries.list') },

  { id: 'integration-platform.mappings.list', module: MODULE, path: '/integration-platform/mappings', sourceFile: 'modules/integration_platform/pages/MappingPages.tsx', Page: lazy(() => import('./pages/MappingPages').then(({ MappingListPage }) => ({ default: MappingListPage }))), modes, navigation: { type: 'sidebar', label: 'Data Mappings', icon: Route, order: 304 } },
  { id: 'integration-platform.mappings.create', module: MODULE, path: '/integration-platform/mappings/new', sourceFile: 'modules/integration_platform/pages/MappingPages.tsx', Page: lazy(() => import('./pages/MappingPages').then(({ CreateMappingPage }) => ({ default: CreateMappingPage }))), modes, navigation: contextual('integration-platform.mappings.list') },
  { id: 'integration-platform.mappings.detail', module: MODULE, path: '/integration-platform/mappings/:id', sourceFile: 'modules/integration_platform/pages/MappingPages.tsx', Page: lazy(() => import('./pages/MappingPages').then(({ MappingDetailPage }) => ({ default: MappingDetailPage }))), modes, navigation: contextual('integration-platform.mappings.list') },
  { id: 'integration-platform.mappings.edit', module: MODULE, path: '/integration-platform/mappings/:id/edit', sourceFile: 'modules/integration_platform/pages/MappingPages.tsx', Page: lazy(() => import('./pages/MappingPages').then(({ EditMappingPage }) => ({ default: EditMappingPage }))), modes, navigation: contextual('integration-platform.mappings.list') },
] satisfies readonly TenantRoute[];

export default tenantRoutes;
