"""Shared, production-faithful test support for SARAISE modules.

Use ``pytest_plugins = ["src.core.testing"]`` in a module test suite to consume
the tenant identities, users, profiles, and session-authenticated API clients.
The reusable isolation assertions live in ``tenant_contract``.
"""

from .factories import (
    TEST_PASSWORD,
    OrganizationFactory,
    PlatformUserFactory,
    PlatformUserProfileFactory,
    TenantFactory,
    TenantIdentity,
    TenantUserFactory,
    TenantUserProfileFactory,
    UserFactory,
    UserProfileFactory,
    api_client,
    authenticated_api_client,
    authenticated_client_a,
    authenticated_client_b,
    authenticated_platform_client,
    authenticated_tenant_a_client,
    authenticated_tenant_b_client,
    create_tenant_identity,
    platform_client,
    platform_profile,
    platform_user,
    tenant_a,
    tenant_a_client,
    tenant_a_profile,
    tenant_a_user,
    tenant_b,
    tenant_b_client,
    tenant_b_profile,
    tenant_b_user,
    tenant_pair,
)
from .tenant_contract import TenantIsolationContract

__all__ = [
    "TEST_PASSWORD",
    "OrganizationFactory",
    "PlatformUserFactory",
    "PlatformUserProfileFactory",
    "TenantFactory",
    "TenantIdentity",
    "TenantUserFactory",
    "TenantUserProfileFactory",
    "UserFactory",
    "UserProfileFactory",
    "api_client",
    "authenticated_api_client",
    "authenticated_client_a",
    "authenticated_client_b",
    "authenticated_platform_client",
    "authenticated_tenant_a_client",
    "authenticated_tenant_b_client",
    "create_tenant_identity",
    "platform_client",
    "platform_profile",
    "platform_user",
    "tenant_a",
    "tenant_a_client",
    "tenant_a_profile",
    "tenant_a_user",
    "tenant_b",
    "tenant_b_client",
    "tenant_b_profile",
    "tenant_b_user",
    "tenant_pair",
    "TenantIsolationContract",
]
