/* eslint-disable @typescript-eslint/consistent-type-imports */
import { lazy } from 'react';
import { CalendarDays, ClipboardCheck, Gauge, ListChecks, Settings2, ShieldAlert, Wrench } from 'lucide-react';
import type { TenantRoute } from '@/navigation/tenant-route-types';

const modes = ['development', 'self-hosted', 'saas'] as const;
const contextual = (parentRouteId: string) => ({ type: 'contextual' as const, parentRouteId });
const riskPage = <K extends keyof typeof import('./pages/RiskPages')>(name: K) => lazy(() => import('./pages/RiskPages').then((module) => ({ default: module[name] })));
const controlPage = <K extends keyof typeof import('./pages/ControlPages')>(name: K) => lazy(() => import('./pages/ControlPages').then((module) => ({ default: module[name] })));
const requirementPage = <K extends keyof typeof import('./pages/RequirementPages')>(name: K) => lazy(() => import('./pages/RequirementPages').then((module) => ({ default: module[name] })));
const workPage = <K extends keyof typeof import('./pages/CalendarRemediationPages')>(name: K) => lazy(() => import('./pages/CalendarRemediationPages').then((module) => ({ default: module[name] })));
const overviewPage = <K extends keyof typeof import('./pages/DashboardConfigurationPages')>(name: K) => lazy(() => import('./pages/DashboardConfigurationPages').then((module) => ({ default: module[name] })));

export const tenantRoutes = [
  { id: 'compliance_risk.dashboard', module: 'compliance_risk_management', path: '/compliance-risk-management/dashboard', title: 'Compliance risk dashboard', sourceFile: 'modules/compliance_risk_management/pages/DashboardConfigurationPages.tsx', Page: overviewPage('ComplianceRiskDashboardPage'), modes, navigation: { type: 'sidebar', label: 'Dashboard', icon: Gauge, order: 410 } },
  { id: 'compliance_risk.risks', module: 'compliance_risk_management', path: '/compliance-risk-management/risks', title: 'Risk register', sourceFile: 'modules/compliance_risk_management/pages/RiskPages.tsx', Page: riskPage('RiskAssessmentListPage'), modes, navigation: { type: 'sidebar', label: 'Risks', icon: ShieldAlert, order: 411 } },
  { id: 'compliance_risk.risks.create', module: 'compliance_risk_management', path: '/compliance-risk-management/risks/new', title: 'Create risk assessment', sourceFile: 'modules/compliance_risk_management/pages/RiskPages.tsx', Page: riskPage('CreateRiskAssessmentPage'), modes, navigation: contextual('compliance_risk.risks') },
  { id: 'compliance_risk.risks.detail', module: 'compliance_risk_management', path: '/compliance-risk-management/risks/:id', title: 'Risk assessment', sourceFile: 'modules/compliance_risk_management/pages/RiskPages.tsx', Page: riskPage('RiskAssessmentDetailPage'), modes, navigation: contextual('compliance_risk.risks') },
  { id: 'compliance_risk.risks.edit', module: 'compliance_risk_management', path: '/compliance-risk-management/risks/:id/edit', title: 'Edit risk assessment', sourceFile: 'modules/compliance_risk_management/pages/RiskPages.tsx', Page: riskPage('EditRiskAssessmentPage'), modes, navigation: contextual('compliance_risk.risks') },

  { id: 'compliance_risk.controls', module: 'compliance_risk_management', path: '/compliance-risk-management/controls', title: 'Controls and tests', sourceFile: 'modules/compliance_risk_management/pages/ControlPages.tsx', Page: controlPage('ControlListPage'), modes, navigation: { type: 'sidebar', label: 'Controls & Tests', icon: ClipboardCheck, order: 412 } },
  { id: 'compliance_risk.controls.create', module: 'compliance_risk_management', path: '/compliance-risk-management/controls/new', title: 'Create control', sourceFile: 'modules/compliance_risk_management/pages/ControlPages.tsx', Page: controlPage('CreateControlPage'), modes, navigation: contextual('compliance_risk.controls') },
  { id: 'compliance_risk.controls.detail', module: 'compliance_risk_management', path: '/compliance-risk-management/controls/:id', title: 'Control detail', sourceFile: 'modules/compliance_risk_management/pages/ControlPages.tsx', Page: controlPage('ControlDetailPage'), modes, navigation: contextual('compliance_risk.controls') },
  { id: 'compliance_risk.controls.edit', module: 'compliance_risk_management', path: '/compliance-risk-management/controls/:id/edit', title: 'Edit control', sourceFile: 'modules/compliance_risk_management/pages/ControlPages.tsx', Page: controlPage('EditControlPage'), modes, navigation: contextual('compliance_risk.controls') },
  { id: 'compliance_risk.tests', module: 'compliance_risk_management', path: '/compliance-risk-management/control-tests', title: 'Control tests', sourceFile: 'modules/compliance_risk_management/pages/ControlPages.tsx', Page: controlPage('ControlTestListPage'), modes, navigation: contextual('compliance_risk.controls') },
  { id: 'compliance_risk.tests.create', module: 'compliance_risk_management', path: '/compliance-risk-management/control-tests/new', title: 'Schedule control test', sourceFile: 'modules/compliance_risk_management/pages/ControlPages.tsx', Page: controlPage('CreateControlTestPage'), modes, navigation: contextual('compliance_risk.controls') },
  { id: 'compliance_risk.tests.detail', module: 'compliance_risk_management', path: '/compliance-risk-management/control-tests/:id', title: 'Control test detail', sourceFile: 'modules/compliance_risk_management/pages/ControlPages.tsx', Page: controlPage('ControlTestDetailPage'), modes, navigation: contextual('compliance_risk.controls') },
  { id: 'compliance_risk.tests.edit', module: 'compliance_risk_management', path: '/compliance-risk-management/control-tests/:id/edit', title: 'Edit scheduled control test', sourceFile: 'modules/compliance_risk_management/pages/ControlPages.tsx', Page: controlPage('EditScheduledControlTestPage'), modes, navigation: contextual('compliance_risk.controls') },
  { id: 'compliance_risk.tests.execute', module: 'compliance_risk_management', path: '/compliance-risk-management/control-tests/:id/execute', title: 'Execute control test', sourceFile: 'modules/compliance_risk_management/pages/ControlPages.tsx', Page: controlPage('ExecuteControlTestPage'), modes, navigation: contextual('compliance_risk.controls') },

  { id: 'compliance_risk.requirements', module: 'compliance_risk_management', path: '/compliance-risk-management/requirements', title: 'Compliance requirements', sourceFile: 'modules/compliance_risk_management/pages/RequirementPages.tsx', Page: requirementPage('RequirementListPage'), modes, navigation: { type: 'sidebar', label: 'Requirements', icon: ListChecks, order: 413 } },
  { id: 'compliance_risk.requirements.create', module: 'compliance_risk_management', path: '/compliance-risk-management/requirements/new', title: 'Create requirement', sourceFile: 'modules/compliance_risk_management/pages/RequirementPages.tsx', Page: requirementPage('CreateRequirementPage'), modes, navigation: contextual('compliance_risk.requirements') },
  { id: 'compliance_risk.requirements.detail', module: 'compliance_risk_management', path: '/compliance-risk-management/requirements/:id', title: 'Requirement detail', sourceFile: 'modules/compliance_risk_management/pages/RequirementPages.tsx', Page: requirementPage('RequirementDetailPage'), modes, navigation: contextual('compliance_risk.requirements') },
  { id: 'compliance_risk.requirements.edit', module: 'compliance_risk_management', path: '/compliance-risk-management/requirements/:id/edit', title: 'Edit requirement', sourceFile: 'modules/compliance_risk_management/pages/RequirementPages.tsx', Page: requirementPage('EditRequirementPage'), modes, navigation: contextual('compliance_risk.requirements') },

  { id: 'compliance_risk.calendar', module: 'compliance_risk_management', path: '/compliance-risk-management/calendar', title: 'Compliance calendar', sourceFile: 'modules/compliance_risk_management/pages/CalendarRemediationPages.tsx', Page: workPage('ComplianceCalendarPage'), modes, navigation: { type: 'sidebar', label: 'Calendar', icon: CalendarDays, order: 414 } },
  { id: 'compliance_risk.calendar.create', module: 'compliance_risk_management', path: '/compliance-risk-management/calendar/new', title: 'Create calendar entry', sourceFile: 'modules/compliance_risk_management/pages/CalendarRemediationPages.tsx', Page: workPage('CreateCalendarEntryPage'), modes, navigation: contextual('compliance_risk.calendar') },
  { id: 'compliance_risk.calendar.detail', module: 'compliance_risk_management', path: '/compliance-risk-management/calendar/:id', title: 'Calendar entry detail', sourceFile: 'modules/compliance_risk_management/pages/CalendarRemediationPages.tsx', Page: workPage('CalendarEntryDetailPage'), modes, navigation: contextual('compliance_risk.calendar') },
  { id: 'compliance_risk.calendar.edit', module: 'compliance_risk_management', path: '/compliance-risk-management/calendar/:id/edit', title: 'Edit calendar entry', sourceFile: 'modules/compliance_risk_management/pages/CalendarRemediationPages.tsx', Page: workPage('EditCalendarEntryPage'), modes, navigation: contextual('compliance_risk.calendar') },

  { id: 'compliance_risk.remediations', module: 'compliance_risk_management', path: '/compliance-risk-management/remediations', title: 'Remediation', sourceFile: 'modules/compliance_risk_management/pages/CalendarRemediationPages.tsx', Page: workPage('RemediationListPage'), modes, navigation: { type: 'sidebar', label: 'Remediation', icon: Wrench, order: 415 } },
  { id: 'compliance_risk.remediations.create', module: 'compliance_risk_management', path: '/compliance-risk-management/remediations/new', title: 'Create remediation', sourceFile: 'modules/compliance_risk_management/pages/CalendarRemediationPages.tsx', Page: workPage('CreateRemediationPage'), modes, navigation: contextual('compliance_risk.remediations') },
  { id: 'compliance_risk.remediations.detail', module: 'compliance_risk_management', path: '/compliance-risk-management/remediations/:id', title: 'Remediation detail', sourceFile: 'modules/compliance_risk_management/pages/CalendarRemediationPages.tsx', Page: workPage('RemediationDetailPage'), modes, navigation: contextual('compliance_risk.remediations') },
  { id: 'compliance_risk.remediations.edit', module: 'compliance_risk_management', path: '/compliance-risk-management/remediations/:id/edit', title: 'Edit remediation', sourceFile: 'modules/compliance_risk_management/pages/CalendarRemediationPages.tsx', Page: workPage('EditRemediationPage'), modes, navigation: contextual('compliance_risk.remediations') },

  { id: 'compliance_risk.configuration', module: 'compliance_risk_management', path: '/compliance-risk-management/configuration', title: 'Risk configuration', sourceFile: 'modules/compliance_risk_management/pages/DashboardConfigurationPages.tsx', Page: overviewPage('RiskConfigurationPage'), modes, navigation: { type: 'sidebar', label: 'Configuration', icon: Settings2, order: 416 } },
  { id: 'compliance_risk.configuration.history', module: 'compliance_risk_management', path: '/compliance-risk-management/configuration/history', title: 'Configuration history', sourceFile: 'modules/compliance_risk_management/pages/DashboardConfigurationPages.tsx', Page: overviewPage('RiskConfigurationHistoryPage'), modes, navigation: contextual('compliance_risk.configuration') },
  { id: 'compliance_risk.configuration.version', module: 'compliance_risk_management', path: '/compliance-risk-management/configuration/history/:version', title: 'Configuration version', sourceFile: 'modules/compliance_risk_management/pages/DashboardConfigurationPages.tsx', Page: overviewPage('RiskConfigurationVersionDetailPage'), modes, navigation: contextual('compliance_risk.configuration') },
  { id: 'compliance_risk.configuration.import_export', module: 'compliance_risk_management', path: '/compliance-risk-management/configuration/import-export', title: 'Configuration import and export', sourceFile: 'modules/compliance_risk_management/pages/DashboardConfigurationPages.tsx', Page: overviewPage('RiskConfigurationImportExportPage'), modes, navigation: contextual('compliance_risk.configuration') },
] satisfies readonly TenantRoute[];

export default tenantRoutes;
