import { lazy } from 'react';
import { ContactRound, MailCheck, Megaphone, ShieldOff, SwatchBook } from 'lucide-react';
import type { TenantRoute } from '@/navigation/tenant-route-types';
import { ROUTES } from './contracts';
const modes = ['development', 'self-hosted', 'saas'] as const;
const contextual = (parentRouteId: string) => ({ type: 'contextual' as const, parentRouteId });
const moduleName = 'email_marketing';
export const tenantRoutes = [
  { id: 'email-marketing.campaigns', module: moduleName, path: ROUTES.CAMPAIGNS, sourceFile: 'modules/email_marketing/pages/EmailCampaignListPage.tsx', Page: lazy(() => import('./pages/EmailCampaignListPage').then((m) => ({ default: m.EmailCampaignListPage }))), modes, navigation: { type: 'sidebar', label: 'Campaigns', icon: Megaphone, order: 700 } },
  { id: 'email-marketing.campaign-create', module: moduleName, path: ROUTES.CAMPAIGN_CREATE, sourceFile: 'modules/email_marketing/pages/CreateEmailCampaignPage.tsx', Page: lazy(() => import('./pages/CreateEmailCampaignPage').then((m) => ({ default: m.CreateEmailCampaignPage }))), modes, navigation: contextual('email-marketing.campaigns') },
  { id: 'email-marketing.campaign-detail', module: moduleName, path: ROUTES.CAMPAIGN_DETAIL(':id'), sourceFile: 'modules/email_marketing/pages/EmailCampaignDetailPage.tsx', Page: lazy(() => import('./pages/EmailCampaignDetailPage').then((m) => ({ default: m.EmailCampaignDetailPage }))), modes, navigation: contextual('email-marketing.campaigns') },
  { id: 'email-marketing.campaign-edit', module: moduleName, path: ROUTES.CAMPAIGN_EDIT(':id'), sourceFile: 'modules/email_marketing/pages/EditEmailCampaignPage.tsx', Page: lazy(() => import('./pages/EditEmailCampaignPage').then((m) => ({ default: m.EditEmailCampaignPage }))), modes, navigation: contextual('email-marketing.campaigns') },
  { id: 'email-marketing.templates', module: moduleName, path: ROUTES.TEMPLATES, sourceFile: 'modules/email_marketing/pages/EmailTemplateListPage.tsx', Page: lazy(() => import('./pages/EmailTemplateListPage').then((m) => ({ default: m.EmailTemplateListPage }))), modes, navigation: { type: 'sidebar', label: 'Templates', icon: SwatchBook, order: 710 } },
  { id: 'email-marketing.template-create', module: moduleName, path: ROUTES.TEMPLATE_CREATE, sourceFile: 'modules/email_marketing/pages/CreateEmailTemplatePage.tsx', Page: lazy(() => import('./pages/CreateEmailTemplatePage').then((m) => ({ default: m.CreateEmailTemplatePage }))), modes, navigation: contextual('email-marketing.templates') },
  { id: 'email-marketing.template-detail', module: moduleName, path: ROUTES.TEMPLATE_DETAIL(':id'), sourceFile: 'modules/email_marketing/pages/EmailTemplateDetailPage.tsx', Page: lazy(() => import('./pages/EmailTemplateDetailPage').then((m) => ({ default: m.EmailTemplateDetailPage }))), modes, navigation: contextual('email-marketing.templates') },
  { id: 'email-marketing.template-edit', module: moduleName, path: ROUTES.TEMPLATE_EDIT(':id'), sourceFile: 'modules/email_marketing/pages/EditEmailTemplatePage.tsx', Page: lazy(() => import('./pages/EditEmailTemplatePage').then((m) => ({ default: m.EditEmailTemplatePage }))), modes, navigation: contextual('email-marketing.templates') },
  { id: 'email-marketing.delivery', module: moduleName, path: ROUTES.DELIVERY, sourceFile: 'modules/email_marketing/pages/AudienceDeliveryListPage.tsx', Page: lazy(() => import('./pages/AudienceDeliveryListPage').then((m) => ({ default: m.AudienceDeliveryListPage }))), modes, navigation: { type: 'sidebar', label: 'Delivery', icon: MailCheck, order: 720 } },
  { id: 'email-marketing.recipient-detail', module: moduleName, path: ROUTES.RECIPIENT_DETAIL(':id'), sourceFile: 'modules/email_marketing/pages/EmailRecipientDetailPage.tsx', Page: lazy(() => import('./pages/EmailRecipientDetailPage').then((m) => ({ default: m.EmailRecipientDetailPage }))), modes, navigation: contextual('email-marketing.delivery') },
  { id: 'email-marketing.delivery-detail', module: moduleName, path: ROUTES.DELIVERY_DETAIL(':id'), sourceFile: 'modules/email_marketing/pages/EmailDeliveryDetailPage.tsx', Page: lazy(() => import('./pages/EmailDeliveryDetailPage').then((m) => ({ default: m.EmailDeliveryDetailPage }))), modes, navigation: contextual('email-marketing.delivery') },
  { id: 'email-marketing.suppressions', module: moduleName, path: ROUTES.SUPPRESSIONS, sourceFile: 'modules/email_marketing/pages/SuppressionListPage.tsx', Page: lazy(() => import('./pages/SuppressionListPage').then((m) => ({ default: m.SuppressionListPage }))), modes, navigation: { type: 'sidebar', label: 'Suppressions', icon: ShieldOff, order: 730 } },
  { id: 'email-marketing.suppression-create', module: moduleName, path: ROUTES.SUPPRESSION_CREATE, sourceFile: 'modules/email_marketing/pages/CreateSuppressionPage.tsx', Page: lazy(() => import('./pages/CreateSuppressionPage').then((m) => ({ default: m.CreateSuppressionPage }))), modes, navigation: contextual('email-marketing.suppressions') },
  { id: 'email-marketing.suppression-detail', module: moduleName, path: ROUTES.SUPPRESSION_DETAIL(':id'), sourceFile: 'modules/email_marketing/pages/SuppressionDetailPage.tsx', Page: lazy(() => import('./pages/SuppressionDetailPage').then((m) => ({ default: m.SuppressionDetailPage }))), modes, navigation: contextual('email-marketing.suppressions') },
  { id: 'email-marketing.consents', module: moduleName, path: ROUTES.CONSENTS, sourceFile: 'modules/email_marketing/pages/ConsentListPage.tsx', Page: lazy(() => import('./pages/ConsentListPage').then((m) => ({ default: m.ConsentListPage }))), modes, navigation: { type: 'sidebar', label: 'Consents', icon: ContactRound, order: 740 } },
  { id: 'email-marketing.consent-create', module: moduleName, path: ROUTES.CONSENT_CREATE, sourceFile: 'modules/email_marketing/pages/RecordConsentPage.tsx', Page: lazy(() => import('./pages/RecordConsentPage').then((m) => ({ default: m.RecordConsentPage }))), modes, navigation: contextual('email-marketing.consents') },
  { id: 'email-marketing.consent-detail', module: moduleName, path: ROUTES.CONSENT_DETAIL(':id'), sourceFile: 'modules/email_marketing/pages/ConsentDetailPage.tsx', Page: lazy(() => import('./pages/ConsentDetailPage').then((m) => ({ default: m.ConsentDetailPage }))), modes, navigation: contextual('email-marketing.consents') },
] satisfies readonly TenantRoute[];
export default tenantRoutes;
