import { useEffect, useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { Download, Eye, History, Upload } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';
import type { ConfigurationEnvironment, ConfigurationWrite } from '../contracts';
import { ROUTES } from '../contracts';
import { purchaseService } from '../services/purchase-service';

const initial: ConfigurationWrite = { default_currency: 'USD', default_payment_terms: 'Net 30', supplier_code_prefix: 'SUP', requisition_prefix: 'REQ', rfq_prefix: 'RFQ', po_prefix: 'PO', receipt_prefix: 'GRN', approval_rules: [], receipt_tolerance_percent: '0.00', minimum_rfq_suppliers: 2, quote_scoring_weights: { price: 60, delivery: 20, quality: 10, service: 10 }, inventory_integration_enabled: false, accounting_integration_enabled: false, supplier_delivery_enabled: false, rollout: { roles: [], cohorts: [], percentage: 100 } };
export const ProcurementSettingsPage = () => {
  useEffect(() => { document.title = 'Procurement settings | SARAISE'; }, []); const [environment, setEnvironment] = useState<ConfigurationEnvironment>('development'); const [documentValue, setDocumentValue] = useState(JSON.stringify(initial, null, 2));
  const active = useQuery({ queryKey: ['purchase-config', environment], queryFn: () => purchaseService.getActiveConfiguration(environment), retry: false });
  const versions = useQuery({ queryKey: ['purchase-config-versions', environment], queryFn: () => purchaseService.listConfigurationVersions(environment) });
  useEffect(() => { if (active.data) { const editable: ConfigurationWrite = { default_currency: active.data.default_currency, default_payment_terms: active.data.default_payment_terms, supplier_code_prefix: active.data.supplier_code_prefix, requisition_prefix: active.data.requisition_prefix, rfq_prefix: active.data.rfq_prefix, po_prefix: active.data.po_prefix, receipt_prefix: active.data.receipt_prefix, approval_rules: active.data.approval_rules, receipt_tolerance_percent: active.data.receipt_tolerance_percent, minimum_rfq_suppliers: active.data.minimum_rfq_suppliers, quote_scoring_weights: active.data.quote_scoring_weights, inventory_integration_enabled: active.data.inventory_integration_enabled, accounting_integration_enabled: active.data.accounting_integration_enabled, supplier_delivery_enabled: active.data.supplier_delivery_enabled, rollout: active.data.rollout }; setDocumentValue(JSON.stringify(editable, null, 2)); } }, [active.data]);
  const preview = useMutation({ mutationFn: (value: ConfigurationWrite) => purchaseService.previewConfiguration(environment, value, [{ amount: '10000.00', category: 'general' }]) });
  const draft = useMutation({ mutationFn: (value: ConfigurationWrite) => purchaseService.createConfigurationDraft(environment, value, { idempotencyKey: crypto.randomUUID() }) });
  const parsed = (): ConfigurationWrite => JSON.parse(documentValue) as ConfigurationWrite;
  return <main className="space-y-6 p-4 md:p-8"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-bold">Procurement settings</h1><p className="text-muted-foreground">Versioned, audited controls. Preview every impact before activation; no service restart is required.</p></div><div className="flex gap-2"><Link className="inline-flex items-center rounded-md border border-input px-4 py-2" to={ROUTES.CONFIGURATION_IMPORT}><Upload className="mr-2 size-4" />Import</Link><Button variant="outline" onClick={() => void purchaseService.exportConfiguration(environment)}><Download className="mr-2 size-4" />Export</Button></div></header><label className="block max-w-xs"><span className="mb-2 block text-sm font-medium">Environment</span><select className="w-full rounded-md border border-input bg-background p-2" value={environment} onChange={event => setEnvironment(event.target.value as ConfigurationEnvironment)}>{['development','staging','production'].map(value => <option key={value}>{value}</option>)}</select></label><div className="grid gap-6 lg:grid-cols-[2fr_1fr]"><Card><CardHeader><CardTitle>Draft configuration document</CardTitle></CardHeader><CardContent className="space-y-4"><textarea aria-label="Configuration document" className="min-h-[34rem] w-full rounded-md border border-input bg-background p-4 font-mono text-sm" value={documentValue} onChange={event => setDocumentValue(event.target.value)} /><p className="text-sm text-muted-foreground">Receipt tolerance is bounded 0–100; RFQ suppliers 2–20; scoring weights must total 100. Integration switches reveal dependencies during server preview.</p><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={preview.isPending} onClick={() => preview.mutate(parsed())}><Eye className="mr-2 size-4" />Preview and simulate</Button><Button disabled={draft.isPending} onClick={() => draft.mutate(parsed())}>Save immutable draft version</Button></div>{preview.data && <pre className="overflow-auto rounded-md bg-muted p-4 text-xs">{JSON.stringify(preview.data, null, 2)}</pre>}{(preview.error ?? draft.error) && <p role="alert" className="text-destructive">{(preview.error ?? draft.error)?.message}</p>}</CardContent></Card><Card><CardHeader><CardTitle><History className="mr-2 inline size-4" />Version timeline</CardTitle></CardHeader><CardContent><ol className="space-y-3">{versions.data?.items.map(version => <li key={version.id} className="rounded-md border border-border p-3"><Link className="font-medium text-primary" to={ROUTES.CONFIGURATION_VERSION(version.id)}>Version {version.version}</Link><div className="text-sm text-muted-foreground">{version.status} · {version.updated_at}</div></li>)}</ol></CardContent></Card></div></main>;
};
