import { useEffect, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { ArrowLeft, Plus, RefreshCw, Save, Search } from 'lucide-react';
import { ApiError } from '@/services/api-client';
import { Button } from '@/components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';
import { Input } from '@/components/ui/Input';
import { ROUTES } from '../contracts';
import type { MutationContext, PurchaseOrderWrite, QuoteWrite, ReceiptWrite, RequisitionWrite, RFQWrite, SupplierWrite } from '../contracts';
import { purchaseService, type PageResult } from '../services/purchase-service';

export type ResourceKind = 'suppliers' | 'requisitions' | 'rfqs' | 'quotes' | 'orders' | 'receipts';
interface Row { id: string; title: string; subtitle: string; status: string; amount?: string; date?: string; lockVersion: number; raw: Record<string, unknown> }
const LABEL: Record<ResourceKind, string> = { suppliers: 'Suppliers', requisitions: 'Requisitions', rfqs: 'Requests for quotation', quotes: 'Supplier quotes', orders: 'Purchase orders', receipts: 'Goods receipts' };
const PATHS: Record<ResourceKind, { list: string; create: string; detail: (id: string) => string; edit: (id: string) => string }> = {
  suppliers: { list: ROUTES.SUPPLIERS.LIST, create: ROUTES.SUPPLIERS.CREATE, detail: ROUTES.SUPPLIERS.DETAIL, edit: ROUTES.SUPPLIERS.EDIT },
  requisitions: { list: ROUTES.REQUISITIONS.LIST, create: ROUTES.REQUISITIONS.CREATE, detail: ROUTES.REQUISITIONS.DETAIL, edit: ROUTES.REQUISITIONS.EDIT },
  rfqs: { list: ROUTES.RFQS.LIST, create: ROUTES.RFQS.CREATE, detail: ROUTES.RFQS.DETAIL, edit: ROUTES.RFQS.EDIT },
  quotes: { list: ROUTES.QUOTES.LIST, create: ROUTES.QUOTES.CREATE, detail: ROUTES.QUOTES.DETAIL, edit: ROUTES.QUOTES.EDIT },
  orders: { list: ROUTES.ORDERS.LIST, create: ROUTES.ORDERS.CREATE, detail: ROUTES.ORDERS.DETAIL, edit: ROUTES.ORDERS.EDIT },
  receipts: { list: ROUTES.RECEIPTS.LIST, create: ROUTES.RECEIPTS.CREATE, detail: ROUTES.RECEIPTS.DETAIL, edit: ROUTES.RECEIPTS.EDIT },
};
const TEMPLATE: Record<ResourceKind, Record<string, unknown>> = {
  suppliers: { supplier_code: '', supplier_name: '', email: '', phone: '', address: '', payment_terms: 'Net 30', currency: 'USD' },
  requisitions: { requisition_date: new Date().toISOString().slice(0, 10), required_date: '', purpose: '', currency: 'USD', lines: [{ item_code: '', description: '', quantity: '1.000000', estimated_unit_price: '0.0000' }] },
  rfqs: { title: '', issue_date: new Date().toISOString().slice(0, 10), submission_deadline: '', currency: 'USD', terms: '', delivery_requirements: '', lines: [] },
  quotes: { rfq_id: '', supplier_id: '', valid_until: '', currency: 'USD', payment_terms: 'Net 30', shipping_amount: '0.0000', lines: [] },
  orders: { po_date: new Date().toISOString().slice(0, 10), supplier_id: '', currency: 'USD', payment_terms: 'Net 30', shipping_address: {}, lines: [] },
  receipts: { receipt_date: new Date().toISOString().slice(0, 10), purchase_order_id: '', warehouse_id: '', lines: [] },
};
function title(kind: ResourceKind, mode: string): string { return `${mode} ${LABEL[kind]} | SARAISE`; }
function useTitle(value: string): void { useEffect(() => { document.title = value; }, [value]); }
function row(raw: Record<string, unknown>): Row {
  const text = (...keys: string[]) => keys.map(key => raw[key]).find(value => typeof value === 'string') as string | undefined;
  return { id: String(raw.id), title: text('supplier_name', 'requisition_number', 'title', 'quote_number', 'po_number', 'receipt_number') ?? String(raw.id), subtitle: text('supplier_code', 'purpose', 'supplier_name', 'currency', 'po_number') ?? '', status: text('status') ?? 'unknown', amount: text('total_amount'), date: text('required_date', 'submission_deadline', 'delivery_date', 'expected_delivery_date', 'receipt_date'), lockVersion: Number(raw.lock_version ?? 1), raw };
}
async function list(kind: ResourceKind, filters: Record<string, string | number | undefined>): Promise<PageResult<Row>> {
  const result = kind === 'suppliers' ? await purchaseService.listSuppliers(filters) : kind === 'requisitions' ? await purchaseService.listRequisitions(filters) : kind === 'rfqs' ? await purchaseService.listRFQs(filters) : kind === 'quotes' ? await purchaseService.listQuotes(filters) : kind === 'orders' ? await purchaseService.listPurchaseOrders(filters) : await purchaseService.listReceipts(filters);
  return { items: result.items.map(value => row(value as unknown as Record<string, unknown>)), meta: result.meta };
}
async function detail(kind: ResourceKind, id: string): Promise<Row> {
  const value = kind === 'suppliers' ? await purchaseService.getSupplier(id) : kind === 'requisitions' ? await purchaseService.getRequisition(id) : kind === 'rfqs' ? await purchaseService.getRFQ(id) : kind === 'quotes' ? await purchaseService.getQuote(id) : kind === 'orders' ? await purchaseService.getPurchaseOrder(id) : await purchaseService.getReceipt(id);
  return row(value as unknown as Record<string, unknown>);
}
function context(lockVersion?: number): MutationContext { return { idempotencyKey: crypto.randomUUID(), lockVersion }; }
async function save(kind: ResourceKind, value: Record<string, unknown>, id?: string, lockVersion?: number): Promise<Row> {
  const saved = kind === 'suppliers' ? id ? await purchaseService.updateSupplier(id, value as unknown as Partial<SupplierWrite>, context(lockVersion)) : await purchaseService.createSupplier(value as unknown as SupplierWrite, context())
    : kind === 'requisitions' ? id ? await purchaseService.updateRequisition(id, value as unknown as Partial<RequisitionWrite>, context(lockVersion)) : await purchaseService.createRequisition(value as unknown as RequisitionWrite, context())
    : kind === 'rfqs' ? id ? await purchaseService.updateRFQ(id, value as unknown as Partial<RFQWrite>, context(lockVersion)) : await purchaseService.createRFQ(value as unknown as RFQWrite, context())
    : kind === 'quotes' ? id ? await purchaseService.updateQuote(id, value as unknown as Partial<QuoteWrite>, context(lockVersion)) : await purchaseService.createQuote(value as unknown as QuoteWrite, context())
    : kind === 'orders' ? id ? await purchaseService.updatePurchaseOrder(id, value as unknown as Partial<PurchaseOrderWrite>, context(lockVersion)) : await purchaseService.createPurchaseOrder(value as unknown as PurchaseOrderWrite, context())
    : id ? await purchaseService.updateReceipt(id, value as unknown as Partial<ReceiptWrite>, context(lockVersion)) : await purchaseService.createReceipt(value as unknown as ReceiptWrite, context());
  return row(saved as unknown as Record<string, unknown>);
}
function CorrelationError({ error, retry }: { error: Error; retry: () => void }) {
  const apiError = error instanceof ApiError ? error : undefined;
  return <Card role="alert"><CardContent className="space-y-3 p-6"><h2 className="font-semibold">This procurement data could not be loaded</h2><p className="text-sm text-muted-foreground">{error.message}</p>{apiError?.correlationId && <p className="font-mono text-xs">Correlation: {apiError.correlationId}</p>}<Button onClick={retry}><RefreshCw className="mr-2 size-4" />Retry</Button></CardContent></Card>;
}

export function ResourceListPage({ kind }: { kind: ResourceKind }) {
  useTitle(title(kind, 'Manage')); const [params, setParams] = useSearchParams(); const search = params.get('search') ?? ''; const status = params.get('status') ?? ''; const page = Number(params.get('page') ?? 1);
  const queryResult = useQuery({ queryKey: ['purchase', kind, search, status, page], queryFn: () => list(kind, { search, status, page, ordering: kind === 'suppliers' ? 'supplier_name' : undefined }) });
  const update = (key: string, value: string) => { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); if (key !== 'page') next.set('page', '1'); setParams(next); };
  return <main className="space-y-6 p-4 md:p-8"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-bold text-foreground">{LABEL[kind]}</h1><p className="text-muted-foreground">Tenant-safe procurement records with traceable lifecycle state.</p></div><Link className="inline-flex items-center rounded-md bg-primary px-4 py-2 text-primary-foreground" to={PATHS[kind].create}><Plus className="mr-2 size-4" />Create</Link></header>
    <Card><CardContent className="grid gap-3 p-4 md:grid-cols-[1fr_12rem]"><label className="relative"><span className="sr-only">Search</span><Search className="absolute left-3 top-3 size-4 text-muted-foreground" /><Input className="pl-9" value={search} onChange={event => update('search', event.target.value)} placeholder={`Search ${LABEL[kind].toLowerCase()}`} /></label><select aria-label="Status filter" className="rounded-md border border-input bg-background px-3" value={status} onChange={event => update('status', event.target.value)}><option value="">All statuses</option>{['draft','active','pending_approval','approved','open','closed','submitted','acknowledged','partially_received','completed','cancelled','archived'].map(value => <option key={value}>{value}</option>)}</select></CardContent></Card>
    {queryResult.isLoading ? <div aria-label="Loading records" className="space-y-3">{Array.from({ length: 5 }, (_, index) => <div key={index} className="h-16 animate-pulse rounded-md bg-muted" />)}</div> : queryResult.error ? <CorrelationError error={queryResult.error} retry={() => void queryResult.refetch()} /> : queryResult.data?.items.length === 0 ? <Card><CardContent className="p-10 text-center"><h2 className="text-xl font-semibold">{search || status ? 'No records match these filters' : `No ${LABEL[kind].toLowerCase()} yet`}</h2><p className="mt-2 text-muted-foreground">{search || status ? 'Keep your filters visible or reset them to broaden the result.' : 'Create the first record to begin this workflow.'}</p>{search || status ? <Button className="mt-4" variant="outline" onClick={() => setParams({})}>Reset filters</Button> : <Link className="mt-4 inline-flex rounded-md bg-primary px-4 py-2 text-primary-foreground" to={PATHS[kind].create}>Create first record</Link>}</CardContent></Card> : <Card className="overflow-hidden"><div className="hidden overflow-x-auto md:block"><table className="w-full"><thead className="bg-muted"><tr>{['Record','Status','Amount','Due / delivery','Next action'].map(column => <th key={column} className="px-4 py-3 text-left text-xs font-semibold uppercase text-muted-foreground">{column}</th>)}</tr></thead><tbody>{queryResult.data?.items.map(item => <tr key={item.id} className="border-t border-border"><td className="p-4"><Link className="font-medium text-primary" to={PATHS[kind].detail(item.id)}>{item.title}</Link><div className="text-sm text-muted-foreground">{item.subtitle}</div></td><td className="p-4"><span className="rounded-full bg-muted px-2 py-1 text-xs">{item.status}</span></td><td className="p-4 tabular-nums">{item.amount ?? '—'}</td><td className="p-4">{item.date ?? '—'}</td><td className="p-4"><Link className="text-primary" to={PATHS[kind].detail(item.id)}>Review</Link></td></tr>)}</tbody></table></div><div className="grid gap-3 p-3 md:hidden">{queryResult.data?.items.map(item => <Link key={item.id} to={PATHS[kind].detail(item.id)} className="rounded-md border border-border p-4"><div className="flex justify-between"><strong>{item.title}</strong><span>{item.status}</span></div><p className="text-sm text-muted-foreground">{item.subtitle}</p></Link>)}</div></Card>}
    {queryResult.data && <nav aria-label="Pagination" className="flex items-center justify-between"><span className="text-sm text-muted-foreground">Page {queryResult.data.meta.pagination.page} of {Math.max(queryResult.data.meta.pagination.total_pages, 1)}</span><div className="flex gap-2"><Button variant="outline" disabled={!queryResult.data.meta.pagination.has_previous} onClick={() => update('page', String(page - 1))}>Previous</Button><Button variant="outline" disabled={!queryResult.data.meta.pagination.has_next} onClick={() => update('page', String(page + 1))}>Next</Button></div></nav>}</main>;
}

export function ResourceDetailPage({ kind }: { kind: ResourceKind }) {
  useTitle(title(kind, 'Review')); const { id = '' } = useParams(); const result = useQuery({ queryKey: ['purchase', kind, id], queryFn: () => detail(kind, id), enabled: Boolean(id) });
  if (result.isLoading) return <div className="space-y-3 p-8" aria-label="Loading detail"><div className="h-12 animate-pulse rounded bg-muted" /><div className="h-72 animate-pulse rounded bg-muted" /></div>;
  if (result.error) return <main className="p-8"><CorrelationError error={result.error} retry={() => void result.refetch()} /></main>;
  if (!result.data) return <main className="p-8"><h1>Record not found</h1></main>;
  const lines = Array.isArray(result.data.raw.lines) ? result.data.raw.lines : [];
  return <main className="space-y-6 p-4 md:p-8"><Link className="inline-flex items-center text-primary" to={PATHS[kind].list}><ArrowLeft className="mr-2 size-4" />Back</Link><header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-3xl font-bold">{result.data.title}</h1><p className="text-muted-foreground">{result.data.subtitle}</p></div><div className="flex gap-2"><span className="rounded-full bg-muted px-3 py-2 text-sm">{result.data.status}</span>{['draft','rejected'].includes(result.data.status) && <Link className="rounded-md bg-primary px-4 py-2 text-primary-foreground" to={PATHS[kind].edit(id)}>Edit</Link>}</div></header><div className="grid gap-6 lg:grid-cols-[2fr_1fr]"><Card><CardHeader><CardTitle>Summary and line evidence</CardTitle></CardHeader><CardContent><dl className="grid gap-4 sm:grid-cols-2">{Object.entries(result.data.raw).filter(([, value]) => ['string','number','boolean'].includes(typeof value)).slice(0, 14).map(([key,value]) => <div key={key}><dt className="text-xs uppercase text-muted-foreground">{key.replaceAll('_',' ')}</dt><dd className="break-words">{String(value)}</dd></div>)}</dl>{lines.length > 0 && <div className="mt-6 overflow-x-auto"><table className="w-full"><thead><tr><th className="text-left">Line</th><th className="text-left">Evidence</th></tr></thead><tbody>{lines.map((line,index) => <tr className="border-t" key={index}><td className="py-3">{index + 1}</td><td><pre className="whitespace-pre-wrap text-xs">{JSON.stringify(line, null, 2)}</pre></td></tr>)}</tbody></table></div>}</CardContent></Card><Card><CardHeader><CardTitle>Immutable activity</CardTitle></CardHeader><CardContent><ol className="space-y-4"><li className="border-l-2 border-primary pl-3"><strong>Created</strong><p className="text-sm text-muted-foreground">{typeof result.data.raw.created_at === 'string' ? result.data.raw.created_at : ''}</p></li><li className="border-l-2 border-border pl-3"><strong>Last updated</strong><p className="text-sm text-muted-foreground">{typeof result.data.raw.updated_at === 'string' ? result.data.raw.updated_at : ''}</p></li></ol></CardContent></Card></div></main>;
}

export function ResourceFormPage({ kind, edit = false }: { kind: ResourceKind; edit?: boolean }) {
  useTitle(title(kind, edit ? 'Edit' : 'Create')); const { id = '' } = useParams(); const navigate = useNavigate(); const client = useQueryClient(); const existing = useQuery({ queryKey: ['purchase', kind, id], queryFn: () => detail(kind, id), enabled: edit && Boolean(id) });
  const initial = useMemo(() => edit && existing.data ? existing.data.raw : TEMPLATE[kind], [edit, existing.data, kind]); const [documentValue, setDocumentValue] = useState(JSON.stringify(initial, null, 2)); const [parseError, setParseError] = useState('');
  useEffect(() => { setDocumentValue(JSON.stringify(initial, null, 2)); }, [initial]);
  useEffect(() => { const block = (event: BeforeUnloadEvent) => { event.preventDefault(); }; window.addEventListener('beforeunload', block); return () => window.removeEventListener('beforeunload', block); }, []);
  const mutation = useMutation({ mutationFn: (value: Record<string, unknown>) => save(kind, value, edit ? id : undefined, existing.data?.lockVersion), onSuccess: saved => { void client.invalidateQueries({ queryKey: ['purchase', kind] }); navigate(PATHS[kind].detail(saved.id)); } });
  const submit = () => { try { const parsed: unknown = JSON.parse(documentValue); if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) throw new Error('The document must be a JSON object.'); setParseError(''); mutation.mutate(parsed as Record<string, unknown>); } catch (error) { setParseError(error instanceof Error ? error.message : 'Invalid JSON document'); } };
  if (existing.isLoading) return <div className="h-72 animate-pulse bg-muted p-8" />;
  return <main className="space-y-6 p-4 md:p-8"><Button variant="ghost" onClick={() => navigate(PATHS[kind].list)}><ArrowLeft className="mr-2 size-4" />Back</Button><header><h1 className="text-3xl font-bold">{edit ? 'Edit' : 'Create'} {LABEL[kind]}</h1><p className="text-muted-foreground">One-screen itemized editor. Server-side validation remains authoritative; calculated status, totals, tenant and actor fields are intentionally unavailable.</p></header><Card><CardHeader><CardTitle>Procurement document</CardTitle></CardHeader><CardContent className="space-y-4"><label className="block"><span className="mb-2 block text-sm font-medium">Fields and itemized lines (JSON)</span><textarea className="min-h-[28rem] w-full rounded-md border border-input bg-background p-4 font-mono text-sm" value={documentValue} onChange={event => setDocumentValue(event.target.value)} aria-describedby="document-help" /></label><p id="document-help" className="text-sm text-muted-foreground">Review quantities, prices, dates and related IDs before submitting. Unknown and protected fields are rejected.</p>{parseError && <p role="alert" className="text-sm text-destructive">{parseError}</p>}{mutation.error && <CorrelationError error={mutation.error} retry={submit} />}<div className="rounded-md bg-muted p-4"><h2 className="font-semibold">Pre-submit review</h2><p className="text-sm text-muted-foreground">The exact document above will be validated atomically. Duplicate clicks are prevented and the mutation carries a unique idempotency key.</p></div><Button disabled={mutation.isPending} onClick={submit}><Save className="mr-2 size-4" />{mutation.isPending ? 'Saving…' : 'Validate and save'}</Button></CardContent></Card></main>;
}
