import { lazy } from 'react';
import {
  Building2, CalendarCheck, Eye, FilePlus2, LayoutDashboard, Palmtree, Pencil,
  Settings, Users,
} from 'lucide-react';
import type { TenantRoute, TenantRouteIcon } from '@/navigation/tenant-route-types';
import { ROUTES } from './contracts';

const module = 'human_resources';
const sidebar = (label: string, icon: TenantRouteIcon, order: number, path?: string) => ({
  type: 'sidebar' as const, label, icon, order, ...(path ? { path } : {}),
});

export const tenantRoutes = [
  { id: 'human-resources.overview', module, path: ROUTES.OVERVIEW, title: 'Human Resources overview', sourceFile: 'modules/human_resources/pages/HumanResourcesOverviewPage.tsx', Page: lazy(() => import('./pages/HumanResourcesOverviewPage').then(({ HumanResourcesOverviewPage }) => ({ default: HumanResourcesOverviewPage }))), navigation: sidebar('Overview', LayoutDashboard, 500) },
  { id: 'human-resources.employees.list', module, path: ROUTES.EMPLOYEES, title: 'Employees', sourceFile: 'modules/human_resources/pages/EmployeeListPage.tsx', Page: lazy(() => import('./pages/EmployeeListPage').then(({ EmployeeListPage }) => ({ default: EmployeeListPage }))), navigation: sidebar('Employees', Users, 510) },
  { id: 'human-resources.employees.create', module, path: ROUTES.EMPLOYEE_CREATE, title: 'Create employee', sourceFile: 'modules/human_resources/pages/CreateEmployeePage.tsx', Page: lazy(() => import('./pages/CreateEmployeePage').then(({ CreateEmployeePage }) => ({ default: CreateEmployeePage }))), navigation: sidebar('Create employee', FilePlus2, 511) },
  { id: 'human-resources.employees.detail', module, path: `${ROUTES.EMPLOYEES}/:id`, title: 'Employee detail', sourceFile: 'modules/human_resources/pages/EmployeeDetailPage.tsx', Page: lazy(() => import('./pages/EmployeeDetailPage').then(({ EmployeeDetailPage }) => ({ default: EmployeeDetailPage }))), navigation: sidebar('Employee detail', Eye, 512, ROUTES.EMPLOYEES) },
  { id: 'human-resources.employees.edit', module, path: `${ROUTES.EMPLOYEES}/:id/edit`, title: 'Edit employee', sourceFile: 'modules/human_resources/pages/EditEmployeePage.tsx', Page: lazy(() => import('./pages/EditEmployeePage').then(({ EditEmployeePage }) => ({ default: EditEmployeePage }))), navigation: sidebar('Edit employee', Pencil, 513, ROUTES.EMPLOYEES) },
  { id: 'human-resources.departments.list', module, path: ROUTES.DEPARTMENTS, title: 'Departments', sourceFile: 'modules/human_resources/pages/DepartmentListPage.tsx', Page: lazy(() => import('./pages/DepartmentListPage').then(({ DepartmentListPage }) => ({ default: DepartmentListPage }))), navigation: sidebar('Departments', Building2, 520) },
  { id: 'human-resources.departments.create', module, path: ROUTES.DEPARTMENT_CREATE, title: 'Create department', sourceFile: 'modules/human_resources/pages/CreateDepartmentPage.tsx', Page: lazy(() => import('./pages/CreateDepartmentPage').then(({ CreateDepartmentPage }) => ({ default: CreateDepartmentPage }))), navigation: sidebar('Create department', FilePlus2, 521) },
  { id: 'human-resources.departments.detail', module, path: `${ROUTES.DEPARTMENTS}/:id`, title: 'Department detail', sourceFile: 'modules/human_resources/pages/DepartmentDetailPage.tsx', Page: lazy(() => import('./pages/DepartmentDetailPage').then(({ DepartmentDetailPage }) => ({ default: DepartmentDetailPage }))), navigation: sidebar('Department detail', Eye, 522, ROUTES.DEPARTMENTS) },
  { id: 'human-resources.departments.edit', module, path: `${ROUTES.DEPARTMENTS}/:id/edit`, title: 'Edit department', sourceFile: 'modules/human_resources/pages/EditDepartmentPage.tsx', Page: lazy(() => import('./pages/EditDepartmentPage').then(({ EditDepartmentPage }) => ({ default: EditDepartmentPage }))), navigation: sidebar('Edit department', Pencil, 523, ROUTES.DEPARTMENTS) },
  { id: 'human-resources.attendance.list', module, path: ROUTES.ATTENDANCE, title: 'Attendance', sourceFile: 'modules/human_resources/pages/AttendanceListPage.tsx', Page: lazy(() => import('./pages/AttendanceListPage').then(({ AttendanceListPage }) => ({ default: AttendanceListPage }))), navigation: sidebar('Attendance', CalendarCheck, 530) },
  { id: 'human-resources.attendance.create', module, path: ROUTES.ATTENDANCE_CREATE, title: 'Record attendance', sourceFile: 'modules/human_resources/pages/CreateAttendancePage.tsx', Page: lazy(() => import('./pages/CreateAttendancePage').then(({ CreateAttendancePage }) => ({ default: CreateAttendancePage }))), navigation: sidebar('Record attendance', FilePlus2, 531) },
  { id: 'human-resources.attendance.detail', module, path: `${ROUTES.ATTENDANCE}/:id`, title: 'Attendance detail', sourceFile: 'modules/human_resources/pages/AttendanceDetailPage.tsx', Page: lazy(() => import('./pages/AttendanceDetailPage').then(({ AttendanceDetailPage }) => ({ default: AttendanceDetailPage }))), navigation: sidebar('Attendance detail', Eye, 532, ROUTES.ATTENDANCE) },
  { id: 'human-resources.attendance.edit', module, path: `${ROUTES.ATTENDANCE}/:id/edit`, title: 'Correct attendance', sourceFile: 'modules/human_resources/pages/EditAttendancePage.tsx', Page: lazy(() => import('./pages/EditAttendancePage').then(({ EditAttendancePage }) => ({ default: EditAttendancePage }))), navigation: sidebar('Correct attendance', Pencil, 533, ROUTES.ATTENDANCE) },
  { id: 'human-resources.leave.workspace', module, path: ROUTES.LEAVE, title: 'Leave workspace', sourceFile: 'modules/human_resources/pages/LeaveWorkspacePage.tsx', Page: lazy(() => import('./pages/LeaveWorkspacePage').then(({ LeaveWorkspacePage }) => ({ default: LeaveWorkspacePage }))), navigation: sidebar('Leave', Palmtree, 540) },
  { id: 'human-resources.leave-balances.create', module, path: ROUTES.LEAVE_BALANCE_CREATE, title: 'Allocate leave', sourceFile: 'modules/human_resources/pages/CreateLeaveBalancePage.tsx', Page: lazy(() => import('./pages/CreateLeaveBalancePage').then(({ CreateLeaveBalancePage }) => ({ default: CreateLeaveBalancePage }))), navigation: sidebar('Allocate leave', FilePlus2, 541) },
  { id: 'human-resources.leave-balances.detail', module, path: `${ROUTES.LEAVE}/balances/:id`, title: 'Leave allocation detail', sourceFile: 'modules/human_resources/pages/LeaveBalanceDetailPage.tsx', Page: lazy(() => import('./pages/LeaveBalanceDetailPage').then(({ LeaveBalanceDetailPage }) => ({ default: LeaveBalanceDetailPage }))), navigation: sidebar('Leave allocation detail', Eye, 542, ROUTES.LEAVE) },
  { id: 'human-resources.leave-balances.edit', module, path: `${ROUTES.LEAVE}/balances/:id/edit`, title: 'Adjust leave allocation', sourceFile: 'modules/human_resources/pages/EditLeaveBalancePage.tsx', Page: lazy(() => import('./pages/EditLeaveBalancePage').then(({ EditLeaveBalancePage }) => ({ default: EditLeaveBalancePage }))), navigation: sidebar('Adjust leave allocation', Pencil, 543, ROUTES.LEAVE) },
  { id: 'human-resources.leave-requests.create', module, path: ROUTES.LEAVE_REQUEST_CREATE, title: 'Request leave', sourceFile: 'modules/human_resources/pages/CreateLeaveRequestPage.tsx', Page: lazy(() => import('./pages/CreateLeaveRequestPage').then(({ CreateLeaveRequestPage }) => ({ default: CreateLeaveRequestPage }))), navigation: sidebar('Request leave', FilePlus2, 544) },
  { id: 'human-resources.leave-requests.detail', module, path: `${ROUTES.LEAVE}/requests/:id`, title: 'Leave request detail', sourceFile: 'modules/human_resources/pages/LeaveRequestDetailPage.tsx', Page: lazy(() => import('./pages/LeaveRequestDetailPage').then(({ LeaveRequestDetailPage }) => ({ default: LeaveRequestDetailPage }))), navigation: sidebar('Leave request detail', Eye, 545, ROUTES.LEAVE) },
  { id: 'human-resources.leave-requests.edit', module, path: `${ROUTES.LEAVE}/requests/:id/edit`, title: 'Edit leave request', sourceFile: 'modules/human_resources/pages/EditLeaveRequestPage.tsx', Page: lazy(() => import('./pages/EditLeaveRequestPage').then(({ EditLeaveRequestPage }) => ({ default: EditLeaveRequestPage }))), navigation: sidebar('Edit leave request', Pencil, 546, ROUTES.LEAVE) },
  { id: 'human-resources.configuration', module, path: ROUTES.CONFIGURATION, title: 'Human Resources configuration', sourceFile: 'modules/human_resources/pages/HumanResourcesConfigurationPage.tsx', Page: lazy(() => import('./pages/HumanResourcesConfigurationPage').then(({ HumanResourcesConfigurationPage }) => ({ default: HumanResourcesConfigurationPage }))), requiredPermission: 'hr.configuration:read', navigation: sidebar('Configuration', Settings, 550) },
] satisfies readonly TenantRoute[];

export default tenantRoutes;
