import { lazy } from 'react'; import { Building2, CalendarCheck, LayoutDashboard, Palmtree, Users } from 'lucide-react'; import type { TenantRoute } from '@/navigation/tenant-route-types'; import { ROUTES } from './contracts';
const module = 'human_resources'; const contextual = (parentRouteId: string) => ({ type: 'contextual' as const, parentRouteId });
export const tenantRoutes = [
  { id: 'human-resources.overview', module, path: ROUTES.OVERVIEW, sourceFile: 'modules/human_resources/pages/HumanResourcesOverviewPage.tsx', Page: lazy(() => import('./pages/HumanResourcesOverviewPage').then(({ HumanResourcesOverviewPage }) => ({ default: HumanResourcesOverviewPage }))), navigation: { type: 'sidebar', label: 'Overview', icon: LayoutDashboard, order: 500 } },
  { id: 'human-resources.employees.list', module, path: ROUTES.EMPLOYEES, sourceFile: 'modules/human_resources/pages/EmployeeListPage.tsx', Page: lazy(() => import('./pages/EmployeeListPage').then(({ EmployeeListPage }) => ({ default: EmployeeListPage }))), navigation: { type: 'sidebar', label: 'Employees', icon: Users, order: 510 } },
  { id: 'human-resources.employees.create', module, path: ROUTES.EMPLOYEE_CREATE, sourceFile: 'modules/human_resources/pages/CreateEmployeePage.tsx', Page: lazy(() => import('./pages/CreateEmployeePage').then(({ CreateEmployeePage }) => ({ default: CreateEmployeePage }))), navigation: contextual('human-resources.employees.list') },
  { id: 'human-resources.employees.detail', module, path: `${ROUTES.EMPLOYEES}/:id`, sourceFile: 'modules/human_resources/pages/EmployeeDetailPage.tsx', Page: lazy(() => import('./pages/EmployeeDetailPage').then(({ EmployeeDetailPage }) => ({ default: EmployeeDetailPage }))), navigation: contextual('human-resources.employees.list') },
  { id: 'human-resources.employees.edit', module, path: `${ROUTES.EMPLOYEES}/:id/edit`, sourceFile: 'modules/human_resources/pages/EditEmployeePage.tsx', Page: lazy(() => import('./pages/EditEmployeePage').then(({ EditEmployeePage }) => ({ default: EditEmployeePage }))), navigation: contextual('human-resources.employees.list') },
  { id: 'human-resources.departments.list', module, path: ROUTES.DEPARTMENTS, sourceFile: 'modules/human_resources/pages/DepartmentListPage.tsx', Page: lazy(() => import('./pages/DepartmentListPage').then(({ DepartmentListPage }) => ({ default: DepartmentListPage }))), navigation: { type: 'sidebar', label: 'Departments', icon: Building2, order: 520 } },
  { id: 'human-resources.departments.create', module, path: ROUTES.DEPARTMENT_CREATE, sourceFile: 'modules/human_resources/pages/CreateDepartmentPage.tsx', Page: lazy(() => import('./pages/CreateDepartmentPage').then(({ CreateDepartmentPage }) => ({ default: CreateDepartmentPage }))), navigation: contextual('human-resources.departments.list') },
  { id: 'human-resources.departments.detail', module, path: `${ROUTES.DEPARTMENTS}/:id`, sourceFile: 'modules/human_resources/pages/DepartmentDetailPage.tsx', Page: lazy(() => import('./pages/DepartmentDetailPage').then(({ DepartmentDetailPage }) => ({ default: DepartmentDetailPage }))), navigation: contextual('human-resources.departments.list') },
  { id: 'human-resources.departments.edit', module, path: `${ROUTES.DEPARTMENTS}/:id/edit`, sourceFile: 'modules/human_resources/pages/EditDepartmentPage.tsx', Page: lazy(() => import('./pages/EditDepartmentPage').then(({ EditDepartmentPage }) => ({ default: EditDepartmentPage }))), navigation: contextual('human-resources.departments.list') },
  { id: 'human-resources.attendance.list', module, path: ROUTES.ATTENDANCE, sourceFile: 'modules/human_resources/pages/AttendanceListPage.tsx', Page: lazy(() => import('./pages/AttendanceListPage').then(({ AttendanceListPage }) => ({ default: AttendanceListPage }))), navigation: { type: 'sidebar', label: 'Attendance', icon: CalendarCheck, order: 530 } },
  { id: 'human-resources.attendance.create', module, path: ROUTES.ATTENDANCE_CREATE, sourceFile: 'modules/human_resources/pages/CreateAttendancePage.tsx', Page: lazy(() => import('./pages/CreateAttendancePage').then(({ CreateAttendancePage }) => ({ default: CreateAttendancePage }))), navigation: contextual('human-resources.attendance.list') },
  { id: 'human-resources.attendance.detail', module, path: `${ROUTES.ATTENDANCE}/:id`, sourceFile: 'modules/human_resources/pages/AttendanceDetailPage.tsx', Page: lazy(() => import('./pages/AttendanceDetailPage').then(({ AttendanceDetailPage }) => ({ default: AttendanceDetailPage }))), navigation: contextual('human-resources.attendance.list') },
  { id: 'human-resources.attendance.edit', module, path: `${ROUTES.ATTENDANCE}/:id/edit`, sourceFile: 'modules/human_resources/pages/EditAttendancePage.tsx', Page: lazy(() => import('./pages/EditAttendancePage').then(({ EditAttendancePage }) => ({ default: EditAttendancePage }))), navigation: contextual('human-resources.attendance.list') },
  { id: 'human-resources.leave.workspace', module, path: ROUTES.LEAVE, sourceFile: 'modules/human_resources/pages/LeaveWorkspacePage.tsx', Page: lazy(() => import('./pages/LeaveWorkspacePage').then(({ LeaveWorkspacePage }) => ({ default: LeaveWorkspacePage }))), navigation: { type: 'sidebar', label: 'Leave', icon: Palmtree, order: 540 } },
  { id: 'human-resources.leave-balances.create', module, path: ROUTES.LEAVE_BALANCE_CREATE, sourceFile: 'modules/human_resources/pages/CreateLeaveBalancePage.tsx', Page: lazy(() => import('./pages/CreateLeaveBalancePage').then(({ CreateLeaveBalancePage }) => ({ default: CreateLeaveBalancePage }))), navigation: contextual('human-resources.leave.workspace') },
  { id: 'human-resources.leave-balances.detail', module, path: `${ROUTES.LEAVE}/balances/:id`, sourceFile: 'modules/human_resources/pages/LeaveBalanceDetailPage.tsx', Page: lazy(() => import('./pages/LeaveBalanceDetailPage').then(({ LeaveBalanceDetailPage }) => ({ default: LeaveBalanceDetailPage }))), navigation: contextual('human-resources.leave.workspace') },
  { id: 'human-resources.leave-balances.edit', module, path: `${ROUTES.LEAVE}/balances/:id/edit`, sourceFile: 'modules/human_resources/pages/EditLeaveBalancePage.tsx', Page: lazy(() => import('./pages/EditLeaveBalancePage').then(({ EditLeaveBalancePage }) => ({ default: EditLeaveBalancePage }))), navigation: contextual('human-resources.leave.workspace') },
  { id: 'human-resources.leave-requests.create', module, path: ROUTES.LEAVE_REQUEST_CREATE, sourceFile: 'modules/human_resources/pages/CreateLeaveRequestPage.tsx', Page: lazy(() => import('./pages/CreateLeaveRequestPage').then(({ CreateLeaveRequestPage }) => ({ default: CreateLeaveRequestPage }))), navigation: contextual('human-resources.leave.workspace') },
  { id: 'human-resources.leave-requests.detail', module, path: `${ROUTES.LEAVE}/requests/:id`, sourceFile: 'modules/human_resources/pages/LeaveRequestDetailPage.tsx', Page: lazy(() => import('./pages/LeaveRequestDetailPage').then(({ LeaveRequestDetailPage }) => ({ default: LeaveRequestDetailPage }))), navigation: contextual('human-resources.leave.workspace') },
  { id: 'human-resources.leave-requests.edit', module, path: `${ROUTES.LEAVE}/requests/:id/edit`, sourceFile: 'modules/human_resources/pages/EditLeaveRequestPage.tsx', Page: lazy(() => import('./pages/EditLeaveRequestPage').then(({ EditLeaveRequestPage }) => ({ default: EditLeaveRequestPage }))), navigation: contextual('human-resources.leave.workspace') },
] satisfies readonly TenantRoute[];
export default tenantRoutes;
