/* eslint-disable complexity -- each configuration workflow has an independent governed recovery path */
import { useEffect, useMemo, useRef, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Download, FileUp, RotateCcw, Save, SearchCheck } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';
import type { CrmConfiguration, CrmConfigurationDocument, CrmConfigurationExport, CrmConfigurationWrite, JsonPrimitive, MetadataValue } from '../contracts';
import { CrmPage, GovernedError, LiveRegion, PageSkeleton, fieldClass } from '../components/CrmPage';
import { crmKeys, crmService } from '../services/crm-service';

type DraftError = Readonly<Record<string,string>>;

function label(path:string):string { return path.split('.').at(-1)?.replaceAll('_',' ') ?? path; }
function jsonValue(value:unknown):MetadataValue { return JSON.parse(JSON.stringify(value)) as MetadataValue; }
function replaceAtPath(document:CrmConfigurationDocument,path:string,next:MetadataValue):CrmConfigurationDocument {
  const clone:unknown=JSON.parse(JSON.stringify(document));
  if(!clone||typeof clone!=='object'||Array.isArray(clone))throw new Error('Configuration document is invalid.');
  const segments=path.split('.'); let cursor=clone as Record<string,unknown>;
  segments.forEach((segment,index)=>{if(index===segments.length-1){cursor[segment]=next;return;}const child=cursor[segment];if(!child||typeof child!=='object'||Array.isArray(child))throw new Error(`Configuration path ${path} is invalid.`);cursor=child as Record<string,unknown>});
  return clone as CrmConfigurationDocument;
}
function validateDraft(draft:CrmConfigurationWrite):DraftError {
  const errors:Record<string,string>={}; const d=draft.document;
  if(!draft.environment.trim())errors.environment='Environment is required.';
  if(draft.rollout.percentage<0||draft.rollout.percentage>100)errors.rollout='Rollout must be between 0 and 100 percent.';
  if(d.lead.score_min>=d.lead.score_max)errors['lead.score_min']='Minimum score must be lower than maximum score.';
  const thresholds=d.lead.grade_thresholds;
  if(!(thresholds.A>thresholds.B&&thresholds.B>thresholds.C&&thresholds.C>=thresholds.D))errors['lead.grade_thresholds']='Grade thresholds must descend from A through D.';
  if(d.opportunity.probability_min>=d.opportunity.probability_max)errors['opportunity.probability_min']='Minimum probability must be lower than maximum probability.';
  if(Number(d.opportunity.minimum_amount)<=0)errors['opportunity.minimum_amount']='Minimum amount must be positive.';
  if(d.forecast.minimum_period_days>d.forecast.default_period_days||d.forecast.default_period_days>d.forecast.maximum_period_days)errors['forecast.default_period_days']='Default forecast period must be within configured limits.';
  if(d.pagination.default_page_size<1||d.pagination.default_page_size>d.pagination.maximum_page_size)errors['pagination.default_page_size']='Default page size must be within the configured maximum.';
  if(d.ui.pipeline_fetch_limit<1||d.ui.pipeline_fetch_limit>d.pagination.maximum_page_size)errors['ui.pipeline_fetch_limit']='Pipeline fetch limit must be within the API pagination maximum.';
  if(!d.opportunity.stages.length)errors['opportunity.stages']='At least one pipeline stage is required.';
  return errors;
}

function ScalarEditor({path,value,error,onChange}:{path:string;value:JsonPrimitive;error?:string;onChange:(value:MetadataValue)=>void}) {
  const id=`crm-config-${path.replaceAll('.','-')}`;
  return <label htmlFor={id} className="block space-y-1 text-sm"><span className="capitalize">{label(path)}</span>{typeof value==='boolean'?<input id={id} type="checkbox" checked={value} onChange={event=>onChange(event.target.checked)} className="ml-2"/>:<input id={id} type={typeof value==='number'?'number':'text'} value={value===null?'':String(value)} onChange={event=>onChange(typeof value==='number'?Number(event.target.value):event.target.value)} aria-invalid={!!error} className={fieldClass}/>}<span className="block text-xs text-muted-foreground">Configuration key: {path}</span>{error?<span role="alert" className="block text-xs text-destructive">{error}</span>:null}</label>;
}
function ConfigurationEditor({value,path='',errors,onChange}:{value:MetadataValue;path?:string;errors:DraftError;onChange:(path:string,value:MetadataValue)=>void}) {
  if(value===null||typeof value!=='object')return <ScalarEditor path={path} value={value} error={errors[path]} onChange={next=>onChange(path,next)}/>;
  if(Array.isArray(value))return <JsonEditor path={path} value={value} error={errors[path]} onChange={next=>onChange(path,next)}/>;
  return <div className="grid gap-4 sm:grid-cols-2">{Object.entries(value).map(([key,child])=>{const childPath=path?`${path}.${key}`:key;return child!==null&&typeof child==='object'&&!Array.isArray(child)?<fieldset key={childPath} className="space-y-3 rounded-md border p-3 sm:col-span-2"><legend className="px-1 font-medium capitalize">{label(childPath)}</legend><ConfigurationEditor value={child} path={childPath} errors={errors} onChange={onChange}/></fieldset>:<ConfigurationEditor key={childPath} value={child} path={childPath} errors={errors} onChange={onChange}/>})}</div>;
}
function JsonEditor({path,value,error,onChange}:{path:string;value:readonly MetadataValue[];error?:string;onChange:(value:MetadataValue)=>void}) {
  const [text,setText]=useState(()=>JSON.stringify(value,null,2)); const [parseError,setParseError]=useState('');
  useEffect(()=>setText(JSON.stringify(value,null,2)),[value]);
  return <label className="block space-y-1 text-sm"><span className="capitalize">{label(path)}</span><textarea rows={Math.min(14,Math.max(4,value.length*3))} value={text} onChange={event=>setText(event.target.value)} onBlur={()=>{try{const parsed:unknown=JSON.parse(text);if(!Array.isArray(parsed))throw new Error('Value must be a JSON array.');setParseError('');onChange(parsed as MetadataValue)}catch(reason){setParseError(reason instanceof Error?reason.message:'Invalid JSON array.')}}} aria-invalid={!!error||!!parseError} className={`${fieldClass} font-mono`}/><span className="block text-xs text-muted-foreground">Edit as a JSON array. Invalid JSON is never applied.</span>{error||parseError?<span role="alert" className="block text-xs text-destructive">{error??parseError}</span>:null}</label>;
}
function toWrite(configuration:CrmConfiguration):CrmConfigurationWrite { return {environment:configuration.environment,document:JSON.parse(JSON.stringify(configuration.document)) as CrmConfigurationDocument,feature_flags:{...configuration.feature_flags},rollout:{...configuration.rollout,roles:[...configuration.rollout.roles],cohorts:[...configuration.rollout.cohorts]}}; }
function parseImport(value:unknown):CrmConfigurationExport {
  if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Import must contain one CRM configuration object.');
  const candidate=value as Record<string,unknown>;
  if(candidate.schema_version!==1||candidate.module!=='crm'||!candidate.configuration||typeof candidate.configuration!=='object')throw new Error('Import must be a CRM schema version 1 export document.');
  return candidate as unknown as CrmConfigurationExport;
}

export function ConfigurationPage(){
  const client=useQueryClient(); const file=useRef<HTMLInputElement>(null); const [draft,setDraft]=useState<CrmConfigurationWrite|null>(null); const [announcement,setAnnouncement]=useState('');const[previewedFingerprint,setPreviewedFingerprint]=useState('');
  const configuration=useQuery({queryKey:crmKeys.configuration(),queryFn:crmService.getConfiguration});
  const versions=useQuery({queryKey:crmKeys.configurationVersions(),queryFn:crmService.listConfigurationVersions});
  useEffect(()=>{if(configuration.data)setDraft(toWrite(configuration.data))},[configuration.data]);
  const errors=useMemo(()=>draft?validateDraft(draft):{},[draft]); const hasErrors=Object.keys(errors).length>0;const fingerprint=draft?JSON.stringify(draft):'';const previewIsCurrent=previewedFingerprint===fingerprint&&fingerprint!=='';
  const refresh=async()=>{await client.invalidateQueries({queryKey:crmKeys.configuration()});await client.invalidateQueries({queryKey:crmKeys.configurationVersions()})};
  const save=useMutation({mutationFn:()=>{if(!draft||!configuration.data||!previewIsCurrent)throw new Error('Preview the current draft before saving.');return crmService.updateConfiguration(draft,configuration.data.version)},onSuccess:async()=>{setPreviewedFingerprint('');await refresh();setAnnouncement('Configuration saved and audit version created.')}});
  const preview=useMutation({mutationFn:()=>{if(!draft)throw new Error('Configuration is unavailable.');return crmService.previewConfiguration(draft)},onSuccess:result=>{setPreviewedFingerprint(result.valid?fingerprint:'');setAnnouncement(result.valid?'Preview passed server validation.':'Preview identified configuration errors.')}});
  const rollback=useMutation({mutationFn:(version:number)=>crmService.rollbackConfiguration(version),onSuccess:async()=>{await refresh();setAnnouncement('Configuration rolled back through a new immutable version.')}});
  const imported=useMutation({mutationFn:async(payload:CrmConfigurationExport)=>{const candidate=toWrite(payload.configuration);const result=await crmService.previewConfiguration(candidate);if(!result.valid)throw new Error('Imported configuration did not pass server preview.');return crmService.importConfiguration(payload)},onSuccess:async()=>{await refresh();setAnnouncement('Configuration previewed, imported, and versioned.')}});
  const exported=useMutation({mutationFn:crmService.exportConfiguration,onSuccess:value=>{const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`crm-configuration-${value.configuration.environment}-v${value.configuration.version}.json`;anchor.click();URL.revokeObjectURL(url);setAnnouncement('Configuration export prepared.')}});
  if(configuration.isLoading)return <CrmPage title="CRM configuration"><PageSkeleton label="Loading tenant CRM configuration"/></CrmPage>;
  if(configuration.error||!configuration.data||!draft)return <CrmPage title="CRM configuration"><GovernedError error={configuration.error} onRetry={()=>void configuration.refetch()} subject="CRM configuration"/></CrmPage>;
  const updateDocument=(path:string,value:MetadataValue)=>setDraft(current=>current?{...current,document:replaceAtPath(current.document,path,value)}:current);
  return <CrmPage title="CRM configuration" description="Tenant-scoped, versioned controls. Preview changes before applying them; every save, import, and rollback is audited." actions={<><Button variant="outline" onClick={()=>preview.mutate()} disabled={hasErrors||preview.isPending}><SearchCheck className="mr-2 h-4 w-4"/>Preview</Button><Button onClick={()=>save.mutate()} disabled={hasErrors||!previewIsCurrent||save.isPending} title={previewIsCurrent?'Apply the server-validated draft':'Preview the current draft before saving'}><Save className="mr-2 h-4 w-4"/>Save</Button></>}>
    <LiveRegion message={announcement}/>{save.error?<GovernedError error={save.error} subject="Configuration save"/>:null}{preview.error?<GovernedError error={preview.error} subject="Configuration preview"/>:null}
    <Card><CardHeader><CardTitle>Environment and phased rollout</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Environment<input value={draft.environment} onChange={event=>setDraft({...draft,environment:event.target.value})} className={fieldClass}/>{errors.environment?<span role="alert" className="text-xs text-destructive">{errors.environment}</span>:null}</label><label className="text-sm">Rollout percentage<input type="number" min={0} max={100} value={draft.rollout.percentage} onChange={event=>setDraft({...draft,rollout:{...draft.rollout,percentage:Number(event.target.value)}})} className={fieldClass}/>{errors.rollout?<span role="alert" className="text-xs text-destructive">{errors.rollout}</span>:null}</label><label className="text-sm"><input type="checkbox" checked={draft.rollout.enabled} onChange={event=>setDraft({...draft,rollout:{...draft.rollout,enabled:event.target.checked}})} className="mr-2"/>Enable configured capability rollout</label><label className="text-sm">Roles (comma separated)<input value={draft.rollout.roles.join(', ')} onChange={event=>setDraft({...draft,rollout:{...draft.rollout,roles:event.target.value.split(',').map(v=>v.trim()).filter(Boolean)}})} className={fieldClass}/></label><label className="text-sm sm:col-span-2">Cohorts (comma separated)<input value={draft.rollout.cohorts.join(', ')} onChange={event=>setDraft({...draft,rollout:{...draft.rollout,cohorts:event.target.value.split(',').map(v=>v.trim()).filter(Boolean)}})} className={fieldClass}/></label><fieldset className="sm:col-span-2"><legend className="mb-2 text-sm font-medium">Feature flags</legend><div className="flex flex-wrap gap-4">{Object.entries(draft.feature_flags).map(([name,enabled])=><label key={name} className="text-sm"><input type="checkbox" checked={enabled} onChange={event=>setDraft({...draft,feature_flags:{...draft.feature_flags,[name]:event.target.checked}})} className="mr-2"/>{name.replaceAll('_',' ')}</label>)}</div></fieldset></CardContent></Card>
    <Card><CardHeader><CardTitle>Complete behavior document</CardTitle></CardHeader><CardContent><p className="mb-4 text-sm text-muted-foreground">Every runtime threshold, workflow, default, safe limit, and visual setting is editable here. Client validation prevents known-invalid combinations; server validation remains authoritative.</p><ConfigurationEditor value={jsonValue(draft.document)} errors={errors} onChange={updateDocument}/></CardContent></Card>
    {preview.data?<Card><CardHeader><CardTitle>Change preview</CardTitle></CardHeader><CardContent><p className={preview.data.valid?'text-primary':'text-destructive'}>{preview.data.valid?'Server validation passed.':'Server validation rejected this draft.'}</p><pre className="mt-3 max-h-80 overflow-auto rounded bg-muted p-3 text-xs">{JSON.stringify(preview.data.diff,null,2)}</pre>{Object.entries(preview.data.errors).map(([path,messages])=><p key={path} role="alert" className="mt-2 text-sm text-destructive">{path}: {messages.join(' ')}</p>)}</CardContent></Card>:null}
    <Card><CardHeader><CardTitle>Import and export</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-muted-foreground">Exports are portable configuration-as-code documents. Imports pass through the same server validation, audit, and versioning path as this UI.</p><input ref={file} type="file" accept="application/json,.json" className="sr-only" onChange={event=>{const selected=event.target.files?.[0];if(!selected)return;void selected.text().then(text=>{const parsed:unknown=JSON.parse(text);imported.mutate(parseImport(parsed))}).catch(reason=>setAnnouncement(reason instanceof Error?reason.message:'Import could not be read.'))}}/><div className="flex gap-2"><Button variant="outline" onClick={()=>file.current?.click()} disabled={imported.isPending}><FileUp className="mr-2 h-4 w-4"/>Import</Button><Button variant="outline" onClick={()=>exported.mutate()} disabled={exported.isPending}><Download className="mr-2 h-4 w-4"/>Export</Button></div>{imported.error?<GovernedError error={imported.error} subject="Configuration import"/>:null}{exported.error?<GovernedError error={exported.error} subject="Configuration export"/>:null}</CardContent></Card>
    <Card><CardHeader><CardTitle>Immutable version history</CardTitle></CardHeader><CardContent>{versions.isLoading?<PageSkeleton label="Loading configuration versions"/>:versions.error?<GovernedError error={versions.error} onRetry={()=>void versions.refetch()} subject="Configuration history"/>:<ol className="space-y-3">{versions.data?.map(version=><li key={version.id} className="flex flex-col justify-between gap-3 rounded border p-3 sm:flex-row sm:items-center"><div><strong>Version {version.version}</strong> · {version.change_type}<p className="text-xs text-muted-foreground">{new Date(version.created_at).toLocaleString()} · actor {version.actor_id} · correlation {version.correlation_id}{version.rollback_of_version!==null?` · rolls back v${version.rollback_of_version}`:''}</p></div><Button variant="outline" size="sm" disabled={rollback.isPending||version.version===configuration.data.version} onClick={()=>rollback.mutate(version.version)}><RotateCcw className="mr-2 h-4 w-4"/>Rollback to this version</Button></li>)}</ol>}{rollback.error?<GovernedError error={rollback.error} subject="Configuration rollback"/>:null}</CardContent></Card>
  </CrmPage>;
}
