/* eslint-disable @typescript-eslint/prefer-nullish-coalescing */
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Button } from '@/components/ui/Button';
import { ActivityTimeline } from '../components/ActivityTimeline';
import { CrmPage, GovernedError, PageSkeleton } from '../components/CrmPage';
import { DeleteEntityControl } from '../components/DeleteEntityControl';
import { DetailCard } from '../components/DetailCard';
import { crmKeys, crmService } from '../services/crm-service';
export function ContactDetailPage(){const{id=''}=useParams(),nav=useNavigate(),client=useQueryClient();const q=useQuery({queryKey:crmKeys.contact(id),queryFn:()=>crmService.getContact(id),enabled:!!id});const timeline=useQuery({queryKey:crmKeys.activities({related_to_type:'Contact',related_to_id:id,page:1}),queryFn:()=>crmService.listActivities({related_to_type:'Contact',related_to_id:id,page:1}),enabled:!!id});if(q.isLoading)return <CrmPage title="Contact" parent={{label:'Contacts',to:'/crm/contacts'}}><PageSkeleton/></CrmPage>;if(q.error||!q.data)return <CrmPage title="Contact" parent={{label:'Contacts',to:'/crm/contacts'}}><GovernedError error={q.error} onRetry={()=>void q.refetch()} subject="Contact"/></CrmPage>;const contact=q.data;const deleted=()=>{void client.invalidateQueries({queryKey:['crm','contacts']});nav('/crm/contacts')};return <CrmPage title={`${contact.first_name} ${contact.last_name}`.trim()} description={contact.title||'Account contact'} parent={{label:'Contacts',to:'/crm/contacts'}} actions={<><Link to={`/crm/contacts/${contact.id}/edit`}><Button variant="outline">Edit</Button></Link><Link to={`/crm/activities/new?related_to_type=Contact&related_to_id=${contact.id}`}><Button>Log activity</Button></Link><DeleteEntityControl label="contact" impact="The contact is removed from active CRM views. Related audit and activity evidence is preserved." onDelete={()=>crmService.deleteContact(contact.id,contact.version)} onDeleted={deleted}/></>}><div className="grid gap-6 lg:grid-cols-3"><div className="space-y-6 lg:col-span-2"><DetailCard title="Contact information" fields={[{label:'Account',value:<Link className="text-primary hover:underline" to={`/crm/accounts/${contact.account_id}`}>Open account</Link>},{label:'Email',value:contact.email?<a href={`mailto:${contact.email}`}>{contact.email}</a>:'—'},{label:'Phone',value:contact.phone||contact.mobile||'—'},{label:'Department',value:contact.department||'—'},{label:'Owner ID',value:contact.owner_id||'Unassigned'},{label:'Version',value:contact.version}]}/><DetailCard title="Activity timeline"><ActivityTimeline activities={timeline.data?.items} loading={timeline.isLoading} error={timeline.error} onRetry={()=>void timeline.refetch()}/></DetailCard></div><DetailCard title="Engagement evidence" fields={[{label:'Engagement score',value:String(contact.engagement_score)},{label:'Last contacted',value:contact.last_contacted_at?new Date(contact.last_contacted_at).toLocaleString():'No qualifying activity yet'}]}/></div></CrmPage>}
