/* eslint-disable complexity, @typescript-eslint/prefer-nullish-coalescing, @typescript-eslint/no-base-to-string */
import { useCallback, useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Button } from '@/components/ui/Button';
import { Dialog } from '@/components/ui/Dialog';
import { CrmPage, Field, GovernedError, LiveRegion, PageSkeleton, fieldClass } from '../components/CrmPage';
import { DetailCard } from '../components/DetailCard';
import { ActivityTimeline } from '../components/ActivityTimeline';
import { useCrmConfiguration } from '../hooks/use-crm-configuration';
import { crmKeys, crmService } from '../services/crm-service';

const key=(prefix:string)=>`${prefix}-${crypto.randomUUID()}`;
export function LeadDetailPage(){
  const{id=''}=useParams(),nav=useNavigate(),qc=useQueryClient();const configuration=useCrmConfiguration();
  const[convert,setConvert]=useState(false),[remove,setRemove]=useState(false),[announcement,setAnnouncement]=useState(''),[jobId,setJobId]=useState<string|null>(null);
  const q=useQuery({queryKey:crmKeys.lead(id),queryFn:()=>crmService.getLead(id),enabled:!!id});
  const timeline=useQuery({queryKey:crmKeys.activities({related_to_type:'Lead',related_to_id:id,page:1}),queryFn:()=>crmService.listActivities({related_to_type:'Lead',related_to_id:id,page:1}),enabled:!!id});
  const invalidate=useCallback(async()=>{await qc.invalidateQueries({queryKey:crmKeys.lead(id)});await qc.invalidateQueries({queryKey:['crm','leads']})},[id,qc]);
  const score=useMutation({mutationFn:()=>crmService.scoreLeadAsync(id,key('lead-score')),onSuccess:operation=>{setJobId(operation.job_id);setAnnouncement('Lead scoring queued.')}});
  const scoreJob=useQuery({queryKey:['crm','job',jobId],queryFn:()=>crmService.getJob(jobId??''),enabled:jobId!==null,refetchInterval:query=>['pending','queued','running','retrying'].includes(query.state.data?.status??'')?1000:false});
  useEffect(()=>{if(scoreJob.data?.status==='succeeded'){void invalidate();setAnnouncement('Lead scoring completed with verified evidence.')}else if(['failed','timed_out','cancelled'].includes(scoreJob.data?.status??''))setAnnouncement(`Lead scoring ${scoreJob.data?.status}. Review the error and retry.`)},[scoreJob.data?.status,invalidate]);
  const conversion=useMutation({mutationFn:(form:FormData)=>crmService.convertLead(id,{amount:String(form.get('amount')),currency:String(form.get('currency')).toUpperCase(),close_date:String(form.get('close_date')),opportunity_name:String(form.get('opportunity_name'))||undefined,account_id:String(form.get('account_id'))||undefined,create_account:form.get('account_id')?undefined:{name:String(form.get('account_name'))},contact_decision:'create',transition_key:key('lead-convert'),expected_version:q.data?.version??0}),onSuccess:async result=>{await invalidate();setAnnouncement('Lead converted in one transaction.');nav(`/crm/opportunities/${result.opportunity.id}`)}});
  const deletion=useMutation({mutationFn:()=>crmService.deleteLead(id,q.data?.version??0),onSuccess:async()=>{await invalidate();nav('/crm/leads')}});
  if(configuration.isLoading)return <CrmPage title="Lead"><PageSkeleton label="Loading CRM configuration"/></CrmPage>;
  if(configuration.error||!configuration.data)return <CrmPage title="Lead"><GovernedError error={configuration.error} onRetry={()=>void configuration.refetch()} subject="CRM configuration"/></CrmPage>;
  if(q.isLoading)return <CrmPage title="Lead" parent={{label:'Leads',to:'/crm/leads'}}><PageSkeleton/></CrmPage>;
  if(q.error||!q.data)return <CrmPage title="Lead" parent={{label:'Leads',to:'/crm/leads'}}><GovernedError error={q.error} onRetry={()=>void q.refetch()} subject="Lead"/></CrmPage>;
  const lead=q.data,rules=configuration.data.document.opportunity,limits=configuration.data.document.field_limits;const closeDate=new Date(Date.now()+configuration.data.document.conversion.close_date_offset_days*86_400_000).toISOString().slice(0,10);const scoringEnabled=configuration.data.feature_flags.async_lead_scoring===true;
  const scoringState=score.isPending?'Submitting scoring job…':scoreJob.data?`Scoring job ${scoreJob.data.status}${scoreJob.data.progress===null?'':` · ${scoreJob.data.progress}%`}`:null;
  return <CrmPage title={`${lead.first_name} ${lead.last_name}`.trim()} description={`${lead.status} lead${lead.company?` at ${lead.company}`:''}`} parent={{label:'Leads',to:'/crm/leads'}} actions={<><Link to={`/crm/leads/${lead.id}/edit`}><Button variant="outline">Edit</Button></Link>{lead.status==='qualified'?<Button onClick={()=>setConvert(true)}>Convert</Button>:null}{scoringEnabled?<Button variant="outline" disabled={score.isPending||['pending','queued','running','retrying'].includes(scoreJob.data?.status??'')} onClick={()=>score.mutate()}>{score.isPending?'Submitting…':'Score lead asynchronously'}</Button>:null}<Button variant="danger" onClick={()=>setRemove(true)}>Delete</Button></>}>
    <LiveRegion message={announcement}/>{!scoringEnabled?<p role="status" className="rounded border p-3 text-sm">Asynchronous lead scoring is disabled by tenant configuration.</p>:null}{scoringState?<section role="status" className="rounded border p-3 text-sm"><strong>{scoringState}</strong>{['failed','timed_out','cancelled'].includes(scoreJob.data?.status??'')?<><p className="text-destructive">{scoreJob.data?.error?.message??'The scoring job failed without a safe result.'}</p><Button className="mt-2" variant="outline" onClick={()=>{setJobId(null);score.mutate()}}>Retry scoring</Button></>:null}{scoreJob.error?<GovernedError error={scoreJob.error} onRetry={()=>void scoreJob.refetch()} subject="Lead scoring job"/>:null}</section>:null}{score.error?<GovernedError error={score.error} subject="Lead score submission"/>:null}
    <div className="grid gap-6 lg:grid-cols-3"><div className="space-y-6 lg:col-span-2"><DetailCard title="Lead information" fields={[{label:'Email',value:lead.email||'—'},{label:'Phone',value:lead.phone||'—'},{label:'Company',value:lead.company||'—'},{label:'Title',value:lead.title||'—'},{label:'Source',value:lead.source||'—'},{label:'Version',value:lead.version}]}/><DetailCard title="Activity timeline"><ActivityTimeline activities={timeline.data?.items} loading={timeline.isLoading} error={timeline.error} onRetry={()=>void timeline.refetch()}/></DetailCard></div><div className="space-y-6"><DetailCard title="Scoring provenance" fields={[{label:'Score',value:`${lead.score}/${configuration.data.document.lead.score_max} · Grade ${lead.grade}`},{label:'Evidence source',value:lead.score_source},{label:'Factors',value:Object.entries(lead.score_explanation).length?Object.entries(lead.score_explanation).map(([name,value])=>`${name}: ${String(value)}`).join(', '):'No scoring factors recorded'}]}/><DetailCard title="Lifecycle" fields={[{label:'Status',value:lead.status},{label:'Converted at',value:lead.converted_at?new Date(lead.converted_at).toLocaleString():'—'},{label:'Transitions',value:lead.transition_history.length}]}/></div></div>
    <Dialog open={convert} onOpenChange={setConvert} title="Convert qualified lead" description="Creates or reuses the account, creates a contact, and opens one opportunity atomically."><form onSubmit={event=>{event.preventDefault();conversion.mutate(new FormData(event.currentTarget))}} className="space-y-4"><Field id="opportunity_name" label="Opportunity name"><input id="opportunity_name" name="opportunity_name" defaultValue={`${lead.company||lead.last_name} opportunity`} className={fieldClass}/></Field><div className="grid grid-cols-2 gap-3"><Field id="amount" label="Amount" required><input id="amount" name="amount" type="number" min={rules.minimum_amount} step={rules.minimum_amount} required className={fieldClass}/></Field><Field id="currency" label="Currency" required><input id="currency" name="currency" maxLength={limits.opportunity_currency} defaultValue={rules.default_currency} required className={fieldClass}/></Field></div><Field id="close_date" label="Close date" required><input id="close_date" name="close_date" type="date" defaultValue={closeDate} required className={fieldClass}/></Field><Field id="account_id" label="Existing account ID"><input id="account_id" name="account_id" className={fieldClass}/></Field><Field id="account_name" label="Or create account"><input id="account_name" name="account_name" defaultValue={lead.company} className={fieldClass}/></Field>{conversion.error?<GovernedError error={conversion.error} subject="Lead conversion"/>:null}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setConvert(false)}>Cancel</Button><Button type="submit" disabled={conversion.isPending}>{conversion.isPending?'Converting…':'Review and convert'}</Button></div></form></Dialog>
    <Dialog open={remove} onOpenChange={setRemove} title="Delete this lead?" description="This soft-deletes the lead and preserves non-PII audit evidence. It will disappear from normal CRM views."><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setRemove(false)}>Cancel</Button><Button variant="danger" disabled={deletion.isPending} onClick={()=>deletion.mutate()}>{deletion.isPending?'Deleting…':'Delete lead'}</Button></div>{deletion.error?<GovernedError error={deletion.error} subject="Lead deletion"/>:null}</Dialog>
  </CrmPage>;
}
