import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/Button';
import { Dialog } from '@/components/ui/Dialog';
import { CrmPage, EmptyPanel, GovernedError, LiveRegion, PageSkeleton } from '../components/CrmPage';
import { useCrmConfiguration } from '../hooks/use-crm-configuration';
import { crmKeys, crmService } from '../services/crm-service';
import type { Opportunity, OpportunityOpenStage, OpportunityStage } from '../contracts';

function isOpenStage(stage:OpportunityStage):stage is OpportunityOpenStage{return stage!=='closed_won'&&stage!=='closed_lost'}

export function OpportunityKanbanPage(){
  const qc=useQueryClient();const configuration=useCrmConfiguration();const[pending,setPending]=useState<{opportunity:Opportunity;target:OpportunityOpenStage}|null>(null);const[message,setMessage]=useState('');
  const stages=configuration.data?.document.opportunity.stages.map(stage=>stage.name).filter(isOpenStage)??[];
  const limit=configuration.data?.document.ui.pipeline_fetch_limit;
  const q=useQuery({queryKey:crmKeys.opportunities({status:'open',page_size:limit}),queryFn:()=>crmService.listOpportunities({status:'open',page_size:limit}),enabled:limit!==undefined});
  const move=useMutation({mutationFn:(request:NonNullable<typeof pending>)=>crmService.transitionOpportunity(request.opportunity.id,{target_stage:request.target,expected_version:request.opportunity.version,transition_key:`pipeline-${crypto.randomUUID()}`,reason:'Pipeline board movement'}),onSuccess:async()=>{await qc.invalidateQueries({queryKey:['crm','opportunities']});setMessage('Pipeline stage updated.');setPending(null)},onError:error=>setMessage(error instanceof Error?`Move rejected: ${error.message}`:'Move rejected; the card was restored.')});
  const request=(opportunity:Opportunity,target:OpportunityOpenStage)=>{if(opportunity.stage!==target)setPending({opportunity,target})};
  const keyboard=(event:React.KeyboardEvent,opportunity:Opportunity)=>{const current=stages.indexOf(opportunity.stage as OpportunityOpenStage);const target=event.key==='ArrowRight'?stages[current+1]:event.key==='ArrowLeft'?stages[current-1]:undefined;if(target){event.preventDefault();request(opportunity,target)}};
  if(configuration.isLoading)return <CrmPage title="Opportunity pipeline"><PageSkeleton label="Loading pipeline configuration"/></CrmPage>;
  if(configuration.error||!configuration.data)return <CrmPage title="Opportunity pipeline"><GovernedError error={configuration.error} onRetry={()=>void configuration.refetch()} subject="Pipeline configuration"/></CrmPage>;
  if(!stages.length)return <CrmPage title="Opportunity pipeline"><GovernedError error={new Error('No open opportunity stages are configured.')} subject="Pipeline configuration"/></CrmPage>;
  return <CrmPage title="Opportunity pipeline" description="Move cards by pointer or arrow keys. Every movement uses a guarded, auditable transition." actions={<Link to="/crm/opportunities/new"><Button>Create opportunity</Button></Link>}><LiveRegion message={message}/>{q.isLoading?<PageSkeleton label="Loading pipeline columns"/>:q.error?<GovernedError error={q.error} onRetry={()=>void q.refetch()} subject="Pipeline"/>:!q.data?.items.length?<EmptyPanel title="Your pipeline is empty" description="Create an opportunity to start managing deal progression." action={<Link to="/crm/opportunities/new"><Button>Create opportunity</Button></Link>}/>:<div className="grid gap-4 overflow-x-auto pb-4" style={{gridTemplateColumns:`repeat(${stages.length}, minmax(16rem, 1fr))`}} aria-label="Opportunity pipeline board">{stages.map(stage=><section key={stage} aria-labelledby={`stage-${stage}`} className="min-h-64 rounded-lg border bg-muted/20 p-3" onDragOver={event=>event.preventDefault()} onDrop={event=>{const opportunity=q.data.items.find(item=>item.id===event.dataTransfer.getData('text/plain'));if(opportunity)request(opportunity,stage)}}><h2 id={`stage-${stage}`} className="mb-3 font-semibold">{stage.replaceAll('_',' ')}</h2><div className="space-y-3">{q.data.items.filter(opportunity=>opportunity.stage===stage).map(opportunity=><article key={opportunity.id} draggable onDragStart={event=>event.dataTransfer.setData('text/plain',opportunity.id)} tabIndex={0} onKeyDown={event=>keyboard(event,opportunity)} className="cursor-grab rounded border bg-card p-3 shadow-sm focus:ring-2 focus:ring-ring"><Link to={`/crm/opportunities/${opportunity.id}`} className="font-medium hover:underline">{opportunity.name}</Link><p className="mt-1 text-sm">{new Intl.NumberFormat(undefined,{style:'currency',currency:opportunity.currency}).format(Number(opportunity.amount))}</p><p className="mt-1 text-xs text-muted-foreground">Use ← → to move</p></article>)}</div></section>)}</div>}<Dialog open={!!pending} onOpenChange={open=>!open&&setPending(null)} title="Confirm pipeline movement" description={pending?`Move “${pending.opportunity.name}” to ${pending.target.replaceAll('_',' ')}? The server will reject illegal or stale transitions.`:undefined}><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setPending(null)}>Cancel</Button><Button disabled={move.isPending} onClick={()=>pending&&move.mutate(pending)}>{move.isPending?'Moving…':'Confirm move'}</Button></div>{move.error?<GovernedError error={move.error} subject="Pipeline transition"/>:null}</Dialog></CrmPage>;
}
