import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useNavigate, useParams } from 'react-router-dom';
import { toast } from 'sonner';
import { Card, CardContent } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { BudgetForm, initialBudgetValue } from '../components/BudgetForm';
import { GovernedError, PageHeader, PageSkeleton, usePageTitle } from '../components/BudgetUI';
import { QUERY_KEYS, ROUTES, type UUID } from '../contracts';
import { BudgetManagementApiError, budgetService } from '../services/budget-service';

export function EditBudgetPage() { usePageTitle('Edit budget'); const { id = '' } = useParams<{ id: UUID }>(); const navigate = useNavigate(); const client = useQueryClient(); const query = useQuery({ queryKey: QUERY_KEYS.budget(id), queryFn: ({ signal }) => budgetService.getBudget(id, signal), enabled: Boolean(id) }); const mutation = useMutation({ mutationFn: (value: ReturnType<typeof initialBudgetValue>) => budgetService.updateBudget(id, { ...value, expected_updated_at: query.data?.updated_at ?? '' }), onSuccess: (budget) => { void client.invalidateQueries({ queryKey: QUERY_KEYS.root }); toast.success('Budget changes saved.'); navigate(ROUTES.DETAIL(budget.id)); } }); if (query.isLoading) return <PageSkeleton/>; if (query.error || !query.data) return <main className="p-4 sm:p-8"><GovernedError error={query.error ?? new Error('Budget not found.')} onRetry={() => void query.refetch()}/></main>; if (!['draft','revision'].includes(query.data.status)) return <main className="space-y-6 p-4 sm:p-8"><PageHeader title="Budget is read-only" description="Approved, pending, rejected, and closed budgets preserve their planning evidence."/><Button onClick={() => navigate(ROUTES.DETAIL(id))}>Return to budget</Button></main>; const conflict = mutation.error instanceof BudgetManagementApiError && mutation.error.status === 409; return <main className="space-y-6 p-4 sm:p-8"><PageHeader title={`Edit ${query.data.budget_code}`} description="Optimistic concurrency protects newer server changes from being overwritten."/><Card className="max-w-4xl"><CardContent className="pt-6"><BudgetForm initial={initialBudgetValue(query.data)} serverErrors={mutation.error instanceof BudgetManagementApiError ? mutation.error.fieldErrors : undefined} busy={mutation.isPending} submitLabel="Save changes" onCancel={() => navigate(ROUTES.DETAIL(id))} onSubmit={(value) => mutation.mutate(value)}/></CardContent></Card>{mutation.error ? <GovernedError error={mutation.error} onRetry={conflict ? () => { mutation.reset(); void query.refetch(); } : undefined}/> : null}</main>; }
