import { lazy } from "react";
import { Database, Rows3, Settings2 } from "lucide-react";
import type { TenantRoute } from "@/navigation/tenant-route-types";

const MODULE = "metadata_modeling";
const modes = ["development", "self-hosted", "saas"] as const;
const contextual = (parentRouteId: string) => ({ type: "contextual" as const, parentRouteId });
export const tenantRoutes = [
  { id: "metadata-modeling.schemas.list", module: MODULE, path: "/metadata-modeling/schemas", title: "Metadata Models · SARAISE", sourceFile: "modules/metadata_modeling/pages/MetadataSchemaListPage.tsx", Page: lazy(() => import("./pages/MetadataSchemaListPage").then((module) => ({ default: module.MetadataSchemaListPage }))), modes, navigation: { type: "sidebar", label: "Metadata Models", icon: Database, order: 180 } },
  { id: "metadata-modeling.schemas.create", module: MODULE, path: "/metadata-modeling/schemas/new", title: "Create Metadata Model · SARAISE", sourceFile: "modules/metadata_modeling/pages/CreateMetadataSchemaPage.tsx", Page: lazy(() => import("./pages/CreateMetadataSchemaPage").then((module) => ({ default: module.CreateMetadataSchemaPage }))), modes, navigation: contextual("metadata-modeling.schemas.list") },
  { id: "metadata-modeling.schemas.detail", module: MODULE, path: "/metadata-modeling/schemas/:id", title: "Metadata Model Details · SARAISE", sourceFile: "modules/metadata_modeling/pages/MetadataSchemaDetailPage.tsx", Page: lazy(() => import("./pages/MetadataSchemaDetailPage").then((module) => ({ default: module.MetadataSchemaDetailPage }))), modes, navigation: contextual("metadata-modeling.schemas.list") },
  { id: "metadata-modeling.schemas.edit", module: MODULE, path: "/metadata-modeling/schemas/:id/edit", title: "Edit Metadata Model · SARAISE", sourceFile: "modules/metadata_modeling/pages/EditMetadataSchemaPage.tsx", Page: lazy(() => import("./pages/EditMetadataSchemaPage").then((module) => ({ default: module.EditMetadataSchemaPage }))), modes, navigation: contextual("metadata-modeling.schemas.list") },
  { id: "metadata-modeling.records.list", module: MODULE, path: "/metadata-modeling/records", title: "Dynamic Records · SARAISE", sourceFile: "modules/metadata_modeling/pages/DynamicResourceListPage.tsx", Page: lazy(() => import("./pages/DynamicResourceListPage").then((module) => ({ default: module.DynamicResourceListPage }))), modes, navigation: { type: "sidebar", label: "Dynamic Records", icon: Rows3, order: 181 } },
  { id: "metadata-modeling.records.create", module: MODULE, path: "/metadata-modeling/records/new", title: "Create Dynamic Record · SARAISE", sourceFile: "modules/metadata_modeling/pages/CreateDynamicResourcePage.tsx", Page: lazy(() => import("./pages/CreateDynamicResourcePage").then((module) => ({ default: module.CreateDynamicResourcePage }))), modes, navigation: contextual("metadata-modeling.records.list") },
  { id: "metadata-modeling.records.detail", module: MODULE, path: "/metadata-modeling/records/:id", title: "Dynamic Record Details · SARAISE", sourceFile: "modules/metadata_modeling/pages/DynamicResourceDetailPage.tsx", Page: lazy(() => import("./pages/DynamicResourceDetailPage").then((module) => ({ default: module.DynamicResourceDetailPage }))), modes, navigation: contextual("metadata-modeling.records.list") },
  { id: "metadata-modeling.records.edit", module: MODULE, path: "/metadata-modeling/records/:id/edit", title: "Edit Dynamic Record · SARAISE", sourceFile: "modules/metadata_modeling/pages/EditDynamicResourcePage.tsx", Page: lazy(() => import("./pages/EditDynamicResourcePage").then((module) => ({ default: module.EditDynamicResourcePage }))), modes, navigation: contextual("metadata-modeling.records.list") },
  { id: "metadata-modeling.settings", module: MODULE, path: "/metadata-modeling/settings", title: "Metadata Modeling Settings · SARAISE", sourceFile: "modules/metadata_modeling/pages/MetadataModelingSettingsPage.tsx", Page: lazy(() => import("./pages/MetadataModelingSettingsPage").then((module) => ({ default: module.MetadataModelingSettingsPage }))), modes, navigation: { type: "sidebar", label: "Metadata Settings", icon: Settings2, order: 182 } },
] satisfies readonly TenantRoute[];
export default tenantRoutes;
